### ISSUE TITLE
Capability leak by fulfilling with a non-fresh handled presence

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#10]
Our way of fulfilling a handled promise with a fulfillment handler has a capability leak: Say Alice and Bob are within the same frozen root realms and supposedly isolated from each other. Alice creates a handled promise and then does `Resolve(Object, fulfilledHandler)`, which fulfills it with `Object`. Bob then does `Promise.resolve(Object)` and retrieves Alice's handled promise.

Our presences are only safe when they are fresh. To enforce freshness, the presence should be created by the eventual-send package in the act of fulfilling a handled promise with a fulfilled handler. I don't see any way to do this while preserving the elegance of the current `HandledPromise` constructor.

API details aside, the most general way I can think of to ask the TCB to create a new fresh object, while still providing flexibility for what the object is, is to provide the parameters of `Object.create` and leave the creation up to the TCB.

Fortunately, there should be no motivated use case for simultaneously fulfilling a handled promise with a pre-existing object while also providing a fulfilled handler for that case. Fulfilled handlers should only be needed for fresh presences, so there shouldn't be any loss of needed functionality.

**Comment by michaelfig** [comment]
This is implemented.
