### ISSUE TITLE
[Zoe] Extend offer hooks with hook helpers

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#1014]
Zoe currently has a `offerAnInvite` hook to add support for checking properties of invites. This has a similar signatures to `zcf.makeInvitation`, and so could be confusing to developers. This proposed a more orthogonal approach:  use helpers to enhance the offer hooks with additional functionality that will e.g., reject an offer if it doesn't have amounts for the correct issuer.

A specific replacement for `inviteAnOffer` would be: 
```js
  function checkedHook(offerHook, expected) {
      return offerHandle => {
        helpers.rejectIfNotProposal(offerHandle, expected);
        return offerHook(offerHandle);
      };
   },
```

Further such hooks could be added for checking expirations, minimum amounts, etc.  Usage might be something like:
```js
zcf.makeInvitation(checkedHook(hook, expected), …);
```

In order to simplify the setup of such hooks, we should consider providing the `zcf` itself as a second argument to the hook. Then more helpers like this can be built without needing to close over `zcf`.

**Comment by erights** [comment]
Fixed by #960
