### ISSUE TITLE
[Zoe] Consider uniformizing wording around "active" and "complete"

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#1016]
Zfc has a `.complete(offerHandles)` and `.getOfferStatuses` methods
Zoe service has a `.isOfferActive(offerHandle)`

And they refer to the same thing (whether an offerHandle still has an allocation associated with it with assets hold by Zoe), but the wording does not make it easy to understand

We've had a question about this during the hackathon

**Comment by katelynsills** [comment]
I think if we make it clear that "active" means the offer has been made but not yet completed, that seems sufficient. Now that we don't have the inviteHandle/offerHandle problems, it should be much clearer.

**Comment by katelynsills** [comment]
Closed in #1414, in which we switch to `exit` and `hasExited`
