### ISSUE TITLE
[Zoe] Return an instanceRecord along with an invite as the result of `makeInstance`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1024]
Edited:

We decided to do two things:

Redo the helper such that it returns the instanceRecord rather than the instanceHandle
Change the result of makeInstance to return a record of { invite, instanceRecord }

**Comment by DavidBruant** [comment]
> We have a helper to get the instanceHandle from an invite

I fail to see the helper in the documentation

In any case, i agree with the intention, but it's not clear to me what better than a helper can be done

**Comment by katelynsills** [comment]
We have a mention of the helper here: https://agoric.com/documentation/getting-started/intro-zoe.html#offers

If we return a record with the instanceHandle and an invite, then it's much more usable than using a helper to grab the instanceHandle. 

The downside is a potential loss of promise pipelining, but I'd like to see that analysis to be sure that's the tradeoff.

**Comment by erights** [comment]
How can we make the helper more usable?

What lessons are there so future helpers are more usable?

**Comment by erights** [comment]
Can you explain what the usability problem is with using the helper?

**Comment by katelynsills** [comment]
Sure, it's the number of steps (5) that a user has to take with a helper in comparison with the number of steps the user has to take if we return the instanceHandle (2). Additionally, needing to import and use a helper at all requires additional documentation and cognitive load. 

Here's a comparison of the steps. 

With a helper and current Zoe:
1. Import `clientSupport` and get the named export `makeGetInstanceHandle`
2. make `getInstanceHandle` by calling `makeGetInstanceHandle` with the issuer
3. call `zoe.makeInstance` and receive a promise for an invite.
4. wait for the promise to resolve to the invite.
5. call `getInstanceHandle(invite)` and receive the `instanceHandle`

Without a helper, if `makeInstance` returns the instanceHandle as well
1. call `E(zoe).makeInstance`, and receive a promise for the result
2. wait for the promise to resolve and then destucture to get the instanceHandle and the invite

**Comment by katelynsills** [comment]
We decided to do two things:
1. Redo the helper such that it returns the instanceRecord rather than the instanceHandle
2. Change the result of `makeInstance` to return a record of `{ invite, instanceRecord }`

**Comment by katelynsills** [comment]
Closed by #1143
