### ISSUE TITLE
[ERTP] `burnAll` and `burnExactly` use empty purses but they don't need to

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#103]
I thought this change had been made already, so I'm possibly missing some reason why it wasn't done, but I thought we had decided that `burnAll` and `burnExactly`, given payment linearity, could just delete the payment from the WeakMap that maps payments to balances. Right now, it creates an intermediate purse, which was necessary before payment linearity but doesn't seem necessary now.

@erights @Chris-Hibbert Anything I'm missing, or did this just get lost in a git merge or something?

**Comment by Chris-Hibbert** [comment]
It doesn't look like my suggestion to drop burnExactly(), and have only burnAll() with an optional parameter was either implemented or written up as an issue, so I'm re-opening this.

**Comment by katelynsills** [comment]
That suggestion is now a different issue, so this Issue should remain
closed. The PRs were split into refactoring that doesn't change the API
(this Issue and PR) and changes that do affect the API (your suggestion).
