### ISSUE TITLE
[ERTP] `burnExactly` is confusing. Can we just have `burn` with an optional parameter?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#104]
What if we just had burn() with an optional parameter for `units`? If `units` is present, then `units` must be equal to the payment balance.

**Comment by dtribble** [comment]
I cannot tell what the actual proposal is here now.  It seems to me like you should only burn payments. I think that the above discussion agrees that the right answer is

```assay.burn(payment)```

Is there anything else proposed?

**Comment by katelynsills** [comment]
Yes, you should only burn payments. The question is whether you are also able to specify the units that you expect the payment to have when it is burned (as an extra check) or not. The ERTP code currently has two functions: `burnExactly` and `burnAll`.  `burnExactly` takes an extra `units` parameter and checks that the current balance of the payment is equal to `units`. 

The current proposal is that there is only one `burn` function, which takes an optional second parameter `units` in addition to the first parameter `payment`.  If no `units` are present, no check is done. If `units` present and not undefined, the check is done.
