### ISSUE TITLE
Why are registries enumerable?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1061]
At
https://github.com/Agoric/agoric-sdk/blob/ca1e2b597b32ecad48781482e3ba944d1f4e81a7/packages/registrar/src/registrar.js#L59
is a `keys` method that enumerates the contents of a registry.

At
https://github.com/Agoric/agoric-sdk/blob/ca1e2b597b32ecad48781482e3ba944d1f4e81a7/packages/cosmic-swingset/lib/ag-solo/vats/vat-mailbox.js#L7
a new encapsulated registry is created, rather than using the public registry, in order to enable known keys to be looked up but not enable them to be enumerated.

If, as I suspect, the `keys` method shouldn't be there, then once it is removed, others won't need to create separate registries in order to hide it.

Attn @katelynsills @dtribble @michaelfig

**Comment by katelynsills** [comment]
Given that we don't currently have a mechanism to tell users what we have put in the public registry for them to use, acting as a user, it has been nice to be able to use the .keys() method to see what exists. I think we should keep it as is unless we add other mechanisms to tell users what we have put in the registry that make this superfluous.

I wasn't using the public registry because I wanted to have a separate namespace, not because of the keys() issue.

**Comment by erights** [comment]
> acting as a user, it has been nice to be able to use the .keys() method to see what exists.

This creates phishing hazards.

If the user uses `.keys()` and sees both `'bucksIssuer_3549'` and `'bucksIssuer_7629'`, what are they to conclude they are seeing to "exist"? What if they only see `'bucksIssuer_3549'` because `'bucksIssuer_7629'` has not yet been registered?

> Given that we don't currently have a mechanism to tell users what we have put in the public registry for them to use

The whole registry mechanism was designed under the assumption that these names would be communicated. It has no authenticity properties unless they are. Until then, our users have no way to avoid being phished.

We must get rid of `.keys()` or at least make it clear that it is *not* for normal use. And we must communicate to them the names they are supposed to use to access the objects we intend them to access.

**Comment by erights** [comment]
We set up users with wallets that start with true petnames, not registry names, like plain `'bucksIssuer'`. If we can do this consistently, so that users never need to see  registry names, then we could even get rid of the prefix, and the resulting hazard that users will make bad inferences about what it names. If users should never normally see them, names like `'6763408009462828'` are more like webkeys than they are like registry names. (Though still only for authenticity for widely holdable things, since there's no unguessability.)

**Comment by katelynsills** [comment]
The phishing argument is convincing. I'm ok getting rid of `keys()` and the prefixes. It sounds like we will need the wallet to be the general petname manager for the user at this point

**Comment by katelynsills** [comment]
We need to delete the registry, as it is subsumed by the board.

**Comment by dtribble** [comment]
That's fine. I'd like to keep the code in some agoric-labs project.

**Comment by katelynsills** [comment]
Closing this issue, as there is another issue to delete the registry and move it to agoric-labs: https://github.com/Agoric/agoric-sdk/issues/1350
