### ISSUE TITLE
[cosmic-swingset] Refactor lib-wallet to expose different facets

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1074]
lib-wallet is intended to be used from the REPL, but also from the wallet frontend and the dapp frontend. We should expose different facets for these different uses, because there are significant differences in how much authority they should have, as well as what format the arguments and results should be in. For instance, the frontend cannot receive presences so everything must be serialized with the user's petnames.

**Comment by rowgraus** [comment]
Redundant with #2042
