### ISSUE TITLE
[Zoe] Reallocate only for Keyword not in user's `give` or `want`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1075]
The scenario:

Alice specifies their proposal:

```
 const aliceProposal = harden({
    give: { Asset: moola(3) },
    want: { Price: simoleans(7) },
    exit: { onDemand: null },
  });
```

We want to give Alice an unrelated token (`Freebie`) that she doesn't previously know about (and importantly, does not mention in her proposal.)

We use the helper `escrowAndAllocateTo`. Within this helper, we call `reallocate` which only reallocates for the particular `keyword` by using the third parameter to filter:

```
          zcf.reallocate(
            harden([tempHandle, recipientHandle]),
            harden([tempAlloc, recipientAlloc]),
            harden([keyword]),
          );
```
In the `reallocate` call, `isOfferSafeForOffer` for offer is called. For the reallocation to be offer safe, either the user must be given what they gave (a refund) or what they want (winnings). When we introduced sparse keywords, we filtered and filled the current allocations by keyword and asserted that all the sparse keywords were present in the `newAllocations`, but we didn't filter the `give` or `want`. 

Because we didn't filter the proposal by the keyword, we are left in the situation of comparing Alice's `give: Asset: moola(3)` and `want: { Price: simoleans(7) }` with the allocation of `Freebie: freebie(100)`. This obviously turns out to not be offer safe. We should be filtering the proposal keywords too, so that we are actually comparing a proposal of `{ want: {}, give: {} }` (Alice had no rule for Freebie) with an allocation of `Freebie: freebie(100)`, which should be offer safe. 

## Actual

After `reallocate` is called with third parameter `sparseKeywords = ['Freebie']`, `isOfferSafeForOffer` is comparing the full original proposal `give` and `want`:

```
    give: { Asset: moola(3) },
    want: { Price: simoleans(7) },
```
with the allocation: `{ Freebie: freebie(1000) }`

Offer safety fails, because we have given neither what the user wanted or gave.

## Expected

Instead, what should happen is:

After `reallocate` is called with third parameter `sparseKeywords = ['Freebie']`, `isOfferSafeForOffer` is comparing  the proposal `give` and `want` filtered by `sparseKeywords`:

```
    give: { },
    want: { },
```
with the allocation: `{ Freebie: freebie(1000) }`

Offer safety succeeds trivially, because the user did not specify Freebie in their `give` or their `want`.

**Comment by Chris-Hibbert** [comment]
I think the payouts only include issuers that are in the offer's proposal.

**Comment by dtribble** [comment]
Since this is a bug report, can you add "expected" and "actual" sections in the initial report.  I cannot quite tell whether the attempted reallocate has both "Simoleans" and "Freebies", and the "Freebies" aren't passing through.  If it's only Freebies, then I would expect the reallocate to fail. If it's both, then I would expect it to succeed with both payouts.

**Comment by katelynsills** [comment]
> I think the payouts only include issuers that are in the offer's proposal.

No, they can include any issuers.

**Comment by katelynsills** [comment]
> Since this is a bug report, can you add "expected" and "actual" sections in the initial report. I cannot quite tell whether the attempted reallocate has both "Simoleans" and "Freebies", and the "Freebies" aren't passing through. If it's only Freebies, then I would expect the reallocate to fail. If it's both, then I would expect it to succeed with both payouts.

sure, I can add `expected` and `actual`. The new allocation in the attempted reallocate only has Freebies, but that should succeed, not fail.

**Comment by katelynsills** [comment]
@dtribble I added `expected` and `actual` sections.
