### ISSUE TITLE
[ERTP] .mint() can take a number as first parameter

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#108]
[The chainmail](https://github.com/Agoric/ERTP/blob/a4061a825394cd531ea5d089b881097dd3c823ca/core/mint.chainmail#L93) suggests the first argument should be a `Units` and [`Units` are a complex object](https://github.com/Agoric/ERTP/blob/a4061a825394cd531ea5d089b881097dd3c823ca/core/unitOps.chainmail#L10-L13), but many examples, a JavaScript `number` can be used:
```js
const myHappyTownBucks = happyTownBucks.mint(100, 'myHappyTownBucks');
```

**Comment by DavidBruant** [comment]
> unit/extent feel extraneous when natural numbers already work

Now that i have more knowledge on the topic, i think units can be removed altogether: #323

**Comment by katelynsills** [comment]
Hi David, like I said in #323, I think units should not be removed because they protect against user/developer error.

**Comment by katelynsills** [comment]
Let's make sure to change the chainmail to reflect the fact that currently makeMint can take extents OR units
