### ISSUE TITLE
Another apparent handled promise failure mode

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#1087]
In the course of updating the `test-vpid-liveslots.js` test suite to account for promise retirement, I turned up the following failure, which at first appeared to be related to promise retirement, but I disabled all the promise retirement mechanisms and the problem persists.  Since the tests simulate the kernel side of the vat/kernel relationship, I reconstructed the problem as a pair of vats I could run under `swingset-runner` in order to check that the problem wasn't something to do with the test logic itself.  It wasn't.

Here's the Alice (bootstrap) vat:
```
function build(E, log) {
  const target = {
    one() {
      log(`target in one`);
    },
    two() {
      log(`target in two`);
    },
  };
  return {
    bootstrap(argv, vats) {
      const bob = vats.bob;
      const p1 = E(bob).result();
      E(bob).promise(p1);
      E(bob).run(target);
    },
  };
}
```

Here's the Bob vat:
```
function build(E, log) {
  let p1;
  const [p0, r0] = makePR();
  return {
    promise(p) {
      p1 = p;
    },
    result() {
      return p0;
    },
    async run(target) {
      const p2 = E(p1).one();
      hush(p2);
      r0(target);
      const p3 = E(p1).two();
      hush(p3);
    },
  };
}
```

During execution, when the resolution of the promise in the middle of Bob's `run` method happens, the `one` message is delivered to the target object, but the `two` message never appears.

**Comment by warner** [comment]
Huh, I can't imagine what's failing there.. it looks just like existing+passing tests.

If you replace the `hush(p3)` with something like `.then( console logging stuff)`, is `two()` throwing an error of some sort?

If you look at the syscalls being made by `run()`, you see the `syscall.send` for `one`, and the `syscall.fulfillToPresence` for `r0(target)`, but not the `syscall.send` for `two`, right?

We might try re-instrumenting the handlers in `makeImportedPromise` and `makeImportedPresence` and see if/when they're being invoked.

**Comment by FUDCo** [comment]
`two` is not throwing an error because it is not being invoked at all.  Your synopsis of the syscalls seen is correct: `send` of `one`, `fulfillToPresence` for `r0(target)`, and no `send` of `two`.

Some deeper examination in the debugger shows that the `two` message delivery is being cut short by the `handlerActive` check in the `unfulfilledHander` in `makeImportedPromise`, which throws `"mIPromise handler called after resolution"`.  Which, indeed, is true, but...  Since the prior invocation of `one` does not trip over this check, I'm thinking there's some kind of mismatch in assumptions between when the resolution is invoked and when it actually happens.

**Comment by FUDCo** [comment]
Further investigation: this fails in the same way on the `master` branch.  Also, `test-vpid-liveslots` on the `master` branch exhibits 4 assert failures; I'm not sure how this is possible, but there it is.

**Comment by FUDCo** [comment]
Addendum to previous: one of the assert failures corresponds to the case I was trying to diagnose.

**Comment by FUDCo** [comment]
Worked this one with Brian.  Diagnosis: operator headspace error.  Although I reflexively rebuild the kernel anytime anything is updated, it turns out that in this case I also needed to rebuild the eventual-send package.  Closing.
