### ISSUE TITLE
[wallet-frontend] Non-fungible extent causes React error

### ISSUE THREAD

**Issue by TerryvanWalen** [Agoric/agoric-sdk#1088]
When a purse in the wallet contains a non-fungible token, react crashes with this error:

> Objects are not valid as a React child (found: object with keys {type}). If you meant to render a collection of children, use an array instead.

I have narrowed the problem down to two files in the package: wallet-frontend:
- src/components/Purses.jsx
- src/components/Inbox.jsx

Both try to render the **extent** directly. This fails when the extent contains an array of objects. Which is the case for non-fungible tokens.

I have temporarily fixed this by replacing every `{extent}` with:
```javascript
{Array.isArray(extent) ? extent.length : extent}
```

However, I think we want to provide more information than only the length of the NFT array in the wallet.

This issue might be related to: #1064

**Comment by katelynsills** [comment]
Thank you @TerryvanWalen! I will create a PR for this. It sounds like for now, you're not blocked with your temporary fix, but let me know if this is blocking.
