### ISSUE TITLE
bundle-source should apply tildot transform

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1101]
Our vats and contracts (can be) written with "tildot syntax": `bob~.foo(arg1, arg2)`. This must be transformed before it can be executed, into `HandledPromise.applyMethod(bob, "foo", [arg1, arg2])`.

Currently, the tildot transform is applied by the kernel by adding a transform function to the `evaluate()` options. The controller gets this transform from the `default-evaluate-options`, and currys it into the evaluator that it provides to the kernel (the metering transform is also bundled in here).

I think we decided to move the responsibility for the tildot transform from the kernel into the `bundle-source` process. Tildot transformation is "optional", in the sense that we're ok with vats/contracts trying to dodge it (unlike the injection of metering, which must be enforced everywhere to be effective). So it's ok for us to have users tildot-transform their code on their own machines, before sending the bundled artifact up to the chain. If they skip this step, their code will fail to parse when loaded into a vat/Compartment, but that's their problem, not ours.

The #477 kernel-on-new-SES work includes changing the way the evaluator is set up, so I'm in the process of moving this transform out.

I'm still trying to figure out how it all works. I think I'll start by *adding* the tildot transform to `bundle-source`, but not yet attempt to remove it from what the kernel does. Applying the transform twice shouldn't be a problem, the second time will be a no-op. Here are the pieces I think I need to look at:

* remove the bundling script in `transform-eventual-send`, since it uses bundle-source and that would get recursive (in general we're aiming to remove all the bundling scripts, and not publish e.g. `dist/transform-eventual-send.cjs` files; just use ES6 modules everywhere)
* build a rollup plugin, copy the transform steps into it (@michaelfig has pointed me at a sample to follow). I think I'll add this plugin to `transform-eventual-send` as an additional export.
* make `bundle-source` grab this plugin and add it to the `plugins:` list in the call to `rollup()`

My experiments so far have run into problems with either rollup's ESM parsers balking at the presence of the non-standard tildot syntax, or the tildot transform's parser balking at the presence of ESM import/export syntax. Obviously this is working somehow already, but I must have broken something as I rearranged the pieces.

Then the second phase is to remove tildot-transform from the kernel side:

* remove `transform-eventual-send` from `default-evaluate-options` (maybe `default-evaluate-options` will go away entirely, it only had two things in it)

**Comment by michaelfig** [comment]
Also, note that the REPL will need its own tildot transform (and HandledPromise endowment) for the Compartment that is used to evaluate code.
