### ISSUE TITLE
Purse.deposit() returns new balance

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1104]
Purse's documentation claims that `deposit(amount)` returns the amount deposited. I think this is correct.

Purse actually returns the new balance of the purse after the deposit.

Edit (Kate, 5/12): Depositing a payment shouldn't implicitly carry the authority to read the balance, so we should not return the new purse balance. Instead, let's go back to returning the payment amount.

**Comment by katelynsills** [comment]
Closed by #1143
