### ISSUE TITLE
`yarn install` changes `packages/cosmic-swingset/go.mod`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#114]
![Screen Shot 2019-12-02 at 3 59 54 PM](https://user-images.githubusercontent.com/2441069/70004946-e09eea00-151c-11ea-9654-ae79e80eb043.png)

PR to follow

**Comment by erights** [comment]
I'm still seeing this. Should I reopen?

**Comment by erights** [comment]
Actually I'm seeing the opposite: that line is being added. Reopening.

**Comment by katelynsills** [comment]
What version of Go do you have?

**Comment by erights** [comment]
go version go1.12.6 darwin/amd64

**Comment by michaelfig** [comment]
Although 1.12 will work to compile, it adds the appengine dependency while 1.13+ removes it.  They're incompatible in this tiny regard.

**Comment by warner** [comment]
Ok, so is the resolution to require Go 1.13? Should we update the README?

**Comment by katelynsills** [comment]
Yeah, it's probably a good idea to recommend Go 1.13. It's not a strict requirement as long as they remember not to check in their changes to `go.mod` but maybe that's too complicated for people
