### ISSUE TITLE
[Zoe] name for bondingCurve's getCurrentPrice

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1153]
Uniswap V1 uses `getInputPrice` and `getOutputPrice` as the names for their functions. We could use that terminology and go both directions.

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/pull/1147_

Chris [said](https://github.com/Agoric/agoric-sdk/pull/1147#discussion_r433508973): "Maybe I'm making an incorrect distinction, but I think of "current price" as either a unit price ($X per item), or price over amount ($22 for 37 moolah). This function seems to be calculating "how much moolah would I get if I spent 37 simoleans?", and the return value isn't price, it's the proceeds. It would look more like a price to me if the question it answered were "How much moola would I have to spend to get 45 Simoleans?""

**Comment by Chris-Hibbert** [comment]
closed by #1672
