### ISSUE TITLE
ES2019 method Array.prototype.flat() doesn't appear to work in Swingset vats

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1157]
**Describe the bug**
I used Array.prototype.flat() in `zoe.js` to flatten an array, but when I did so, the Zoe Swingset tests no longer passed. An error message said that `flat` was not a function.

For instance, in the test `zoe - sellTickets - valid inputs`, you get this result:

<img width="995" alt="Screen Shot 2020-06-03 at 4 23 25 PM" src="https://user-images.githubusercontent.com/2441069/83698593-ab9c4e80-a5b6-11ea-8099-59112c35ef2e.png">

**To Reproduce**
1. Checkout https://github.com/Agoric/agoric-sdk/blob/zoe-release-0.7.0/
2. Remove `flattened` and add `.flat()` to the end here:
https://github.com/Agoric/agoric-sdk/blob/36a793f5ba36b5f8dbd7b9f2f26736208756bcbe/packages/zoe/src/zoe.js#L490

To produce:

<img width="513" alt="Screen Shot 2020-06-03 at 4 35 24 PM" src="https://user-images.githubusercontent.com/2441069/83699202-4d706b00-a5b8-11ea-8b2f-0c930d78a4eb.png">

**Expected behavior**
Both the Zoe Swingset tests and the non-Swingset tests should pass.

**Platform Environment**
 - what OS are you using? : MacOS Catalina 10.15.4 (19E287)
 - what version of Node.js? Node v14.4.0
 - is there anything special/unusual about your platform? I don't think so
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`): NA

**Comment by erights** [comment]
Now that we require much more recent platforms than Node 14, we're using `flat` without problem, so closing.
