### ISSUE TITLE
Add agoric-cli commands to run multiple ag-solos against a local chain

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1165]
**What is the Problem Being Solved?**

It should be possible to run multiple ag-solos against the same chain using the `agoric` CLI.

**Description of the Design**

```sh
# Start a local chain.
agoric start local-chain &
Logging to _agstate/logs/local-chain.log
# Start an ag-solo running on port 127.0.0.1:8001
agoric start local-solo 8001 &
Logging to _agstate/logs/local-solo-8001.log
# Start an ag-solo running on port 0.0.0.0:8002
agoric start local-solo 8002 --listen=0.0.0.0 &
Logging to _agstate/logs/local-solo-8002.log
```

**Security Considerations**

Internet-accessible ag-solo nodes have not been battle-tested.  They probably can be easily compromised.  The `--listen=0.0.0.0` option is designed for running an ag-solo only on a protected LAN.

**Test Plan**

Add a CI step to start two ag-solos and run some testing deploy scripts on them.

**Comment by dtribble** [comment]
since it defaults to port 8000, should the default log include the port number that same as the others?  Or is it useful to have it so distinguished because it is the main one people will use?

**Comment by dtribble** [comment]
@PanGan21 @haischel In using `agoric-sdk` you had noted that easy access to multiple users/wallets would help. Would this proposal address that, where there's effectively a new user created for each port/`ag-solo` that's requested.

**Comment by michaelfig** [comment]
> since it defaults to port 8000, should the default log include the port number that same as the others? Or is it useful to have it so distinguished because it is the main one people will use?

It should be explicitly started, as `agoric start local-solo 8000`.  The example I provided didn't do that, just for fun.

**Comment by michaelfig** [comment]
This design has been obsoleted by the one that is described in https://docs.google.com/document/d/1SurmzBL_4XX9hNKrjc3LUouKs0eo_YpiN5VN0DeVodk/edit?usp=sharing and merged into current master.
