### ISSUE TITLE
tame-metering plus new-ses breaks endowments

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1179]
I've run into some kind of conflict between the agoric-sdk `tame-metering` package, and new SES (0.8.0). The symptom is that endowments aren't visible to the evaluated code.

Using the `@agoric/tame-metering` in the current trunk, I set up two files. The first injects metering code into all the global objects (so confined code cannot use built-ins to provoke very large memory usage or runtime). To avoid upsetting SES, it must also add a property to one of the objects it replaced.

```js
// install-global-metering.js
import { tameMetering } from '@agoric/tame-metering';
tameMetering();

Object.defineProperties(RegExp, {
  [Symbol.species]: {
    get() { return RegExp; },
  },
});
```

The second imports the first (first, before importing anything else, which is important, because the first file modifies built-in objects like `Object`, and we need the other imports to use those modified objects):

```js
import './install-global-metering.js';
import 'ses';
lockdown();
const c = new Compartment({ foo: 0 });
const namespace = c.evaluate('foo');
```

(I'll attach a draft PR with this test, for ease of reproduction).

The symptom is that the `c.evaluate('foo')` fails with `ReferenceError: foo is not defined`.

I've instrumented `Compartment`, specifically `performEval`, and I can see that `scopeHandler.get(whatever, 'foo')` succeeds. If I harden `c.globalThis` then I also see `foo` in the `getScopeConstants` array (among lots of other object names). But when it finally calls `apply(evaluate, globalObject, [source])`, it fails with the ReferenceError.

If I comment out the `tameMetering()` call, it all works.

The use case that provoked this was using the metering transform, which injects code that includes calls to `getMeter()`. I'm supposed to be able to use the transform in conjunction with a `getMeter` endowment, but the transformed code could not be evaluated, with the same kind of ReferenceError.

I'm guessing that something `tameMetering` does to some globals is causing problems in our magic lines. Maybe the built-in `eval` is modified, and stops working for our "magic lines of code"?

Cc @michaelfig who wrote tame-metering, and @kriskowal who knows SES the best, and @erights because I'm desperate :).

**Comment by michaelfig** [comment]
I have some theories to try... Should have positive or negative results by Monday.
