### ISSUE TITLE
Importing @agoric/marshal in wallet-frontend throws error

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1187]
**Describe the bug**
Importing `@agoric/marshal` in wallet-frontend, such as `Purses.jsx` gives the follow error when loading the wallet page. The wallet is built without error. 
<img width="713" alt="Screen Shot 2020-06-16 at 3 22 38 PM" src="https://user-images.githubusercontent.com/2441069/84834178-a511cc00-afe5-11ea-94a6-4e19ea35712a.png">

**To Reproduce**
1. Checkout https://github.com/Agoric/agoric-sdk/tree/marshal-wallet-frontend-error
2. `agoric install`
3. `agoric build`
4. navigate to the local `dapp-encouragement`
5. `agoric install`
6. `agoric start --reset`
7. In a separate console: `agoric deploy contract/deploy.js` `agoric deploy api/deploy.js`
8. In a separate console: `cd ui && yarn start`
9. Request encouragement for a tip
<img width="582" alt="Screen Shot 2020-06-16 at 3 31 42 PM" src="https://user-images.githubusercontent.com/2441069/84834568-8bbd4f80-afe6-11ea-8cfb-0e94c29b4d31.png">
10. navigate back to the wallet. It will have the error.

**Expected behavior**
I would not expect importing @agoric/marshal would cause the wallet to error.

**Platform Environment**
MacOS, Node  v14.4.0

**Comment by michaelfig** [comment]
This is a problem with the current `@agoric/harden` package (which `@agoric/marshal` relies on) when used outside of SES, specifically in the browser.

Tagging @erights, @warner, and @kriskowal, as they may have opinions on using `harden` in library code that may or may not run under SES.  In my opinion, this use case should be supported when desired, even if it cannot give the same guarantees that harden under SES can give.

**Comment by kriskowal** [comment]
I would like to move us away from using a module for `harden` and instead pick it up from the global. That would make it considerably easier to write code that uses a no-op `harden` in the situations where enforcement is not viable.

With the current release, `import "ses"` has the side-effect of introducing a global `harden` that throws an error until after `lockdown`.

**Comment by warner** [comment]
In my swingset-on-new-SES branch, I'm leaning in the same direction: any program that uses swingset must first import a special module named `@agoric/install-ses` (in fact they might import `@agoric/install-metering-and-ses`), and after that a functional `Compartment` and `harden` are available as globals. I still have bundle-source treating `@agoric/harden` as an "external", and I still allow vats and the kernel to do `import harden from '@agoric/harden'` (which just returns the global), but only so I can defer the huge import-removing patch. I'll do that after everything is landed, then remove support for vats importing `harden` and force them to rely upon the global.

The consequence is that every program that uses swingset, or which uses a library which uses `harden` as a global, must first do the `install-ses` dance. That means every unit test file, and the handful of actual applications (`ag-solo`, `ag-cosmic-swingset`, and `swingset-runner`).

This is cleaner and safer, I think, but it takes us away from the previous "`ses-adapter`" plan, which had (as a corollary) the "you can import `harden` and use it even outside SES and it might reveal a few mistakes you're making but it won't actually be secure" plan. The nice thing about that old plan was that a library author could import+use `harden` without imposing obligations on the hapless downstream application that wound up using it (possibly through a couple of third parties). I feel a little bad about that change, but I think it's for the best.

I don't know much about adding things to globals in different environments (I've kind of internalized the ESM model, maybe too much). I hope the answer is "no", but would it make sense to publish a `fake-harden` module whose only job is to add a no-op `harden` to the global? (I know we've talked about this before, but at that time I was keen on the `ses-adapter` approach, and I think @michaelfig subsequently talked me into the all-SES-all-the-time model). The only instructions on that module would be "if you're an application author, and something in your dependency graph uses `harden`, then you need to import `fake-harden` before you import them).

If the environment was not so module-ish, then instead we could offer instructions like "add `globalThis.harden = obj => obj;` to your first `<script>` tag" or something.

But in any case, the frustrating bit is that the application author wasn't even trying to use `harden` (or `Compartment`, which of course has the same issues), they were just using some library, which used some other library, which thought `harden` was cool. So there's not a great discovery pathway from some `ReferenceError: harden does not exist` or `TypeError: harden is not a function` in some library you haven't heard of, to this documentation that says "oh BTW to fix this you need to be inside SES, or install this shim thing".

I imagine there must be prior art on this. Is there some common practice we could follow? I guess in most of these cases, the library depends on a polyfill-it-if-it-doesn't-exist library, which solves the problem locally. But I don't think we can make `harden` work that way.

**Comment by michaelfig** [comment]
@warner I didn't intend to throw out the `ses-adapter` plan.  I think it's still reasonable to have.

Instead of exporting a `make-hardener`-inspired `harden`, have it set a global `harden` variable to `Object.freeze` or even `x => x`.  It would include the other shims, too, but could install them on globals (like `Promise.delegate`/`HandledPromise`) instead of necessarily exporting them from the module.

**Comment by michaelfig** [comment]
> I imagine there must be prior art on this. Is there some common practice we could follow? I guess in most of these cases, the library depends on a polyfill-it-if-it-doesn't-exist library, which solves the problem locally. But I don't think we can make `harden` work that way.

Why not?

**Comment by warner** [comment]
Hm, I'm assuming that the embedded WeakMap means all `harden` users in the program need to be using the same instance, and that having each module/library do its own polyfill might not achieve that. I can't claim to have thought it through very carefully, though.

**Comment by michaelfig** [comment]
> Hm, I'm assuming that the embedded WeakMap means all `harden` users in the program need to be using the same instance, and that having each module/library do its own polyfill might not achieve that. I can't claim to have thought it through very carefully, though.

I'm not suggesting a faithful polyfill, just a cheap one (like `Object.freeze` with a "SecurityWarning"), since we have to stop somewhere short of "secure" with a polyfill, or else ice-9 the universe.

**Comment by michaelfig** [comment]
We have avoided this issue by using SES in the frontend.
