### ISSUE TITLE
[ERTP] decimal property

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#119]
follow up to https://github.com/Agoric/documentation/issues/65#issuecomment-559197144_

> If you look at Ethereum's ERC20 tokens, they all have a field called `decimal` which describes how many places the decimal should be moved over for display purposes.
>
> In ERTP, the extents are the smallest denomination of digital asset such that it is always a natural number. We don't currently have a place to put information about how it should be represented to the user, like `decimal` but we do need it.

I imagine a good place for this could be the mint configuration. It's not clear to me how exactly yet
But it could take the form of a `stringify` function that takes units as argument and would return a string representing the units. Example: units representing dollars would be an object with the extent expressed as cents (like the number `1234` for $12.34) and the stringify function would return the string `12.34`

**Comment by erights** [comment]
How does Intl (internationalization API) handle formatting of currency amounts?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

**Comment by DavidBruant** [comment]
I've used it only a little, but i've had a really good experience with it
That said, i'm not sure this is directly relevant to the problem of this issue

This issue is about the fact that if you create a currency with ERTP, you represent it only with natural numbers (like cents for dollars or satoshi for bitcoins), but ERTP does not allow to configure what a canonical string representation for the currency would be. This is where allowing mint authors to provide a `stringify` function would come handy

Where i see the connection is that it can be recommanded to mint authors to use Intl/NumberFormat to write their formatting functions. But ERTP still needs to provide a way to share the `stringify` function so that an application knows how to represent a payment or purse object
