### ISSUE TITLE
Update Dapps for Zoe 0.7.0 release

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1193]
**What is the Problem Being Solved?**

The Zoe API and tool affordances have changed (will change shortly). The Dapps weren't updated in sync with the change to agoric-sdk. 

**Description of the Design**

Updates

**Security Considerations**

Should be released at the same time as Zoe 0.7.0.

**Test Plan**

manual

**Comment by katelynsills** [comment]
Closed by #1143
