### ISSUE TITLE
SwingSet bootstrap failures are silent

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1199]
**Describe the bug**
When the `bootstrap.js` vat's `bootstrap(...)` function returns a rejected promise, it results in a silent failure.

**To Reproduce**
1. Create a `bootstrap.js` that exports `async bootstrap() { throw Error('Failure') }`
2. Run `ag-solo` on it.
3. See no error

**Expected behavior**
A logged error, probably fatal.

**Platform Environment**
- nothing special
- agoric-sdk as of 2020-06-22T00:09:21Z

**Additional context**

@warner I noticed that if the bootstrap vat's `bootstrap(...)` throws an error (ie. returns a rejected promise), it gets swallowed.  Is there any way to improve this so that bootstrap failures become swingset failures?

yeah, that's a good idea. @FUDCo and I were just talking about a mode (mostly for tests) that would make any failed turns into a fatal error, or at least log them

but if bootstrap throws, that should always be fatal

one tricky part is that bootstrap is a `sendOnly` (because it's synthesized by the kernel), so there's no result promise

so the best not-messy thing to do is to watch for an exception in just the first turn

how about we add a flag to the message structure that means "if the first turn of this message throws, that's a fatal error", or at least log it or something (I don't know how we should implement a "fatal error" from within the kernel)

it'll go into `vatManager.js` `doProcess`, and/or `runAndWait`.

**Screenshots**
n/a

**Comment by michaelfig** [comment]
Related to this, is there any way to hand a capability to crash/panic the system to the bootstrap function?  If so, then I could log the error and panic.

This would be preferable especially since an async failure would not be detected even if we watched for an exception in the first turn.

**Comment by warner** [comment]
Hmmm. I wouldn't want to share a new object with the vats (that'll get in the way of Worker-per-vat later), but I can imagine providing a `syscall.panic` to the bootstrap vat.

Moving up a level to liveslots.. in the new-SES branch I'm enhancing the `vatPowers` object (which I think maybe you introduced), mostly for transform functions and metering controls, but it might be a place to add a `panic()` method, which would the be available to the function that creates the root object, and maybe anything else that function chooses to share it with.

@FUDCo and I were talking about marking unit-test-driven vat deliveries somehow, so errors in their processing would be at least logged, hopefully flunk whatever test is running at the time, and maybe even terminate the application. Maybe this annotation should be delivered all the way into the vat, where liveslots could act upon it with this new `panic` authority. Perhaps liveslots could say "if I have panic authority, and if this message was marked as 'panic on failure', then attach a `.catch(err => syscall.panic(err.toString()))` to the result".

**Comment by warner** [comment]
The `bootstrap` message is generated as the kernel starts with a method named `queueToExport()`. `queueToExport` is also used in a few other halfway-outside-the-kernel contexts (dynamic vat creation uses it to notify the manager vat that the new vat is ready to go, or that it's been terminated, and also a lot of unit tests).

In #1219 this method acquires two new features. The first is that it returns a kind of result object, which the caller can poll to see whether the result promise has been resolved or rejected yet. This is only really useful for unit tests, although host applications can grab the `bootstrapResult` from the controller and poll it, if the bootstrap message somehow needed to communicate something back out to its host. The second feature is that you can set a mode along with the message, telling the kernel what to do if/when the message result promise is resolved. Usually these are ignored, but now they can also be logged on rejection, or they can panic the kernel upon rejection. The "dynamic vat is ready" message result is now logged (this would fire if the vat manager had an internal exception while processing that message), and the bootstrap message result is now a panic-on-reject.

The way we panic right now is to set a kernel-wide flag to the Error object, and then check+raise on all entries into the kernel from the outside: specifically `controller.run()`. We also check it on the way out of each crank, but I'm not 100% sure of the Promise chaining so I'd want to test that, say, a panic registered by the second turn of the third crank of the initial `c.run()` would cause the `c.run()` Promise to reject. But the intention is that it does, so the host can tell that the kernel is now broken and shut down the application.

In our "care and feeding of SwingSet" document, we should establish a rule that rejections of the `c.run()` and `c.step()` promises indicate the kernel has failed, it will never work again, and the application should then decide what to do about it. Eventually we'll get the state transactionality cleaned up so we can also document that the saved kernel state is still intact (with instructions on when/if the host ought to commit that state), and that the state pretends that the previous batch of cranks never happened. And some notes on how to decide whether starting it back up again is likely to fall into the same hole it hit before, or if the failure was somehow transient, so a replay might work out better this time.

**Comment by warner** [comment]
also for completeness note that #1206 describes the new API

**Comment by warner** [comment]
Closed by #1219, and we're now seeing reports of tests crashing when the bootstrap method failed (which, in many cases, was being silently ignored before). That sounds like success to me.
