### ISSUE TITLE
Provide a path for values to return from `bootstrap`

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#1206]
### Background

The kernel API has a `queueToExport` method that injects messages into the kernel.  This is used by the swingset controller at startup to send the `bootstrap` message to the bootstrap vat.  It is also exposed on the controller's own API in a slightly augmented form as the `queueToVatExport` method and thence used by swingset-runner to send the `runBenchmarkRound` message (also to the bootstrap vat) when doing performance benchmarking.  It is a one-way interface, in that it merely drops a message onto the kernel's run queue with no return value available or expected (the message is enqueued with its `result` property set to `null`).

### The problem

If the bootstrap vat has a failure processing the `bootstrap` message (or any other message delivered via `queueToExport`), there is no way for that failure to be communicated back to the controller and from there to whatever client application was invoking the controller.  However, in the event of such an error we'd very much like the client to be able to react in some useful way, such as by displaying an error diagnostic or perhaps even terminating the swingset itself.  Possibly the choice of action to take might depend on the nature of the failure.  Normally we'd implement this kind of backchannel by returning a promise for the result of the method invocation that was triggered by the message delivery.  However, since the client in this case is outside any vat (indeed, outside the swingset itself), this pathway is not available: neither the swingset nor its controller inhabit the same plane of existence as the vats.  In particular, we have no CapTP implementation available in the controller layer nor do we wish to comingle vat promises with non-vat promises -- the vat boundary can only pass data.

### Proposed solution

The `queueToExport` method will be changed to create a new kernel promise for the message it is enqueueing, just as if the message had been enqueued by deserializing it from one of the vats as the result of a syscall rather than having been provided exogenously.  This promise will be passed in the `result` property of the message that gets queued, just as if the message had been properly generated by a result-producing eventual send from inside a vat.  Instead of `void`, the return value from `queueToExport` will be a fresh instance of a new kind of object, which for purposes of discussion and humor I will dub (until we come up with a better name) a `completionValue`.  There will be a new kernel table whose keys are the KPIDs of the just mentioned kernel promises and whose values are `completionValue`s.  Note that we expect this table to be very small -- typically 1 or 2 entries; if it gets much bigger than that it means somebody is abusing the `queueToExport` API.

The `completionValue` object represents the state of its corresponding kernel promise.  It is essentially a tri-state value: it lets the holder find out if the kernel promise is still pending or if it has settled, and, in the latter case, what the fulfillment or rejection value was.  Note that it is not itself a promise, since a kernel promise isn't actually a promise either but the kernel's model of the state of a promise between vats.  In addition, since the vat/kernel boundary only passes data, the fulfillment or rejection value it holds will be a copy of the capdata object that is the serialized representation of the resolution, rather than the resolution itself.  This is because the slots of a resolution cannot be translated into actual object references outside a vat, while the capdata object may be printed or inspected by a developer attempting to debug a problem with the bootstrap process.  The state of the `completionValue` for a settled promise is snapshotted at the time its kernel promise is fulfilled or rejected, since the kernel promise itself might subsequently be garbage collected (if a kernel promise is fulfilled to another promise, the `completionValue` will be updated to point to the later promise but will itself continue to indicate that it is in the unsettled state).

The API will look something like:
```
    cv.status(): string;  // "pending", "fulfilled", or "rejected"
    cv.resolution(): CapData; // throws if pending
```

Generally speaking, one should only interrogate a `completionValue` when the kernel is in a quiescent state, e.g., after a call to `step()` or `run()` has returned.  (Question: should we consider having its methods throw if the kernel is not in such a state?)

The kernel's completion value table is ephemeral.  Any messages delivered via `queueToExport` will be recorded for replay in the kernel transcript, but any `completionValue` objects that would have resulted are irrelevant at replay time because the code execution context that was holding them no longer exists.

**Comment by FUDCo** [comment]
@warner

**Comment by warner** [comment]
awesome writeup, great API, ideal functionality. five stars, would review again.
