### ISSUE TITLE
metering dynamic vats

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1208]
In my new-SES branch, I provided for the existing metering-within-vats (specifically Zoe), but I have not yet implemented metering-per-(dynamic)-vat. The Zoe split is coming along, and I'd like to have metering-per-vat ready in time for it to land.

* apply `transformMetering` to the `importBundle()` call the kernel uses to load the new vat
* create a meter for the new vat, add the `getMeter` endowment/lexical to the `importBundle`
* arrange for the meter to be refilled between cranks
* but if the meter ever expires, never refill it again: the dead should stay dead
* arrange to check the meter at the end of each crank for expiration
* if expired, do something minimal to mark the vat as dead, maybe a flag on the ephemeral record
* bonus: notify the admin facet of the vat's demise
* double bonus: reject any promises owned by the vat. Be careful when synthesizing syscalls: think about transcript replay and kernel state persistence.
* figure out what to do with dead inbound references when other vats send messages to it. eventually delete the dead vat's entire c-list
* defer GC for later

**Comment by Chris-Hibbert** [comment]
> but if the meter ever expires, never refill it again: the dead should stay dead

Don't we (eventually) want to arrange for some keeper to be able to perform a pre-mortem intervention? When the meter is on the verge of expiring, ask the keeper if it wants to intercede so it can refill the meter. Clearly not something we're ready to do now, but a consideration to keep in mind. 

Carefully phrased so there's no danger of creating zombies by revivifying the actually dead.

**Comment by warner** [comment]
Yep, definitely. For now, with exactly one meter per dynamic vat, meter expiration == vat death. But we certainly want to get to a place where either a different meter can swoop in and save the vat at the last moment, or there's some synchronous keeper ready to refill the meter just in time. I think we'll still say that dead vats stay dead, but there will be more ways to save a vat.
