### ISSUE TITLE
zoe could give fewer endowments to contracts

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1210]
It should be straightforward to convert the rest to imports. Wanna create an issue and assign step one to me?

_Originally posted by @Chris-Hibbert in https://github.com/Agoric/agoric-sdk/pull/1201_

**Comment by warner** [comment]
The code in `zoe/src/evalContractCode.js` where Zoe creates a set of names to put into the contract's global scope currently (as of new-SES branch) provides:

```js
  const defaultEndowments = {
    assert,
    console: louderConsole,
    harden,
    Nat,
    produceIssuer,
    producePromise,
    sameStructure,
    HandledPromise,
  };
```

We need to nail down what exactly vats (and contracts) get as globals, vs what they get via special `import`/`require` calls that are handled by a `require` endowment, vs what they should import/require that gets folded into the bundle as source code during the `bundleSource` rollup process. But @michaelfig and I think that this `defaultEndowments` list wants to be shrunk down to just `console` and `HandledPromise`.

`assert`, `Nat`, `producePromise`, and probably `sameStructure` can be imported without problems: that adds to the total amount of code in the contract bundle, but they're computationally equivalent.

`harden` should be redundant because all Compartments get harden, it's part of SES. We have a lot of code which does `import harden from '@agoric/harden'`, and we need to decide whether we leave that import in place, or just get it from the global (and declare that this code must always run in a SES environment, which means changes to the test programs that use it, and downstream applications that include it). So removing it from `defaultEndowments` should be trivial, the larger question is whether to remove it from the `myRequire` functions a bit further up.

I have no idea what `produceIssuer` is. If it's pure/powerless, then switching it to an import is probably best.

Changes to this list will affect the environment that dapp contract code runs inside, and since we don't have a clear definition (that I know of) of that environment, we might accidentally violate an expectation. Worst case we cause code outside the repo to start breaking, and we don't notice because the tests for it are outside the repo. Fortunately @Chris-Hibbert wrote a lot of that external code, so I'm sure you'll know what to look for :).

**Comment by michaelfig** [comment]
Also, pending the next batch of eventual-send proposal changes, `HandledPromise` will go away as a global. It will be replaced instead just by methods attached to the existing `Promise` global (and those methods will be added to the SES whitelist, so shimming them becomes convenient).

`produceIssuer` ~~gives you fruits and vegetables~~ produces an Issuer, of course!  It is both pure and powerless.

**Comment by katelynsills** [comment]
It's pure and powerless. Basically, I think what happened is we don't know how to use the lower stacks in the best way, so any help in learning the best practices is much appreciated :)

**Comment by katelynsills** [comment]
I believe this is done in #1414. The defaultEndowments are:

```
  const defaultEndowments = {
    console: louderConsole,
    HandledPromise,
  };
```

**Comment by michaelfig** [comment]
> I believe this is done in #1414. The defaultEndowments are:
>     console: louderConsole,

`console` will probably always be a custom console (scoped to the contract), so it can stay.

>     HandledPromise,

The only reason `HandledPromise` is an endowment is because we haven't yet moved to shimming `Promise.delegate` instead of introducing a new global.  That should go away in the future, but will happen as part of a global renaming and removal of `HandledPromise`.

So yes, this is done (and what is not will be a different issue when the time comes).

Closing!
