### ISSUE TITLE
name all test programs test-XYZ.js

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1211]
`bundle-source` is one of the few (only?) packages that has e.g. `circular.js` and `sanity.js` as test files, rather than as libraries that the real test files import from.

I'd like to rename those files (and any others which are meant to be run by the `tap`-equivalent test runner) to be like `test*.js`, and unify the `test` script lines in all our `package.json`s to use the same glob.

_Originally posted by @warner in https://github.com/Agoric/agoric-sdk/pull/1201#discussion_r445907793

**Comment by warner** [comment]
Also, as @kriskowal pointed out, SES-shim uses `*.test.js` instead of `test-*.js`, so we should talk about whether we'd want to migrate agoric-sdk to that pattern instead.

**Comment by erights** [comment]
@dtribble @warner done, right? Closing.
