### ISSUE TITLE
maybe replace 'harden' import with a global

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1214]
Swingset's `controller.js` and `kernel.js` both contain functions that look somewhat like:

```js
  function kernelRequire(what) {
    if (what === '@agoric/harden') {
      return harden;
    } else {
      throw Error(`cannot require${what}`);
    }
  }
```

which are provided to the kernel and to vats (respectively) as a `require` endowment. While reviewing #1201, @FUDCo said:

    I understand this is to avoid having to change a bunch of existing code.
    I hate this kind of thing, I'll volunteer to do the refactor when the new SES stuff stabilizes.

You rock!

We need to have a group decision about what SES/vat/contract code can expect on the global, what it gets by import, and what it gets by argument. And how that affects the developer experience (i.e. if you get `harden` as a global, your library cannot be imported by applications which aren't using SES, which might be a pain point and reduce the audience for your library, or maybe it's no big deal). But assuming we decide to go with the global, then yeah, the task is to delete the import from everything (agoric-sdk and all the dapp repos), remove it from the `externals` configuration in `bundle-source`, then remove the `@agoric/harden` clause from the `kernelRequire` and `vatRequire` lines. And then (probably) remove the `require` endowments entirely.

But, maybe, leave it in just for the purpose of revealing (in an error) the leftover unbound package name which the bundle depended upon. I was talking to @michaelfig about this today: if a contract imports some random NPM library, and that library's dependency graph happens to be well-behaved and doesn't use any Node.js builtins, then `rollup` will be able to find source code for everything, and the bundle will have no remaining `require` statements. But if something (maybe several levels deep) is *not* so well-behaved, `rollup` will be faced with some `import 'fs'` or `import 'http'` somewhere, and currently rollup emits a warning and then includes a `require('fs')` anyways. When that bundle finally meets `importBundle`, then either the `require` will fail (ReferenceError, or maybe "TypeError: undefined is not a function"), or the `kernelRequire` will fail ("cannot satisfy require('fs')"), and the latter is slightly more informative. *But*, what would be even better is if `bundle-source` rejected it in the first place, and showed the full dependency chain that resulted in attempting to bundle an unbundleable native module, so the contract author could either say "oh bummer, I can't use that library", or "oh hey I'll go bug the author of the not-so-well-behaved module to tame it nicely so I can use it from a SES-confined environment".

_Originally posted by @warner in https://github.com/Agoric/agoric-sdk/pull/1201_

**Comment by warner** [comment]
As discussed in the meeting this morning, `harden` is special: it is part of the SES specification. The future version of JavaScript that we're providing will include `harden` as a global, not a special import. So relying upon it as a global in our vat/contract environments is fine, as is removing all those import statements.

We'll separate the question of whether to remove the *ability* to do the import for later. The task of removing imports can proceed incrementally, one module at a time. When we've finally removed them all, *then* we can decide whether to get rid of `vatRequire`'s support for `@agoric/harden`. We can remove `kernelRequire`'s support much earlier, once we've removed all the imports from `SwingSet/src/kernel/`, because that's an internal interface.

**Comment by michaelfig** [comment]
As a tangent, I would eventually like something I'd call `@agoric/shim`, which may be as simple as:

```js
// Modify globals to closer emulate our desired EcmaScript future.
import './harden-shim'; // if harden is missing, complain and use Object.freeze
import './eventual-send-shim'; // Add Promise.delegate (currently HandledPromise)
import './compartment-shim'; // Add Compartment
```

I want to use this to shim and future-proof library code I intend to write.

**Comment by warner** [comment]
As of the current trunk (4fe3c83a70000cb9f933bf6e158cc2bc1862bae9), we're down to one import of `@agoric/harden`:

https://github.com/Agoric/agoric-sdk/blob/4fe3c83a70000cb9f933bf6e158cc2bc1862bae9/packages/agoric-cli/lib/install-ersatz-harden.js#L3-L8

That's @michaelfig 's domain, and I don't think it's involved in vat/contract code. So I think we can consider this ticket closable without removing that one.

We've removed `harden` from both the `externals` retained by `bundle-source`:

https://github.com/Agoric/agoric-sdk/blob/4fe3c83a70000cb9f933bf6e158cc2bc1862bae9/packages/bundle-source/src/index.js#L45-L52

and the `require` provided to static and dynamic vats:

https://github.com/Agoric/agoric-sdk/blob/4fe3c83a70000cb9f933bf6e158cc2bc1862bae9/packages/SwingSet/src/controller.js#L178-L180

But we still want to remove it from the names honored by the `require()` provided to the kernel bundle:

https://github.com/Agoric/agoric-sdk/blob/4fe3c83a70000cb9f933bf6e158cc2bc1862bae9/packages/SwingSet/src/controller.js#L119-L122

And then, since #362 is closed, I think we can remove support for `require` in static/dynamic/kernel bundles entirely.

**Comment by warner** [comment]
oops, #362 isn't really done yet, I can remove the `kernelRequire` clause for `@agoric/harden`, but I can't remove the `require` endowments yet

**Comment by warner** [comment]
#362 is fixed, I'll make a PR to remove `require` from `vatEndowments` and `kernelEndowments`.
