### ISSUE TITLE
revived Errors have misleading stack trace

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1224]
**Describe the bug**
When code in one vat sends a message to a second vat, and the second vat throws an Error, that Error is serialized by `marshal` on the second side, then deserialized back into an Error object on the first side. The serialized form contains `name` and `message`, but deliberately does not include a stack trace (the internal details of the second vat should be concealed from exterior callers).

However, when the first side deserializes the response and constructs a new `Error` object, the JS engine captures the stack trace leading to the deserialization code. To developers who print the error object, it will look as if `marshal` suffered an internal error, whose `name` and `message` just happen to match ones that the remote vat might have thrown.

I think that if we aren't going to deliver the real stack, we should deliver one that is empty or obviously fake. Ideally, the only stack frame visible on the Error would be a string like `error was remote, stack is unavailable`. If/when we get "deep stacks", it would also be appropriate to include a message/promise UUID which is meaningless to the receiving vat, but which could be correlated by external tools (who have more global debugging authority) with the locally-recorded stack on the far side that created it.

I don't know whether it's possible to control the stack strings that go into an Error object under SES. Just a few days ago @erights walked us through the various APIs used by JS engines (https://v8.dev/docs/stack-trace-api) so we could figure out how SES ought to tame them. Maybe part of our taming shims should introduce an Error constructor that can control the stack trace (`Error.createWithDummyStack(name, message, stackMessage)` ??), which `marshal` could then use when create these less-deceptive Error revivals.

**Comment by erights** [comment]
Done. Closing.
