### ISSUE TITLE
marshal cannot serialize Errors with unexpected .code property

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1226]
**Describe the bug**
While working with Babel inside a vat, I discovered that `marshal` refuses to serialize Errors with unexpected properties. This makes sense (you never know what secrets might be in them), but it causes some confusion. The `marshal` check is this one: https://github.com/Agoric/agoric-sdk/blob/bd57c147061c3f2a9f32cf039bacce0cac50af27/packages/marshal/marshal.js#L156-L168

Apparently Babel catches errors that occur during parsing, and re-throws them with a new `.code` property (in this case, its value was a string: `'BABEL_TRANSFORM_ERROR'`). This happened when my vat was applying the tildot transform but my kernel was (unhelpfully) metering the transform code: the meter ran out in the middle of Babel. I think the same problem would occur if the REPL were given an unparseable string, or a dynamic vat were given a broken bundle.

The original error was thrown in a vat during the processing of some inbound message. Liveslots catches this exception and serializes it (in `thenReject`) to create the arguments of a `syscall.reject()` invocation: https://github.com/Agoric/agoric-sdk/blob/bd57c147061c3f2a9f32cf039bacce0cac50af27/packages/SwingSet/src/kernel/liveSlots.js#L448-L452

The surprising Error is thrown by `marshal` while performing this serialization. Liveslots catches errors during serialization (at the end of `deliver`) and rejects the result promise as if the delivery failed with the `marshal` error instead:
https://github.com/Agoric/agoric-sdk/blob/bd57c147061c3f2a9f32cf039bacce0cac50af27/packages/SwingSet/src/kernel/liveSlots.js#L380-L384

From the caller's point of view, they get a `TypeError(Unexpected own properties in error: code)`, which originates with `marshal`. The original Babel error is lost: `marshal` discards it during serialization.

It took me a while to track down the problem as coming from outside the code I was invoking. I grepped the Babel tree for `Unexpected own properties in error` without luck. I didn't know which message was triggering the error, so I didn't know which method to wrap with a `try { } catch(e) { console.log(e); throw e; }`. I wound up grepping the agoric-sdk tree to discover where the message was really coming from, and then modified `marshal` to dump the error it was attempting to serialize.

One improvement might be to change `marshal` to at least put its own name on the Error it creates: `throw new TypeError('marshal: Unexpected own properties...`). In many cases, Errors don't need to be so self-descriptive because the stack trace tells you where to find out more about them. In this case, the stack trace is discarded, losing that context.

I don't think we'd feel comfortable allowing `.code` (or other non-standard Error properties) through the marshaller. But maybe we should simply strip them instead, and let the subset of known properties through?

cc @erights who certainly has opinions on defensive debugging

**Comment by erights** [comment]
Done. closing.
