### ISSUE TITLE
transforms: import babel internally, simplify API

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1228]
**What is the Problem Being Solved?**
`transform-eventual-send` and `transform-metering` effectively provide string-to-string transformation functions. The first one expands tildot syntax into `HandledPromise` invocations, while the second inserts meter checks into code that is not trusted to behave politely.

The actual APIs are a bit more complex than they could be. Both modules export a "make me a transform function" function, rather than directly exporting the string-to-string function. These tranform-makers expect to be given access to Babel tools as arguments, rather than importing Babel internally:

https://github.com/Agoric/agoric-sdk/blob/bd57c147061c3f2a9f32cf039bacce0cac50af27/packages/transform-eventual-send/src/index.js#L1

https://github.com/Agoric/agoric-sdk/blob/bd57c147061c3f2a9f32cf039bacce0cac50af27/packages/transform-metering/src/transform.js#L9-L18

When I talked with @michaelfig about it, I learned of two motivations for this design. One was that Babel doesn't run nicely under SES (it assumes a lot about its environment), so if the transform functions were to be evaluated inside SES, they'd need to be granted endowments that reference the Babel code evaluated *outside* SES. The other reason was to allow callers to provide their own parser, perhaps one that's smaller than Babel.

At this point, I think I'd like both packages to export a simple string-to-string transform function, rather than a transform-maker. I'd remove the `babelCore`, `babelParser`, and `babelGenerate` arguments from their API (although retaining an options bag to let them be overridden sounds fine to me, if we have a use case for it). When we do this, we'll update the callers in other packages, which currently have dependencies on babel (which should be removed):

* bundle-source
* install-metering-and-ses
* swingset
* cosmic-swingset
* agoric-cli
* zoe
* spawner

**Comment by warner** [comment]
In addition, both transform functions are written to the old-SES `transforms` interface, in which the transforms also got to manipulate endowments at the same time. During the new-SES work, I changed the callers to wrap these old-style transforms in a new-style (string-to-string) API, and I'd like to remove those wrappers.

`transform-metering` imports the `re2` package so it can add it as the `RegExp` global for the transformed code. This should go away, I think. The transform function is responsible for rewriting regexp literals (`/foo\d+/`) into RegExp constructor calls. Downstream callers are then responsible for replacing the `RegExp` global with `re2` to prevent backref explosion.

The metering transform looks at the endowments it's been given and only performs the transform if `getMeter` is present. I think that switch should be removed. The transform also calls this `getMeter` and uses it to charge the length of the function being transformed to the meter. I'd like to think about whether we can perform this elsewhere. The goal is to prevent guest code from exhausting memory/compute/stack by causing a really large string to be evaluated in a Compartment that has the metering transform applied (basically any `eval` by the metered code). That's an important check, but I'm inclined to put it in a wrapper that we feed to the Compartment's `transforms` option rather than making it part of the transformer API.

@michaelfig thoughts?

**Comment by michaelfig** [comment]
> @michaelfig thoughts?

Not many. I like it!

**Comment by warner** [comment]
our transforms are now completely different, I think this ticket is too stale to be useful, closing
