### ISSUE TITLE
make metering sound

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1230]
I know of several issues which prevent our current metering approach from being "sound", that is, there are ways contracts could crash the host process by using too much memory or CPU, in a way that isn't caught by our metering code. We'll need to fix all of these (and probably more that we're currently unaware of).

## Inescapable `Compartment` wrapper

The metering transform is applied to dynamic vats by adding the function to the `transforms` option on a new `Compartment`. However code within that compartment can make a new child compartment, and the child does not currently apply the same transforms.

We need a library function that takes a `Compartment`, fetches its normal `globalThis.Compartment` constructor, wraps it with a version that imposes the extra `transform` function (at the end of any new transforms the child provides), and stomps it down on top of the original. The child compartment should not be able to access its original `Compartment` constructor: it must only be able to reach the wrapper.

This doesn't need support in the low-level Compartment API, but it's fiddly enough that we want to write a library (once, carefully) for people to use (including ourselves).

## `getMeter` as a lexical, not a global

The previous transform rewrites the metered code to inject calls to something like `getMeter().decrement`. This meter object must be available to the injected code, but not the code being metered, because the meter object can be used for both incrementing and decrementing the current usage (specifically the number of stack frames in use, which goes back down as functions return).

This `getMeter` is currently provided as a property of the global, but this means the metered code can retrieve it with `globalThis['get'+'Meter']` or other tricks which would escape any kind of static analysis we might attempt. The fix is to provide it in the global lexical scope, not as a global property. This depends upon a SES [fix](https://github.com/Agoric/SES-shim/pull/356) that's in progress. Once that lands and we're using the new version, we should change our `importBundle` calls and use `globalLexicals: { getMeter }` rather than `endowments`.

## RegExp vs re2

The native JS RegExp object allows backrefs which can cause a complexity explosion with fairly short regexp strings. The metering transform replaces all regexp literals (`/foo\d+/`) with explicit calls to the RegExp constructor, which means we can get control of the process by replacing the Compartment's `RegExp` global. The `re2` library provides a (native-code) RegExp engine that does not include backrefs. So the task is to impose `endowments: { RegExp: re2 }` on all metered Compartments. We'll need the same kind of inescapable wrapper described above.

@erights @michaelfig can you think of any others?

**Comment by michaelfig** [comment]
It might be worth mentioning that all of `re2`'s regexps perform in linear-time (for some relatively large constant factor), since naive Regexp implementations are vulnerable to [REDOS](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS), where their superlinear behaviour can be triggered even without backreferences.

**Comment by michaelfig** [comment]
All our global metering is rather coarse-grained and doesn't wrap some (many) potential culprits that could spend tremendously more resources than bugeted.  We could improve the metering wrappers to be more surgical (taking into account argument lengths or values that trigger non-constant time consumption or greater than zero allocations), but that work would be better invested in low-level metering of the engine itself.

**Comment by warner** [comment]
Yeah, I guess there's a fuzzy line between "soundness" and "accuracy". Our immediate goal is that malicious/buggy contracts should not be able to prevent well-behaved ones from working. But the difference between infinity and "merely large" is not a sharp one.

Maybe the question is "what's the worst a contract could do before it gets terminated"? We definitely want to prevent it from crashing Node, so its memory usage must remain below the Node heap limit, and any stack-size limits must kick in before the kernel gets interrupted or confused or something. The runtime should be limited enough to prevent a validator from missing a voting window. Depending upon how many contract messages can get processed in a single block, that gives us a budget of maybe 5 seconds or so?

Allocations are cumulative, though: a contract which has access to any other vat (say, a Purse) can use that to schedule more work in a future crank (with a simple `p~.getBalance().then(doMoreStuff)`), and that will run in the same block (until we stop using `c.run()` and pay closer attention to CPU-time budgets). So it could get a lot of cranks, and each one could allocate up to its budget, and hang on to that forever. We could accumulate this usage by not refilling the meter between cranks, but as you said before, that may get confusing for contract developers. At some point, we'll probably have per-crank limits as well as a lifetime limit, and either one might trigger.

Yeah, low-level engine metering is the only way to make this work properly.

Maybe the short-term goal is that a **single crank** cannot kill the node, or take more than 5 seconds to complete.

**Comment by warner** [comment]
### `c.evaluate(src, { endowments: { getMeter }})`

This one is scheduled to be removed (https://github.com/Agoric/SES-shim/issues/365), but we should keep it in mind until then.

We create a separate `Compartment` for the metered code, and impose both `transforms: [ transformMetering ]` and `globalLexicals: { getMeter }` upon it. Call that `c1`. When we use `c1.evaluate(code)`, or `c1.import(module)`, that code gets metered.

The code *inside* that compartment can evaluate more code in two ways, all of which need to be trapped so the same transform and lexical can be imposed:

* `eval()`/`Function`: these are provided by the Compartment, and automatically get the same properties as you'd get by doing `c1.evaluate` from the outside
* `c2 = new Compartment()`, then `c2.evaluate(src)` or `c2.import(module)`

As described above, we'll be wrapping c1's `Compartment` constructor (i.e. `c1.globalThis.Compartment`) to automatically add inescapable `transforms` and `globalLexicals` options, so all child compartments are at least as restricted as the first one. We need to make sure there are no options available to this wrapped constructor that could inhibit the metering.

Currently, `c.evaluate()` accepts an `endowments` option: `c.evaluate(src, { endowments: {..} })`. These endowments shadow any given at Compartment-construction time, and would also shadow any `globalLexicals` from that time. If this remains, metered code could do `c2.evaluate(src, { endowments: { ["getMeter"]: fakeMeter } })`, and get control of the `getMeter` seen by the injected code. This would let them run on a bogus (unlimited) meter.

That per-evaluate option is scheduled for removal, which will remove this problem. The only globals/lexicals left will be per-Compartment, not per-evaluation. That will simplify things a lot: if it remained, we'd have to wrap `c.evaluate` too, and filter out `getMeter` from the list of `endowments` its option bag would accept.

We need to think through the rest of this scope chain and make sure there's no way for the metered code to either steal or override `getMeter`. @kriskowal says to think about the scope chain as `globalThis` < `globalLexicals` < `moduleScope`, and also (at the `c.evaluate` level) `globalThis`, `globalLexicals`, `globalContour`.

**Comment by erights** [comment]
Funny, today when I saw the title of this issue my first thought was "How would we generate metering sounds?" "What does metering sound like?"

**Comment by michaelfig** [comment]
> "What does metering sound like?"

"Tick-tick-tick-tick-tick-tick-tick-tick-tick-tick-tick-tick-tick-tick-BOOM!"

**Comment by warner** [comment]
@Chris-Hibbert caught up to the first limitation sooner than I expected. In his split-Zoe work, the dynamic vat is loaded with a "ZCF" facet, which then uses `importBundle` to load the contract code. The ZCF code is subjected to the metering transform, because it is loaded into the dynamic vat's `Compartment` (and the kernel's dynamic-vat loading code adds that transform to the Compartment options). But ZCF doesn't provide any transform options when it calls `importBundle(contractBundle)`, because those really ought to be imposed upon all uses of the `Compartment` constructor that's available everywhere in the dynamic vat. As a result, the metering transform is not being applied to the contract code, and the tests which exercise that metering are failing.

**Comment by dckc** [comment]
Sound metering is addressed by using metering in the XS engine.
