### ISSUE TITLE
yarn test leaves a changed go.mod file as debris

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#1253]
Running a `yarn test` that tests cosmic-swingset (i.e., either the `cosmic-swingset` directory or running all the tests globally) modifies `packages/cosmic-swingset/go.mod`, which then keeps sneaking into my commits.  Please make it stop doing this.

**Comment by FUDCo** [comment]
@michaelfig

**Comment by michaelfig** [comment]
This is inevitable, if your version of Go disagrees enough with what everybody else is using.  If the disagreement causes a different `go.mod` to be generated, then we'll just fight back and forth with what is checked in.

I have:
```
$ go version
go version go1.14.2 darwin/amd64
$ 
```

What do you have?

**Comment by michaelfig** [comment]
(I can add a flag to prevent Go from modifying the `go.mod`, but then your builds and tests will fail.  Let me know if that is better.)

**Comment by FUDCo** [comment]
> I have:
> 
> ```
> $ go version
> go version go1.14.2 darwin/amd64
> $ 
> ```
> 
> What do you have?

The machine it says `go version go1.13.5 darwin/amd64`

Was there something that should have told me that upgrading go was called for?  How would I have suspected that this was the problem?

If there was some kind of tickler that would tell me to upgrade it, I would.  Having a build fail once with a warning that I needed to upgrade would be fine.  One build failure is less hassle than constantly having to edit commits to take this file out.

Also, how do I upgrade it?

**Comment by michaelfig** [comment]
I don't understand why the tickler didn't work.  The `go.mod` has a version requirement of `go 1.14` (on line 3), but your compiler didn't squawk at it?

> Also, how do I upgrade it?

https://golang.org/dl/

**Comment by michaelfig** [comment]
> I don't understand why the tickler didn't work. The `go.mod` has a version requirement of `go 1.14` (on line 3), but your compiler didn't squawk at it?

Ah, it doesn't do what it says on the tin.  The version isn't used unless within a "build tag". https://github.com/golang/go/issues/23969#issuecomment-367806204

I've made a PR, and tested that it fails compilation if the version is wrong (i.e. lower than the specified).
