### ISSUE TITLE
CTP_RETURN should not delete the question

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1259]
BTW, an additional thing to possibly comment, once understood:

```
<Zarutian_HTC> dustyweb: one thing I noticed about CTP_RETURN that the question gets deleted. No idea why.
<Zarutian_HTC> seem to prevent usage patterns like: const t1 = remoteObj~.x(); t1.y(); t1.z();
<dustyweb> Zarutian_HTC: yes that is curious
<dustyweb> Zarutian_HTC: mind if I put that on the issue tracker?
<Zarutian_HTC> sure
<dustyweb> Zarutian_HTC: I have a guess
<dustyweb> it's an attempt to prevent things from getting too out of hand before GC support in captp
<dustyweb> .js
<Zarutian_HTC> right
<Zarutian_HTC> the gc thing requires weakref and post mortem finalization
```

Are we right? :)

_Originally posted by @cwebber in https://github.com/Agoric/agoric-sdk/pull/1139#issuecomment-634963639_

**Comment by michaelfig** [comment]
> Are we right? :)

Yes you are.  This needs to be changed.

**Comment by michaelfig** [comment]
Oh, maybe not.  There may be a more fundamental misuse of the `questions` table, but I see that it is only actually used by the (one-per-questionID) `CTP_RETURN` call.  Can @cwebber or @Zarutian explain how that `questions` entry would be reused?

**Comment by michaelfig** [comment]
Indeed, I ran:
```js
    const t1 = E(rightRef).x();
    const [y, z] = await Promise.all([E(t1).y(), E(t1).z()]);
```

and both the `y` and `z` results were successful.

**Comment by zarutian** [comment]
Reused as in re-alloted to a diffrent question or reused as a target of eventual-sends?

Try putting in delay between the .x() message and the .y(), .z() messages and see if those latter then fail.

**Comment by michaelfig** [comment]
> Reused as in re-alloted to a diffrent question or reused as a target of eventual-sends?

The questions table is only for in-flight calls.  The userland already receives an unresolved HandledPromise as the results of a given RPC, and can copy that promise wherever it wants.  When the in-flight call is resolved or rejected (by receiving `CTP_RETURN`), the HandledPromise is also resolved or rejected.  There will never be another `CTP_RETURN` for that question, so the questions table can be cleaned up.

Some of the state present in the 4 tables model is different because it lives in the HandledPromises as well.

> Try putting in delay between the .x() message and the .y(), .z() messages and see if those latter then fail.

I did, and it succeeds.

If you do a text search for "questions" in captp.js, you will find that the map is only read by `CTP_RETURN`, which only happens once per question.  After that, the question can be deleted, but only because its HandledPromise still lives.

The answers, on the other hand, still need to persist, as the pipelined messages can target them.  Maybe that's the table you were concerned about?

**Comment by zarutian** [comment]
Ah, I think I understand now how this works in this captp opposite how it worked in captp of E.

If the .y() and .z() messages are made and sent before CTP_RETURN comes from the other end they use the question id as the target identifier. But if they do after they use the export id of the resolved question.

What happens though if the link this goes over is higher latency?
That is, the remote end sent CTP_RETURN while messages using the question id as target (or argument) is still in flight?

**Comment by zarutian** [comment]
After staring at captp.js some more, the deletion of the question from the question table is harmless as the HandledProxy that has curried into it the question id used.

However, the answers table slowly memory leaks in current implementation.
But that is fixable when WeakRefs and postmortem finalizers come into javascript.

**Comment by zarutian** [comment]
Hmm... another test case because I do not see how question ids get marshalled when the question is used as an argument:
`const t1 = E(rightRef).x();
 const t2 = E(anotherRef).y(t1);`

**Comment by michaelfig** [comment]
Thanks for this... I'm in the middle of a hackathon, so I won't attend to this immediately, but I appreciate your feedback and will address it when I can.

**Comment by zarutian** [comment]
I do not know the ettique of bumping issues but I did have a question: what is the questions map in captp.js used for? the only possible use for it I can see in the current implementation is sort of gc root.

**Comment by michaelfig** [comment]
> I do not know the ettique of bumping...

Your comments are welcome!  I just won't have time to get to them immediately, but I will try to answer and improve the implementation.

**Comment by zarutian** [comment]
Here is my evolving take on captp from the perspective of E
https://github.com/zarutian/agoric-sdk/blob/zarutian/captp_variant/packages/captp/lib/captp_v2.js
I though have not done the capdata and liveslots seperation yet.
Feel free to read for your edification.

**Comment by michaelfig** [comment]
All the testing I did with `CTP_RETURN` was successful, so I'm closing this issue.

@zarutian, if you want to discuss your `captp` implementation more, feel free to open a `question` or `feature` issue specifically about it.  Another appropriate venue would be https://github.com/tc39/proposal-eventual-send/issues
