### ISSUE TITLE
Bug: Intermittent error when running contract/deploy.js on all three dapps

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1269]
**Describe the bug**

I run `agoric deploy contract/deploy.js` and get the error message `SyntaxError: Cannot use import statement outside a module`, indicating that the `import fs from 'fs';` is the problem. 

**To Reproduce**
1. cd to dapp-encouragement
2. run `agoric start --reset`
3. in another tab, enter `agoric deploy contract/deploy.js`. Note that this may or may not throw the error.
4. enter `agoric deploy api/deploy.js`. This also may or may not throw the error
5. repeat steps 2 through 4 until the error is reproduced.

**Expected behavior**
There should be no error.

**Platform Environment**
MacOS 10.15.5, nvm node version is "system"

**Screenshots**
<img width="620" alt="Screen Shot 2020-07-07 at 2 15 05 PM" src="https://user-images.githubusercontent.com/2441069/86845392-48428800-c05e-11ea-9d2e-a753db8c79ac.png">

**Comment by michaelfig** [comment]
@katelynsills Do you still see this error?  I haven't seen it in a long time.

**Comment by katelynsills** [comment]
I haven't seen it in a while either. Let's close and reopen if we do ever see it.
