### ISSUE TITLE
zoe: unexpected asset leads to unhelpful error message

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1274]
**Describe the bug**
I'm haphazardly trying to get a zoe contract working. I'm not yet sure what I'm doing wrong, but the error message I'm seeing is:

```
LOGGED ERROR: key not found: Object <[Object: null prototype] {}> {
  isMyIssuer: [Function: isMyIssuer] Function <Function <[Object: null prototype] {}>>,
  getAllegedName: [Function: getAllegedName] Function <Function <[Object: null prototype] {}>>
} Error <Object <[Object: null prototype] {}>>: "key" not found: (an object)
See console for error data.
    at Object.complain (/home/warner/stuff/agoric/agoric-sdk/packages/assert/src/assert.js:164:19)
    at fail (/home/warner/stuff/agoric/agoric-sdk/packages/assert/src/assert.js:190:20)
    at assert (/home/warner/stuff/agoric/agoric-sdk/packages/assert/src/assert.js:217:5)
    at assertKeyExists (/home/warner/stuff/agoric/agoric-sdk/packages/weak-store/src/weakStore.js:19:5)
    at Object.get (/home/warner/stuff/agoric/agoric-sdk/packages/weak-store/src/weakStore.js:27:7)
    at getAmountMathForBrand (/home/warner/stuff/agoric/agoric-sdk/packages/zoe/src/zoe.js:360:54)
    at /home/warner/stuff/agoric/agoric-sdk/packages/zoe/src/cleanProposal.js:64:5
    at Array.map (<anonymous>)
    at coerceAmountKeywordRecord (/home/warner/stuff/agoric/agoric-sdk/packages/zoe/src/cleanProposal.js:63:34)
    at cleanProposal (/home/warner/stuff/agoric/agoric-sdk/packages/zoe/src/cleanProposal.js:108:10)
```

(of course, that *is* the console, so `See console for error data` isn't giving me any more to go on).

I *think* that this is Zoe using `cleanProposal.js` to validate an Offer somewhere in my program, because that file's line 108 is on the stack trace:

```js
  want = coerceAmountKeywordRecord(getAmountMath, want);
```

And I think it means my `want` list includes an asset whose Issuer or Brand is not among the set known to the Zoe instance. But I don't know what the unknown Brand is (it is described as `(an object)` in the exception), nor do I know what Brands *are* present in the map.

If this error is likely to happen to other beginners, it might be nice for that assertion to make a brief attempt to unpack the unrecognized `key` and display something more helpful. If it's a real Brand, maybe we should put a `toString` on it? If it's a Presence for a remote Brand (which makes more sense), this might be an argument for some of the named-interface/Unum designs to let Presences include some non-normative descriptive properties for use by debugging. Maybe the Presence could include a type and description which `marshal` or liveSlots registers with `console` or assert's `details`, so it could be rendered in debug messages later?

**To Reproduce**
Grab the `dapp-token-economy` repo from agoric-labs, commit `7a77c77`. Do `yarn test`.

**Comment by katelynsills** [comment]
Related issue that explains why we easily can't display information about brands in an error message currently: https://github.com/Agoric/agoric-sdk/issues/990#issuecomment-619274884

**Comment by katelynsills** [comment]
This error is now better: `brand not found`.

However, we still can't easily display information about brands in an error message https://github.com/Agoric/agoric-sdk/issues/990#issuecomment-619274884

I think this particular error may improve with the refactoring of Zoe, though, so we should revisit after that happens.

**Comment by katelynsills** [comment]
Closing as the remaining problem is covered by #990
