### ISSUE TITLE
bug: bundle-source generates invalid bundle

### ISSUE THREAD

**Issue by kumavis** [Agoric/agoric-sdk#1281]
**Describe the bug**
`bundle-source` creates an invalid bundle when transforming the below text
```js
// below is the bad voodoo
//         */
// above is the bad voodoo
```
the javascript is transformed into the following invalid code with error
`SyntaxError: Unexpected token '*'`

```js
"(function getExport(require, exports) {   'use strict';   const module = { exports };     

'use strict'; /* below is the bad voodoo*/ /* */*/ /* above is the bad voodoo*/
  return module.exports;
})
//# sourceURL=/bundled-source/bug.js
```

this can be found in the `zlib` package of 
[rollup-plugin-node-builtins](https://github.com/calvinmetcalf/rollup-plugin-node-builtins), specifically [here](https://github.com/calvinmetcalf/rollup-plugin-node-builtins/blob/63ab8aacd013767445ca299e468d9a60a95328d7/src/es6/zlib-lib/deflate.js#L353)

**Comment by warner** [comment]
cc @michaelfig 
I wonder if this is coming from rollup, or from something we've added on top of it (the tildot or metering transforms).

**Comment by michaelfig** [comment]
It's the bundle-source comment transform: needs to, e.g. `value = value.replace(/\*\//g, '*X/')` when converting comment contents into block comments.
