### ISSUE TITLE
upgrade to SES-0.9.0

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1290]
Upgrading to yesterday's new SES-0.9.0 release. There's one problem with `String.toLocaleLowerCase`, which was removed in 0.9.0, but is used by `rollup`, which causes our `bundle-source` package to break. I'll add a temporary `patch-package` patch to change rollup to use `toLowerCase` instead. The next SES release will probably bring that back (https://github.com/Agoric/SES-shim/issues/378).

**Comment by erights** [comment]
See https://github.com/Agoric/SES-shim/pull/382

**Comment by warner** [comment]
SES-0.9.1 fixes that problem, so I'll push a new version of this branch that omits the `patch-package` hack.
