### ISSUE TITLE
[ERTP] Rename `produceIssuer` to `makeIssuerKit`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1292]
**What is the Problem Being Solved?**

`produceIssuer` is a confusing name for a function that returns `{ mint, issuer, brand, amountMath }`. We thought we might be able to make a distinction between `produce` and `make` such that `produce` can return such a bundle, but that's not very clear.

**Description of the Design**
Rename to `makeIssuerKit`, where `kit` is the new term for a bundle of things returned that are all interconnected.

**Security Considerations**
None

**Test Plan**
Current unit tests

**Comment by zarutian** [comment]
perhaps, "produceIssuerKit"? that way the grocers' puns dont shrivel ;3

(Injected comment only for levity)

**Comment by katelynsills** [comment]
Closed by #1305
