### ISSUE TITLE
"kerneldump --filedb" (no TARGET) crashes

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1298]
**Describe the bug**
I used swingset-runner to run a little demo vat, then ran `kerneldump --filedb` to display the final kernel state. The program crashed with:

```
$ node -r esm ../packages/swingset-runner/bin/kerneldump --filedb
/home/warner/stuff/agoric/agoric-sdk/packages/swingset-runner/src/kerneldump.js:1
TypeError: Cannot read property 'endsWith' of undefined
    at main (/home/warner/stuff/agoric/agoric-sdk/packages/swingset-runner/src/kerneldump.js:108:14)
    at Object.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/swingset-runner/bin/kerneldump:8:1)
    at Generator.next (<anonymous>)
```

(I used `node` instead of directly invoking `kerneldump` because the shbang line reads `#!/usr/bin/env -S node -r esm`, and at least on MacOS 10.14.6, the `env` program does not accept `-S`. I seem to remember we debugged this at one point, or learned that the linux boxes used by CI behaved differently than our local laptops).

The `--help` text, and the options-processing code, both suggest that running `kerneldump` without a primary argument means "look in the current working directory for a statedir". But the order in which `target` is processed precludes that case from working: it attempts to do `target.endsWith()` on an `undefined`, which fails.

```js
  const target = argv.shift();
  let kernelStateDBDir;
  if (target.endsWith(dbSuffix)) {
    kernelStateDBDir = path.dirname(target);
  } else if (dirContains(target, dbSuffix)) {
    kernelStateDBDir = target;
  } else {
    kernelStateDBDir = path.join(target, 'swingset-kernel-state');
    if (!dirContains(kernelStateDBDir, dbSuffix)) {
      kernelStateDBDir = null;
    }
  }
```

I think the fix is to either rearrange the cases and start with a `if (target === undefined)`, or modify the first two conditionals to read `if (target && target.endsWith(dbSuffix))` and `if (target && dirContains...`.

**To Reproduce**

* pick a vat basedir (with at least a `bootstrap.js`)
* run `swingset-runner --filedb`, let it run to completion
* run `kerneldump --filedb`

**Comment by FUDCo** [comment]
Closed by #3214
