### ISSUE TITLE
Pipelining support

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#13]
For proper pipelining, we will need to create a `BasePromise` class that has the necessary hooks to forward messages from one `ERelay` to another.

Look at https://github.com/ysmood/yaku/blob/master/src/yaku.core.js for how this can be done minimally, and all we'll require is the ES5-compatible `BasePromise` constructor function with its prototype.

**Comment by erights** [comment]
@michaelfig I'm assigning both of us and closing. If I'm missing something, please let me know or reopen.
