### ISSUE TITLE
Separate `home.*` into `chain.*` and `local.*`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1327]
**What is the Problem Being Solved?**

There is often confusion as to whether objects in `home` are actually decentral services (on the chain), or local-to-the solo (closely held).

**Description of the Design**

We will create new `chain` and `local` endowments to act as containers for the presences from each of those sources.

In order to have a smooth transition, for some time we will keep `home` intact, with the intent of deprecating it only when all clients (first, the Agoric documentation site, and then dapp deploy scripts) have been updated.

For deploy scripts, we will migrate from just providing a single mixed bootstrap object (current `home`) over CapTP, by migrating it to include `{ chain, local }`, and eventually remove everything from the bootstrap object except `{ chain, local }`.

**Security Considerations**

Improved security and clarity: the ag-solo REPL will be explicit about where you fetch a reference from.

At first, these changes will be opt-in, which will not impact security negatively, then they will become mandatory, which will improve security.

**Test Plan**

Continue running existing integration tests to ensure compatibility.

Check that a branch of `dapp-encouragement` passes integration tests with all references to the `home` bootstrap object replaced by appropriate `chain.*` and `local.*` references.

**Comment by erights** [comment]
I like the distinction. `local.*` is a fine term for one side of the distinction. I don't like `chain.*` for the other side, as that other side will often not be a chain. We should find a term that's about the difference in purpose rather than about one particular substrate technology.

**Comment by katelynsills** [comment]
I really really like this idea.

> I like the distinction. `local.*` is a fine term for one side of the distinction. I don't like `chain.*` for the other side, as that other side will often not be a chain. We should find a term that's about the difference in purpose rather than about one particular substrate technology.

Hmm, I think in this case, what we are referring to is actually a chain or a simulated chain. So I wouldn't see it as referring to the "other side" but actually a chain. If we refer to something else which is not a chain, I think that would be named something else

**Comment by michaelfig** [comment]
> > I like the distinction. `local.*` is a fine term for one side of the distinction. I don't like `chain.*` for the other side, as that other side will often not be a chain. We should find a term that's about the difference in purpose rather than about one particular substrate technology.
> 
> Hmm, I think in this case, what we are referring to is actually a chain or a simulated chain. So I wouldn't see it as referring to the "other side" but actually a chain. If we refer to something else which is not a chain, I think that would be named something else

It's not just the "chain", but it's also not "the other side".  Both of these terms are pretty center-of-the-universe terminology.

Can we just call it `agoric.*`?  It's specific, it reflects our brand, and it's still short.

**Comment by michaelfig** [comment]
Closing until somebody tears down the bike shed to paint it a different colour.

**Comment by erights** [comment]
Sad to see this closed. I'd rather see the split happen with names I don't like than for it to not happen. It seems like a) the split in non-controversial, and b) `local` for that side is non-controversial. The only names suggested for the other side are `chain` and `agoric`. I prefer `agoric` but do not object to `chain`.

Rethinking my objection to chain led me to contemplate the linguistic phenomenon by which a word gains meaning by association, often accidental association. What we might once have called a "foo scandal" we might now call a "fooGate", merely due to the name of a hotel. In like manner, perhaps "chain" will come to mean "a highly credible and widely shared virtual machine which reliably runs programs with mutually suspicious participants". No blocks or hash chaining necessarily involved.

**Comment by michaelfig** [comment]
> Sad to see this closed.

Oh, I should have been more explicit.  It's closed because I went ahead and "painted the bike shed" with `agoric` and `local` (landed in the linked PR #1336).

I just meant that if anybody disagrees with that, they can reopen the discussion, but for now this job is done.

**Comment by erights** [comment]
Awesome, thanks!
