### ISSUE TITLE
remove support for within-same-vat metering

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1341]
Now that the zoe-split PR has landed, Zoe no longer needs support for metering code that shares the zoe vat (instead, all the code it would want to meter now lives in a separate dynamic vat). This will remove `makeGetMeter` and `transformMetering` from `staticVatPowers`.

@michaelfig pointed out that `spawner` is still using this functionality, so a subtask is probably to find a way to move spawner off to dynamic vats: #1343

**Comment by katelynsills** [comment]
I think there's an open question of whether the spawner is worth spending time on. I had originally thought that the spawner would be how we mint payments, but it appears we're going to be using Zoe for that. Currently we use the spawner to run long-lived but local code, like handler.js in the dapps. It's a bit of a weird usage since it doesn't use the spawner invitations. Should we rewrite the spawner to focus only on this one usage? Then we could get rid of the old tests which have been skipped.

**Comment by Chris-Hibbert** [comment]
I think the existing focus of the spawner is still valuable. People will want to write contracts with visible source on-chain. We've come up with a couple of use-cases, but I see this as an essential escape valve for our customers to be able to write many different things that don't fit Zoe's paradigm.  We've show that these can be done within Zoe, eschewing Zoe's protections, but it seems like giving customers an alternative that looks built for that purpose would be better than documenting how to use Zoe without taking advantage of Zoe's guarantees.

**Comment by erights** [comment]
> with visible source on-chain

This implies support for authenticity of transparency. That's what the invites are about. Spawn without invites is neither usefully transparent nor (when on a chain) usefully opaque.

**Comment by warner** [comment]
I heard @michaelfig say that our current needs (API deployment on ag-solo) are minimal, and would be met by a spawner which merely knew how to create a dynamic vat, import a bundle into it, and return access to its root object. I could rewrite `spawner` into that form on my own. Once that was complete, I could remove support for within-same-vat metering.

But, if we think that spawner wants to grow back into something that provides authenticity, then the thing I wrote would be short-lived, and I'm not sure that's worth the effort, if the only purpose is to remove within-same-vat metering. I think we need to remove that sooner or later, but I don't *think* it affects soundness (#1230) because dynamic vats can't access it.

So here's a different question, probably for @michaelfig : would it be ok if I merely removed metering support from our current spawner? I'd leave in the installation/offer/invitation stuff, but I'd change the `importBundle` call to remove the `getMeter` endowment. Code loaded by a spawner would share the vat with the spawner itself, and could kill the spawner with an infinite loop. But the API would remain the same, and it'd be a lot less work. And I could still remove within-same-vat metering.

**Comment by Chris-Hibbert** [comment]
If the current spawner would work in this state, including installation/offer/invitation, then what's missing from declaring that it works, but isn't currently used?

If we want compatibility with the current forms of installation/offer/invitation, I'd be happy to upgrade those to compatible APIs.

**Comment by warner** [comment]
I think I assumed that metering support was critical, and to retain that I'd have to rewrite the spawner to use dynamic vats. If metering support is not necessary, then the delta to remove metering is a lot smaller and there are fewer questions of API changes to answer. But I couldn't tell if metering was needed here.. I don't think `spawner` has any tests that exercise it, and it's not clear to me whether the API deployment thing needs to distrust the code it's loading into the ag-solo.

**Comment by michaelfig** [comment]
The spawner needs to distrust the loaded code.  Infinite loops will hang the whole ag-solo, which is terrible if it's connected to assets.  I would go further and say that the repl also needs metering.

**Comment by warner** [comment]
Ok, I'm hearing that the spawner needs metering, and it needs the fancy installation/offer/invitation API. So I'm going to put off removing same-vat metering for now, and wait for someone to have the time to address #1343 and update the spawner to use a dynamic vat (which will get metering for free).

**Comment by warner** [comment]
when we remove this, we can close #1209 as wont-fix.
