### ISSUE TITLE
migrate from producePromise() to makePromiseKit()

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1349]
**What is the Problem Being Solved?**

Our new naming convention for a function that makes something important, and returns a record that includes other things, and might or might not include the important thing is makeFooKit.  `producePromise()`, which used to be `makePromise()` should follow that path.

**Security Considerations**

pay attention to migration issues.

**Test Plan**

existing tests should be sufficient.

**Comment by erights** [comment]
In progress at #1329
