### ISSUE TITLE
ERTP types.js correction around line 258

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1371]
```
 * If payment is an unresolved promise, throw an error.
```
If payment is a promise, throw an error.

_Originally posted by @erights in https://github.com/_render_node/MDExOlB1bGxSZXF1ZXN0NDYwNjg2MzI3/pull_requests/unread_timeline_

**Comment by erights** [comment]
That link is broken. See https://github.com/Agoric/agoric-sdk/pull/1357#discussion_r465871018 instead
