### ISSUE TITLE
[ERTP] Pre-make deposit facet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1372]
```
* @property {() => DepositFacet} makeDepositFacet
```
Freshness doesn't do anything useful here. Prefer `getDepositFacet` and pre-make one and return the same one each time.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/1357_

**Comment by zarutian** [comment]
Good, this makes writing an Agoric contract version of [the grant matcher puzzle](http://www.erights.org/elib/equality/grant-matcher/index.html) much easier using [E.join](http://erights.org/elib/equality/after-both.html) or js equaliant.

(Basically making sure that the deposit facets of the benefectee given by the grantors is the same facet)

**Comment by katelynsills** [comment]
should be `getDepositFacet`
