### ISSUE TITLE
Sometimes we use the singular `mathHelper` Elsewhere we use the plural

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1376]
Sometimes we use the singular `mathHelper` as above. Elsewhere we use the plural `mathHelpers`. The type is `MathHelpers`. Why aren't all these singular? Each would then be an individual MathHelper. The plural would then non-confusingly be for many of them.

The mathHelperName parameter should be optional

_Originally posted by @erights in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDYxMjg0NDE5/pull_request_reviews/more_threads_

**Comment by erights** [comment]
That link to the original posting is broken. See instead https://github.com/Agoric/agoric-sdk/pull/1357#discussion_r465437364

**Comment by katelynsills** [comment]
Closed in https://github.com/Agoric/agoric-sdk/pull/1414
