### ISSUE TITLE
Remove obsolete producePromise package

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1377]
About 
https://github.com/Agoric/agoric-sdk/blob/d9bc9ecc7fb2fe73c3fb08d978db5928e5663b5c/package.json#L18
at 
https://github.com/Agoric/agoric-sdk/pull/1329#pullrequestreview-461354084 
@warner writes:

> I think this was a typo, because this PR did not also rename packages/produce-promise/everything to packages/producePromise/. This doesn't seem to be hurting anything (maybe yarn just ignores a workspace entry when the corresponding directory is missing?), but it effectively deletes @agoric/produce-promise. So @erights you might as well go ahead and make a PR to delete the packages/produce-promise/ directory, this entry in workspaces, and the .github/workflows/test-all-packages.yml job.

**Comment by warner** [comment]
@michaelfig oh, did we want to publish "one last version" of `@agoric/produce-promise` with a deprecation message and a README that points users at the new name?

Probably not important, but if we did want to do that, then before deleting `producePromise`, we'd want to rename it back to `produce-promise`, add the deprecation stuff, make a release, and *then* delete it.

**Comment by michaelfig** [comment]
> Probably not important, but if we did want to do that, then before deleting `producePromise`, we'd want to rename it back to `produce-promise`, add the deprecation stuff, make a release, and _then_ delete it.

I think it is legitimate to branch off of an earlier commit, make and tag a release, and never have that tag hit the main branch.
