### ISSUE TITLE
Zoe is gullible to issuer's allegation of brand

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1378]
https://github.com/Agoric/agoric-sdk/blob/d9bc9ecc7fb2fe73c3fb08d978db5928e5663b5c/packages/zoe/src/state.js#L208
together with
https://github.com/Agoric/agoric-sdk/blob/d9bc9ecc7fb2fe73c3fb08d978db5928e5663b5c/packages/zoe/src/state.js#L229-L231
enters a binding from the brand that the issuer alleges to an issuer record which includes the issuer. But a malicious issuer could report someone else's brand, disrupting Zoe's possible later attempt to register the true issuer of that brand. We just need to also check `brand.isMyIssuer(issuer)` to ensure they are mutually acceptable to each other. The pair may still misbehave, but they can't interfere with a later attempt to register the true owner of that brand.

There may be similar vulnerabilities elsewhere we ask an issuer for its brand without asking the brand's opinion.

**Comment by katelynsills** [comment]
Yup, this is indeed a vulnerability. We use the issuerTable in a couple of places: the Zoe Service, the Contract Facet, and the wallet. We should check each of these places. I think the Zoe redesign PR is an appropriate place for this change.

**Comment by katelynsills** [comment]
@erights does this address the vulnerability for at least the Zoe package? https://github.com/Agoric/agoric-sdk/pull/1357/commits/4ec0070a4889db303d06289b5973fb92c8ab9a54

**Comment by erights** [comment]
Yes, that looks good.

**Comment by katelynsills** [comment]
Fixed in agoric-sdk in #1414 but we should remain aware of this issue.

**Comment by katelynsills** [comment]
Closed in #1443
