### ISSUE TITLE
Typescript non-null assertion is postfix bang

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#14]
Unfortunately, the Typescript folks have [already coopted postfix bang](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) (at least in .ts files, not .js).  Not sure if that conflict is going to be problematic.

**Comment by katelynsills** [comment]
I think we can close this as we went with `~.` instead.
