### ISSUE TITLE
[Zoe] Add Zoe method that takes an invitation and returns installation, instance, instanceRecord etc.

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1456]
**What is the Problem Being Solved?**

this is modeled on `getInvitationFields()`, currently in zoeTestHelpers. The observation is that clients outside the contracts often have an invitation and want access to verified value of various fields. `getInvitationFields()` hides the way that it's retrieved from the inviteIssuer. To make this easier to use, we should add methods to zoe that return the info that Zoe guarantees to be present in the invitation.

**Description of the Design**
instead of 
```
export const getInvitationFields = (invitationIssuer, invitationP) =>
  E(invitationIssuer)
    .getAmountOf(invitationP)
    .then(amount => amount.value[0]);
```
zoe can synchronoously access the individual fields.

**Security Considerations**

The only security consequences are that clients of the API will be less aware of the invitation issuer's role.

**Test Plan**

None.

**Comment by erights** [comment]
See https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470235092

**Comment by katelynsills** [comment]
Closed by https://github.com/Agoric/agoric-sdk/pull/1414
