### ISSUE TITLE
Multipool Autoswap - TOCTOU error due to stateful assumption across `await`

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1461]
https://github.com/Agoric/agoric-sdk/blob/cec9e48d2af8044c03ac3cefb3710e2dac6db4dd/packages/zoe/src/contracts/multipoolAutoswap/pool.js#L151-L155

On lines 151 and 153 we check that these new keywords are not yet registered. (This is what the confusing name `assertUniqueKeyword` is about.) But then we do an `await` before we register them (lines 165 and 167). During that await, we might have done the same thing, resulting in an (undetected?) collision on the same keywords, which is exactly what this `assertUniqueKeyword` was supposed to prevent.

**Comment by erights** [comment]
The fact that these `await`s stay within our Jessie restriction on `await` did not save us here. I don't see that there is any plausible shallow static analysis that would have flagged this danger either. The actual bug will accidentally occur so rarely as to escape almost all testing efforts that do not already know to look for this bug here.

Beware `await`! Even with all of our disciplined static rules, and upcoming static hazard checks. These are not enough.

**Comment by dtribble** [comment]
The same issue would arise with a `then` version. There are other ways that this contract should be streamlined using the new APIs (like it still uses and async `makeEmptyOffer`).

**Comment by katelynsills** [comment]
We removed `makeEmptyOffer` so it cannot be using that method.

**Comment by dtribble** [comment]
In any case, the lines doing verification of the brand or both strange to a normal programmers and not very async-friendly.  Better code would be either:
```javascript
    const secondaryBrandP = E(secondaryIssuer).getBrand();
    const brandMatches = await E(secondaryBrand).isMyIssuer(secondaryIssuer);
    const secondaryBrand = await secondaryBrandP;
```
Or 
```javascript
    const secondaryBrandP = E(secondaryIssuer).getBrand();
    const [secondaryBrand, brandMatches] = await Promise.all([
           secondaryBrandP, E(secondaryBrand).isMyIssuer(secondaryIssuer)]);
```
I would not expect clients of our API to write either of those. Thus, I think it needs a helper or direct support:
```javascript
cost secondaryBrand = await getConfirmedBrand(secondaryIssuer);
```

**Comment by Chris-Hibbert** [comment]
ZCF's saveIssuer now has a `assertUniqueKeyword(keyword)` of its own. While its internal call to register the issuer with Zoe is asynchronous, I think that moves the issue out of autoswap.

**Comment by Chris-Hibbert** [comment]
[zcf.saveIssuer()](https://github.com/Agoric/agoric-sdk/blob/9985dc4ef6d1f1e75bb722c8abd19eefc1479e36/packages/zoe/src/contractFacet/contractFacet.js#L268)

**Comment by katelynsills** [comment]
This is fixed, right?

**Comment by Chris-Hibbert** [comment]
the TOCTOU bug is now gone because `saveIssuer()` asserts that the issuer hasn't already been added. That eliminates any deleterious race on `secondaryIssuer` and its `keyword`. 

That protection on the new secondary issuer means that even though there are multiple awaits between checking `liquidityKeyword` and using it, only one racer can succeed at `saveIssuer()` with a particular issuer, and attempt to add the pool. The others will fail out of `saveIssuer()`.
