### ISSUE TITLE
[Zoe/ERTP] Typing fixes from Mark's Zoe Release Candidate Review

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1465]
For context, these are typing-related review comments (yes, each link is different):

- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469542420
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468144498
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468146840
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468978796
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468986037
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468987573
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468990391
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468994223
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r468994784
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469574981
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469582691
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469582749
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469591773
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469597713
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469605060
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469615154
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469689542
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469689884
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469693275
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r469694785

**Comment by michaelfig** [comment]
I will deal with these once the underlying Zoe code has basically stabilized.  The plan is to do that when we are improving our unit tests.

**Comment by erights** [comment]
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470420119
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470420415
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470422365
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470422838
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470425966
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470427494
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470428411
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470437157
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470440770

**Comment by erights** [comment]
- [x] https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r470932987

**Comment by erights** [comment]
- [x]  https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471039536

**Comment by michaelfig** [comment]
- [x]  Also, add:
```diff
diff --git a/packages/zoe/src/types.js b/packages/zoe/src/types.js
index 0d229720..a652487b 100644
--- a/packages/zoe/src/types.js
+++ b/packages/zoe/src/types.js
@@ -215,7 +215,7 @@
  * @callback MakeZCFMint
  * @param {Keyword} keyword
  * @param {AmountMathKind=} amountMathKind
- * @returns {ZCFMint}
+ * @returns {Promise<ZCFMint>}
  */
 
 /**
```
