### ISSUE TITLE
Saving the genesis vat source code

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1485]
> Would it make sense to add the genesis vats to the kernelDB as well, and treat their sources the same as the dynamic vats? I would like this, so that it's a little harder to accidentally modify the genesis vat source code without resetting state from scratch, and also so that exporting the kernel state is just a matter of doing a direct dump of the kernelDB and not having to rebundle sources at export time (which is sensitive to the bundler we use, and any changes to the sources). It would also mean we don't need to copy the vat directory to every created basedir.
> 
> If not now, but you think this is a good idea, I can create an issue for it.

Yes, absolutely. I think we'll wind up going farther than that: the "payload"/deployment level of the stack will be defined by a set of additions to the "blob pool" (where bundles get stored), and an initial series of messages to the singular initial vat, which creates dynamic vats for zoe and whatever else the system should have from T=2 (where T=1 has the initial vat but nothing else). Genesis vats should be replaced by messages. I'm not sure how long the medium-term (genesis vat source code goes into the DB) will last, so I'm kinda deferring it a bit in the hopes we can jump directly to the messages form, but if we haven't made any progress on the latter within, say, a month, let's go ahead and do the genesis-code-in-DB thing.

_Originally posted by @warner in https://github.com/Agoric/agoric-sdk/pull/1481#issuecomment-674453353_

**Comment by michaelfig** [comment]
@warner is this done yet?

**Comment by Tartuffo** [comment]
@warner This is in the "Up Next" pipeline, but does not have a MN-1 label.  If it is needed for MN-1, please label, otherwise move from "Up Next" to "Product Backlog".

**Comment by warner** [comment]
We can close this: we currently save the source code for static vats (our new name for the "genesis vats" referenced above) at kernel startup. This will change a little bit as we introduce vat upgrade, but I think all the issues that prompted this ticket are addressed.
