### ISSUE TITLE
add sourcemaps to bundled code

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#149]
We might be able to improve the debugging experience by having our `bundleSource()` utility arrange for a sourcemap to be attached to the bundled code. There are two places I'm hoping to improve.

The first is the stack trace displayed when vat code throws an uncaught exception. These currently show a trace to the `eval()` that SES uses, then a line/column number within the anonymous string bundle:

```
Error: here
    at m2 (eval at run (.../SwingSet/.misc/smap.js:70:21), <anonymous>:9:9)
    at build (eval at run (.../SwingSet/.misc/smap.js:70:21), <anonymous>:13:14)
    at run (.../SwingSet/.misc/smap.js:73:5)
```

It would be nice if that `<anonymous>:9:9` bit could instead point to a real source file.

The second is within a debugger (e.g. browser dev-tools) when stopped within the evaluated code.

I think I've figured out how to attach sourcemaps with `rollup`, but so far they aren't improving either situation. The devtools in Chrome, when I insert a `debugger` call into the evaluated code, shows me a source file that appears to be the bundled output of `rollup`. Since we aren't compressing/minifying/uglifying anything, this isn't too hard to read, but it's still not the original file name or line number. So I expect IDEs like VSCode may not be happy, especially if you want to set a breakpoint on code that has not yet been evaluated.

The stacktrace printed when just running `node smap.js` in a shell didn't seem to get any better with sourcemaps.

I'll keep poking at this one.

**Comment by michaelfig** [comment]
This is now much better supported by `bundle-source` honouring file divisions and evaluating files separately (called the `"nestedEvaluate"` moduleFormat).
