### ISSUE TITLE
swingset: enable re-use of config object, treat as immutable

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1490]
**What is the Problem Being Solved?**

I've got a few transcript-exercising unit tests (`test/vat-admin/test-replay.py` in particular) that are easiest to write if we could re-submit the same config object into multiple calls to `buildVatController()`. However that function modifies the config object, by adding `.parameters` and `.parameters.argv` if the (legacy?) `argv` argument was passed into `buildVatController`.

In my test, the second call to `buildVatController()` threw a `Cannot assign to read only property 'argv'` error at that point of mutation. I *think* this happened because those parameters were `harden()`ed by something during the first call, maybe at the point where the parameters were passed through to the vatManager. So by the second call, they're frozen and can't be modified (even to replace them with an exact duplicate).

I think `buildVatController` should treat the incoming `config` object as immutable. If changes need to be made, it should make a copy, modify the copy, and then `harden()` the copy, and use that instead.

OTOH, that approach is probably incompatible with the presence of uncopyable `.device` endowments in the config file. We're moving towards config-is-just-data, but maybe we have to implement something like #1351 first, so that devices are configured with an entirely different pathway, leaving the vat configuration free to be pure (immutable, copyable) data.

So consider this as a cleanup task to do after #1351 is implemented.

cc @FUDCo

**Comment by FUDCo** [comment]
Closed by #1814
