### ISSUE TITLE
misuse of config.hostStorage in a swingset unit test

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1491]
One of the dynamic vat tests is using a pattern which I *think* is wrong, but I'm not sure:

https://github.com/Agoric/agoric-sdk/blob/a3bf3cdc71ad3ad834ddc2e66cc2e6bfca1b63e8/packages/SwingSet/test/vat-admin/test-innerVat.js#L12-L14

@FUDCo I think you currently know the most about `hostStorage`, so I wanted to check my hunch: `config.hostStorage` is ignored, and storage should be passed through`runtimeOptions` (third argument to buildVatController). Is that correct? 

Should we just delete this `config.hostStorage =` line? The test doesn't need to do anything special with storage, it can use ephemeral RAM.

Please reassign back to me if that's the case, and I'll make the PR to remove it.

**Comment by FUDCo** [comment]
Yup, I think your intuitions are correct.  I somehow missed this one when I was upgrading everything to the new config model.  Simply deleting the line and falling back on the default ephemeral store is fine (since that's effectively what now happens anyway when this is run).

**Comment by FUDCo** [comment]
Fixed by #1686
