### ISSUE TITLE
[Zoe] Call to saveIssuer might succeed and call to makeZCFMint might fail

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1502]
Aha! See #1461 . But it is worse than that. Even with the test here, at https://github.com/Agoric/agoric-sdk/blob/cec9e48d2af8044c03ac3cefb3710e2dac6db4dd/packages/zoe/src/contracts/multipoolAutoswap/pool.js#L151-L155 the call to `saveIssuer` on line 165 might succeed and then the call to `makeZCFMint` on line 167 might fail, leaving only one of two coordinated side effects done. 

The problem is that all the checks that might cause failure have to happen before any of the side effects, and there must be no interleavings possible between the tests and the side effects --- if the interleavings may invalidate the tests as here.

Nevertheless, keep the test on line 228 above. We're better off with it than without it.

_Originally posted by @erights in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDY0NTMyNDQw/pull_request_reviews/more_threads_

**Comment by Chris-Hibbert** [comment]
In the code as of the time of the comment, line 166, between the two identified lines was 
```js
    assertNatMathHelpers(zcf, secondaryBrand);
```
which is the main reason I can see why line 167 would have failed after 165 succeeded. [The current code](https://github.com/Agoric/agoric-sdk/blob/d84cf846628f56bbb76bdddc54af051f3c71b57e/packages/zoe/src/contracts/multipoolAutoswap/pool.js#L224) checks for NAT earlier, and has nothing between those two steps. 

I think this issue has been resolved.
