### ISSUE TITLE
Was non-currying over zcf a successful experiment?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1512]
We stopped having the helpers curry over zcf so now we have to provide zcf to each one. Good to try as a spike experiment. Having tried it, is this an improvement? Should we go back to currying zcf?

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471039970

**Comment by Chris-Hibbert** [comment]
While rewriting autoswap, I considered currying `trade`. Its parameters are noisy, and this would have simplified the code, I think.  But this also illustrates that it can be done on the client side.

**Comment by katelynsills** [comment]
We think it was mostly an improvement but will stay cognizant of the costs of passing in zcf in each call.
