### ISSUE TITLE
Swap helper - add msg param with default

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1515]
Since this is called `defaultAcceptanceMsg`, should you provide another parameter that defaults to this, and then here return the value of that parameter? By analogy with the `keepHandleInactiveMsg` parameter.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471041434

**Comment by katelynsills** [comment]
Actually, I think we shouldn't do this. The error message and the return message are not symmetric. The error message is part of the thrown error so it must be a parameter if the code using this function wants to change it. The default acceptable message can be overridden in an offerHandler by just not returning the return value of swap. I think this should stay as is.
