### ISSUE TITLE
Can we consolidate `trade` and `swap` into one helper?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#1531]
I wonder if we really need `trade` and `swap` as distinct abstractions. Swap begins by checking if keepSeat has exited. However, it should also error if trySeat has exited. `trade` should also error if either has exited, so both checks could be moved into `trade`.

Looking at the callers of `trade`, a major reason they can't use `swap` is that the `keepSeat` remains open. They all do exit the trySeat. 

Looking at the callers of `swap`, since `swap` throws on failure and only closes the `keepSeat` on success, it would not be an undue burden for swap's callers to exit the keepSeat after the call to swap. Since we did presciently call it the `keepSeat`, it would also not be surprising for `swap` itself not to close it.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471053021

**Comment by katelynsills** [comment]
Let's look into checking whether the seats have exited and otherwise making the two functions more uniform but let's make sure to keep swap for the specialized use cases. Open issue in documentation to clarify use cases for each.

**Comment by katelynsills** [comment]
Just as a study of how we use `swap`, we currently use it in 3 contracts:

https://github.com/Agoric/agoric-sdk/blob/da2b92d2e80152b6d48010433c90784ec0f22cc4/packages/zoe/src/contracts/atomicSwap.js#L31-L34

https://github.com/Agoric/agoric-sdk/blob/da2b92d2e80152b6d48010433c90784ec0f22cc4/packages/zoe/src/contracts/coveredCall.js#L49-L54

https://github.com/Agoric/agoric-sdk/blob/da2b92d2e80152b6d48010433c90784ec0f22cc4/packages/zoe/src/contracts/simpleExchange.js#L68-L79
