### ISSUE TITLE
[Zoe] Multipool Autoswap review comments

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1539]
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471033927
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471034718
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471146673
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035135
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035559
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035612
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471035866
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471036229
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471036706
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471145017
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471162311
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471164476
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471165778

The calculation of addLiquidity bug:
https://github.com/Agoric/agoric-sdk/pull/1414#discussion_r471160253

**Comment by Chris-Hibbert** [comment]
Closed by #1672
