### ISSUE TITLE
Confusing error text when vat code is malformed

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#1609]
**Describe the bug**
If the source file defining a vat fails to export a `buildRootObject` function, the error message the kernel prints is `vat source bundle lacks (default) setup() function`, which is confusing

**To Reproduce**
PIck a vat.  Rename `buildRootObject` to `buildRootOrbject`.  Run.

**Expected behavior**
I'd expect an error message more like `vat source bundle lacks a buildRootObject() function`

**Comment by warner** [comment]
good point. That error is being generated at https://github.com/Agoric/agoric-sdk/blob/796dc68b3d10cf29bdd30865e9f1a9b9464c4b1d/packages/SwingSet/src/kernel/vatManager/localVatManager.js#L154 , and that code is factored to handle both `export function buildRootObject()` -style vats and the older `export default function setup()` style. The presence of a named `buildRootObject` export should override any `default`. We have a managerOption flag to enable the use of `setup`, which is disabled for everything except the comms vat. The particular sequence there is:

* look for `buildRootObject`, use it if present
* else grab `default`
  * complain if it's not a function
  * complain if the use of `setup` is not enabled in the vat options
  * else use it

Maybe that should be refactored to be more like:

* look for `buildRootObject`, use it if present
* if `setup` is disabled, complain about the lack of `buildRootObject
* else:
  * grab `default`
  * complain if it's not a function
  * else use it
