### ISSUE TITLE
SimpleExchange OfferResult of "Trade Successful" is the wrong message for adding to the order book

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1640]
**What is the Problem Being Solved?**
Currently we are returning the message "Trade successful" when an order is added to the order book in Simple Exchange. This is misleading, because the trade has not yet happened. We should return a message that says the order has been added to the exchange.

<img width="1382" alt="Screen Shot 2020-08-28 at 2 57 33 PM" src="https://user-images.githubusercontent.com/2441069/91618345-f7a12a00-e93e-11ea-9388-54d07fc15eb9.png">

**Description of the Design**
Change the message returned.

**Security Considerations**

None.

**Test Plan**
Change the offerResult tests for simpleExchange.

**Comment by erights** [comment]
"Security Considerations: None." is misleading. A user thinking a trade happened when it did not opens the door to many attacks.

**Comment by katelynsills** [comment]
> "Security Considerations: None." is misleading. A user thinking a trade happened when it did not opens the door to many attacks.

Good point
