### ISSUE TITLE
Update outdated packages

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1698]
**What is the Problem Being Solved?**

A number of packages are outdated in agoric-sdk. Some of them, like Prettier, would be nice to update to keep up with the rest of the industry.

**Description of the Design**

The following are outdated according to `yarn outdated`

- [ ] @agoric/babel-parser
- [ ] @agoric/nat
- [ ] @babel/core
- [ ] @babel/generator
- [ ] @babel/traverse
- [ ] @iarna/toml
- [ ] @rollup/plugin-commonjs
- [ ] @rollup/plugin-node-resolve
- [ ] acorn
- [ ] anylogger
- [ ] ava
- [ ] chalk
- [ ] commander
- [ ] eslint
- [ ] eslint-config-airbnb
- [ ] eslint-config-airbnb-base
- [ ] eslint-config-jessie
- [ ] eslint-config-prettier
- [ ] eslint-plugin-eslint-comments
- [ ] eslint-plugin-import
- [ ] eslint-plugin-jsx-a11y
- [ ] eslint-plugin-prettier
- [ ] inquirer
- [ ] lerna
- [ ] livereload-js
- [ ] minimist
- [ ] morgan
- [ ] node-addon-api
- [ ] node-lmdb
- [ ] prettier
- [ ] re2
- [ ] rollup
- [ ] rollup-plugin-livereload
- [ ] rollup-plugin-svelte
- [ ] rollup-plugin-terser
- [ ] semver
- [ ] ses
- [ ] sirv-cli
- [ ] svelte-themer
- [ ] tmp
- [ ] vega
- [ ] vega-canvas
- [ ] ws
- [ ] yargs

**Security Considerations**

The more we keep up to the latest versions, the easier it probably is to patch vulnerabilities. 

**Test Plan**

No tests per se, but `yarn outdated` should only show packages that we intend to be outdated.

**Comment by turadg** [comment]
This will happen incrementally as needed
