### ISSUE TITLE
marshal package.json: specify "files"

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#17]
When making the v0.1.1 release, I noticed that this `package.json` doesn't have a `files:` key, which means the tarball includes everything that was in the source directory, including the tarballs made from earlier releases that happened to still be lying around. I don't have this problem with our other repos, so I think a `files` key would limit the tarball contents to the specific items.

**Comment by erights** [comment]
@warner can I give this to you?

**Comment by warner** [comment]
this ticket is too stale to be useful, and I suspect we've addressed the problem by now in some other way
