### ISSUE TITLE
zcf.saveIssuer() with bad issuer - improve error message

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1701]
**What is the Problem Being Solved?**

If we call `zcf.saveIssuer()` with a bad issuer, we get the following unhelpful error message:

```
    message: 'o["getBrand"] is not a function',
```

**Description of the Design**

Improve this error message by either doing an assertion before this call (an extra trip) or catching any errors related to the issuer not having the expected API and inserting a custom, improved error message.

**Security Considerations**

If we catch errors, we should make sure that we are not suppressing errors unrelated to the issuer not having the expected API.

**Test Plan**
The ZCF tests that found the issue should confirm the error message has improved. We may want to have additional tests to ensure we aren't suppressing errors unrelated.

**Comment by erights** [comment]
Now that some remotables (aka pass-by-presence objects) including issuers have explicit tags like `Alleged moola issuer`, HandledPromise, when it delivers a method call to an object, could check whether the object has a method of that name, and if not, could also check the `getInterface` tag of the object it would have invoked. If the object with the missing method does have such a tag, it could be revealed (declassified by `q`) in the error message. In we do that, then an error that reveals no such tag indicates that the object being invoked did not have one. In this case, it would indicate that the object is not an issuer.

Attn @michaelfig

**Comment by michaelfig** [comment]
> Now that some remotables (aka pass-by-presence objects) including issuers have explicit tags [...]

If you think this feature is worth implementing, can you please create an issue for it and assign me?  That way it'll be tracked on our board.
