### ISSUE TITLE
zcf.saveIssuer - improve error message if arguments reversed

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1702]
**What is the Problem Being Solved?**

Currently the error message if the arguments are reversed is not as helpful as it could be:

```js
test(`zcf.saveIssuer - args reversed`, async t => {
  const { moolaKit } = setup();
  const { zcf } = await setupZCFTest();
  t.throws(() => zcf.saveIssuer('A', moolaKit.issuer), {
    message: `(an object) must be a string\nSee console for error data.`,
  });
});
```

**Description of the Design**

Mention in the error message that the arguments may have been reversed.

**Security Considerations**

None.

**Test Plan**
ZCF tests

**Comment by dtribble** [comment]
Types should be pointing at the problem here already. Punt to await a more general error reporting plan?

**Comment by katelynsills** [comment]
Related: https://github.com/Agoric/agoric-sdk/issues/1701

**Comment by katelynsills** [comment]
With type checking, the linting error looks like this:

![Screen Shot 2021-02-09 at 10.58.36 AM.png](https://images.zenhubusercontent.com/6011b99bf93960b4fb3272a1/fb1e7ef5-5704-4673-a8d1-9a4e8abcc402)

Closing as this is probably sufficient.
