### ISSUE TITLE
Synthetic presences are not first-class

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1719]
**Describe the bug**
Presences that are created within a SwingSet vat's user code do not have their handlers invoked by liveSlots.  Instead, messages arriving for them are reified as method calls on the presence itself.

**To Reproduce**
1. Create a presence with a fulfilledHandler within a Vat, and return it to a caller:
```js
xport function buildRootObject(vatPowers) {
  return harden({ getPresenceP() { 
    return new HandledPromise((_res, _rej, resolveWithPresence) => {
      resolveWithPresence({
        applyMethod(_p, name, args) {
          return `Hello there ${name}`;
        },
      });
    });
  } });
};
```
2. Fetch that vat's presence from the REPL:
```js
presence = E(myVat).getPresenceP()
```
3. The handler is not triggered when called:
```
E(presence).foo()
// Promise.reject("TypeError: target[foo] does not exist, has ")
```

**Expected behavior**
I expected messages inbound to the vat to be forwarded to the presence's handler, and to receive `"Hello there foo"`.

**Platform Environment**
 - MacOS, Node.js 12.16.1
 - what version of the Agoric-SDK are you using? `@agoric/sdk@2.7.2-72-g2be22e63`

**Additional context**
This is blocking the #1718 plugin interface design.

**Screenshots**
![Screen Shot 2020-09-08 at 1 41 32 AM](https://user-images.githubusercontent.com/457244/92447437-70d92200-f174-11ea-8f15-4164a71947f8.png)

**Comment by michaelfig** [comment]
Here is a diff that does what I need, but fails a test case https://github.com/Agoric/agoric-sdk/pull/1718#issuecomment-689175130:
```diff
diff --git a/packages/SwingSet/src/kernel/liveSlots.js b/packages/SwingSet/src/kernel/liveSlots.js
index ef430043..df5992f8 100644
--- a/packages/SwingSet/src/kernel/liveSlots.js
+++ b/packages/SwingSet/src/kernel/liveSlots.js
@@ -373,21 +373,17 @@ function build(
     // Both situations are the business of this vat and the calling vat, not
     // the kernel. deliver() does not report such exceptions to the kernel.
 
-    try {
-      // We have a presence, so forward to it.
-      let res;
-      if (args) {
-        // It has arguments, must be a method application.
-        res = HandledPromise.applyMethod(t, method, args);
-      } else {
-        // Just a getter.
-        // TODO: untested, but in principle sound.
-        res = HandledPromise.get(t, method);
-      }
-      res.then(notifySuccess, notifyFailure);
-    } catch (err) {
-      notifyFailure(err);
+    // We have a presence, so forward to it.
+    let res;
+    if (args) {
+      // It has arguments, must be a method application.
+      res = HandledPromise.applyMethod(t, method, args);
+    } else {
+      // Just a getter.
+      // TODO: untested, but in principle sound.
+      res = HandledPromise.get(t, method);
     }
+    res.then(notifySuccess, notifyFailure);
   }
 
   function retirePromiseID(promiseID) {
```

**Comment by warner** [comment]
I was able to trigger a similar failure (test-vpid-liveslots.js, `-m 'liveslots vpid handling case3 promise-reject stalls=0'`, symptom is that `four` is pipelined into the kernel rather than being rejected locally) by patching liveslots to delay the delivery of an inbound message by one turn:

```diff
diff --git a/packages/SwingSet/src/kernel/liveSlots.js b/packages/SwingSet/src/kernel/liveSlots.js
index 26b11bb8..c47a923d 100644
--- a/packages/SwingSet/src/kernel/liveSlots.js
+++ b/packages/SwingSet/src/kernel/liveSlots.js
@@ -385,7 +385,7 @@ function build(
           `target[${method}] is not a function, typeof is ${ftype}, has ${names}`,
         );
       }
-      const res = t[method](...args);
+      const res = Promise.resolve(t).then(t => t[method](...args));
       Promise.resolve(res).then(notifySuccess, notifyFailure);
     } catch (err) {
       notifyFailure(err);
```

**Comment by warner** [comment]
In the working case, test-vpid-liveslots emits the following log, which shows `p-8` being rejected first, then `three` being sent to the object:

```
-- Array <Array <[Object: null prototype] {}>>(3) [
  Object <[Object: null prototype] {}> {
    type: 'reject',
    promiseID: 'p-8',
    data: Object <[Object: null prototype] {}> {
      body: '[{"@qclass":"slot","index":0}]',
      slots: [Array <Complex prototype>]
    }
  },
  Object <[Object: null prototype] {}> {
    type: 'send',
    targetSlot: 'o-1',
    method: 'three',
    args: Object <[Object: null prototype] {}> {
      body: '[{"@qclass":"slot","index":0}]',
      slots: [Array <Complex prototype>]
    },
    resultSlot: 'p+7'
  },
  Object <[Object: null prototype] {}> {
    type: 'subscribe',
    target: 'p+7'
  }
]
```

after adding the extra stall, we see `three` being sent first, then `four` is pipelined out, then `p-8` is rejected:

```
$ yarn test test/test-vpid-liveslots.js -m 'liveslots vpid handling case3 promise-reject stalls=0'
yarn run v1.22.5
$ ava test/test-vpid-liveslots.js -m 'liveslots vpid handling case3 promise-reject stalls=0'

-- Array <Array <[Object: null prototype] {}>>(5) [
  Object <[Object: null prototype] {}> {
    type: 'send',
    targetSlot: 'o-1',
    method: 'three',
    args: Object <[Object: null prototype] {}> {
      body: '[{"@qclass":"slot","index":0}]',
      slots: [Array <Complex prototype>]
    },
    resultSlot: 'p+7'
  },
  Object <[Object: null prototype] {}> {
    type: 'subscribe',
    target: 'p+7'
  },
  Object <[Object: null prototype] {}> {
    type: 'send',
    targetSlot: 'p-8',
    method: 'four',
    args: Object <[Object: null prototype] {}> {
      body: '[]',
      slots: Array <Complex prototype>(0) []
    },
    resultSlot: 'p+8'
  },
  Object <[Object: null prototype] {}> {
    type: 'subscribe',
    target: 'p+8'
  },
  Object <[Object: null prototype] {}> {
    type: 'reject',
    promiseID: 'p-8',
    data: Object <[Object: null prototype] {}> {
      body: '[{"@qclass":"slot","index":0}]',
      slots: [Array <Complex prototype>]
    }
  }
]
  liveslots vpid handling case3 promise-reject stalls=0

  test/test-vpid-liveslots.js:484

   483:   const targets = { target2, localTarget, p1 };
   484:   t.deepEqual(log.shift(), resolutionOf(p1, mode, targets));
   485:

  Difference:

    {
  -   args: {
  -     body: '[{"@qclass":"slot","index":0}]',
  -     slots: [
  -       'p-8',
  -     ],
  -   },
  -   method: 'three',
  -   resultSlot: 'p+7',
  -   targetSlot: 'o-1',
  +   data: {
  +     body: '[{"@qclass":"slot","index":0}]',
  +     slots: [
  +       'p-8',
  +     ],
  +   },
  +   promiseID: 'p-8',
  -   type: 'send',
  +   type: 'reject',
    }

  › doVatResolveCase23 (test/test-vpid-liveslots.js:484:5)
  › async test/test-vpid-liveslots.js:563:9

  ─

  1 test failed
```

I'm puzzled as to how this could happen: we delay the `t.run()` call by one turn, but we're at the top of the crank, there shouldnt' be anything else ready to go.

Maybe the return value from the `t.run` is significant? It's a Promise (because `run()` is `async`, and then we `Promise.resolve` it again (why??)), in both the working case and my delay-one-turn failing case. In @michaelfig 's failing case, it's a `HandledPromise`. Maybe that's affecting the order in which `notifySuccess`/`notifyFailure` is being called.

**Comment by warner** [comment]
Looking at the comment I wrote when we [last changed](https://github.com/Agoric/agoric-sdk/commit/42c2193ce62f527eb2dfa1b5bed4f8b32f2d452d#diff-dd60601e7de47e5c2fd0adcff252e95c) this code:

    fix: rewrite liveslots use of HandledPromise, remove deliver() stall
    
    The exception-catching idiom I used in `deliver()` was introducing an
    unnecessary stall into the result resolution pathway, making
    `syscall.fulfill*` calls show up later than I expected. I rewrote it with a
    different pattern (try/catch instead of `Promise.resolve().then()`), which
    makes it easier to follow what we do and do not wait for. The new `deliver()`
    does not return a Promise to the kernel.
    
    ...
    
    I expanded test-vpid-liveslots to exercise resolution to a local object, in
    addition to the other kinds of resolution. With the removal of the
    unnecessary `deliver()` stall, the syscall traces no longer depend upon how
    many stalls we did after the resolve, so the test no longer needs a
    complicated set of options that switch on the stall count. Resolutions and
    message sends now occur in the same order they appear in the vat code.

So when PR #1718 replaces the immediate call with a `HandledPromise.applyMethod`, it's re-introducing the stall I'd removed, making the test re-dependent upon the number of stalls the test code does between resolving the Promise and sending three/four. (When @michaelfig and I walked through this code, he noted that the try/catch around the changed block is now redundant; that try/catch was also added in the above-noted commit precisely to make up for the similar rely-upon-a-Promise-to-catch-exceptions behavior that I was removing, because it was the source of the stall)

I'm not excited to revert the behavior: there's a certain purity to knowing that the outbound messages happen in the same order regardless of how many turns appear between one/two and three/four. I don't really understand where the sensitivity to those stalls was coming from, so perhaps I'm just being fooled into thinking that I **do** understand what's going on when it goes away :).

I'm not rejecting this yet.. I know we can't address the main feature (first-class treatment of synthetic Presences) without something like this patch.

Does the proposed patch also give up the `getOwnPropertyNames` diagnostic when the method name cannot be found? I think we find that pretty handy.

**Comment by michaelfig** [comment]
> Does the proposed patch also give up the `getOwnPropertyNames` diagnostic when the method name cannot be found? I think we find that pretty handy.

In ~~#1716~~ #1718 I move that diagnostic into `@agoric/eventual-send` directly.

**Comment by michaelfig** [comment]
> > Does the proposed patch also give up the `getOwnPropertyNames` diagnostic when the method name cannot be found? I think we find that pretty handy.
> 
> In ~~#1716~~ I move that diagnostic into `@agoric/eventual-send` directly.

I meant #1718.

https://github.com/Agoric/agoric-sdk/pull/1718/files#diff-7e2014d9e342057635e2e22addd6a893

We should include that change if/when we resolve the current issue without merging #1716.

**Comment by warner** [comment]
Let's see, the deeper issue here is a set of assumptions that liveslots makes. One is that the world of things it will be asked to serialize is broken up into three categories: data, Promise, callable objects (more generally: pass-by-copy, pass-as-promise, pass-as-presence), and that every Presence we have was created by liveslots as a result of an inbound deserialization of somebody else's callable object.

Originally the categorization test was fairly simple (are all enumerable properties frozen functions? does `Promise.resolve(x)===x`?), and `Presence` was entirely a construct of liveslots. Over time, this responsibility moved into other libraries and became more generalized, starting with `HandledPromise` and then `Presence`, which are now both part of the eventual-send proposal. `marshal` evolved along with them, so now liveslots delegates most of its serialization/recognition logic to `marshal` instead.

The proposed change here is a logical continuation of that evolution. `marshal` uses its own "data or not" test ([`passStyleOf`](https://github.com/Agoric/agoric-sdk/blob/b41b6a396144d46558087064cae9ad867b0c77b6/packages/marshal/marshal.js#L318)) to decide whether or not it exercises `conertValToSlot`, and that test naturally treats Presences as pass-by-copy. Liveslots delegates that decision making to `marshal`, so it must be prepared to honor whatever decisions `passStyleOf` makes.

**Comment by michaelfig** [comment]
I added the following to #1718 to get the tests to pass.

```diff
diff --git a/packages/SwingSet/test/test-vpid-liveslots.js b/packages/SwingSet/test/test-vpid-liveslots.js
index ab1e8d9b..cab81e31 100644
--- a/packages/SwingSet/test/test-vpid-liveslots.js
+++ b/packages/SwingSet/test/test-vpid-liveslots.js
@@ -558,9 +558,19 @@ async function doVatResolveCase23(t, which, mode, stalls) {
 for (const caseNum of [2, 3]) {
   for (const mode of modes) {
     for (let stalls = 0; stalls < 4; stalls += 1) {
-      test(`liveslots vpid handling case${caseNum} ${mode} stalls=${stalls}`, async t => {
-        await doVatResolveCase23(t, caseNum, mode, stalls);
-      });
+      if (stalls === 0) {
+        // FIXME: Need to resolve with solution to #1719
+        test.failing(
+          `liveslots vpid handling case${caseNum} ${mode} stalls=${stalls}`,
+          async t => {
+            await doVatResolveCase23(t, caseNum, mode, stalls);
+          },
+        );
+      } else {
+        test(`liveslots vpid handling case${caseNum} ${mode} stalls=${stalls}`, async t => {
+          await doVatResolveCase23(t, caseNum, mode, stalls);
+        });
+      }
     }
   }
 }
```

**Comment by warner** [comment]
Yeah, `test.failing` sounds good for now: please proceed with that. I'll open a new ticket to pay attention to the ordering changes.
