### ISSUE TITLE
Pre-install our main contracts on Zoe

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1730]
**What is the Problem Being Solved?**

Currently, we do not make any installations of our provided contracts on Zoe. We require users of the contracts to do the installation. However, ideally, there would be a single installation already done in the bootstrap phase such that the installation objects themselves can be used as a coordination point.

**Comment by dckc** [comment]
We now do install several contracts as part of bootstrap. Is this done? Or are there other "main" contracts?

**Comment by katelynsills** [comment]
I would say this isn't done. We should include things like the covered call option or anything else that we want people to use. This would only apply on testnet and mainnet 2, though.

**Comment by Tartuffo** [comment]
Subsumed by bootstrap work.
