### ISSUE TITLE
zcfSeat doesn't get exited on zcf.shutdown()

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1755]
**What is the Problem Being Solved?**

When `zcf.shutdown()` is called, the userSeats are exited, but the zcfSeats are not. Perhaps this doesn't matter because the entire vat that the zcfSeats are in, will be soon deleted.

**Comment by Chris-Hibbert** [comment]
Is it just taking a couple of turns, or do the seats never get marked as exited?  Presumably they can't do anything.

**Comment by Chris-Hibbert** [comment]
sorry wrong button.

**Comment by katelynsills** [comment]
> Is it just taking a couple of turns, or do the seats never get marked as exited? Presumably they can't do anything.

The seats never get marked as exited.
