### ISSUE TITLE
`zoeHelpers.saveAllIssuers()` allows adding an issuer twice

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1786]
**Describe the bug**

`zoeHelpers.saveAllIssuers()` allows you to add an issuer under multiple keywords

**To Reproduce**

see `test-zoeHelpersWZcf.js`

```js
test.failing(`zcf saveAllIssuers - already known`, async t => {
```

**Comment by katelynsills** [comment]
Yes, but this is not a bug. We should expect that the same issuer (for instance, the Zoe invitation issuer) is often used in the contracts under multiple keywords.
