### ISSUE TITLE
Integrate Chainlink oracles

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#1813]
**What is the Problem Being Solved?**
enable the smooth integration of Chainlink oracles into the Agoric platform so that they can be easily used by third-party JS smart contracts and/or the Agoric chain's economic institutions. 

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by zarutian** [comment]
Link to documentation of Chainlink oracles? @dtribble

**Comment by dtribble** [comment]
we are just starting the work, so this is the place where that doc and design will get attached :)

**Comment by zarutian** [comment]
Ah, I see where the misunderstanding arose.

I was looking for something like [the main site](https://chain.link/) or [this explanation](https://gemini.com/learn/what-is-chainlink-and-how-does-it-work/), and how it might be achived.

**Comment by zarutian** [comment]
[A good start](https://github.com/Agoric/dapp-oracle).

**Comment by katelynsills** [comment]
Can this be closed?

**Comment by Tartuffo** [comment]
@dtribble Can this be closed?

**Comment by Tartuffo** [comment]
Closing, re-open if need be.
