### ISSUE TITLE
XS vat worker should host multiple vats

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#1845]
The XS-based vat-worker process described in #1299 is partially complete, in `packages/xs-vat-worker/`. At present, it accepts a `load-bundle` command over the fd3/4 message pipe to load a single vat bundle into memory, and then accepts a sequence of `deliver` commands to process message deliveries in that vat. It emits `syscall` commands back to the parent to invoke syscalls and get their results (if any).

While we have no code to support it in the kernel process yet, it would be straightforward to run multiple child subprocesses, each hosting a single vat, and each controlled through it's own pair of message pipes. However this will incur some overhead that we don't want: we expect thousands of vats, and we certainly don't want thousands of child processes. We'd also eventually run out of file descriptors in the parent process for all the message pipes.

So the next step is to enhance this program to handle multiple vats per subprocess. We anticipate a small number of these subprocesses, organized according to the provenance of the vat code we run inside them. When we enable `seccomp(2)`-based sandboxing of the child process, a fault in the XS engine might allow vat code to compromise the process (and thus get control of all objects available to any vat hosted by that process), but it will still be limited by its pipe to the kernel, protecting vats hosted in other processes. So we plan to run e.g. all Agoric-authored vats in one process, and externally-authored vats in their own process.

This enhancement will require a redesign of `xs-vat-worker` into a "dispatch unit" and zero or more vat workers:

![xs-worker-diagram](https://user-images.githubusercontent.com/27146/95270311-1de4a000-07f0-11eb-8111-da14f4ae195a.png)

Each vat worker will have a separate `struct xsMachine`, which can be serialized/restored separately. The dispatch unit will have its own `struct xsMachine`, and does not need to be persisted.

The dispatch unit gets access to the message pipes, not the vat workers.

Each vat worker should be created with a "callback" (the XS term for a function/object that can be invoked by javascript but which is not written in javascript) for making syscalls (and possibly more for certain `vatPowers`). The worker's "start Compartment" should define `globalThis.deliver` as a function that accepts message deliveries and returns a Promise that resolves (after the promise queue has drained) for the delivery result.

The dispatch unit needs access to the XS `C` APIs to create a new `xsMachine` and load the right code into it, and then to pull the `deliver` function off the global.

**Comment by warner** [comment]
@dckc the `1845-xs-worker-multiple-vats` branch has the code we were working on the other day

**Comment by dckc** [comment]
tiny bit of progress last Thu... https://github.com/dckc/agoric-sdk/tree/xs-multi-vat 3cf53ed

**Comment by dckc** [comment]
> ... we expect thousands of vats, and we certainly don't want thousands of child processes.

This is addressed by the vat warehouse (#2277), which ensures a finite number of vats are online at a time.
