### ISSUE TITLE
Wallet inbox should be more intuitive

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1879]
**What is the Problem Being Solved?**
When the wallet receives an new (unapproved) dapp, payment, or offer, it doesn't stand out in the inbox.  Also, the approve/decline flow is not the same for the different item types.

**Description of the Design**
For the inbox page:
- [x] only unapproved items should display (including only the unapproved dapps)
- [x] unapproved items should be expanded by default
- [x] it should be able to approve/dismiss any of those (including payments)
- [x] the approve/decline (and cancel, in the case of pending approvals) UI should be consistent for all items

**Security Considerations**
No additional considerations.

**Test Plan**
Go through the normal dapp flow, and ensure that the wallet inbox behaves as desired.

**Comment by michaelfig** [comment]
@dtribble please add to this issue as desired.

**Comment by rowgraus** [comment]
* Distinction between offers that are transactional/recent vs. offers that are long lived
* Active offers vs. inactive offers

**Comment by samsiegart** [comment]
> * Distinction between offers that are transactional/recent vs. offers that are long lived
> * Active offers vs. inactive offers

The latter is done in the react wallet, but I'm not sure about the first point. We do show the current offer status as pending which may be enough to signal that it's long-lived, but they show up in the same place as transactional/recent offers. I'm leaning towards just closing this for now and opening up new issues for any more specific tweaks we want to make. Does that sound good @rowgraus?

**Comment by rowgraus** [comment]
Agreed
