### ISSUE TITLE
Fix breaking change: makeVatAdmin

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#1894]
**Describe the bug**
The `fakeVatAdmin` changes broke the contract tests for dapps.

**To Reproduce**
Run tests for dapp-otc or dapp-token-economy

**Expected behavior**
Tests pass.

**Platform Environment**
Current master

**Comment by katelynsills** [comment]
dapp-otc is fixed.

**Comment by katelynsills** [comment]
Closed by #1901 (dapps confirmed fixed with CI) plus the fix for dapp-token-economy (https://github.com/agoric-labs/dapp-token-economy/pull/8) plus CI in dapp-token-economy running on an hourly basis against agoric-sdk (https://github.com/agoric-labs/dapp-token-economy/pull/6)
