### ISSUE TITLE
Refactor Zoe Implementation for Unit Tests

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1911]
**What is the Problem Being Solved?**

Some of the internals of how the Zoe Service and ZCF are connected are hard to test and are not tested. It would be nice if the code base was divided up into smaller chunks that could be tested individually. 

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by zarutian** [comment]
hmm?

isnt this done already for and via ava?

**Comment by katelynsills** [comment]
> hmm?
> 
> isnt this done already for and via ava?

I edited the description. I think there's more that can be done

**Comment by katelynsills** [comment]
This has been completed
