### ISSUE TITLE
Want not exact (e.g., any 3 tickets)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1915]
**What is the Problem Being Solved?**

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by erights** [comment]
This would be a natural extension of the pattern notion explored in the #1905 spike, if that works out. The spike already almost covers this one.

**Comment by katelynsills** [comment]
Closing in favor of https://github.com/Agoric/agoric-sdk/issues/2230
