### ISSUE TITLE
expose chain storage data (aka Zoe level events) via notifier 

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1919]
**What is the Problem Being Solved?**
Users, applications, and third party services need to track transaction histories based on Zoe events.  These may include reallocate, offer exits, and other contract-specific items.

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by erights** [comment]
If we think of these as audit records or receipts, then we should fold it into our thoughts of how to handle the equivalent of signed audit records or signed receipts or signed oracle reports. (Which was a motivation for #1905 --- so you can `want` one.)

**Comment by Tartuffo** [comment]
Can you please put an estimate on this?

**Comment by Tartuffo** [comment]
Contracts need to generate more events.  E.g. when an offer is paid out.  @rowgraus and @erights please discuss (may be related to the ticket about not seeing the result of offers)?  Critically, is there anything here for MN-1.

**Comment by Tartuffo** [comment]
@erights @gibson042 is this subsumed by #4639?

**Comment by dckc** [comment]
We got a good update on this (and points nearby) from @gibson042 and company in today's kernel meeting.

**Comment by gibson042** [comment]
This is in fact subsumed by #4639.

**Comment by dckc** [comment]
Sure, #4639 subsumes this, inasmuch as it is blocked by this. But #4639 includes updating contracts and all sorts of other stuff. Which ticket is the smallest amount of work that includes reading *any* data from off-chain without a new blockchain transaction? Lacking knowledge of another such ticket, I'm using this one to track that part.

**Comment by gibson042** [comment]
#5366

**Comment by dckc** [comment]
bingo. thanks.
