### ISSUE TITLE
Add invariant APIs - separate spec of invariant

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1920]
**What is the Problem Being Solved?**

**Description of the Design**
Implement as hooks called at particular points by zoe.  needed for our own economy contracts. Should not hand over control during Zoe actions to the contract

**Security Considerations**

**Test Plan**

**Comment by katelynsills** [comment]
Next step is providing an example that is a wrapper around zcf that enforces an invariant before calling zcf.reallocate

**Comment by katelynsills** [comment]
Closed by #3090. Let's reopen if that is insufficient
