### ISSUE TITLE
hybrid tokens - can be used as fungible or non-fungible. Tickets, stocks, etc. (Subsumed by Zoe proposal flexiblity)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1922]
**What is the Problem Being Solved?**

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by erights** [comment]
See #1905 which would provide for "subjective hybrids". At some point, we may also want "objective hybrids" as explored in spike at https://github.com/Agoric/agoric-sdk/pull/1870/files#diff-1a404c253101ca905008c47552df7acd94563e1eac552dc33eec7341d9273886

**Comment by katelynsills** [comment]
Closing as subsumed by https://github.com/Agoric/agoric-sdk/issues/2230
