### ISSUE TITLE
Redesign TimerService (or a wrapper) to resolve a promise

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#1930]
**What is the Problem Being Solved?**

The API of the TimerService is `setWakeup(delaySecs, handler)`, which requires the kernel to keep track of all the handlers. A more performant approach would be to resolve a promise, which could be shared across many clients that wanted to be woken at the same time. When we're talking about price oracles, and callSpread options, there could be many actions all reliant on the same deadline.

**Description of the Design**

`resolveAfter` is a possible name.

For backwards compatibility, the old API should be maintained, but in order to get the benefit, this would want to change the driver (`timer-src.js`).

**Security Considerations**

None.

**Test Plan**

There are existing tests.

**Comment by warner** [comment]
If we redesigned devices as in #1346 , we could let the device resolve promises directly. The downside would be needing to write devices in a less ocap-ish style.

**Comment by Chris-Hibbert** [comment]
@warner @FUDCo,

We've added bunch of functionality (persistence, restart, etc.) recently to the kernel, vats, and devices. Most of it was expected when we designed the current split of responsibilities for devices, but perhaps some of it came out differently than we foresaw. Are there any obvious changes we'd make to the way devices work given the functionality we've actually built?

**Comment by dckc** [comment]
@Chris-Hibbert do you suppose recent work on TimerService addressed this issue?

**Comment by Chris-Hibbert** [comment]
Nope. This hasn't been addressed.

**Comment by warner** [comment]
This got fixed in #5847
