### ISSUE TITLE
Start a contract instance in cosmic-swingset bootstrap

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1932]
**What is the Problem Being Solved?**

We know that we want some contracts, such as autoswap and some of our oracle contracts, to have an instance already started and running when a chain starts. There is a previous task (https://github.com/Agoric/agoric-sdk/issues/1730) that calls for installing our main contracts on Zoe. This task goes one step further to actually start a contract instance with an installation: `E(zoe).startInstance(installation, ...)`

**Description of the Design**

**Security Considerations**

**Test Plan**

**Comment by dckc** [comment]
bootstrap currently starts the AMM etc. This seems pretty clearly done.

(context: In reviewing #4026 , I'm looking for issues that represent work to refactor bootstrap to more clearly separate test / demo mechanisms from production)
