### ISSUE TITLE
As a dev in the hackathon, I want to test my contract against the price authority API in unit tests in the contracts so I can develop effectively

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1934]

**Comment by rowgraus** [comment]
Acceptance Criteria:
* Call spread (and later loan/CDP) demonstrate mocked oracle responses
* Documentation shows how to accomplish this such that a new developer can understand how to implement it in their own contracts

**Comment by katelynsills** [comment]
I would add another acceptance criteria: The mock can be easily imported from the dapp the user is working on..
