### ISSUE TITLE
Add `agoric.priceAuthority` to decentral services

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#1943]
**What is the Problem Being Solved?**

We want to have a consistent identity for a free and trusted price authority to point people towards when writing their contracts.

**Description of the Design**

Install an extensible `agoric.priceAuthority` to serve as part of decentral services.  This provides the API as discussed in #1916, but allows grouping several disjoint price authorities in a common identity.  Initially, this price authority will only produce fake quotes for `moola-simolean` (cycling through 5, 10, 15 simoleans per moola) but can be extended to other pairs as the chain is running.

If an ag-solo is using the sim chain or is provisioned with the `priceAuthority` Agoric power (i.e. via `ag-cosmos-helper provision-one chris agoric1....ktkhi priceAuthority`, the same mechanism as is used to hand out `vattp` administration abilities), then they will also be given an `agoric.priceAuthorityAdmin` capability to allow them to add and remove specific authorities for the central `agoric.priceAuthority`.

**Security Considerations**

The power to add and remove price authorities from the decentral `agoric.priceAuthority` needs to be closely held.

**Test Plan**

Write a `cosmic-swingset` test that exercises the range of `moola-simolean` APIs.

**Comment by katelynsills** [comment]
Can we close this?
