### ISSUE TITLE
Add a PriceAuthority to Autoswap and Multipool Autoswap. Retain old methods for backwards compatiblity

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#1947]
**What is the Problem Being Solved?**

We will need to use Autoswap or Multipool Autoswap in the loan contract for liquidation. It would be nice if they also included the priceAuthority API such that getting quotes was standardized. 

Additionally, Autoswap and Multipool Autoswap may give slightly different quotes based on whether you ask `getInputPrice` or `getOutputPrice`. From the perspective of the `priceAuthority`, if the quotes are indistinguishable, the quoted amountOut should be also the same. We should fix this in Autoswap and Multipool Autoswap and write tests to ensure the quoted amount is the same if the quotes are otherwise indistinguishable. 

**Description of the Design**

We should add a priceAuthority but still retain the methods `getInputPrice` and `getOutputPrice` for backwards compatibility.

**Security Considerations**

**Test Plan**

**Comment by katelynsills** [comment]
Some prior discussion between @michaelfig, @Chris-Hibbert and @katelynsills :

Both quotes mean: if you supply this amountIn, you will get this amountOut.

Due to fees and quantization, simultaneous quotes for getInputAmount() and getOutputAmount() with the same amountIn can display different amountOuts. I think people might want to be able to distinguish them, but I'm willing to go along with a decision to not mark the quotes distinctly.  I haven't thought of a scenario in which the difference would matter.

I think the different quantization can be handled by first calculating the amountIn (if only amountOut is given), then calculating the quoted amountOut from it, rather than passing through the amountOut as supplied by the user.

I agree that that would work. I think that correction would happen in AutoSwap rather than on the oracle side.

**Comment by Chris-Hibbert** [comment]
#1672 made the quotes consistent so multipoolautoswap always does this.

> the different quantization can be handled by first calculating the amountIn (if only amountOut is given), then calculating the quoted amountOut from it, rather than passing through the amountOut as supplied by the user.

So it's still the case that multiple quotes at the same time could have different quantization since the price isn't linear, but each inputPrice or outputPrice should be uniquely paired with a single price on the other side..
