### ISSUE TITLE
Publish `package/zoe` to npm

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#196]
- [x] Publish `package/zoe` to npm under `@agoric/zoe`
- [x] Change cosmic-swingset references to use `@agoric/zoe` rather than `@agoric/ertp`
- [x] Test cosmic-swingset
- [x] Check `wallet-frontend` and `autoswap-frontend` and change references if applicable
- [ ] Go through "Getting Started" steps and make sure everything still works

**Comment by katelynsills** [comment]
@michaelfig how does the Agoric CLI tool from the Getting Started documentation get access to ERTP and Zoe? It looks like it is still using the old versions.

**Comment by katelynsills** [comment]
@michaelfig just bumping this question in case it got lost in emails

**Comment by michaelfig** [comment]
The versions are defined in `agoric-sdk/packages/agoric-cli/template/*/package.json`.  Once you update those, you need to run `agoric init NEWDIR` and that will create a new project directory `NEWDIR` with the new templates.  

Alternatively, you can use `agoric init --force OLDDIR` and it will replace the templates in `OLDDIR`.

**Comment by katelynsills** [comment]
Thanks! So those changes will only propagate once a new release of agoric-cli is cut? Is there a good way to test our "getting start" comments out before cutting a new release of agoric-cli?

**Comment by katelynsills** [comment]
Zoe has been published to npm. Even though there are significant questions about our release process for Zoe and how agoric-cli is affected, I'm closing this.
