### ISSUE TITLE
priceAuthority pairs (moola-$fake, simolean-$fake, agstake-$fake, $link-$fake)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#1979]
* Moola and simolean prices will be fake and volatile
* $link-$fake will be backed by a $LINK-USD price oracle

**Comment by katelynsills** [comment]
@Chris-Hibbert and @michaelfig is this done?

**Comment by michaelfig** [comment]
> @Chris-Hibbert and @michaelfig is this done?

Yup, to the extent that software changes are needed.
