### ISSUE TITLE
Add a Notifier<Timestamp> to the TimerService

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2002]
Gotcha, if we add a TODO with a link to a Github issue for adding a notifier to the timerService, I'm ok with this.

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/pull/2001#discussion_r520215068_

From the code:
```js
/** @type {NotifierRecord<Timestamp>} We need to have a notifier driven by the
   * TimerService because if the timer pushes updates to individual
   * QuoteNotifiers, we have a dependency inversion and the timer can never know
   * when the QuoteNotifier goes away.  (Don't even mention WeakRefs... they're
   * not exposed to userspace under Swingset because they're nondeterministic.)
   *
   * TODO It would be desirable to add a timestamp notifier interface to the
   * TimerService
   */
```

**Comment by michaelfig** [comment]
It would be ideal to provide our whole taxonomy of pullable data sources, some way to construct:

- a `Promise<Timestamp>` that resolves after a delay
- a lossy `Notifier<Timestamp>` that starts updating after a delay and thereafter on an interval
- a lossless `Subscription<Timestamp>` for the same

These would be very useful, and not require adaptation to use remotely with multiple clients.  It would be great to build the TimerService internals so that the server-side of them can be garbage-collected when their client drops them on the floor.  With the enhancements coming to vat/kernel garbage-collection under Swingset, this could work very well.

**Comment by michaelfig** [comment]
@Chris-Hibbert @erights, PTAL.

**Comment by Chris-Hibbert** [comment]
Seems like a good thing to have. I could build the version that is not GC-safe, but I'd need to consult with @erights (or possibly @warner) to build the more sophisticated version. Do we need this imminently, or is it okay to leave this open for now?

**Comment by michaelfig** [comment]
> Do we need this imminently, or is it okay to leave this open for now?
 It's not urgent... Let's do it right the first time.

**Comment by zarutian** [comment]
Something like this, perhaps?
```javascript
  /*
  * @typedef TimerService
  * @prop {(desiredTime: Timestamp) => Promise<Timestamp>} resolveOnTime the returned promise resolves at or bit later than desiredTime with the actual time of resolvement
  * @prop {(startTime: Timestamp, interval: TimeInterval) => PeriodicRepeater} makePeriodicRepeater
  */
  /*
  * @typedef PeriodicRepeater
  * @param {(done: Promise<void>) => Subscription<Timestamp>} subscribe 
  * When a subscriber is done with the subscription they settle the done promise they gave upon subscription.
  * When all such promises are settled the PeriodicRepeater can be discarded and cleanup done.
  * @param {() => Notifier<Timestamp>} getNotifier
  * 
  */
```

(note: it is always possible to transform from a lossless subscription to a lossy notifier. [Like this](https://gist.github.com/zarutian/bb9ed1b99986609539d76a9228d66f18#file-subscription2notifier-js) )

**Comment by michaelfig** [comment]
> Something like this, perhaps?

I like it!  Thanks for this.

Just wanted to ask: does this API prevent leaks if only `getNotifier` is called and the notifier is later just discarded, or will we also need to use explicit cleanup?  We don't yet allow library code to use unrestricted WeakRefs since they are nondeterministic.

If we need to explicitly clean up, I would prefer the earlier version of the API (`PeriodicRepeater.destroy()`) since it is possible that there are no subscribers, just a bunch of `getNotifier`s.  The fact that you removed `PeriodicRepeater.destroy()` suggests that we don't need explicit cleanups in that case.

> (note: it is always possible to transform from a lossless subscription to a lossy notifier. [Like this](https://gist.github.com/zarutian/bb9ed1b99986609539d76a9228d66f18#file-subscription2notifier-js) )

In my understanding, such a generic transform will have a problem with leaking if the notifier is discarded (unless we have WeakRefs).

**Comment by zarutian** [comment]
Hmm... the main reason why I removed `PeriodicRepeater.destroy()` was that I expect an created PeriodicRepeater to be public-ishly exposed and allowing any potential invoker to destroy it is too much authority and can cause mischief/unforseen-plan-interferance.
So here is an updated version:
```javascript
  /*
  * @typedef TimerService
  * @prop {(desiredTime: Timestamp) => Promise<Timestamp>} resolveOnTime the returned promise resolves at or bit later than desiredTime with the actual time of resolvement
  * @prop {(startTime: Timestamp, interval: TimeInterval) => PeriodicRepeaterDestroyerPair} makePeriodicRepeater
  */
  /* @typedef PeriodicRepeaterDestroyerPair
  * @prop {PeriodicRepeater} repeater
  * @prop {PeriodicRepeaterDestroyer} destroyer
  /*
  * @typedef PeriodicRepeater
  * @prop {(done: Promise<void>) => Subscription<Timestamp>} subscribe 
  * When a subscriber is done with the subscription they settle the done promise they gave upon subscription.
  * When all such promises are settled the PeriodicRepeater can be discarded and cleanup done.
  * @prop {Notifier<Timestamp>} notifier
  * 
  */
  /*
  * @typedef PeriodicRepeaterDestroyer
  * @prop {() => PeriodicRepeater} getTheRepeater
  * @prop {() => Promise<void>} getAllDonePromise
  * This promise resolves when all the done promises given to PeriodicRepeater.subscribe() settle
  * @prop {() => void} destroy
  * Finishes any outstanding subscriptions and discards/removes the periodic repeatet.
  */
```

Perhaps I went ahead of myself with the parathentized note but I was thinking that this subscription to notifier would be internal to the periodic repeater. Though the converter can be external to it.

The done promises given to PeriodicRepeater.subscribe() are meant to be the way to do WeakRefs-less cleanup. Note that the text above says the clean up is possible when these promises settle. And settle means they either got resolved or rejected (possibly by swingset kernel when the decifing vat of a done promise was terminated or by captp connection serverance).

**Comment by michaelfig** [comment]
I'm now of the opinion that we shouldn't provide a subscription, just a `makePeriodicNotifier` and a `resolveOnTime`.  I think that consumers of the timer will not want timer events to stack up if they don't consume them rapidly enough.

My feeling is that an implementation that only hands out notifiers can be constructed so as not to run into leakage problems.  The PeriodicNotifier's `getUpdateSince` could be implemented in terms of checking internal state against the `currentTimestamp`.  Then it could lazily make calls to `resolveOnTime` so that when there are no outstanding calls to `getUpdateSince`, there won't be any scheduled promises.

**Comment by zarutian** [comment]
Hmm.. this question regarding if `PeriodicTimer` should only provide a `notifier` and not `subscription` seems to creep into the territory of soft to hard real(ish)-time scheduling and if loosing a period 'tick' is acceptable or not.

**Comment by erights** [comment]
I like the notifier-only option. As for whether it is acceptable to lose a tick, the notification carries the timestamp, so the notified can tell how many ticks they "missed". There's no reason to expect that a subscription would have actually been more timely. Rather, in this case, a subscription might just have a vastly larger memory cost for no actual benefit.

AFAICT, a notifier in this role should have pleasing GC characteristics before weakrefs and even better GC after weakrefs.

**Comment by erights** [comment]
> (note: it is always possible to transform from a lossless subscription to a lossy notifier. [Like this](https://gist.github.com/zarutian/bb9ed1b99986609539d76a9228d66f18#file-subscription2notifier-js) )

@zarutian OMG uncallers! Are you trying to recapitulate the old Data-E pass-by-construction Una? This will be fun!

**Comment by zarutian** [comment]
> > (note: it is always possible to transform from a lossless subscription to a lossy notifier. [Like this](https://gist.github.com/zarutian/bb9ed1b99986609539d76a9228d66f18#file-subscription2notifier-js) )
> 
> @zarutian OMG uncallers! Are you trying to recapitulate the old Data-E pass-by-construction Una? This will be fun!

Not in that gist file, just wanted to be able to save and restore these kind of pipeline setups. Am still sad that Yahoo! pipes were fully retired, they could kept or open sourced the editor, and that gist file is a small tribute to that.
