### ISSUE TITLE
Identify objects that are leaking in the exchange benchmark.  Deconstruct the slog

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2013]

**Comment by warner** [comment]
We think we fixed this, by a combination of XS bugfixes (which were retaining objects too long) and liveslots improvements (doing the same).

We need to look at @mhofman 's current loadgen/perftest data to see if the kernel object table is growing over time (given a non-accumulative workload). We can re-open this if that data suggests that the problem isn't really gone.
