### ISSUE TITLE
Board IDs should self-identify as boardIDs

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2014]
**What is the Problem Being Solved?**

Board IDs are currently raw numbers. They are used to refer to registered ocaps out of band, including installations and user depositFacets. The problem is that then they cannot be distinguished with the wild from other numbers like keys. There remain situations where the IDs are shared among people.

**Description of the Design**

- [ ] Add a prefix (e.g., board:092384)
- [ ] Specify the boardID format (e.g., it currently has a CRC
- [ ] Make sure they are actually sparse

**Security Considerations**

Sparseness protects against typos when entering one. A prefix protects against using one as a different kin dof ID and being confused. (e.g., as a public key).

**Test Plan**

**Comment by michaelfig** [comment]
From me on Discord#support-agoric:

> Currently I've hacked in `board:...` to some of the UIs, but the clearest would be to somehow use the chain ID (i.e. `agoricsim:...`, `agorictest:...` or `agoric:...` for mainnet).  The plumbing to make this possible is already done, just the board needs to take advantage of it.

**Comment by dckc** [comment]
Something like `agoric:...` is the first thing that comes to mind for me too.

In case hooking into web browsers is a consideration, the [registerProtocolHandler][1] docs suggest `web+agoric:...` or `urn:agoric:...`. I'm not sure why arbitrary protocol identifiers aren't supported; I just see that they're not.

I thought I saw some recent announcement that `did:` was getting added to the URL schemes that browsers support, but now I can't find it. For reference:

 - [my objection to prefixing these things with did:](https://github.com/w3c-ccg/did-spec/issues/32)
   - which is on the same grounds as earlier objections to `urn:`; it's somewhat ironic that browsers now support `urn:`.
 - [the registry of DID methods](https://w3c.github.io/did-spec-registries/#did-methods)

[1]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler

**Comment by rowgraus** [comment]
Needs to also update the UI so that board: doesn't get added a second time once that's part of the ID
Update anywhere else we hardcoded "board:" in other checks

**Comment by Tartuffo** [comment]
@dtribble Do we really need this for MN-1?  Maybe we just put a prefix on the id?

**Comment by Tartuffo** [comment]
@dtribble Dean gently re-emphasized that we need to do this.  A prefix is better than what we have.

**Comment by michaelfig** [comment]
> @dtribble Dean gently re-emphasized that we need to do this. A prefix is better than what we have.

@dckc had shown some interest.  Here are just a few random notes on what I was thinking in this area:

Some of our UIs accommodate using (and automatically stripping) a prefix of `'board:'`... we should be sure *not* to use that prefix when we enforce one in the board itself.

I'd suggest keeping the current CRC checksum suffix, but just using a BigInt sequence number rather than the sparse ints, so something like this:

`` `agoricboard:${seq}${crc}` ``

This is a trivial change but has big implications for some of our unit tests.

I dream of a day when the board ID is a bech32, so the above convention of `agoricboard:...` accommodates the bech32 prefix of `agoricboard1...` if we ever get there.

**Comment by dckc** [comment]
why only dream of bech32? why not just do it?
_p.s. MF says he encourages me to do it if it seems easy_

And why sequence rather than sparse?
_p.s. Because sequence + crc gets us the same value as sparse without the possibility of collisions._

lower probability, anyway.

IIRC, sparse ints were @dtribble 's idea. hm.

And why strip the prefix before sending it to the board?
Or are you saying: some stuff already does this, and we should be compatible with such stuff. If that's the case, I disagree that it's cost-effective.

_p.s. MF says: some UI stuff already does this.  Just don't use `board:` as the prefix and we're good._

@turadg expressed a preference for `board:`. Perhaps you want to re-play it here, @turadg ?

**Comment by michaelfig** [comment]
> And why sequence rather than sparse? _p.s. Because sequence + crc gets us the same value as sparse without the possibility of collisions._
> 
> lower probability, anyway.

If it's a fixed-length CRC, there's no possibility of generating two matching sequence+crc strings.  With the `sparse-int` library, we would need to do careful implementation to ensure there aren't collisions, and that the range is big enough.  A BigInt sequence number ensures we have an unlimited, nonrepeating range.

**Comment by michaelfig** [comment]
> @turadg expressed a preference for `board:`. Perhaps you want to re-play it here, @turadg ?

There is no reason I can think of to deliberately confuse our board IDs with the prefix-stripping (mis?)design of some of the UIs.  If we go to bech32, I have no argument against `board1...`, but *please* do not use `board:...`.

**Comment by turadg** [comment]
> @turadg expressed a preference for board:. Perhaps you want to re-play it here, @turadg ?

When this came up in chat, I said,
> if there's value in mixing these keys into other namespaces then perhaps agoric:board:123 but from my understanding the "agoric" is implied by where it's appearing

That's before reading,
> Some of our UIs accommodate using (and automatically stripping) a prefix of 'board:'... we should be sure not to use that prefix when we enforce one in the board itself.

…which I wasn't aware of and don't quite understand. Are the things labeled `board:foo` different than the boards we're talking about here? (That I understand to be https://agoric.com/documentation/repl/board.html , also mentioned at https://agoric.com/documentation/glossary/#board-agoric-board )

I don't have a position on whether to include "agoric" per se. My position is that whatever prefix is used here should match the name used in documentation and UIs. The user's mental model should not have to adapt to the context.

**Comment by michaelfig** [comment]
> Are the things labeled `board:foo` different than the boards we're talking about here? (That I understand to be https://agoric.com/documentation/repl/board.html , also mentioned at https://agoric.com/documentation/glossary/#board-agoric-board )

The UI in some places prefixes the `boardId` gotten from `boardId = await E(home.board).getId(someobj)` with `board:${boardID}` before displaying to the user, and then conversely strips off any `board:` prefix when submitting it to the board as `E(home.board).getValue(boardId)`.  That behaviour needs to change, and the least surprising change would be to use a different prefix that *isn't* already added or stripped.  Then the prefix is owned by `home.board`, and it becomes obvious where the UIs need to be fixed not to mangle it.

> I don't have a position on whether to include "agoric" per se. My position is that whatever prefix is used here should match the name used in documentation and UIs. The user's mental model should not have to adapt to the context.

Totally agreed!

**Comment by turadg** [comment]
> The UI in some places prefixes the boardId gotten from boardId = await E(home.board).getId(someobj) with board:${boardID} before displaying to the user

K, makes sense that the DOM doesn't have `board:`.

> and then conversely strips off any board: prefix when submitting it to the board as E(home.board).getValue(boardId).

That's odd to me. The UI can keep anything in state and render it differently.

> That behaviour needs to change, and the least surprising change would be to use a different prefix that isn't already added or stripped. 

Given that MN-2 will support 3rd party dapps and we're still working on MN-1, we should be careful ranking transition costs over parsimonious design.

> Then the prefix is owned by home.board, and it becomes obvious where the UIs need to be fixed not to mangle it.

For the same reason we use units in amounts, I think we should pass around `prefix:unique` instead of just `unique`. It's allows some type safety at runtime.

**Comment by dtribble** [comment]
The UI adding/removing "board:" was the workaround for the fact that the IDs were raw numbers. That should just go away and the UI should enforce that it's expecting e.g., "board[0-9]+". We SHOULD add a CRC digit the number. I think we should not try to design more complicated naming scheme. The naming could be a term of the contract so that's it's easy for someone to deploy a different version.

**Comment by dckc** [comment]
if we use a serial number, we'll be have the same board id on multiple chains (devnet, mainnet, ...), right?

**Comment by michaelfig** [comment]
> if we use a serial number, we'll be have the same board id on multiple chains (devnet, mainnet, ...), right?

Correct.  An upgrade to ``bech32({ prefix: 'board', data: `${chainID}:${serial}` })`` would fix that, but isn't necessary for MN-1 IMO.

**Comment by dtribble** [comment]
If the prefix is configurable, then other chains can use a different prefix. Since we do want a checksum, using bech32 might be easy though we would have to make sure there were no collisions. But otherwise, just doing what we are doing but sticking a prefix on the front is strictly better than what we are currently doing (as was the extent of my ambition here).
