### ISSUE TITLE
`agoric start --reset` has poor user experience

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2038]
Following the instructions at https://github.com/Agoric/dapp-fungible-faucet/pull/10 , when I got to step 5:

```
$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
agoric: start: setting sim chain with 0 second delay
agoric: start: /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/cosmic-swingset/bin/ag-solo set-fake-chain --delay=0 sim-chain
agoric: start: /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/cosmic-swingset/bin/ag-solo start
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
agoric: deploy: running /Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/dapp-svelte-wallet/api/deploy.js
```

I sat there for a long time waiting for this to complete. Finally I asked if it is supposed to take this long. Then I learned it is actually supposed to "hang" there as it waits for input. Only then did I notice, two lines up from the bottom

```
web: Listening on 127.0.0.1:8000
```
If this had been the last line, I would have seen and understood it. Of course, an even better indicator would be welcome.

**Comment by erights** [comment]
Continuing to document rough spots in this process. On step 6 when I did `agoric deploy contract/deploy.js` I then saw I no longer had a clean git state:
```
$ git status
...
        modified:   ui/public/conf/installationConstants.js

$ git diff
diff --git a/ui/public/conf/installationConstants.js b/ui/public/conf/installationConstants.js
...
-// GENERATED FROM /Users/michael/agoric/dapp-fungible-faucet/contract/deploy.js
+// GENERATED FROM /Users/markmiller/src/ongithub/agoric/dapp-fungible-faucet/contract/deploy.js
```
Can we avoid checking generated files into version control? Especially those that are regenerated as part of normal operation?

**Comment by katelynsills** [comment]
> Can we avoid checking generated files into version control? Especially those that are regenerated as part of normal operation?

Yup, the alternative was worse, in that an error was produced in CI and we needed to move fast. We filed an issue here but probably need it either in a more central place or in all the dapps: https://github.com/Agoric/dapp-encouragement/issues/75

**Comment by erights** [comment]
Hi @katelynsills I see you have https://github.com/Agoric/dapp-encouragement/issues/75 and commented in the thread above. This may already be fixed and closable, I don't know. Ok if I assign to you?

**Comment by katelynsills** [comment]
Sure, it will be a while until we can get to this, but yes!

**Comment by turadg** [comment]
Obsolete
