### ISSUE TITLE
OfferResults for offers made in the user's wallets cannot easily be presences

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2043]
**Describe the bug**

Many Zoe contracts are intentionally designed to return an object as the `offerResult`. For instance:

* `secondPriceAuction.js`: The seller's `offerResult` is an object with the method `makeBidInvitation`. It was designed this way to ensure that bid invitations can only be made once the seller has escrowed, and that bid invitations are handed out privately at the seller's discretion.
* `loan/borrow.js` The borrower's `offerResult` is an object with methods that allow the borrower to make invitations to add collateral and close the loan. It was designed this way so that only the borrower should be able to make these invitations.

Returning an object as an `offerResult` is integral to how these contracts are designed. However, dapp-svelte-wallet is not currently designed to handle presences as `offerResults`. Here's how the wallet currently works:

The `offerResult` is saved as `outcome` in the wallet and `E(offer.actions).result` is called:

https://github.com/Agoric/agoric-sdk/blob/9d0949084cd741b76375955e990911bfdd1c19d4/packages/dapp-svelte-wallet/api/src/lib-wallet.js#L917-L919

This `result` method was defined previously when the `walletAddOffer` message was received:

https://github.com/Agoric/agoric-sdk/blob/9d0949084cd741b76375955e990911bfdd1c19d4/packages/dapp-svelte-wallet/api/src/wallet.js#L104-L119

What this does is send a message with the `outcome` (`offerResult`) back to the dapp UI. This means it cannot be a presence since we cannot marshal object capabilities to the UI and use them in the UI.

## Future solutions

Some potential ways to handle offerResults as presences are passing them to the dapp backend (@michaelfig has done work on a rendezvous service) or giving the user a generic way to view and use object capabilities in the wallet.

**Comment by michaelfig** [comment]
> Some potential ways to handle offerResults as presences are passing them to the dapp backend (@michaelfig has done work on a rendezvous service) or giving the user a generic way to view and use object capabilities in the wallet.

Just to point out: these options are not mutually exclusive.  I do like the idea of the wallet becoming a general ocap management interface to empower users.  Another possibility would be to extend the ocap fabric into the dapp UI, much as we've done with `dapp-svelte-wallet/ui` itself.  That ocaptivates the whole network between ag-solos, the chain, and the UIs.

I see the rendezvous service as a baby step towards full three-party handoff, when the dapp UI can convey a wallet facet ocap in a method call to the API server.

**Comment by michaelfig** [comment]
#2050 is an issue designed to put this into perspective.

**Comment by katelynsills** [comment]
The `offerResult` is now saved in the wallet. Dapps have limited access to it. Dapps can:

* get a UINotifier (#2172)
* tell the wallet how to make an invitation from an offerResult
