### ISSUE TITLE
Enable backend-less dapps

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2057]
As @zarutian [observed](https://github.com/Agoric/agoric-sdk/issues/2050#issuecomment-735468711), dapp deployment is easier if a dapp developer does not need to continuously host an Internet reachable ag-solo. Furthermore, without an ag-solo backend, the dapp could be stored on something like IPFS.

## Definition of Backend-less Dapps

(Previously we called this "[API-less](https://github.com/Agoric/agoric-sdk/issues/2050#issuecomment-735871717)" due to the backend part of the dapp typically being in the `api/` directory.) Backend-less means that the dapp doesn't require a handler.js. However, the dapp may _still include an ag-solo running occasionally with deploy scripts for instantiation, shutdown, and maintenance_. In other words, the UI will not be making calls to any backend, although an ag-solo may still be used on the instantiator's behalf.

**Description of the Design**

As per @zarutian and @michaelfig, running a dapp without a backend server requires:

- the dapp web ui through wallet bridge iframe through websocket through wallet ag-solo through to Agoric captp comm path
- routing all actions triggered by the dapp UI through the `publicFacet` (accessible from the contract instance via Zoe, via the board) or through another object publicly accessible through the board.

**Design Considerations**

We should ensure that dapps that require the UI triggering privately held ocap methods have equal support and billing in our documentation and architecture. For example, the OTC Desk contract doesn't currently have a UI, but the contract is designed specifically such that invitations (free covered call options) are private, not public. This is a feature of the original design by Hasseb, so we shouldn't change it.

**Security Considerations**

We should make sure that we are never making something public that should not be public merely to fit this design category.

**Plan**
We should split out another issue for analyzing the current and future Zoe contracts and dapps to see which are good candidates for a backend-less approach, and which are not. We should continue to support dapps which require a backend.

**Comment by michaelfig** [comment]
> running a dapp without a backend server requires: [captp to the wallet bridge and publically accessible ocaps.]

Just to add, another way of obtaining private on-chain references would be to expose offer results as part of the wallet API, such that they could be accessible in the dapp UI via CapTP (#2058).  Current rules in the wallet only make offer records accessible by the same origin that proposed them.  Then the scarcity of the erights required by the offer would govern the underlying access control model.

**Comment by katelynsills** [comment]
Linking to note that I think there are security design concerns with exposing offer results to dapps through the wallet: https://github.com/Agoric/agoric-sdk/issues/2058#issuecomment-736143584

**Comment by zarutian** [comment]
If an dapp needs to get access to priviledged functionality on behalf of the user then I recommend the following.

On dapp side
```javascript
const { promise, resolve, reject } = makePromiseKit();
const Resolver = harden({ resolve, reject });
E.sendOnly(smartcontractPublicFacet).askForControler(controlerId, zoeInvitationsDepositFacet, Resolver);
// oppertunistically do something spefic with the controler
const controler = promise;
E(controler).crankItLouder();
```
And in the publicFacet method of the smart contract:
```javascript
  askForControler: (controlerId, depositFacet, resolver) => {
    E(depositFacet).deposit(zcf.makeInvitation(seat => {
      // check if seat has ControlerTicket for the controlerId requested
     if (!seat.hasExited() && ControlerTicketAM.isEqual(seat.getCurrentAllocation().ControlerTicket, ControlerTicketAM.make(controlerId))) {
        const controler = makeNewControlerFor(controlerId);
        seat.exit("ticket inspected as valid");
        E.sendOnly(resolver).resolve(controler);
      } else {
        const err = new Error('incorrect or no controler ticket given');
        seat.fail(err);
        E.sendOnly(resolver).reject(err);
      }
    }, "ticket check"));
  },
```
Design of the controler, if it should be automatically revocate, et ceterata left as an excercise for the reader.

**Comment by michaelfig** [comment]
It's worth noting that as of last week, the wallet bridge exposes Zoe and the Board over CapTP, so now backend-less dapps are possible (use CapTP to the wallet bridge, and then request `E(bridge).getZoe()` or `E(bridge).getBoard()`).  For that reason, I'm closing this ticket.

> If an dapp needs to get access to priviledged functionality on behalf of the user then I recommend the following.

This seems to be one approach to "use-objects", which would bridge the ocap and ERTP worlds.  I'll leave it to @katelynsills, @erights, or @Chris-Hibbert to describe the current plan for them in a new issue as they're the experts.
