### ISSUE TITLE
Fix domain-specific knowledge vs. authority for dapps vs. wallet

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2060]
Subtasks
- [x] [Make Deploy Script to Handle the Borrower OfferResult / Loan Manager](https://github.com/Agoric/agoric-sdk/issues/2061)

**Comment by rowgraus** [comment]
See #2043 for additional context

**Comment by katelynsills** [comment]
The offerResult is now saved in the wallet. Dapps have limited access to it. Dapps can:

get a UINotifier (#2172)
tell the wallet how to make an invitation from an offerResult
