### ISSUE TITLE
Protect against accidental arithmetic of Amounts

### ISSUE THREAD

**Issue by kriskowal** [Agoric/agoric-sdk#2064]
**What is the Problem Being Solved?**

Contract programmers are likely to reach for mathematical operators like `+` between amounts, which will silently corrupt said amounts. One bumper already exists to nudge users back onto the intentional path: TypeScript annotations will reveal that these kinds of arithmetic do not result in Amounts.

**Description of the Design**

We may implement `Amount.prototype.valueOf` such that it throws an exception that suggests the use of amount methods. JavaScript calls `valueOf()` on object arguments when they participate in arithmetic.

**Security Considerations**

This would be a guard rail and would not protect against a programmer determined to craft an invalid amount.

**Test Plan**

Create unit tests against the cross product of valid and invalid operands in common arithmetic operations.

**Comment by katelynsills** [comment]
This requires a change to marshal

**Comment by Chris-Hibbert** [comment]
AmountMath resolved this issue in early 2021
