### ISSUE TITLE
Deploy script error messages are not as helpful as they should be

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2076]
**Describe the bug**
<img width="805" alt="Screen Shot 2020-12-10 at 11 19 37 AM" src="https://user-images.githubusercontent.com/2441069/101842303-99b6dd80-3afc-11eb-8971-db1594bf08f5.png">

The error stack gives information that is too low level to be helpful, and the things hidden in `details` are not displayed.

**To Reproduce**
1. Check out branch `petname-not-found-error-message` on agoric-sdk
2. Check out branch `petname-not-found-error-message` on https://github.com/Agoric/dapp-loan
3. On agoric-sdk:
`yarn install`
`yarn build`
4. On dapp-loan:
`agoric install`
`agoric start --reset -v`
5. In a separate terminal on dapp-loan:
agoric deploy contract/scripts/setup/startAutoswap.js
agoric deploy contract/scripts/setup/periodAsyncIterable.js
agoric deploy contract/scripts/contractDeveloper/installLoan.js
agoric deploy contract/scripts/lender/startInstance.js

**Expected behavior**
I would like to see the petname revealed and the lines in lib-wallet.js in agoric-sdk and the deploy script in the stack trace

**Comment by erights** [comment]
The steps to reproduce above, on step 5, the paths starting `scripts/...` should all be `contract/scripts/...`

**Comment by katelynsills** [comment]
> The steps to reproduce above, on step 5, the paths starting `scripts/...` should all be `contract/scripts/...`

Ah, yes, I was doing this from the `contract/` directory

**Comment by erights** [comment]
Turns out the core problem is that I never ported #2037 + #2044 from the hackathon branch to main. Now in progress at #2082

**Comment by erights** [comment]
> > The steps to reproduce above, on step 5, the paths starting `scripts/...` should all be `contract/scripts/...`
> 
> Ah, yes, I was doing this from the `contract/` directory

I edited your comment above in place to add the `contract/`. Did you know that GitHub lets me edit your comments? Did it notify you that someone else had modified your comment? At least they changes the attribution line to 

> **katelynsills** commented. **erights** edited.

**Comment by erights** [comment]
With upcoming changes in #2082 I am now seeing the following in the second dapp-loan terminal, with uninteresting lines elided:

```
$ agoric deploy contract/scripts/lender/startInstance.js
Open CapTP connection to ws://127.0.0.1:8000/private/captp...o
agoric: deploy: running /Users/markmiller/src/ongithub/agoric/dapp-loan/contract/scripts/lender/startInstance.js
CapTP bundle exception: (Error#1)

  Error#1: "petname" not found: (a string)
    ...
    at dispatch (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/captp/lib/captp.js:386:9)
    at WebSocket.<anonymous> (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:109:13)
    ...
  
  Error#1 ERROR_NOTE: Received as error:captp:http://127.0.0.1#1
CapTP bundle exception: (Error#2)

  Error#2: "petname" not found: (a string)
    ...
    at dispatch (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/captp/lib/captp.js:386:9)
    at WebSocket.<anonymous> (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:109:13)
    ...
  
  Error#2 ERROR_NOTE: Received as error:captp:http://127.0.0.1#2
agoric: (Error#2)
```

For example, the error locally identified as Error#1 was received as distributed error identifier `error:captp:http://127.0.0.1#1` so we want to find where an error with this distributed identifier was sent. (Note that these distributed identifiers are *not* currently even close to collision free. Expect collisions! See #2045 .) We look for this distributed identifier on the first dapp-loan terminal:

```
  Error#5: petname not found: IE:"zoe invitation"
    ...
    at assertKeyExists (/bundled-source/packages/store/src/store.js:23:22)
    at Object.get (/bundled-source/packages/store/src/store.js:31:15)
    at Object.get (/bundled-source/packages/dapp-svelte-wallet/api/src/lib-dehydrate.js:139:42)
    at Object.getPurse (/bundled-source/packages/dapp-svelte-wallet/api/src/lib-wallet.js:618:46)
    ...
  
  Error#5 ERROR_NOTE: Thrown from: (Error#6) : 2014 . 0
  Error#5 ERROR_NOTE: Sent as error:liveSlots:v1#2
  Error#5
    Error#6: Event: 2013.1
      ...
      at Object.deliver (kernel/packages/SwingSet/src/kernel/liveSlots.js:423:28)
      at eval (kernel/packages/SwingSet/src/kernel/vatManager/deliver.js:50:48)
    
SwingSet: v2: Temporary logging of sent error (Error#7)

  Error#7: "petname" not found: (a string)
    ...
    at Object.notifyReject (kernel/packages/SwingSet/src/kernel/liveSlots.js:554:19)
    at eval (kernel/packages/SwingSet/src/kernel/vatManager/deliver.js:50:48)
  
  Error#7 ERROR_NOTE: Received as error:liveSlots:v1#2
  Error#7 ERROR_NOTE: Sent as error:captp:http://127.0.0.1#1
Error#7 ERROR_NOTE: Sent as error:captp:http://127.0.0.1#2
```

Here we see that an error locally identified as Error#7 was sent with the matching distributed identifier. But Error#7 is not the original. It was received from somewhere that sent it with distributed identifier `error:liveSlots:v1#2`. We see that earlier an error locally identified as Error#5 was sent as `error:liveSlots:v1#2`. Error#5 is the original and shows the uncensored error message: `Error#5: petname not found: IE:"zoe invitation"` together with the stack trace when the error was thrown.

**Comment by erights** [comment]
The results above are as of #2083

**Comment by katelynsills** [comment]
I just tried to reproduce with the agoric-sdk branch `petname-not-found-deep-stacks` checked out, and I think I got exactly what you describe above @erights.  I can see that the bad petname is `zoe invitation` in the terminal tab in which I did `agoric start --reset -v`. Furthermore I can see what line in `lib-wallet.js` created the error. This is a great improvement!

It looks like I still can't see what line in my deploy script used the bad petname. Is this something that is impossible currently or just outside the scope of this particular fix?

**Comment by erights** [comment]
> It looks like I still can't see what line in my deploy script used the bad petname. Is this something that is impossible currently or just outside the scope of this particular fix?

As of
https://github.com/Agoric/agoric-sdk/pull/2082/commits/48122cf77476faa3ac406f0bf6a7e0413a0e31b6
identical to
https://github.com/Agoric/agoric-sdk/pull/2083/commits/68cdb72d14f83a746f1f2a338a28387bec82748f
we now get additional diagnostics on this example like

```
Error#1 ERROR_NOTE: Rejection from: (Error#2) : 22 . 0
Error#1
  Error#2: Event: 21.1
    ...
    at deployContract (/Users/markmiller/src/ongithub/agoric/dapp-loan/contract/scripts/lender/startInstance.js:97:45)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WebSocket.<anonymous> (/Users/markmiller/src/ongithub/agoric/agoric-sdk/packages/agoric-cli/lib/deploy.js:228:13)
```

where line 97 is the line you wanted
```js
  const zoeInvitationPurse = E(walletAdmin).getPurse('zoe invitation');
```
and column 45 is at the beginning of `getPurse`
