### ISSUE TITLE
MarkM and the Terrible, Horrible, No Good, Very Bad Logging Report

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2085]

**Comment by katelynsills** [comment]
I think this is a duplicate of https://github.com/Agoric/agoric-sdk/issues/2076 which I filed for Mark last week.

**Comment by erights** [comment]
Yeah but the issue title is so cool!

**Comment by katelynsills** [comment]
> Yeah but the issue title is so cool!

It is much better! 😄
