### ISSUE TITLE
Global meter taming is unsound

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2105]
**Describe the bug**

Refs https://github.com/Agoric/agoric-sdk/pull/2095#pullrequestreview-555789454

The `packages/tame-metering` approach of wrapping global properties is not sound.  Some things accessible via syntax (like Bignum multiplication) don't trigger the wrappers, and so need to be fixed at the JS engine level.

Also, some JS engine features (such as freezing a prototype) prevent installing the meter wrappers.

**Comment by dckc** [comment]
we no longer rely on global metering, so I'm moving this to technical-debt (i.e. get rid of leftover tame metering code)

**Comment by michaelfig** [comment]
We no longer have `packages/tame-metering`.
