### ISSUE TITLE
Withdraw an invitation from the wallet by a search not based on invitationHandle

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2120]
We need a way to withdraw an invitation from the wallet by a search not based on invitationHandle:

const lendInvitationAmount = E(walletAdmin).findInvitationAmount({
instance: loanInstance,
description: 'lend',
});

Importantly, we need to be able to withdraw an invitation based on the above search and associate it with a proposed offer

**Comment by katelynsills** [comment]
Completed in https://github.com/Agoric/agoric-sdk/pull/2174
