### ISSUE TITLE
Get a contact by petname from the wallet (API)

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2121]
We need a way to get a contact by petname from the wallet (API)
Notifier of the entire set of contacts

**Comment by rowgraus** [comment]
Goal: a human user can pay another human user

**Comment by samsiegart** [comment]
@rowgraus Does the current functionality outlined in https://agoric.com/documentation/guides/wallet/ui.html#transfers satisfy this?

**Comment by rowgraus** [comment]
Yes, closing
