### ISSUE TITLE
Get SES Working on XS

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2131]
- [ ] get the SES test suite is regularly running on XS (https://github.com/endojs/endo/issues/508).

**Comment by dckc** [comment]
dup of https://github.com/Agoric/SES-shim/issues/507 ?
is there a definition of "working"?

**Comment by dckc** [comment]
Fixed in #2194 5fdaf9d .

@kriskowal @warner @erights please re-open if I missed the mark here.

For more context, see #2107

**Comment by dckc** [comment]
@rowgraus I re-opened #511 , which represents possibly the most relevant end-user feature here. Maybe we should re-open this one, update the title / description, and add #511 (and/or some other stuff) to it?

**Comment by dckc** [comment]
Perhaps this should stay open until we get the SES test suite is regularly running on XS (https://github.com/endojs/endo/issues/508).

**Comment by aj-agoric** [comment]
Closing here and we will track any additional work on the endo ticket https://github.com/endojs/endo/issues/508

**Comment by aj-agoric** [comment]
close
