### ISSUE TITLE
efficient validator restart from snapshots

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2138]
Without snapshots, validators would have to re-play vats from genesis.

 - [x] #2277
 - [x] #2273

**Comment by rowgraus** [comment]
Business metrics impacted
* Improves Restart Time
* Lazy loading of Vats improves memory usage

**Comment by dckc** [comment]
While restart from snapshots is our plan for avoiding long replays on restart, while working on #2865 and #2911 we discovered some low-hanging fruit around metering that seems to speed things up significantly.

I tried to measure the difference but I'm struggling to get an apples-to-apples comparison in the current work-in-progress state.

Stay tuned.

p.s. Apr 29:
> Startup is an order of magnitude faster (23s vs 247s). Restart is 20x faster (13.3s vs 244s). -- https://github.com/Agoric/agoric-sdk/pull/2995#issuecomment-829083278

but also May 5:
> datapoint: 14min to restart a chain node that had 24h of 1cycle/60s faucet loadgen running, with everything on XS

**Comment by dckc** [comment]
fixed in #2848
