### ISSUE TITLE
console API on XS: compatibility, security impact?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2146]
**What is the Problem Being Solved?**

On XS, to date, we have stubbed out the `console` API; for example, in https://github.com/Agoric/agoric-sdk/pull/2145). This API gets exposed to user code, which is an incompatibility risk and such incompatibility risks notoriously lead to vulnerabilities.

See also UTF-8 in XS https://github.com/Agoric/agoric-sdk/issues/2118

cc @kriskowal @erights @warner 

**Description of the Design**

goals... somewhat conflicting...

 - [ ] never throws an error
 - [ ] when on chain: deterministic: don't let caller detect when you did toString() -> don't mess with args... so noop
 - [ ] slog
 - [ ] post-hoc debugging

also:

 1. [console-shim.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/lib/console-shim.js) as of 79e81b0 
     - provides a `console` that has at least `noop` methods for everything in SES [VirtualConsole](https://github.com/Agoric/SES-shim/blob/master/packages/ses/src/error/types.js#L259) (52e6830).
 2. [vatConsole](https://github.com/Agoric/agoric-sdk/blob/79e81b014ea6e3df1a98ef0d35e7cad2d1d966a6/packages/SwingSet/src/kernel/slogger.js#L34) seems to make a facet with `['debug', 'log', 'info', 'warn', 'error']` methods for use in local vat managers. Other vat managers seem to do likewise.

**Security Considerations**

Incompatibility risks notoriously lead to vulnerabilities

Are contract writers prepared for `console.clear()` to throw? Do we teach them about commit points?

**Test Plan**

?

**Comment by dckc** [comment]
In the xsnap design landed this week, the console methods are all noop:
https://github.com/Agoric/agoric-sdk/blob/e775a99afae43a8581cdeedd22545c7fa703c691/packages/xs-vat-worker/src/console-shim.js

**Comment by dckc** [comment]
@kriskowal notes in https://github.com/Agoric/agoric-sdk/pull/2225#discussion_r563024048 that our vat managers provide an incomplete `Console` API to vats. Is this a conscious (documented) policy decision or a bug? @warner ?

**Comment by dckc** [comment]
notes from chat with @warner  ...

goals... somewhat conflicting...
 - never throws an error
 - when on chain: deterministic: don't let caller detect when you did `toString()` -> don't mess with args... so noop
 - slog
 - post-hoc debugging

This merits further discussion. But it's not clear that there's a next step for me, so I'm removing my assignment.

**Comment by dckc** [comment]
I think the use of object-inspect should move this into MN-1.

**Comment by dckc** [comment]
@turadg should we re-open this? well, I guess this issue is about XS, and what bit you is the SwingSet vat console:

https://github.com/Agoric/agoric-sdk/blob/9cb480c5f3de7b194f37f9932df56cdc126b1c51/packages/SwingSet/src/supervisors/supervisor-helper.js#L158-L170

https://github.com/Agoric/agoric-sdk/pull/5429#discussion_r883797032

**Comment by turadg** [comment]
I think it needs an open issue. Whether you reopen this one or I file a new one, up to you.

*Acceptance criteria*
- the `console` type while coding in agoric-sdk matches the available `console` object during code execution

That could be by making Swingset's console support the [console API](https://developer.mozilla.org/en-US/docs/Web/API/console) or by modifying the typedef for the global console. I'd prefer to support the API as much as possible (if even with throwing "not implemented") than to create more special cases.

**Comment by dckc** [comment]
please open a new one, then, @turadg

**Comment by turadg** [comment]
👍 https://github.com/Agoric/agoric-sdk/issues/5453
