### ISSUE TITLE
TimerService createRepeater() deprecated; remove before Beta

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2164]
**What is the Problem Being Solved?**
The TimerService method `createRepeater()` was  renamed  to `makeRepeater()` and the old version deprecated. It should be removed before Beta.

**Security Considerations**

No impact.

**Test Plan**

Clean up any tests that reference the old name when done.

**Comment by dckc** [comment]
@Chris-Hibbert do you suppose recent work on TimerService addressed this issue?

**Comment by Chris-Hibbert** [comment]
Yes. absolutely.  fixed by #3853
