### ISSUE TITLE
Zoe invitation purse assumptions in lib-wallet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2165]
Paraphrasing @michaelfig: The user, not knowing any better, might manually deposit their Zoe invitations in a second purse and then wonder why the process of making an offer through the wallet isn't finding the invitation.

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/pull/2117#discussion_r551641304_

**Comment by samsiegart** [comment]
@michaelfig I assume this was from when we had the dropdown to select which purse payments get sent to. Now that we're just auto-depositing all payments into the default purse, I believe this isn't an issue. I'll close this, but anyone feel free to reopen if there's more considerations.
