### ISSUE TITLE
put comms tables in DB, not RAM

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2192]
## What is the Problem Being Solved?

The comms vat maintains one c-list that faces the kernel, plus one c-list facing each remote system to which we are connected. These behave just like the kernel-side c-lists (one per local vat), but live entirely in the "userspace" of the comms vat. The kernel treats the comms vat just like every other vat; the only exception is that the comms vat has the "please send me pipelined messages" flag enabled.

These comms vat c-lists are currently implemented as a collection of `Map` objects in the vat's heap. As a result, the RAM usage will grow with the size of the c-lists. The task here is to replace these `Map`s with database syscalls, specifically the `vatstore{Get,Set,Delete}` calls. These provide the lowest level of a vat (usually liveslots) with a synchronous disk-based key-value store. The comms vat does not use liveslots, and its state-management code can use these syscalls any time it would have accessed a `Map`.

## Description of the Design

The comms state is managed in [SwingSet/src/vats/comms/state.js](https://github.com/Agoric/agoric-sdk/blob/437814cf6dc78ecb7ee878e574f121b29a1e761f/packages/SwingSet/src/vats/comms/state.js). It creates a `state` object with five `Map`s and a handful of counters.

For each memory of the state object, we'll assign a unique string key. For the Maps (which are indexed by identifiers like `p+NN`, or by a remote name), we will prepend a distinguishing prefix to convert the old `Map` key to a unique DB key.

Once we've moved all the state into the DB, we may also be able to stop using the transcript, because there won't be any state left in RAM that needs to be rebuilt when the comms vat is restarted. This would provide an infinity-% speed up for swingset restarts. We'll tackle this in a separate ticket.

## Security Considerations

This won't increase the authority of the comms vat at all. It might expose slightly more authority to some comms vat code which did not previously have it (having access to `syscall` now provides access to the state table, whereas previously they were distinct authorities). However the comms vat does not have a lot of internal partitioning, so pretty much all code already had access to both `syscall` and `state`.

## Test Plan

Regular unit tests.

**Comment by FUDCo** [comment]
Closed by #2856
