### ISSUE TITLE
subtraction in getOutputPrice can cause errors

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2193]
**Describe the bug**
getOutputPrice calculates
```
  const oneMinusFeeInTenThousandths = subtract(10000, feeBasisPoints);
  const numerator = multiply(multiply(outputValue, inputReserve), 10000);
  const denominator = multiply(
    subtract(outputReserve, outputValue),
    oneMinusFeeInTenThousandths,
  );

  return floorDivide(numerator, denominator);
```
if outputValue is greater than outputReserve, the result will be negative, which will break things later. It should return zero in that situation.

**Additional context**
Observed in demo practice runs.

**Comment by erights** [comment]
Got a test case for reproducing this? Would be nice to include in #2191

**Comment by Chris-Hibbert** [comment]
I did it from the UI. The cause was passing in an `outputValue` that was larger than `outputReserve`.  The structure of `test-bondingCurve.js` makes that scenario easy to construct.

```
test('getOutputPrice too large', t => {
  const output = getOutputPrice(100, 50, 50);
  t.deepEqual(output, 0);
});
```
