### ISSUE TITLE
Something in our tools doesn't like bigint literal syntax

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2196]
**Describe the bug**

some tool somewhere in our toolchain is using a JavaScript parser that doesn't know how to parse bigint literal syntax.

**Expected behavior**

bondingCurve.js uses `const BIG_10000 = BigInt(10000)` because  `const BIG_10000 = 10000n` would misbehave. I haven't observed this, so I don't know what it takes to reproduce.  I think [@erights is more familiar]( https://github.com/Agoric/agoric-sdk/pull/2191#discussion_r556962291_).

**Comment by erights** [comment]
It fails under CI. The error message indicated a failure to parse. Something in our toolchain is using an old parser.
Could you try to reproduce and record the actual error (as I should have :( ) ?

**Comment by Chris-Hibbert** [comment]
Fixed by #2261
