### ISSUE TITLE
Cannot JSON.stringify Remotables

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2207]
![bad-stringify](https://user-images.githubusercontent.com/273868/104796946-64428700-576f-11eb-896f-1caf8f9de2dd.png)

On the left we see a call to `JSON.stringify` in lib-wallet.js. On the right we see in the debugger an expansion of the `values` argument being stringified. We see at the lower right that, at `[0].value[0]` this includes `handle`, `installation`, and `instance`. Currently these are simply empty objects, and this stringifies them as empty objects. However, these are actually remotables. As explained at #804 and #2018 (expecially https://github.com/Agoric/agoric-sdk/issues/2018#issuecomment-760707829 ) we must declare them as `Remotable` instead, as #2178 does. 

This debugger screenshot is from debugging #2178 where these are properly declared `Remotable`. However, these are still stringified as empty objects. The breakage at https://github.com/Agoric/agoric-sdk/pull/2178/checks?check_run_id=1707115405 is due to this. What happens is when

https://github.com/Agoric/agoric-sdk/blob/5ad007a5cc8392ad6a5b631be41748feeb2df6bf/packages/dapp-svelte-wallet/api/test/test-lib-wallet.js#L491-L497

first does a `JSON.parse` to recover this structure, which turns these remotables back into plain empty objects, and then does an ava `deepEqual` comparison with what should be the equivalent structure but had not gone through this information loss.

To fix this correctly, we should use marshal's `serialize` and `unserialize` rather than JSON's `stringify` and `parse`. But I don't know what the purpose of the stringification in `lib-wallet.js` is, so I don't know what a correct fix is.

#2178 is blocked on this. Attn @michaelfig 

There are a tremendous number of calls to `JSON.stringify` throughout our code. I have no idea if others have similar problems, but I worry.

**Comment by erights** [comment]
This debugging display was only possible due to https://github.com/Agoric/SES-shim/pull/559 . That PR was motivated by the experience of trying to figure out why #2178 was failing, which was finally diagnosed as this bug.

**Comment by michaelfig** [comment]
I will try to comment on this more fully, but please don't assume that the flattening of presences is unintended.  Several of the data structures are conveyed over json already.  Different paths are used when speaking captp.

**Comment by erights** [comment]
> please don't assume that the flattening of presences is unintended.

Excellent news! Looking forward to understanding this. Thanks.

**Comment by erights** [comment]
If it is intentional, is https://github.com/Agoric/agoric-sdk/pull/2178/commits/8ad59d50558b504946b2e44dbb6de07561f48e3c a correct fix to unblock #2178 ?

**Comment by michaelfig** [comment]
> If it is intentional, is [8ad59d5](https://github.com/Agoric/agoric-sdk/commit/8ad59d50558b504946b2e44dbb6de07561f48e3c) a correct fix to unblock #2178 ?

IIUC, yes it is.

**Comment by erights** [comment]
Fixed by fixing #2018
