### ISSUE TITLE
Our Nat arithmetic should use BigInts.

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2210]
Our previous hypothesis is that we could upgrade our `@agoric/nat` dependency to the current version which validates BigInts rather than Numbers (aka floats). However, the https://github.com/Agoric/agoric-sdk/pull/2209 experiment shows that too many call sites would change, mostly pointlessly. Instead, https://github.com/Agoric/nat/issues/137 would change `Nat` to be a coercer, as `BigInt` is. It also suggests that this package should export a validator as well as an `isNat` predicate.

Once `@agoric/nat` is upgraded to fix https://github.com/Agoric/nat/issues/137 and released, only then should we upgrade our own nat arithmetic to use it.

Note that the call siites at #2209 that are simply `BigInt(<integer literal>)` do not count against the original hypothesis, as those should all be written using the bigint literal syntax. We avoid it for now due only to #2196

**Comment by katelynsills** [comment]
This has been completed and `@agoric/nat` 4.0.0 is published!
