### ISSUE TITLE
xsnap release build has mxDebug

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2216]
**Describe the bug**

The XS SDK has 2 `GOAL`s in their makefiles: release and debug. Normally, only the debug build does stuff like print each exception. But the xsnap makefiles define `mxDebug=1` even for release builds.

https://github.com/Agoric/agoric-sdk/blob/0ef8ef14a04ba6ba7fef6e8ea42a5c5289907d74/packages/xsnap/makefiles/lin/xsnap.mk#L28

I don't think we want this.

@kriskowal @warner thoughts?

**Comment by kriskowal** [comment]
Seems like a bug to me.

**Comment by dckc** [comment]
p.s. for more on `mxDebug`, see

 - #2578
