### ISSUE TITLE
Represent resolution descriptions in a uniform way everywhere

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#2248]
In some of our APIs between the kernel and liveslots and comms, resolutions are represented as `[ vpid, { rejected, data } ]` and in some places as `[ vpid, rejected, data ]`.  This ought to be uniform (i.e., the same way everywhere), to minimize the odds of breaking things under maintenance.  In discussion, @warner and I lean towards the latter form.

**Comment by warner** [comment]
Also, this would be an excellent place to introduce type annotations to catch the leftovers.

**Comment by FUDCo** [comment]
Closed by #2443
