### ISSUE TITLE
use virtual pools in multipoolAutoswap

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2259]
## What is the Problem Being Solved?

`swapIn()`, swapOut()` and `getCurrentPrice()` all test a pair of brands to see which are secondary, and which is central and have code for three different cases. 

## Description of the Design

a single `getPool()` function could return either a single pool (for the secondary to central cases) or a synthetic pool (for the secondary to secondary case), then those functions ought to be able to have a single code path.

## Security Considerations

should be purely internal, with no security consequences.

## Test Plan

Existing tests should be sufficient, but we should make sure certain that there are tests for each user of the new `getPool()` that validate both of the new cases (simple pool, and synthetic pool.)

**Comment by rowgraus** [comment]
Just curious what you mean by synthetic pool?  I'm assuming this is some construction of two pools for convenience sake?

I'd suggest a different name for it as synthetic is commonly used to mean a synthetic asset and this could be confusing.

**Comment by Chris-Hibbert** [comment]
We could call it a virtual pool. It's an object that has the same API as a single-currency autoswap pool (which trades one currency for the central asset), but under the covers talks to two separate single-currency pools. As Dean pointed out, once we have this architecture, a virtual pool could also be used to interface to some other currency conversion exchange as long as it could present the required API to the multipool autoswap.

**Comment by Chris-Hibbert** [comment]
The ConstantProduct AMM (#3771, #4097) uses virtual pools.
