### ISSUE TITLE
add kernel option to use XS worker for all vats

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2260]
## What is the Problem Being Solved?

Thanks to hard work by @dckc and @kriskowal , we now have a swingset test (`test/workers/test-worker.js`) which exercises a reasonably complete set of vat interactions using the XS worker.

The next step is to run the full swingset unit test suite using the XS worker instead of the default "local" worker.

## Description of the Design

The first part of that is to add a kernel option which changes the default worker from "local" to XS. Let's add a `defaultManagerType` to the `runtimeOptions` that gets passed into either `makeSwingsetController()` (in `src/controller.js)` or the legacy `buildVatController` (same file). This value should be added to `kernelOptions`.

Within `kernel.js`'s `buildKernel()` function, this should be extracted from `kernelOptions` and passed as a new option-bag field to `makeVatManagerFactory`. Then `src/kernel/vatManager/factory.js` can use it as the default value, instead of `"local"`.

With this in place, we can do at least a manual test-everything-with-XS by modifying `controller.js` to set the default (as if a caller had provided one). Once we've done that and made sure everything works, we need to find a clean way to run all the tests with both settings. This might take the form of an alternate `package.json` command (`yarn test:xs` in addition to just `yarn test`), which.. sets an environment variable? maybe?

**Comment by dckc** [comment]
I'm working on [test-splitPayments.js](https://github.com/Agoric/agoric-sdk/blob/master/packages/ERTP/test/swingsetTests/splitPayments/test-splitPayments.js) from ERTP.

Ran into `TypeError#2: sort: no original host function`: some interaction between SES and metering:
https://github.com/Moddable-OpenSource/moddable/issues/550
