### ISSUE TITLE
Treasury: Governance model is ready for Beta

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2314]

**Comment by rowgraus** [comment]
* On chain governance to set collateralization ratio and margin requirement in the Treasury (per asset type)

**Comment by dckc** [comment]
Is this subsumed by #3473?

**Comment by Chris-Hibbert** [comment]
> Is this subsumed by https://github.com/Agoric/agoric-sdk/issues/3473?

I'm going to answer "yes" and close this ticket.
