### ISSUE TITLE
Treasury: Users can create and manage vaults

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2315]
Create a vault, pay back some debt, take out more collateral, add more collateral, close vault, get liquidated.

**Comment by rowgraus** [comment]
Rowland to clean up issues

* UI for each action here (possibly in other epic)

**Comment by katelynsills** [comment]
@Chris-Hibbert Is there anything left here that is needed for the Beta Treasury release?

**Comment by Chris-Hibbert** [comment]
Nope. This is all done.
