### ISSUE TITLE
Release SES with new debugging hooks

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2317]

**Comment by dckc** [comment]
PRs:

 - [x] https://github.com/Agoric/SES-shim/pull/568
 - [x] https://github.com/Agoric/SES-shim/pull/559

Also consider:
 - [x] https://github.com/Agoric/SES-shim/issues/567
   -  `packages/ses/NEWS.md` is the CHANGES file
   - [x] move SECURITY.md under packages/ses?

**Comment by dckc** [comment]
0.12.1 https://www.npmjs.com/package/ses

17aa9eb  chore(ses): Back to development with 0.12.1+1-dev https://github.com/Agoric/SES-shim/tree/master/packages/ses
