### ISSUE TITLE
Package source file names without /packages/ cannot be shortened

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2326]
***Low priority*** annoyance problem that can be postponed. However, if it turns out to be easy and quick to fix, that would be great.

Now that the stack filtering is in, the stack traces appearing on the console log output look much more pleasant. (under the default 'concise' setting. 'verbose' is still available.) Among the filtering rules I use to reduce the noise, keep the signal, and enable a pleasant interaction within vscode is to transform filenames like 
```
stuff/to/the-left/packages/stuff-to/the/right.js:80:3
```
into
```
packages/stuff-to/the/right.js:80:3
```
by recognizing `/packages/` and keeping only the right. Command clicking on the filename embedded in the console output stack display in VSCode takes me right to the correct place in the correct file. This particular heuristic is less ad-hoc than it looks. Looking for `/packages/` should work for anyone organizing a monorepo for the lerna path of least resistance. (hat tip @danfinlay )

This works even for most of our bundled files as long as the part starting with `/packages/` remains accurate. In looking at the output of `yarn test` and clicking on things, there's one case that doesn't fit the pattern. Frames like
```
    at Object.bootstrap (v1/SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
    at Object.terminateWithFailure (v3/SwingSet/src/kernel/vatAdmin/vatAdminWrapper.js:30:25)
```
If these were instead, for example
```
    at Object.bootstrap (v1/packages/SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
    at Object.terminateWithFailure (v3/packages/SwingSet/src/kernel/vatAdmin/vatAdminWrapper.js:30:25)
```
it would be more like the file names we're successfully shortening. They'd be shortened to
```
    at Object.bootstrap (packages/SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
    at Object.terminateWithFailure (packages/SwingSet/src/kernel/vatAdmin/vatAdminWrapper.js:30:25)
```
Clicking on these in vscode would go to the correct place, resulting in a more pleasant debugging experience.

Would that be easy and quick to fix?

**Comment by michaelfig** [comment]
> Clicking on these in vscode would go to the correct place, resulting in a more pleasant debugging experience.

That's only assuming all the vat code comes from Agoric SDK.

> Would that be easy and quick to fix?

These are bundled sources running in a vat (`v1` for vat number 1, `v3` for vat number 3).    Getting rollup to emit sensible filenames is very difficult.  Methods for finding the original sources after they have been transmitted to SwingSet will frequently be wrong, so I'm loathe to try making just one of the special cases work at the expense of complexity.

Maybe try stripping the `v\d+/` from the filename and see if that helps?

**Comment by erights** [comment]
> That's only assuming all the vat code comes from Agoric SDK.

I didn't explain it, but that's actually very pleasant in vscode as well. It the filename clicked on is the suffix of any file of any of the currently loaded projects but not of the current project, then vscode will prompt you with a menu of all the choices --- all the files from all the currently loaded projects with that suffix. I've used this with both SES-shim and agoric-sdk as loaded projects, with agoric-sdk as the project I'm using, clicking of a filename from SES-shim, getting prompted, clicking on the obvious choice, and going to *the correct position* within that chosen file. It's cool!

> Maybe try stripping the v\d+/ from the filename and see if that helps?

I can certainly special case it that way. I was just hoping to avoid that. The current rule is less of a special case because it aligns with the monorepo pattern encouraged by lerna.

I will proceed to do the special case for now with a TODO comment. Thanks.

**Comment by michaelfig** [comment]
> I can certainly special case it that way. I was just hoping to avoid that.

I'm willing to change the filename format, just am trying to understand where we can stash the var number (if we need to).

**Comment by erights** [comment]
> I'm willing to change the filename format, just am trying to understand where we can stash the var number (if we need to).

Instead of `v1/SwingSet/` if it were `v1/packages/SwingSet` as in
```
    at Object.bootstrap (v1/packages/SwingSet/test/vat-admin/terminate/bootstrap-speak-to-dead.js:40:59)
```
that would solve the problem. Does that work?

**Comment by michaelfig** [comment]
> Instead of `v1/SwingSet/` if it were `v1/packages/SwingSet` as in.... Does that work?

Could we have a literal ellipsis for this case to indicate that the prefix is unknown?  I would be less concerned about that, since the actual filename may not be a child of the `packages` directory.

`vat-v1/.../SwingSet/rest`

The `packages` heuristic would still be useful for cases when the sourceURL doesn't cooperate.
