### ISSUE TITLE
merge the multiple kernelKeeper resolution methods into a single one

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2359]
## What is the Problem Being Solved?

As part of retiring all resolved promiseIDs, we @FUDCo merged the three distinct kinds of resolution (`fulfillToPresence`, `fulfillToData`, `reject(ToData)`) into a single unified function. This merged three syscalls into a single `syscall.resolve`, and three dispatch functions into a single `dispatch.notify`. It also changed the comms protocol to merge three different messages into a single `resolve:` message.

The remaining step is to address the `kernelKeeper`, which still has three distinct methods: `fulfillKernelPromiseToPresence`, `fulfillKernelPromiseToData`, and `rejectKernelPromise`. These should be merged into `resolveKernelPromise(reject, data)`.

This is medium priority.. it isn't significant, but we should do it while we're still thinking about kernel promises. Whoever of me or @FUDCo gets a chance first should claim it (and remove the other from the assignments list).

**Comment by FUDCo** [comment]
The main reason these were not unified is that each of the three contains unique logic specific to the unique way its particular kind of resolution is represented in the kernel state database.  To properly carry this task to conclusion, I think the merging should be carried all the way through to the state store.  This arguably bumps the priority of this task, as it would be an incompatible change with respect to the state representation.

In a similar vein, we should probably also rectify the asymmetry between how resolutions are represented in `notify` deliveries and in `resolve` syscalls.  I don't know if that wants to be a second ticket or if it can be rolled into this one.

**Comment by FUDCo** [comment]
Turns out we already have a ticket for unifying the kernel representations, #2248

**Comment by FUDCo** [comment]
Turns out we already have a ticket for unifying the notify/resolve representations, #2248.

**Comment by FUDCo** [comment]
Closed by #2415
