### ISSUE TITLE
Hazard: Object.entries is surprising

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2360]
I (@erights ) have used `Object.entries` a lot, assuming I knew its semantics while misunderstanding it. I assumed it would provide entries for all enumerable own properties. It turns out it only provides entries for string-named enumerable own properties. This caused bugs. We need to look at all uses of `Object.entries`, see if they make sense, and fix the ones that don't.

See https://github.com/Agoric/agoric-sdk/pull/2331

**Comment by zarutian** [comment]
You are not the only one, I also assumed it worked like the [polyfill snippet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#polyfill) given at the MDN javascript documentation site.

Does having that in SES-shim break too much?

**Comment by erights** [comment]
> You are not the only one, I also assumed it worked like the [polyfill snippet](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#polyfill) given at the MDN javascript documentation site.

Actually, I think that MDN snippet is correct, because it builds on `Object.keys` which has the same possibly-surprising behavior about what property names it produces. But I have not looked it up or tested it to confirm.

> Does having that in SES-shim break too much?

`Object.entries` is stably specified and correctly implemented, by everyone AFAIK. SES will not change this. We simply need to be careful to only use it where its semantics are appropriate. By misunderstanding those semantics I failed at that. SES should not change to help avoid *this* hazard.

**Comment by zarutian** [comment]
Here is a replacement that enumerates symbols too:
```javascript
Object.allTheEntries = obj => {
  const entries = Object.entries(obj);
  Object.getOwnPropertySymbols(obj).forEach(item => entries.push([item, obj[item]]));
  return entries;
}
```

**Comment by erights** [comment]
Done!
