### ISSUE TITLE
Design: Select initial values for all RUN governance parameters

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2362]

**Comment by Tartuffo** [comment]
@rowgraus This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, ui, wallet, zoe, zoe contract

**Comment by Tartuffo** [comment]
@rowgraus Bump.  For proper project planning and tracking, this needs an area label covered by one of our weekly planning meetings.  Please pick the appropriate one from: agd, agoric-cli, agoric-cosmos, amm, core economy, cosmic-swingset, endo, ertp, getrun, governance, installation-bundling, metering, oracle, pegasus, run-protocol, ses, staking, swingset, swingset-runner, tc39, token economy, tooling, ui, wallet, xsnap, zoe, zoe contract

**Comment by dtribble** [comment]
@rowgraus I renamed this to better reflect the work that is missing.

**Comment by rowgraus** [comment]
Closing given MVP release.  New issue as needed for future releases
