### ISSUE TITLE
add eslint rule to forbid for..in loops

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2364]
## What is the Problem Being Solved?

The JavaScript `for .. in` [looping construct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) is error-prone and should not be used. It iterates over property names, and includes properties defined up the prototype chain, which can cause surprises, especially with Arrays.

The `for .. of` [construct](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) is much safer, and uses the JS iterator protocol in a sensible way. Our code should either use `for..of` or one of the reflection APIs meant specifically for examining object properties (`Object.getOwnPropertyDescriptors`, `Reflect.ownKeys`, etc).

@erights recommends that we add an eslint rule to forbid the use of `for .. in` throughought our codebase.

**Comment by erights** [comment]
Closed by #2423
