### ISSUE TITLE
Manual Timer and Timer have different APIs according to type checks

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2371]
From line 913 in test-zcf.js:
<img width="622" alt="Screen Shot 2021-02-09 at 11 00 03 AM" src="https://user-images.githubusercontent.com/2441069/107414169-7c839880-6ac6-11eb-90ef-caef5d1f73f7.png">

**Comment by Chris-Hibbert** [comment]
We weren't able to reproduce this. The current declaration of `ManualTimer` is ` {ManualTimerAdmin & TimerService}`, so it re-uses the same declaration of `setWakeup`.  VSCode currently seems to think everything is fine.
