### ISSUE TITLE
Vega (used in stat-logger) overrides O.p.hasOwnProperty by assignment

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2373]
Our mitigation of the override mistake adds 8 junk lines to every display of every object by the VSCode debugger's object inspector. https://github.com/Agoric/agoric-sdk/issues/2324 would enable to stop mitigating `Object.prototype.constructor` and thereby remove two of these. If we could stop mitigating `Object.prototype.hasOwnProperties` we could remove another two. Together, this would be a significant noise reduction.

@FUDCo AFAICT `Object.prototype.hasOwnProperty` is overridden by assignment only by something called "vega-util" which I think is only linked in due to some stats library you're pulling in. https://github.com/vega/vega-util itself claims to be superceded by https://github.com/vega/vega , so it is possible that upgrading that dependency might painlessly make the problem go away.

**Comment by FUDCo** [comment]
It's probably good to keep up with updates to libraries we use, but I'm willing to bet you a nickel that upgrading will not fix this.  How would I go about testing if the newer version of `vega` is still broken or not?

**Comment by erights** [comment]
In your local copy of SES-shim, comment out the listing of `hasOwnProperty` at https://github.com/Agoric/SES-shim/blob/bf06c3a4c97991b7377eba08af049c6d2ea64d31/packages/ses/src/enablements.js#L62

Locally link an agoric-sdk to that modified local copy of the SES-shim.

Then, I think it fails under the normal `yarn test`. If it doesn't, let's try to reproduce this together.

**Comment by erights** [comment]
> but I'm willing to bet you a nickel that upgrading will not fix this

You are correct. See https://github.com/vega/vega/issues/3075 . I owe you a nickel. Would you accept $0.05 worth of bitcoin instead?

**Comment by erights** [comment]
Hi @FUDCo See https://github.com/vega/vega/pull/3109 . I think this means 
   * we can make this problem go away by upgrading to the latest vega
   * my nickel debt to you is cancelled
   * you now owe me a nickel

I'll accept it in IST
