### ISSUE TITLE
kernel logging errors have their embedded values erased in the name of security

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2389]
@erights and I were talking about the use of `assert` within the kernel, which I've found to be frustrating, because it hides information that I need to figure out what caused the problem. He was (not unappropriately) horrified to learn that I deal with this situation by changing the assert from:

```js
assert(condition, details`important ${thing}`);
```

to:

```js
assert(condition, `important ${thing}`);
```

or even just:

```js
console.log(`important ${thing}`);
assert(condition, etc
```

He recommended using `quote` as a workaround instead of using a raw quasiliteral:

```js
import { assert, details, quote as q } from '@agoric/assert';

assert(condition, details`important ${q(thing)}`);
```

But, he was surprised that the `details` approach was hiding `thing` from the console, and this ticket is about providing steps-to-reproduce so he can investigate. Those steps are:

* check out the current agoric-sdk tree, `yarn` / `yarn build` as usual
* patch `packages/SwingSet/src/kernel/kernel.js` with:

```diff
diff --git a/packages/SwingSet/src/kernel/kernel.js b/packages/SwingSet/src/kernel/kernel.js
index 8371b17d..0f02858d 100644
--- a/packages/SwingSet/src/kernel/kernel.js
+++ b/packages/SwingSet/src/kernel/kernel.js
@@ -1,5 +1,5 @@
 import { Remotable, getInterfaceOf } from '@agoric/marshal';
-import { assert, details } from '@agoric/assert';
+import { assert, details, quote as q } from '@agoric/assert';
 import { importBundle } from '@agoric/import-bundle';
 import { assertKnownOptions } from '../assertOptions';
 import { makeVatManagerFactory } from './vatManager/factory';
@@ -397,6 +397,7 @@ export default function buildKernel(
   }

   async function deliverToTarget(target, msg) {
+    assert(false, details`nope target is ${target}`);
     insistMessage(msg);
     const { type } = parseKernelSlot(target);
     if (type === 'object') {
```

* `cd packages/SwingSet`
* `yarn test test/test-kernel.js -m "outbound call"`

The extra `assert false` should be triggered as the kernel is trying to send a message to a vat. The stack at this point should be pretty empty, and contain only kernel code.

Note that this particular test is fairly low-level, and creates a kernel from the start compartment. Our usual environment is creating the kernel inside its own compartment, from a `bundleSource` -created kernel bundle, which has its own copy of `@agoric/assert`. In general, if this detail-hiding mechanism depends upon cooperation (i.e. a shared `WeakMap`) between `@agoric/assert` and `console`, the use of multiple Compartments and multiple bundled copies of `assert` is likely to interfere.

**Comment by erights** [comment]
Done!
