### ISSUE TITLE
Do something useful with CI-generated perf benchmark data

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#2398]
## What is the Problem Being Solved?

As of the landing of #2387 our CI process is running a performance benchmark each time code changes are merged into the master branch of agoric-sdk.  Currently the data produced is published as a GitHub artifact associated with each CI run, which allows us to validate that the benchmarking is working and to manually examine the perf results on a case-by-case basis, but it's not terribly useful for tracking improvement (or lack thereof) over time.  The data should instead be put into some kind of data graphing/tracking repository/service so that it can be surfaced on a dashboard of some kind that people can watch.  We need to (1) determine what an appropriate home and presentation form for this data should be, and then (2) update the benchmarking script to send the data there.

**Comment by michaelfig** [comment]
I'm considering a solution based on https://github.com/prometheus/pushgateway

I think it would be easy for @FUDCo to push metrics at the end of the script, and then for me to try wrangling some of the data to see if we can get something useful.

I'll have more details later.

**Comment by michaelfig** [comment]
Implemented in #2599, the data is being exposed on the "Autobench" dashboard on our grafana instance.  Alerts sending to discord have also been set up if there are changes in the reported values.
