### ISSUE TITLE
Add Counter abstraction to Swingset

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2400]
As part of the work transitioning agoric-sdk to use the BigInt version of @agoric/nat, I realized that Swingset uses Nat extensively for asserting ids and counts. There is a open question of whether BigInt is the right thing to use for ids and counts which I will set aside for others to decide on, but to make the transition from the old versions of Nat easier, @warner suggested adding a `counter` abstraction such that the implementation details of using `number` or `bigint` would be hidden.

The counter would have:
* to/from string
* increment

And potentially:
* decrement (for counts, not ids)
* comparisons to 0 or initial state (for counts which decrement)

**Comment by erights** [comment]
I hope this is temporary until we make up our mind, and I hope we make up our mind quickly to use BigInt. Yes, there may be a performance cost currently for BigInts compared to floats on XS. But we do know how to fix that. Yes, we probably cannot get it fixed quickly. But neither do we know whether the performance difference will be a significant cost in the interim.

Aside from the options value of enabling us to postpone this decision, #2420 does not seem like a useful abstraction beyond that already provided by `Nat`. None of its operations are more convenient than just doing them directly with Nats.

**Comment by katelynsills** [comment]
The PR has additional benefits like:

* Using constants for special numbers like `1n` and other initial values.
* Eliminating duplicate code in kernelKeeper.js
