### ISSUE TITLE
improvements needed in Percent

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2417]
## What is the Problem Being Solved?

Use of Percent has revealed missing features and APIs that aren't ideal.

### scaleUp/scaleDown vs. multiiply and divide

Currently Percent's only operation is `scale(amount)`. It turns out that sometimes we need to both multiply and divide amounts by the same Percent. I originally thought that Percents should all be in the range 0-100, but that turns out to be wrong (e.g. collateralization ratios make more sense written as 120% or 150% than their inverse.) With `scale()` as the operation, I thought about `scaleUp` and `scaleDown`, but those assume the percent is larger than 100%. @dtribble suggested that the operations should look more like math, but `rate.divideBy(amount)` is the wrong sense. It's more like `rate. beTheDivisorOf(amount)` or `rate. beDividedBy(amount)`.

I think it would be good to have a convention for how to name Percent objects that is clearer about whether they are to be treated as larger or smaller than one, so it's clear whether the result is larger or smaller. What operation names would work sensibly with both ratios larger and smaller than one?

### toString

There  are a few places where the Vault wants to display the percent. Percents don't have an operation for this currently, so Vault applies the rate to a number like 100 or 10000 and displays that. Percents should be able to display themselves. The denominator isn't standardized, but displaying the numerator and denominator is probably the right answer. Is `toString()` the javascript idiom for this, or should a different method name be used? Is there a standard approach to producing a value to be displayed? (I18n and L10n libraries are the norm elsewhere. How far are we from a need for those? What can we do in the meantime?)

### Ratios of different brands

The current constructor of Percents presumes that percents will be used to scale amounts of a particular brand to the same brand. I haven't found a case yet where our code needs to mix Brands, but a plausible case is for exchange rates. Once we have such things, they would need to be careful about order of application.  If you have a rate that is $/¥, you want to multiply Yen amounts by the rate, and divide Dollars by the rate. The point of Percent was to enable this type checking.

For context, here are the uses of `makePercent()` and `.scale()` in agoric-sdk. 

https://github.com/Agoric/agoric-sdk/blob/a53c1af0bf86b4664dccb6e9549ff5bdbdec190b/packages/zoe/src/contracts/callSpread/pricedCallSpread.js#L150
https://github.com/Agoric/agoric-sdk/blob/f41efb727736dd589c3da8b665d76fbd9099e601/packages/zoe/src/contracts/loan/index.js#L65

https://github.com/Agoric/agoric-sdk/blob/f41efb727736dd589c3da8b665d76fbd9099e601/packages/zoe/src/contracts/loan/borrow.js#L54

https://github.com/Agoric/agoric-sdk/blob/a53c1af0bf86b4664dccb6e9549ff5bdbdec190b/packages/zoe/test/unitTests/contracts/loan/helpers.js#L94

https://github.com/Agoric/agoric-sdk/blob/f41efb727736dd589c3da8b665d76fbd9099e601/packages/zoe/src/contracts/loan/borrow.js#L60

https://github.com/Agoric/agoric-sdk/blob/a53c1af0bf86b4664dccb6e9549ff5bdbdec190b/packages/zoe/src/contracts/loan/scheduleLiquidation.js#L25

https://github.com/Agoric/agoric-sdk/blob/a53c1af0bf86b4664dccb6e9549ff5bdbdec190b/packages/zoe/src/contracts/callSpread/payoffHandler.js#L39

https://github.com/Agoric/agoric-sdk/blob/a53c1af0bf86b4664dccb6e9549ff5bdbdec190b/packages/zoe/src/contracts/callSpread/pricedCallSpread.js#L100

In some code under review, I also see these. (I've included a few lines for context.)

```
  const loanFee = makePercent(rates.loanFeeBPs, sconeMath, BASIS_POINTS);
  const liqMargin = makePercent(rates.liquidationMargin, collateralMath, 100);
```

for display:
```
          const margin = vm
            .getLiquidationMargin()
            .scale(amountMath.make(10000));
```
```
    const ratio = manager
      .getLiquidationMargin()
      .scale(collateralMath.make(10000)).value;
```
for computation:
```
    const margin = manager.getLiquidationMargin();
    const scaledCollateral = margin.scale(remainingCollateral);
    // that will require at least this much collateral:
    const maxScones = await E(autoswap).getInputPrice(
      scaledCollateral,
      sconeBrand,
    );
```
```
    const liquidationMargin = manager.getLiquidationMargin();
    // compute how much debt is supported by the current collateral
    const debtAllowed = liquidationMargin.scale(getCollateralAmount());
    E(priceAuthority)
      .quoteWhenLT(debtAllowed, sconeDebt)
      // priceQuote is { amountIn, amountOut, timer, timestamp }
      .then(quote => {
```

**Comment by katelynsills** [comment]
Still processing, but what would be a good example of needing to divide by a percent?

**Comment by dtribble** [comment]
> Still processing, but what would be a good example of needing to divide by a percent?

For a loan, the max amount to loan would be the value of the collateral currently, divided by the liquidation percent (i.e., `price(collateral) / 120%`).

**Comment by katelynsills** [comment]
I'm not sure whether this should be a record with properties or an object with methods, but what about calling it `ratio` instead of percent to make it more general, and what about using functions for multiply and divide that take in the ratio as a parameter? I think that seems more natural. Maybe it's just me, but every time I see "scale by a percent" I have to reinterpret what that means. Whereas divide or multiply by a ratio seems a lot clearer to me. 

```js
const makeRatio = (numerator, denominator, brand, amountMath) => {
  return harden({
    getAmountMath: () => amountMath,
    getBrand: () => brand,
    getNumerator: () => numerator,
    getDenominator: () => denominator,
    assertBrand: amount =>
      assert(
        brand === amount.brand,
        `ratio's brand ${brand} does not match amount's brand ${amount.brand}`,
      ),
    toString: () => numerator / denominator, // not to be used for calculations
  });
};

const multiplyByRatio = (amount, ratio) => {
  ratio.assertBrand(amount);
  return ratio
    .getAmountMath()
    .make(
      floorDivide(
        multiply(amount.value, ratio.getNumerator()),
        ratio.getDenominator(),
      ),
    );
};

const divideByRatio = (amount, ratio) => {
  ratio.assertBrand(amount);
  return ratio
    .getAmountMath()
    .make(
      floorDivide(
        multiply(amount.value, ratio.getDenominator()),
        ratio.getNumerator(),
      ),
    );
};
```

**Comment by katelynsills** [comment]
Oh also, once we redo the amountMath API, we can drop it as a parameter of `makeRatio` and drop `getAmountMath`

**Comment by Chris-Hibbert** [comment]
That has a lot to recommend it. That calling syntax is reasonably natural. Thanks for the ideas.

It's unfortunate that the methods don't live on the object, and would have to be explicitly imported  (unless there's a javascript trick I've missed).  Thinking of this as a stand-in for the overloaded operators that may be coming to JavaScript makes it easier to accept that. It's interesting that that would put the operators on the Amounts rather than the Ratios in order to make the syntax natural.

I think this is consistent with an extension to ratios of different brands. `multiplyByRatio()` and `divideByRatio()` would assert complementary brands and use different amountMaths, but otherwise this approach would continue to work. 

In the writeup above, I didn't mention `makeAll()` `makeNone()` and `complement()`, which all make more sense for percents (used primarily for the callSwap) than ratios. They'd all need special purpose replacements (`make100Percent()`, `makeZeroPercent()` and something for "subtract from 100%"), but maybe those won't be widely used.

I suspect that code that wanted to actually display the value to a user wouldn't use `toString()`, but having `getNumerator()` and `getDenominator()` lets them choose how to handle it.

**Comment by katelynsills** [comment]
> I suspect that code that wanted to actually display the value to a user wouldn't use toString(), but having getNumerator() and getDenominator() lets them choose how to handle it.

Hmm, in thinking about it, if we expect to return `ratios` from a contract, we probably want it to be a record with properties so that we don't have to make remote calls.

**Comment by dtribble** [comment]
Random thoughts:

I also think it must be pass-by-copy. They are a pretty basic numeric type. Does that mean it cannot have operations?  (/cry).  If so, then Kate's direction seems the way to go.  Otherwise, `apply` and `applyInverse` might be an alterative naming direction.  If we are using a static math for it, then multiply seems fine, and we wouldn't need longer names.

In the general case, there's a different brand for numerator and denominator. For example, a conversion rate between currencies is a ratio.

It shouldn't need both an amountMath and a brand?

If we kept the distinct amountMath approach, then the similar pattern here is that a units-ratio is a distinct instance (e.g., sconeEthRatioMath for Scones:Eth or just sconesRatioMath Scones:Scones). What's the comparable thing for the simpler amountMath?

Ideally, the ratios would actually have parameterized types in our typescript definitions :).

**Comment by Chris-Hibbert** [comment]
> Hmm, in thinking about it, if we expect to return ratios from a contract, we probably want it to be a record with properties so that we don't have to make remote calls.

I interpreted this as the return value of a toString/forDisplay method, rather than its own native representation. Was that what you meant?

> I also think it must be pass-by-copy. They are a pretty basic numeric type. Does that mean it cannot have operations?

Hmm. I agree we don't want to use them as remote objects, but so far nothing has shown a need to share them. There's often a value specification passed to an interface, but once constructed, it's only used internally, other than for display-to-human purposes. Maybe we can get away without passing them as objects? Is there a javascript idiom for passing the construction parameters rather than the object itself?

> In the general case, there's a different brand for numerator and denominator. For example, a conversion rate between currencies is a ratio.

Agreed. The case where the two are the same is extremely common, and should be easier to program with.

> It shouldn't need both an amountMath and a brand?

brand is available from the amountMath, so we don't need both.

> Ideally, the ratios would actually have parameterized types in our typescript definitions :).

I thought about that as well, but we don't do the same for amountMath, Payments or Purses. If it's worth doing, I'd think it's worth doing pervasively. Typescript supports generic types, I think, so this shouldn't be too hard. Is it worth the effort to declare on Purses and Payments?

**Comment by Chris-Hibbert** [comment]
Oh, and since we're talking about AmountMath, it might make sense to take another look at the design once we settle on a direction for that redesign (#2310).

**Comment by Chris-Hibbert** [comment]
To turn it into a pass-by-copy record, we can drop the amountMath, and build the result Amounts manually. Ratios only apply to Nat AmountMaths, so any checking amountMath would have done is unnecessary. All they were used for in `multiplyByRatio()` and `divideByRatio()` above was building the amount record, which doesn't take an AmountMath.

In order to make conversionRates (one brand to another) have the same API as pure Ratios, they can both be `{ numerator, denominator, numBrand, denomBrand }`.  

The constructors will verify that the numerator and denominator are compatible number types (Nat until we convert to BigInt, BigInt afterwards.)

We'll provide `ratioToString(ratio)` that divides and returns just the resulting Number if the brands are the same. When the brands are different, it would print more detail. Any UI element that wants a different format (120, 120%, 1.2, 1.20) has access to all the data.

I will also provide helpers for complement (1 - ratio if the ratio is less than 1) and invert (1/ratio if the ratio is non-zero).

**Comment by katelynsills** [comment]
Sounds good to me. One thing on this:

>We'll provide ratioToString(ratio) that divides and returns just the resulting Number if the brands are the same. When the brands are different, it would print more detail. Any UI element that wants a different format (120, 120%, 1.2, 1.20) has access to all the data.

Anytime we represent the brands to the user, we will want to use their petnames for the brands, so I'm not sure how well this can be stringified in a place other than the dapp and any helpers we provide dapp developers. Maybe we should take the stringification and move it into the ui-components package when it exists. What were you thinking for the case where the brands are different?

**Comment by Chris-Hibbert** [comment]
something simple and visibly wrong so it shows up early in the UI if someone tries to use the default for a conversionRate.

`${ numerator / denominator } (${numBrand}/${denomBrand})`

I'm open to suggestions.  I think the above is better than throwing an exception, even though I think the output is unlikely to be what anyone wants. In a debugging situation, I think the above would be more helpful.

**Comment by katelynsills** [comment]
Hmm, we don't ever want to display the alleged name in the UI, which I think `${numBrand}` would do. In my opinion, we should not do the stringify function in this set of improvements but should instead make sure to have a UI component for it.

**Comment by Chris-Hibbert** [comment]
Okay, good point. It's a foot-gun for other frontend developers, and we should just not build a toString.  I think all the data is available, so it's not a significant loss.

**Comment by dtribble** [comment]
I think the discussion got to the right place. I'm not sure what the final API is. 

We should also have the ability to multiply a ratio by another ratio, to get a new ratio.

**Comment by Chris-Hibbert** [comment]
The API is that Ratios are Records. They include both a numeratorBrand and denominatorBrand, which will often be the same. There are various constructors and functions for multiplyBy and divideBy. 

> We should also have the ability to multiply a ratio by another ratio, to get a new ratio.

What's the use case for this? It should be easy to support, and to validate the units are properly applied, but knowing the expected use cases may tell me how many support functions are required.

**Comment by dtribble** [comment]
Going through two AMM curves was the example that made me think of it.

**Comment by katelynsills** [comment]
I missed this the first time around, but it occurred to me that we should just represent the `numerator` and `denominator` as amounts rather than splitting up the value and brand, since the amount is merely a record of the value and brand:

Rather than:

```
{ numerator, denominator, numBrand, denomBrand }
```

```
{ 
  numerator: { brand, value },
  denominator: { brand, value }
}
