### ISSUE TITLE
yarn lint-fix does not reach dapp-svelte-wallet/ui

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2419]
Especially after a big search replace, I rely on `yarn lint` to renormalize the source code as well as to alert me to any static lint errors I introduced. However, at 
https://github.com/Agoric/agoric-sdk/blob/667397754fc3d4db5956a340ef78b94e030a9701/packages/dapp-svelte-wallet/ui/src/display.js#L18 
we see, for example, a statement that's too wide. whereas at 
https://github.com/Agoric/agoric-sdk/blob/667397754fc3d4db5956a340ef78b94e030a9701/packages/dapp-svelte-wallet/ui/src/display.js#L20-L24
we see a statement that's too tall. Accepting suggestions in the IDE fixed them.

My primary concern though is not aesthetics. I've been using `yarn lint` to catch statically catchable problems.

**Comment by tgrecojs** [comment]
i've run `yarn lint` script and see that `dapp-svelte-wallet` and `dapp-svelte-wallet-ui` were the only 2 packages that showed `exit 0`. i would've thought that `dapp-svelte-wallet-api` would fail to lint as well but found that its npm scripts object seems to be configured properly whereas  `dapp-svelte-wallet/package.json` isn't.
  
https://github.com/Agoric/agoric-sdk/blob/1eb65d4af52a40e229ec1eefaff0200d3ab6aba0/packages/dapp-svelte-wallet/package.json#L19-L24

here is the `dapp-svelte-wallet-api` package. I'm running into an issue with my local eslint atm but I think that updating the code above to follow suit should fix it? 

https://github.com/Agoric/agoric-sdk/blob/1eb65d4af52a40e229ec1eefaff0200d3ab6aba0/packages/dapp-svelte-wallet/api/package.json#L9-L14
