### ISSUE TITLE
vatWarehouse transcript replay must commit changes, and coordinate with crank success/fail rewind

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2422]
## What is the Problem Being Solved?

I wanted to capture an issue with the new #2277 "Vat Warehouse" that came up in conversation with @dckc today. It won't be a problem right now, but there are a couple of different lines of development that are destined to collide in an interesting way.

* when the VatWarehouse is asked to deliver a message to a vat, it might need to load that vat into memory (if it wasn't already resident)
* when doing that load, it must replay some number of transcript entries (all of them, unless the vat was loaded from a snapshot, in which case it only needs to replay the entries that occurred after the last snapshot was taken)
* at present, transcript replay does *not* cause any kernel state changes: all syscalls are ignored (well, compared against the transcript for consistency, then ignored)
* however, one path for #1872 is to do extra work at the end of each crank to gather FinalizationRegistry callbacks and report the newly-released imports to the kernel with some sort of `syscall.drop()`
  * on consensus-hosted swingsets (i.e. on-chain), this is required to behave deterministically. We plan to achieve this by running all vats on XS-based workers, instructing the XS engine to perform a full GC sweep at the end of each crank, and giving the supervisor+liveslots time to run (after the vat code has gone quiescent) to let the finalizers fire and send the resulting `syscall.drops` back up to the kernel
  * on non-consensus swingsets, if we're using local workers, this might *not* be deterministic: the finalizers will fire earlier/later between the initial execution of a transcript, vs on subsequent replays
  * if a `drop` happens during replay for a vref that is not in the c-list, we ignore it: we observed and processed this one in the previous run
  * but if the vref *is* still in the c-list, we must collect it and and process the resulting refcount work, because it's not going to happen again, and if we ignore it during replay, we'll never release the object
  * the refcount work will make state changes, some collection of c-list removals, refcount decrements, deletion of kernel object/promise table entries, and "hey exporting vat we don't need this anymore" run-queue work items
    * (we might not do the full refcount work right away, but we'll record at least enough information to let it happen later)
* so the act of "paging in" a vat will potentially cause state changes
* these changes need to be committed independently of the crank which provoked the paging-in
  * if that crank fails, any syscalls that happen during the crank get rolled back, so the saved state of the vat will be left in a coherent state, so it can be reloaded again if/when we attempt the crank again
  * the changes that get committed during page-in should not also get rolled back
  * in particular, the cycle begins with a run-queue item being popped off the queue. Our current "crank failed, abort the txn and record vat-termination handling instead" code assumes that this pop gets unwound as well, and it re-pops the item (so we won't try it again, after the vat is deleted). The two sides of the delivery need to coordinate correctly to make sure only one item is popped from the queue.
  * likewise the `crankNum` is a database entry, which we increment just before (or after? on which side of the circular fencepost do you stand?) the crank is processed, and we should increment it exactly once, no matter how the crank fares

Now that I write it up, I see that maybe it wouldn't be fatal to unwind the page-in `syscall.drop` consequences (in response to a failed crank) too: if the vat is then terminated, we'll be dropping *all* its imports, so any refcounting consequences will be repeated as part of the vat-termination logic. If we allow the vat to live (so that we might attempt the delivery again in the future, e.g. with a different Meter), then when we re-load it, we'll have another opportunity to observe the drop.

But in general, we need to be very deliberate about the transaction windows, and be clear about what state changes are and are not subject to rewind when a crank fails.

**Comment by dckc** [comment]
@warner notes complications around `evict` in https://github.com/Agoric/agoric-sdk/pull/2784#pullrequestreview-679089149

**Comment by dckc** [comment]
@warner is this addressed by #2848 for the same reasons #3279 is?
