### ISSUE TITLE
Use index objects for dapp communication to the wallet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2449]
When the dapp uses the wallet bridge to communicate with the wallet backend, the dapp should not use the user's petnames, as those could change. It should talk with the wallet in terms of some sort of index/objects for purses, etc.

**Comment by Tartuffo** [comment]
@samsiegart @dckc can you say whether this is out of date due to our new communications mechanism?  assigning to @dckc to triage and close if possible.

**Comment by dckc** [comment]
It is not out of date; it's as relevant as it ever was. The fact that we've gotten this far supports **possible-post-launch** but conservatively, let's say it blocks #3995 , for now.

**Comment by dckc** [comment]
We're now using board ids in marshal slots.
