### ISSUE TITLE
Cannot initialize @agoric/assert, missing globalThis.assert under Node 15

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2454]
## Describe the bug

In the documentation repo, which uses the agoric-sdk packages through `agoric install`, building agoric-sdk with Node 15 causes errors in the documentation tests that building with Node 14 does not. The error is:

```
Cannot initialize @agoric/assert, missing globalThis.assert
```

coming from agoric-sdk/packages/assert/src/assert.js:21

[Full log here](https://gist.github.com/dckc/4ccfb54128f0b3fe0bc2956c1e4e9e28)

## To Reproduce
1. Use Node 15
2. Checkout the [documentation branch](https://github.com/Agoric/documentation/pull/439)
2. Within agoric-sdk, do `yarn install --force`
3. Within agoric-sdk, do `yarn build`
4. Within agoric-sdk, do `yarn link-cli /usr/local/bin/agoric`
5. Within documentation, do `agoric install`
6. Within documentation, do `yarn test`

To make the tests pass, use Node 14 and repeat the instructions above, including the `yarn install --force`

## Expected behavior
The tests should pass

## Platform Environment
 - what OS are you using? 
 11.2.1 (20D74)
 what version of Node.js?
v15.7.0 (npm v7.5.2)
 - is there anything special/unusual about your platform? No
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)
 - agoric-sdk maste

**Comment by dckc** [comment]
odd... what is SES 0.10.4 doing in here?

```
$ grep version packages/install-ses/node_modules/ses/package.json 
  "version": "0.10.4",
```

even though install-ses says it depends on ses 0.11.0:

```
$ grep '"ses"' packages/install-ses/package.json 
    "ses": "^0.11.0"
```


trying to reproduce with a clean check-out, I lose at `yarn install`
https://gist.github.com/dckc/71c20bb02b04fe12cbd087e293f68054

if I switch to 14, `yarn install` and switch back, I can continue...

**Comment by dckc** [comment]
This bit from a `yarn-error.log` suggests we're picking up an out-of-date published version of `@agoric/install-ses`:

```json
  "@agoric/install-ses@*", "@agoric/install-ses@^0.3.1":
    version "0.3.1"
    resolved "https://registry.yarnpkg.com/@agoric/install-ses/-/install-ses-0.3.1.tgz#ede5eebc41dacab6ec7a4071dea26d8512f0a2b4"
    integrity sha512-3iTxk35ijk0F7xPSOMbxHnEhz//ixZon0ZAab2wVTELJ2p1t6NioK5VE5ozmGeAs/jnpY9W8qNRk7ZphEyvgTg==
    dependencies:
      "@agoric/eventual-send" "^0.11.0"
      ses "^0.10.1"
```

**Comment by katelynsills** [comment]
From what I can tell, `agoric install` does not create a yarn.lock, and it may not update it.

**Comment by dckc** [comment]
re node 15 support, Kate points out CI updates coming... #2264

**Comment by dckc** [comment]
I gather I shouldn't have closed this.

**Comment by dckc** [comment]
result of discussion: while there's a risk that this affects dapps, we'll update ci to 15 to check that (#2264) and not worry too much about the documentation repo working with odd-numbered node versions.

**Comment by katelynsills** [comment]
I'm working in the dapps for an unrelated reason and seeing messages like the following, which I think lends credence to the old lockfile that doesn't get updated by `agoric install` explanation:

`dapp-pegasus-api > @agoric/zoe > @agoric/import-bundle@0.2.0" has unmet peer dependency "ses@^0.11.0".`
