### ISSUE TITLE
Move cosmic-swingset kernel metric metadata into SwingSet

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2456]
I wasn't aware that cosmic-swingset was depending on the particular details of what was contained by the kernel stats object. We should probably revisit how these are generated.  Since what you're doing is providing the stats with descriptive strings, these strings (and other metadata, such as what I suspect are symbolic labels of some kind that I suspect are being fed to the external graphing service) probably should be attached at the source where these counters are originally defined so that they can be maintained.

_Originally posted by @chipmorningstar in https://github.com/Agoric/agoric-sdk/issues/2455#issuecomment-780265949_

**Comment by FUDCo** [comment]
@michaelfig I've lost track of the PR, but didn't you do this?  Can this issue be closed?
