### ISSUE TITLE
xsnap isn't pinned to a Moddable version

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2457]
our `build.js` grabs the latest version rather than the version pinned in the git submodule

cc @warner @kriskowal @michaelfig

**Comment by michaelfig** [comment]
Part of this is mea culpa: I blindly implemented the expansion of the `git submodule update --init` in `build.js` without thinking about the consequences of automatic updates.

Thanks for taking this on.

**Comment by dckc** [comment]
fixed in #2542
