### ISSUE TITLE
Rename Multipool autoswap

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2459]

**Comment by Tartuffo** [comment]
@rowgraus  to finalize the name ("Kinetic"?), then @Chris-Hibbert  to implement.

**Comment by Chris-Hibbert** [comment]
There's nothing in our code base that's called multipool autoswap at this point. I don't think there's any work here other than relabelling things in the UI. Can we close this?

**Comment by Tartuffo** [comment]
Done!
