### ISSUE TITLE
add sequence number to comms protocol

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2483]
## What is the Problem Being Solved?

To support the upcoming "drop exports only after all imports are known to be dropped" feature of the comms protocol, which will need to track which outgoing messages (that reference some exported object or promise) have not yet been received by the side that sends a `drop`, we need to attach a sequence number to each outbound message. This number should be monotonically increasing, scoped to a single remote (i.e. a distant swingset's comms vat), starting at 0, and optional. Each message will start with e.g. `NNN:deliver:o+4:...` instead of `deliver:o+4:...`.

Our vat-tp layer provides guaranteed in-order delivery of all messages, so the sequence number can be implicit (just count the messages). We'd like to include an explicit copy of the seqnum to start, because debugging a mismatch would be really difficult, but we'd like to drop it once we're sure it's working correctly. So the seqnum is optional. Messages that lack a seqnum will start with `:deliver:o+4:...`, so we can still parse them by splitting on colons as before: if the first field is empty, the seqnum was omitted.

The receiving side should maintain a counter. If the message includes a seqnum, it must match, else the connection is considered broken. If the message lacks a seqnum, the message cannot trigger a mismatch error.

The comms vat will eventually need to know the highest inbound seqnum that it has processed, and include this seqnum in outbound `drop` messages. The comms vat will also need to learn the seqnum that will be applied to an outbound message that is being assembled, to update the c-list entries for any exported objects/promises with that value.

cc @FUDCo

**Comment by FUDCo** [comment]
Closed by #2702
