### ISSUE TITLE
per-block data logging (performance mostly)

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#249]
I added code in 0ca366c6427fb2c620d739f19bb5458b0469b49f to display (with `console.log`), after each SwingSet invocation, the following data:

* size of the resulting kernel state vector (this includes the transcripts, so it grows over time)
* size of the current mailbox contents (this shrinks back to tiny after messages get acked)
* time spent in `controller.run()` (processing all messages)
* time spent serializing the mailbox contents
* time spent serializing and saving the kernel state

in a line like this (which involved a batch of 100 `Purse.getBalance()` calls):

```
wrote SwingSet checkpoint (kernel=4070828, mailbox=28392), [run=97ms, mb=3ms, save=44ms]
```

It would be lovely to record this, along with the block number and the number of inbound messages added, to some kind of database. Our block explorer should show this data, as well as let us look at some statistics (histogram of processing times, top-most-expensive block in the last 24 hours, growth rate of kernel state, graphs, etc).

**Comment by dckc** [comment]
this is addressed by the slogger, I'm pretty sure.
