### ISSUE TITLE
add `resolved-promise` qclass, drop kernel promises after fulfillToData/reject

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#25]
In today's meeting we worked out a performance improvement that Dean said was pretty important on Midori. Basically we want to forget the short-lived promises that are created for the result of a method send that yields plain data (or rejects to an error), instead of resolving to a callable reference.

When the liveSlots layer serializes an outgoing promise (i.e. in the argument of a method send, but the more interesting case is during the receipt of a `dispatch.deliver`) for the first time, it calls `.then` on it to subscribe to hear about its resolution. It also calls `syscall.createPromise()` to  generate a kernel-side promise/resolver pair, and sends the generated `promiseID` in the marshalled slots. This will let the receiving side know what kernel promise to reference if it wants to send messages to the promise as a target. The `.then` is used to invoke `syscall.fulfillToXYZ` when the local promises resolves, and closes over the resolverID value for use in that call.

Now, if the promise is resolved to something (data or a rejection), the kernel learns that the promise state has changed (the kernel promise table has its `state` value changed from `unresolved` to `data` or `slot` or something), but the local liveSlots layer doesn't particularly care. It sent the `syscall.fullfil` method, so it's job is done.

But, to improve things, we'd like for both the kernel and the subsequent comms vat (if the message is being sent over the wire) to be able to forget about the promise. In a lot of cases, the sending vat will forget about the promise quickly, so we'd like everyone else to forget about it too. We don't know *when* the vat forgets about it, though, since we don't have weakrefs. If it turns out the vat didn't forget about it (i.e. it sends it a second time), we need to make sure the receiving side still gets the right thing (a promise which, when asked with `.then`, yields the same resolution as before) (and BTW it doesn't have to be the exact same Promise instance: we declare Presences to have identity, but not Promises).

So, the liveSlots layer should maintain a weakmap from local promises to their resolved value. If liveSlots is asked to serialize something that turns out to be in this map, it should generate data that represents a "resolved promise": something like `{"@qclass": "resolved-promise", "data": {...}}`, and something similar for rejection (either using `rejection:` instead of `data:`, or using a different `@qclass` value). The kernel is unaware of this slot type, and does no special mapping on it. This object travels all the way through to the far side, and is demarshalled using `Promise.resolve(data)`.

LiveSlots keeps a map from Promises that have been serialized to the kernel-allocated promiseID that it uses to serialize them. When liveSlot sees the promise get resolved, it should delete this mapping.

When the kernel sees the `syscall.fulfillToData`, it will queue `dispatch.notifyFulfillToData` calls to all subscribed vats. When that dispatch makes it to the top of the run-queue, it invokes the `dispatch()` call. Just before delivering that call, it should remove the promise from the import table of the receiving vat, making that promise no longer accessible. The receiving vat should remove the promiseID from its tables. The kernel should also remove the receiving vat from the subscriber list. The kernel/vat contract is that vats cannot expect to reference a resolved(-to-data-or-rejection) promise after being notified of its resolution.

When all subscribed vats have been removed from the list, the kernel should remove the promiseID from the promise table entirely.

`fulfillToPresence` cannot prune promises this way, only `fulfillToData` or `reject`. TODO: understand why, then explain it.

The comms vat, after it delivers the resolution to some remote machine, can delete the promise too.

Dean pointed out that sending a locally-generated promise is not where this improves anything. The real win is for the promises that are generated in response to an inbound remote message (which represented more than half of all Promises, if I remember him correctly). These promises are frequently resolved quickly and then discarded, never to be shared with anyone but the caller.

**Comment by erights** [comment]
@FUDCo @warner I'm reasonably certain this is obsolete so closing. But I'm assigning you two in case I'm missing something.
