### ISSUE TITLE
Print object methods rather than `[Presence 23]`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#250]
I realized that it's very hard for people to inspect the objects that they have access to in our pixel demo. For instance, if they do:

```js
home.gallery!tapFaucet()
```
they get:

```[Presence 14]```

But they would be able to poke at things in a much more natural way if we told them what methods were present on the object that they receive. Maybe something that uses `Object.getOwnPropertyNames()` and prints:

```[Presence 14]: has methods [getBalance, getName, getIssuer]```

**Comment by erights** [comment]
See #804
