### ISSUE TITLE
rename makeAsyncIterableFromNotifier

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2506]
## What is the Problem Being Solved?

`makeAsyncIterableFromNotifier` is an unwieldy name. Dean suggests `iterateNotifier`.

## Description of the Design

add name, deprecate, migrate, cleanup.

## Security Considerations

None
## Test Plan

None

**Comment by kriskowal** [comment]
`iterateNotifier` or maybe even `iterateNotifications` seem good to me, unless we can have notifiers just implement `Symbol.asyncIterator` directly. Do they not?

**Comment by Chris-Hibbert** [comment]
Notifiers do not implement `Symbol.asyncIterator`. 

@erights would that be reasonable to add?

**Comment by erights** [comment]
> Notifiers do not implement `Symbol.asyncIterator`.

Yes they do. Look again.

> @erights would that be reasonable to add?

Done long ago.

**Comment by erights** [comment]
Now that we understand `makeAsyncIterableFromNotifier` is not for general normal use, and is no longer even mentioned anywhere in agoric-sdk outside of the notifier package, it no longer needs to be renamed. Given its tightly scoped intended usage, having a painfully clear name is probably better. So I'm closing this bug.
