### ISSUE TITLE
slogger surprisingly hardens console.log() arguments

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2517]
While debugging some #2018 changes that attempted to apply `Far()` to an object, I ran into some very weird behavior. I tracked it down to the fact that my `slogger` code was independently calling `harden()` on the arguments it received. Because vats get a `console` which also routes to the slogger, and because `Far()` and `Remotable()` cannot be called on already-`harden()`ed objects, my diagnostic logging was changing the state of the objects under observation, which cost me several hours trying to unwind the weirdness.

https://github.com/Agoric/agoric-sdk/blob/8afe6046dd4e7fdc52c73f2617cc888975b59994/packages/SwingSet/src/kernel/slogger.js#L19-L21

The fix is simple: remove that `harden()`. I'm not entirely sure why I included that call.. I try to be in the habit of `harden()`ing anything before allowing it to leave the function I'm writing, but now I think that's the wrong instinct. Rather, I should `harden()` only when creating a new object: if someone else handed the object to me, it is *their* responsibility to harden it, and it would be surprising for me to `harden()` it for them.

cc @erights to see if I'm updating my instincts correctly

**Comment by erights** [comment]
>  I should harden() only when creating a new object: if someone else handed the object to me, it is their responsibility to harden it, and it would be surprising for me to harden() it for them.
>
> cc @erights to see if I'm updating my instincts correctly

Correct. Usually literally correct, but there's one valid pattern where this is correct once we expand the meaning of "create".

Sometimes one need to do some further computed initialization before exposing the object to clients. An object lifecycle is often
   * literally create the object. Keep it closely held.
   * initialize the object. Keep it closely held during initialization.
   * initialization is complete. All invariants are in place. It is ready to be exposed to clients.
   * harden it
   * expose it to clients.
