### ISSUE TITLE
add vatParameters to setup() arguments, make comms starting ID configurable

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2529]
## What is the Problem Being Solved?

While debugging unit tests that use multiple comms vats (e.g. `test-message-patterns.js`), it would be nice to make the two comms vats use different number ranges when allocating their remote object/promise IDs, so the wire messages are easier to distinguish. We can accomplish this by changing `state.js` to start from an ID provided in `vatParameters` (with a suitable default when it is not provided), but currently `vatParameters` don't make it into a comms vat, because the `setup()` form of vat creation does not include it.

The task is to change `src/kernel/vatManager/manager-local.js` to call `setup(syscall, state, helpers, vatPowers, vatParameters)` instead of the current `setup(syscall, state, helpers, vatPowers)`.

Then, change the comms vat to pass a configuration value in from `vatParameters` into the state initialization code.

**Comment by FUDCo** [comment]
Closed by #2537
