### ISSUE TITLE
Globally accessible mocks for `makeKind` and `makeWeakStore` for use outside of Swingset in AVA tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2534]
## What is the Problem Being Solved?

ERTP and Zoe have many tests that run using AVA, but which are not in vats for performance reasons (Tests using Swingset vats are much slower to spin up.). 

## Description of the Design

It would be nice to have these tests still run, even if the real `makeKind` and `makeWeakStore` are not accessible. A mocked version should be fine, as the non-SwingSet tests are usually testing functionality that doesn't have to do with virtual objects. 

## Security Considerations

We should make sure that anything that could depend on virtual objects being used correctly has a SwingSet test. 

## Test Plan
Use `makeKind` and `makeWeakStore` for ERTP purses and payments. Ensure all Zoe and ERTP tests still pass.

**Comment by FUDCo** [comment]
One minor but important open design-ish question whose answer is not obvious to me is: where (as in what package) should these mocks live?

**Comment by katelynsills** [comment]
Just recording the suggestion I made this morning: I think Swingset/tools might be a good place

**Comment by FUDCo** [comment]
Fixed in #2543
