### ISSUE TITLE
clean up coerceDisplayInfo

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2553]
@katelynsills recommended a change to packages/ERTP/src/displayInfo.js  :

> I believe these lines can be changed to:

```js
export const assertDisplayInfo = allegedDisplayInfo => {
  const displayInfoKeys = harden(['decimalPlaces']);
  assertKeysAllowed(displayInfoKeys, allegedDisplayInfo);
};

export const coerceDisplayInfo = allegedDisplayInfo => {
  if (allegedDisplayInfo === undefined) {
    return undefined;
  }
  assert(passStyleOf(allegedDisplayInfo) === 'copyRecord');
  allegedDisplayInfo = pureCopy(allegedDisplayInfo);
  assertDisplayInfo(allegedDisplayInfo);
  return allegedDisplayInfo;
};
```

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/pull/2531#discussion_r585130017_

**Comment by katelynsills** [comment]
This was fixed by @erights in #2900 https://github.com/Agoric/agoric-sdk/commit/3dc66385b85cb3e8a1056b8d6e64cd3e448c041f#diff-10233a8bdfc08fdff5a1d56980d882e683c824ed0f4ca80b2469e4d898230f0a
