### ISSUE TITLE
declarative environment import module

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2571]
## What is the Problem Being Solved?

In our ecosystem, each importable module has a certain set of expectations about the environment in which it will run. All our code expects ES6 with module syntax and the usual (powerless) JavaScript objects. Most of our code expects a SES environment where `harden` is available as a global (and sometimes `Compartment` too). Contract code may expect that the virtual-object manager functions (`makeKind` and `makeWeakStore`) are available.

These environment requirements cannot be provided from within a module. Instead, whoever imports that module must ensure that it is loaded in an environment that meets the needs of the imported code. Most modules outsource this requirement to their own importers, until the buck stops at the top-level application or program that is launched from the command line. `node foo.js` or `ava test-foo.js` are the usual starting points.

We currently provide two importable modules to help the top-level program create an environment. `import '@agoric/install-ses'` gets you a SES "start compartment", in which `harden` and `Compartment` are available everywhere as a global. `import '@agoric/install-metering-and-ses'` additionally instruments the global objects with metering code, which is necessary for tests that exercise metering, but slows down execution somewhat.

As we start to use `makeKind` in our contract libraries (#1830), we have a need to provide a contract environment to test code, in which `makeKind` and `makeWeakStore` are globals. So we need a third import.

@dtribble suggested that, rather than having the imports named after the things they provide, we name them after the environment they are providing. So a `test-foo.js` that imports code which expects a "contract environment" could start with some sort of `import '@agoric/zoe/provide-contract-environment'`. A test that imports less-specialized code which merely expects a swingset vat-like environment could do `import '@agoric/swingset-vat/provide-vat-environment'`. Even less specialized code that only needs `harden` could `import '@agoric/install-ses'` (maybe renamed to `@agoric/provide-ses-environment`).

Some of these environments are real: the `harden` you get in a SES environment is fully functional. Some are simulated. The `makeKind` you get in a swingset/contract environment normally works with the liveslots infrastructure to offload the data to secondary storage. When you aren't running in a live vat, there's no secondary storage to use. So the `@agoric/swingset-vat/provide-vat-environment` would inject a global `makeKind` that's just a mock, which stores all its data in RAM.

## Description of the Design

```js
import `@agoric/swingset-vat/provide-vat-environment`;
```

```js
import `@agoric/zoe/provide-contract-environment';
```

**Comment by katelynsills** [comment]
This sounds great to me, in general, but what would ```import '@agoric/zoe/provide-contract-environment';``` import that would be different than `import '@agoric/swingset-vat/provide-vat-environment';`?

For my usages, I think these would be the same thing.

**Comment by dtribble** [comment]
SwingSet might not import globals for `makeKind`, mocks for oracle services, etc.  Also, SwingSet may have some globals (like a k/v storage service) that should not be available in a contract environment.

**Comment by katelynsills** [comment]
> SwingSet might not import globals for `makeKind`

Hmm, but it is Swingset in particular that is making `makeKind` and `makeWeakStore` available. This is not a Zoe or ERTP thing.

**Comment by katelynsills** [comment]
> SwingSet may have some globals (like a k/v storage service) that should not be available in a contract environment.

If we are talking about `makeWeakStore` and `makeExternalStore`, these are available in a contract environment. And more than that, we require them to be available because ERTP code depends on them. 

I think most of the needs for testing Zoe contracts are captured in providing a mock Swingset environment. So I think we can separate it out into two tasks - the Swingset environment is required for getting dapps working with https://github.com/Agoric/agoric-sdk/pull/2526. A separate Zoe environment is not needed right now, and needs work to further define what it is, and that could be much farther down the road.

**Comment by warner** [comment]
Yeah, I don't think contracts get anything special right now. If they did, it would be provided by ZCF when it does the `importBundle` in https://github.com/Agoric/agoric-sdk/blob/f70cc7666036b16d803b117dc957daf1c8504720/packages/zoe/src/contractFacet/evalContractCode.js (which provides `console` and `assert`), or in https://github.com/Agoric/agoric-sdk/blob/f70cc7666036b16d803b117dc957daf1c8504720/packages/zoe/src/contractFacet/contractFacet.js#L459 where ZCF calls `evalContractBundle()` (which doesn't provide a second argument, so `additionalEndowments` is empty).

But, given the declarative nature of this import name, it might be appropriate to tell test authors who are testing contract code to use the "contract environment", even if for now that's the same as a "vat environment", so we can change ZCF to provide different endowments in the future without rewriting those tests to import something else.

I can imagine an `assert.exit` behaving differently in the two environments: for generic vat code, it kills the vat, but for a contract, it politely asks ZCF to ignore anything else the contract might say and then shut down more cleanly. I don't know how that would translate into how the mocks ought to to behave, however.

**Comment by katelynsills** [comment]
> But, given the declarative nature of this import name, it might be appropriate to tell test authors who are testing contract code to use the "contract environment", even if for now that's the same as a "vat environment", so we can change ZCF to provide different endowments in the future without rewriting those tests to import something else.

I like that. Makes a lot of sense to me.
