### ISSUE TITLE
Updating the Validator Guide

### ISSUE THREAD

**Issue by lenox11** [Agoric/agoric-sdk#2584]
Hi!

I would like to make a small change to the documentation for installing the validator

https://github.com/Agoric/agoric-sdk/wiki/Validator-Guide 

In the section **To start syncing:**

```
sudo systemctl enable ag-chain-cosmos
sudo systemctl start ag-chain-cosmos
```

Need to add the `sudo systemctl daemon-reload command`

Result

```
sudo systemctl enable ag-chain-cosmos
sudo systemctl daemon-reload
sudo systemctl start ag-chain-cosmos
```

Without updating the configuration and users, problems may occur

Thanks!

**Comment by dckc** [comment]
seems reasonable; can't hurt...
https://github.com/Agoric/agoric-sdk/wiki/Validator-Guide/7c67ddc8dd97b7bc766d90eb0624f8f2f8506b92

**Comment by dckc** [comment]
oh... and thanks!
