### ISSUE TITLE
comms vat: use real kernel-facing c-list

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2586]
## What is the Problem Being Solved?

The comms vat is a nexus of message interchange between multiple systems, just like the kernel. The kernel has a set of "krefs" (kernel object/promise IDs), tables of object/promise data indexed by krefs, and one c-list per vat to map krefs to vrefs and back again. The comms vat has "crefs" ("comms") or "lrefs" ("local") (we haven't settled on which name to use yet), a table of object/promise data indexed by those crefs, and one c-list per remote system to make crefs to "rrefs" ("remote").

The comms vat also nominally has a kernel-facing c-list, to map crefs to vrefs and back. However, when I implemented it, I noticed that the crefs and vrefs were always the same, so I used a "degenerate c-list" and didn't actually assign a distinct crefs. The resulting data structure (in `state.js`) does not include a kernel-facing c-list.

Since then, we've found that the lack of a proper kernel-facing c-list is confusing. The crefs/vrefs might have had the same value, but c-lists also keep track of whether the identifier is present in the table or not. When we retire a promise ID, we normally remove it from a c-list, so the next time we might find a need to send that promise back to them, we'll allocate a new (short-lived) ID. If we don't have a c-list to remove it from, we must instead track that state with a separate flag. And we've seen bugs (#2393) related to that flag not being updated/checked from all the right places.

So we think it's time to give the comms vat a proper kernel-facing c-list. This should unify the way we handle messages going to both remote comms and the local kernel, and should give us the right foundation to handle GC/`drop` of these items as well.

**Comment by FUDCo** [comment]
Closed by #2680
