### ISSUE TITLE
init-autoswap takes a long time

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#261]
When we run:
`ag-solo bundle -e init-autoswap zoe::autoswap=..../ertp/core/zoe/contracts/autoswap.js`

in a scenario-2 environment (local single-node chain), it takes a long time to complete, on the order of 60 seconds. We're guessing that it has a lot of `await` calls, which inhibit pipelining. In a non-chain (scenario-3) environment, that won't cause much of a delay, but if there's a chain involved, each roundtrip will cost about 5 seconds (the inter-block time).

We should look at init-autoswap and enable as much pipelining as possible.

**Comment by katelynsills** [comment]
Dean and I aren't sure if this is still an issue @warner

**Comment by katelynsills** [comment]
I'm going to close this so that we can open a new fresh issue for when our current dapps might be slow when connected to the testnet
