### ISSUE TITLE
add performance/metering callbacks to swingset API

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2617]
## What is the Problem Being Solved?

We're looking for a clean way to let a host application learn time-based performance data from internal SwingSet events.

In particular, when swingset starts up, it will spend some amount of time replaying vat transcripts to get all vats ready for messages. In our current code, where everything runs under Node.js, startup involves reloading each vat, one at a time, replaying the full transcript for each before moving on to the next, and all non-terminated vats are loaded before `makeSwingsetController`'s return Promise is fired. The total replay time this takes is interesting to measure (and report on a dashboard), as it represents the (probable) majority of the time that restart consumes, and total restart time is downtime for a validator.

As our system gets more sophisticated, we'll reduce this downtime. First, we'll move vats to XS, and we'll get snapshots working, so reloading a single vat will really mean loading a snapshot and then replaying a truncated transcript instead of the full one, which should go a lot faster. Then, we'll avoid reloading *all* vats at startup, instead we'll only reload some of them (the most popular, the largest, some heuristic), and leave the others to be loaded on-demand as messages arrive. In this state, each individual crank may spend some amount of time waiting for the target vat to be loaded. This will appear as latency: block processing time that was lost because the kernel did not have the resources in place by the time they were needed. We want to measure this and look for ways to reduce it. This time is like the `iowait` time in a Unix-like kernel: time that userspace spends blocking, waiting for the kernel.

One way we'll reduce it is to preemptively load more vats. With an XS worker process, we can do this in the background. Swingset startup will load the most critical vats, then announce itself open for business (`makeSwingsetController`'s return promise fires), then continue loading some additional number of vats in the background. If we have the RAM, we could load all of them. If we don't, we'll load some middle tier and leave the outliers for demand loading. With luck, by the time messages arrive, the target vat will be loaded, but misses will still result in some downtime, which we'll want to measure.

As a block is processed, we'll spend some amount of time running cranks, some time doing non-swingset cosmos-sdk operations (like balance transfers), then some time performing consensus operations, and finally some amount of idle time while we're waiting for the block proposer to announce the next block. We'd like to know the ratio of these periods. If we spend a lot of time idle, but the swingset run-queue is not empty, that suggests we should spend more time processing cranks, and we should adjust our scheduler/metering limits to achieve that. If we spend no time idle, and the inter-block time grows above our target rate (e.g. once per 6 seconds), that implies we might be spending *too much* time doing cranks, and should reduce a limit somewhere.

We want a clean way to get this data out of swingset, without having swingset itself know about wallclock time (to preserve the hygiene of swingset being generally deterministic and lacking IO).

## Description of the Design

We're thinking that `makeSwingsetController()`'s `runtimeOptions` parameter should get a set of callbacks. Swingset will then invoke these callbacks as it runs, allowing the host application to use its private clock access to measure the durations of interest. We can also add callbacks into the `controller.step()/run()` arguments, for data that is scoped to a single crank.

One pair of callbacks would be `beginVatLoad(vatID)` and `finishVatLoad(vatID)` (perhaps reporting a number of transcript entries processed as an extra argument to `finishVatLoad`). This would give the host the ability to measure the "iowait" time, either during startup (in `makeSwingsetController`), or during a crank.

We could have a coarser-granularity pair of callbacks to be invoked during startup, to indicate when the first vat is beginning to be reloaded, and when the last vat is finished. This will become less useful when we start loading vats in parallel, or on-demand, but might be more convenient in the current phase.

## Delivering Metering Data via Callback, not Return Value

@michaelfig suggested that we should also use this to report metering data. Currently we've been planning to have `controller.step()` return a "meter consumed" number in the resolution of its return promise, so that the host can do a limited amount of work (per block) like:

```
let used = 0;
while (used < limit) {
  used += await controller.step();
}
```

Instead, we might provide a callback to which the usage data would be reported:

```
let used = 0;
function use(amount) {
  used += amount;
}
while (used < limit) {
  await controller.step({ callbacks: { meteringUsed: use } });
}
```

If we use this approach, the rules would be:

* the callbacks are observe-only
  * swingset would protect itself against exceptions thrown by the callback
  * the kernel input queue (#720) would protect against the callback attempting to call back into swingset
  * we'd normally prefer to use a Promise here, to avoid all the reentrancy hazards that inspired Promises in the first place, but for the callbacks who want to measure the elapsed time of something, running them at the end of a promise queue might impact the accuracy of their results
* the `meteringUsed` callback might be called once, many times, or none at all

One argument in favor of this approach is that the kernel has roughly five code paths that can result from a `controller.step` (depending upon whether the top-most run-queue item is a delivery or a notification, and whether the delivery is to an object or a promise in one of the various fulfillment states). It seems slightly easier to pass a callback into each of these paths than to ensure that all of the paths have the same return signature. Another argument is that we might add a new kind of metering unit, and a host which does not know how to deal won't be exposed to it unless they registered a new kind of callback.

(I'm not entirely convinced by these arguments, but I'd like to explore them further).

We'll be changing the way we measure CPU usage over time. It will certainly be helpful to report new kinds of metering measurements (to dashboards and the like) well before we change the code to act upon their values. For example, in an early phase, we might continue to execute at most 1000 cranks per block, but could report bytecode instructions executed as well. We can analyze the additional metrics offline to try and model the relationship between bytecode-instructions and wallclock time, to come up with the initial bytecode-instructions-per-block limit that we should switch to.

## Security Considerations

I'm slightly concerned about the opportunity for reentrancy hazards or general authority escalation inherent in giving functions into swingset, rather than having swingset return data back out. If we don't actually need the host to measure wallclock time of events, it may be better to report those events through a less scheduling-hazard-prone pathway.

## Test Plan

not sure, probably unit tests to make sure the callbacks get executed when we expect, but their values are by nature nondeterministic for many of them

**Comment by michaelfig** [comment]
> not sure, probably unit tests to make sure the callbacks get executed when we expect, but their values are by nature nondeterministic for many of them

I would expect that though the sequence for parallelised tasks could result in different order of callbacks, the ordering and arguments to each callback would be deterministic per vat.
