### ISSUE TITLE
Integrate epoch staking module

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2624]
...from Sunny.

**Comment by michaelfig** [comment]
From @dtribble:

> PR for epoch staking: https://github.com/cosmos/cosmos-sdk/pull/8829
> with some remaining tasks.
>
> Epoch pipelining is described here : https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-039- epoched-staking.md#pipelining-the-epochs
>
> Also an old implementation of proportional slashing: https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-014-proportional-slashing.md
>
>the epoch is only for staking, slashing, and unbonding. It is not epoch-based rewards. That we would do in JS anyway.

**Comment by Tartuffo** [comment]
@michaelfig This is in the "Up Next" pipeline, but does not have a MN-1 label.  If it is needed for MN-1, please label, otherwise move from "Up Next" to "Product Backlog".

**Comment by Tartuffo** [comment]
@JimLarson Please follow up with @michaelfig for details.

**Comment by ivanlei** [comment]
Closing as this is no longer plan of record.
