### ISSUE TITLE
refactor: move solo node out to separate repository

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#263]
`lib/ago-solo` was originally intended to contain strictly solo-node code, but the need to glue it to the cosmos-sdk libraries (and the usual drift of software projects) means that it's aquired a lot of stuff that shouldn't really live in a solo node, like many of the Mint/ERTP components in the `vats/` directory.

We should move the solo node out to a separate repository, It will use the connector library in Agoric/agoric-sdk#262, which should make things much clearer.

**Comment by warner** [comment]
#2956 is a start on this

**Comment by dckc** [comment]
@michaelfig tells me remaining work is tracked as https://github.com/endojs/endo/issues/879
