### ISSUE TITLE
Load generation service for testnet/devnet

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2630]
## What is the Problem Being Solved?

We want to deliver a steady stream of configurable traffic to our testnet (aka the "devnet"). @katelynsills is writing a client for this. We expect it to be a dapp-shaped directory, with some setup script, and then one or more scripts that should be run at a periodic interval. We anticipate a `crontab`-like config file (maybe JSON) that names the periodic scripts and the rate at which they should be run. She's started on the process in https://github.com/Agoric/testnet-load-generator .

We'd like a framework for executing this traffic definition. Some kind of hosted service or VM, which is configured with a GitHub URL and knowledge of an existing testnet chain. When it starts:

* do a `git clone` of the repo, `agoric install`/etc
* start the ag-solo and keep it running (if the machine is rebooted, we want the ag-solo to restart without resetting its state)
* read the config file
* execute any startup scripts listed in the config file
* prepare timers to execute the given scripts at the given times
* when running a script, ensure no more than one copy is active at a time

In addition, we'd like the scripts to be able to report some numbers to a dashboard. For example, a traffic script that performs a simple exchange can report whether the exchange succeeded or failed. We'll want to see that number along with the chain-reported performance metrics, so if something has gone wrong and the traffic is not really being executed correctly, we'll find out about it more easily than scanning every `console.log` produced by the generation script.

Maybe a grafana URL in an environment variable to which the script can run `curl` to upload this data? Or maybe something less low-level. It doesn't need to be particularly complex, just a few integers, which we can sum over time on the dashboard to make sure it's incrementing at the expected rate. The most sophisticated output I can currently imagine would be a token balance, to show how e.g. a loan is earning interest over time: not exactly a performance metric but a simple way to demonstrate that the simulated client is seeing the behavior it expects.

The end result should be a long-running deployed single-node service which automatically updates each time the devnet is restarted, and/or when the testnet-load-generator repo is changed.

Note that the load generator scripts will assume some number of services are already installed on the chain. So part of the devnet setup/restart process needs to be the installation of e.g. Zoe, the token economy, the usual "decentral services". The load generator scripts will *not* install those things itself: it is pretending to be an ordinary client, not an admin.

## Security Considerations

None of this code should touch the actual mainnet. We can imagine supplying traffic to the mainnet with the same tools, but that would involve actual money. 1: I don't want us to put a lot of effort into the load generation scripts, so if they lose tokens in error conditions/etc, that's fine. 2: I don't think we'll learn significantly more by pointing these against mainnet rather than a devnet, at least for now.

## Scaling Considerations

For now, I don't expect us to need more than one client machine to drive this. We're initially going to look at performing one simple transaction per minute. Later, we'll move to a 1/min txn that creates (and terminates) an ephemeral contract vat. Still later, we'll move to a txn every few seconds, of varying types. The goal is to learn the slope of the usage graphs in each mode, so we'll probably want to run the generator for a day or so between making changes.

**Comment by ski** [comment]
I created an artillery test at https://github.com/ski/perf-testing to take a stab at the problem being articulated here. The test invokes an API operation to install a Zoe contract. It was not clear to me what is meant by a 'transaction' in the description above. So I took a transaction to mean a Zoe contract installation executed from an API call into a dapp. 
The artillery script I have generates 4 requests per second which the Agoric setup on my local machine is able to handle more than eminently. Artillery generates the following latency graphs for this load.
![latency](https://user-images.githubusercontent.com/458710/113015522-898f4080-9175-11eb-9dda-c7400fbaf02d.JPG)

Could you provide me with more detail on what you mean by 'transaction' please? I am currently in the process of hooking up Datadog tracing into the dapp and the chain so that I can have a better understanding of what is happening in the layers underneath so that I can have a better view of performance.

**Comment by dckc** [comment]
@warner @michaelfig how about we call this done as of https://github.com/Agoric/testnet-load-generator/commit/dcfdb4411df42e7801dc2040f00fa563fa61ff28 July 2?

It's one of two open issues left on this milestone.

**Comment by mhofman** [comment]
https://github.com/Agoric/testnet-load-generator/pull/12 is currently deployed and running on a single machine. Keeping open as we still need to setup reporting of the results (e.g. github integration)

**Comment by Tartuffo** [comment]
Questions we need to answer:
1. Is kernel object table growing, if so we are leaking objects.
2. Is mem footprint of XNSAP runners growing over time (slow leak).
3. Is kernel process memory size growing over time.
4. Is amount of time taken to do a loadgen growing over time.
5. Is amount of time in swingset growing over time (currently yes).
6. How much load can we handle (and want point does time / transaction spike with # transactions / sec submitted and/or number of current submitters).
7. Is block time growing, and past the point we are comfortable with (?)

**Comment by Tartuffo** [comment]
@mhofman to split the ticket, between what is done and what remains (visualization).

**Comment by Tartuffo** [comment]
@warner , @mhofman , @Tartuffo to determine exact scope for MN-1.

**Comment by mhofman** [comment]
> Questions we need to answer

Re-reading this issue, this seem specifically scoped to providing automated activity on a long running devnet or testnet, so I will move those question to  #3107

**Comment by mhofman** [comment]
There is a lot of overlap in the infrastructure between this, which from what I understand is to provide and report load on an existing testnet or devnet, and a daily perf test (#3107) which spawns its own chain node with the latest head of the SDK.

The loadgen at https://github.com/Agoric/testnet-load-generator supports both `local-chain` and `testnet`, the latter can be used for this issue.

What is still needed for this issue:
- Script for launching the loadgen with the right SDK revision, network config and genesis file. These are all command line parameters.
- Command line to not reset the state on restart (`--no-reset`), and run with infinite duration `--stages=2 --stage.1.duration=-1`
- Potentially a script to automatically rebuild the docker image when a version of the loadgen is merged
- Script to remove or rotate the loadgen output (loadgen will not clobber existing files)
- Possibly new loadgen tasks specific to this mode

The live reporting requirement doesn't yet exist in the loadgen, and is definitely needed for this mode, but would probably have a different visualization than for the daily perf. https://github.com/Agoric/testnet-load-generator/issues/64.

We probably have room to run this on the benchmark machine used to run the daily perf.

**Comment by Tartuffo** [comment]
@warner Thoughts on how important this is, given we have our daily loadgen regression test suite?

**Comment by mhofman** [comment]
> * Potentially a script to automatically rebuild the docker image when a version of the loadgen is merged

I just added a script to regenerate the image every day. Docker caching should make this quick if there are no changes.
