### ISSUE TITLE
make XS CI optional

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2647]
## What is the Problem Being Solved?

We're seeing some strange test failures (involving GC and `WeakMap`) when certain unit tests (especially Zoe) are run under XS. These are serious problems but not a direct consequence of the Zoe changes being made, so they probably shouldn't hold up landing the Zoe PRs.

We decided to make the XS CI optional, so failures in it are reported, but won't prevent a PR from landing.

## Description of the Design

Currently our top-level `yarn test` expands to a `yarn workspaces test`, which runs `yarn test` in each package in turn. Then, within several packages (`ERTP` and `zoe`), the `yarn test` target expands to `yarn test:node && yarn test:xs`.

I think we need to rotate that: add a top-level `yarn test:xs` target, which expands to `yarn workspaces test:xs`. We'll add a `"test:xs": "exit 0"` to all of the other packages. And then we'll revert the ERTP/zoe `yarn test:node && yarn test:xs` bit.

Finally, we'll modify `.github/workflows/test-all-packages.yml` to introduce a new job (with `continue-on-error: true` to make it not flunk PRs). This job will run `yarn test:xs` at the top level.

**Comment by dckc** [comment]
@michaelfig pointed out that we're running `test:xs` 3x for 3 different versions of node. Is that a bug or a feature?

**Comment by warner** [comment]
> @michaelfig pointed out that we're running `test:xs` 3x for 3 different versions of node. Is that a bug or a feature?

That's probably a bug, the amount of Node.js code running under `test:xs` is minimal and not very interesting. I'll change #2651 so that the `matrix: node-version` clause only runs under a single version (
`14.x`).
