### ISSUE TITLE
refactor: move Central Services out to separate package

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#265]
I'm gonna define "Central Services" as the collection of objects that need to be hosted in a credible domain. In the Agoric system, that means Mints, Issuers, the Contract Host, Zoe, and the registrar. In a full system ("scenario 1"), Central Services needs to run on the chain. In a development environment, they might run in a local single-member "degenerate chain" (aka "scenario 2"), or even in the same solo machine as the client-side code (scenario 3).

Central Services consist of some number of vats, which are glued together in various ways. Their main export is a `makeUserBundle` method, which produces a set of objects that should be shipped down to a newly-provisioned user, to empower them to upload contracts, perform registrar searches, validate payments, etc.

A Swingset host that wants to provide Central Services should import a module (tentatively named `@agoric/central-services`) and expect it's default export to be a function named `getVats`. Calling `getVats()` should return a table of vat names and source paths (just like swingset's `getCommsSourcePath()` returns the filename of the comms vat). The host can then add all those vats into the config structure passed into `createVatController`. The host should also provide the names of the CS vats to the bootstrap's `argv` list.

The CS vat list should have a vat named `central_services`. The bootstrap function will call `vats.central_services~.initialize(cs_vats, timer_service)` at startup. `cs_vats` will receive a mapping of vat name to Vat root object, for all of the CS vats (so `cs_vats` is a subset of the `vats` object that the bootstrap function gets). The `timer_service` object will be from the Timer Vat, and allows Central Services to schedule timers.

`initialize` should return an object with a `createUserBundle(nickname)` method. When called, this should allocate any per-user objects (e.g. empty purses, accounts, etc), and combine them with important objects that are shared among all users (the registrar, the contract host, various Assays) into a single "user bundle" record that it returns. This bundle is delivered to the solo-side client, for incorporation into the client-side agents and the REPL's `home` object.

The Central Services package will thus wrap ERTP, Zoe, and maybe other packages. The host will not be aware of what exactly Central Services provides.

We'll probably split the other vats into `User Services` and maybe `Dapp Services`.

Different hosts will have bootstrap vats/functions that invoke `createUserBundle` at different times. The local-one-process "scenario 3" will invoke it once, at startup, and share the bundle reference with the nearby Vat that handles the user agents (e.g. Central/User/Dapp Services are all in the same vat). In "scenario 2", there is a single-node degenerate chain that contains Central Services, and `createUserBundle` is called once (or once per client) at startup, but the result is registered with the comms layer in a fixed location. In "scenario 3" (the full chain), `createUserBundle` is not called until the Provisioning/Controller node gets a provisioning request from a new client.

This should help clean up our `bootstrap.js`, and remove some of the current confusion as to where some of the services are run. At least some of @Chris-Hibbert 's recent work was untangling the wallet demo in which we had Mints being created on the user side. That will be more obviously wrong when the mint and ERTP vats move into Central Services.

**Comment by warner** [comment]
"Decentral Services" is starting to grow on me

**Comment by warner** [comment]
I went to investigate where `spawner` is used, and got a bit lost in our tangled `bootstrap.js`, reminding me that we need to make progress on this. To get things started, I'd like to make a list of what, exactly, we're running on the chain and on the solo node, and who uses them. I'm going to write up a straw-man here, ask for corrections, and then edit it to converge towards accuracy.

## All Vats

Both our chain node and our solo machine are currently built from `packages/cosmic-swingset/lib/ag-solo/vats/*`, which contains the following vats:

* vat-board.js
* vat-host.js
* vat-http.js
* vat-ibc.js
* vat-mints.js
* vat-network.js
* vat-provisioning.js
* vat-registrar.js
* vat-sharing.js
* vat-uploads.js
* vat-wallet.js
* vat-zoe.js

## How each vat seems to be used in `bootstrap.js`

* vat-board: bootstrap calls `makeBoard()` (via `vats.board~.getBoard()`) and makes the resulting `board` reference available in the client-side `userbundle`. Clients give both `zoe` and `board` to their vat-wallet.
* vat-host: bootstrap calls spawner/`makeContractHost` and shares the `contractHost` reference with `userBundle`. ALSO client-side `createLocalBundle` creates its own local spawner (same kind of functionality, but different hosting location) and adds the `spawner` reference in the `localBundle`
* vat-http: referenced by `createLocalBundle` plus from all the different scenario sections, no idea
* vat-ibc: referenced by `registerNetworkProtocols`, called by all the different scenario sections, no idae
* vat-mints: used on-chain to create the `moola` and `simolean` demo mints, the corresponding Issuers are included in the user bundle
* vat-network: `.bind` called in `createUserBundle`, `.bind` and `.registerProtocolHandler` called in `registerNetworkProtocols` (which is called by all scenarios). Probably used by both client and services
* vat-provisioning: used in `registerNetworkProtocols` (called by all scenarios), also `one`/`one_chain`/`two_chain` scenarios
* vat-registrar: bootstrap calls `getSharedRegistrar()`, makes resulting `registry` reference available in user bundle
* vat-sharing: bootstrap calls `getSharingService()`, makes resulting `sharingService` reference available in user bundle
* vat-uploads: `createLocalBundle` calls `getUploads()`, provides `uploads` reference in local bundle
* vat-wallet: `createLocalBundle` builds callet from `zoe` and `board`, uses `wallet` to remember chain-created Issuers, create empty purses for each, accept chain-sourced demo payments for each, share `wallet` in local bundle
* vat-zoe: bootstrap calls `makeZoe(adminVat)` (via `vats.zoe~.buildZoe()`) and makes the resulting `zoe` reference available in the client-side "user bundle" (`createUserBundle`)


## Chain / Decentral Services

These are objects/services that, in a production Agoric ecosystem, exist in exactly one highly-credible highly-reliable shared machine: the blockchain.

We have other flavors of our ecosystem (testing environments). Each such deployment will have its own instance of these services too. For example the public testnet chain will have one (same properties, lower stakes). Also each developer's local test environment will have an instance, which lacks the credible/reliable properties, and is only used by that one developer.

* board
* mints
* registrar
* sharing
* zoe
* provisioning

These services appear to be built on the chain but should not be:

* spawner (vat-host): the client builds their own

## Solo / Clients

These are objects/services that live in a machine private to each user. They are not shared with central services or any other user.

* spawner (vat-host, `contractHost`): used to deploy API services used by local wallet UI things??
* `uploads`
* `wallet`
* http

## Both

These services are lower-level utilities that are built in both environments.

* network
* ibc (we do not yet have client-side support for IBC, so maybe this should be chain-only for now)

**Comment by Chris-Hibbert** [comment]
We might end up with redundant mints in all the various places, but most likely the shared mints are the most valuable. I think vat-mints will only exist on-chain and (once each) in testing environments. If particular dapp developers need mints, they'll build them but not as pervasively replicated services.

We will eventually want to host a shared reliable spawner service for all the reasons we originally had. People can also run a spawning service on their own chain, but if you want to convince someone else that you've installed a non-zoe contract that they can rely on, it'll have to be on-chain.

**Comment by katelynsills** [comment]
> We might end up with redundant mints in all the various places, but most likely the shared mints are the most valuable. I think vat-mints will only exist on-chain and (once each) in testing environments. If particular dapp developers need mints, they'll build them but not as pervasively replicated services.

I think vat-mint will probably go away and be replaced with a Zoe contract that mints payments.

**Comment by Chris-Hibbert** [comment]
> I think vat-mint will probably go away and be replaced with a Zoe contract that mints payments.

This makes me really want to revive the Spawner service. I don't like the idea of using Zoe for things that aren't enforcing offer safety and payout liveness. I think it sends the wrong signals about how to use our platform. 

I'd much rather have a special purpose vat that just creates these currencies.

**Comment by dckc** [comment]
@warner does `packages/vats` address this issue?

**Comment by dckc** [comment]
I'm reasonably confident that `packages/vats` addresses this issue.
