### ISSUE TITLE
monorepo

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#267]
We're considering moving SwingSet, cosmic-swingset, and some related packages into a monorepo.

## The Problem

It's currently pretty difficult to run cross-package tests. Chris has run into many of these, while implementing the Timer Device (which lives in SwingSet but must be configured to use host-specific sources of timing in cosmic-swingset). This also hit JF while working on the wallet/exchange demo, where it wasn't convenient to run anything beyond scenario3 (no-chain, everything in a single process), so the vats didn't get partitioned properly to work under scenario2 or 1 (actual chains). ERTP and Zoe have extensive unit tests, but we don't have a good place to run integration tests, to see how they behave in an actual chain environment.

`cosmic-workspace` is a response to this, a git-submodule -based "monorepo", currently using [Lerna](https://lerna.js.org/) for setup. Michael uses it to manage the testnet, and updates the component modules (to the most recent release of that package) each time the testnet needs updating. However:

* we don't have any integration tests
* manipulating submodules (editing, branching, submitting PRs) is a hassle, especially because git submodules (correctly) record only a specific commit-id, not a branch
* it's confusing to sometimes do editing and unit-testing work in the submodule, and sometimes do it in a direct checkout of the given project

A "real" monorepo would be the canonical git home of all of the projects it contains, rather than using git submodules to fake it. It would not necessarily be restricted to having the most recent release of all the projects it contains.

## Mechanics

We'll probably use [these tools](https://github.com/shopsys/monorepo-tools) to build a new repo that contains the full history of each project (rewritten into the same number of commits, with the same author/timestamp/comment, but which puts the code in a subdirectory), along with a final big N-parent merge commit. We'll use [lerna](https://lerna.js.org/) and Yarn to handle the installation process, which recognizes when one package depends upon another one in the same repo, and replaces the `node_modules/` directory with a symlink.

We'll have integration tests in the top of the repo, and unit tests in each separate package.

We might put the results in the `agoric-sdk` repo on GitHub, or maybe create a new one.

The rule will be that the current trunk (`master`) of this repository should pass all integration tests, and the unit tests of each package.

We must decide whether to release all the packages in the monorepo at the same time (with the same version number, abandoning semver), or release individual packages (each with their own version number) only when their changes warrant a new release.

## What to Include

At least: `swingset`, `cosmic-swingset`.

Probably `bundle-source`, `captp`.

Maybe `eventual-send` and `acorn-eventual-send`, which provide support for the tildot (`x~.foo(args)`) operation.

Quite possibly `ertp` and `zoe`. I think a lot of the "does this all work together" questions that would be easier to test/ansewr in a monorepo will involve these two. Basically everything that goes into the "central services" in an Agoric platform, and maybe even a bunch of the client-side stuff.

We might even want to put `agoric-sdk` here too, since the purpose of the SDK is to produce an `agoric` executable that will need to import or install copies of many of the other repos. That would suggest we also include `wallet-frontend`, and maybe `autoswap-frontend` as an example.

We think SES will remain as a separate (mono)repo, which will include `evaluator-shim`, Realms stuff, and module loader packages.

## Pros

* we'll have a place for integration tests that execute more of the Agoric platform
* it will be easier to test multi-package changes that affect cross-package compatibility
  * we anticipate doing a lot of this in the near future, as we clean up "Central Services" and our platform in general
* 

## Cons

* releasing all packages at the same time (with the same version number) is easier to manage, but abandons semver semantics (most packages will see multiple identical releases, prompted only by the need to release changes in other packages)
* releasing packages separately will cause a difference between the monorepo's trunk (which we test on a regular basis, with CI), and the current releases on NPM (as used by downstream users)
* monorepos in general favor developers of the packages over downstream users of those packages

**Comment by warner** [comment]
I'm emptying/archiving the old individual repos. I've moved all the issues (open and closed) manually to the monorepo. Now I'm waiting for the old open PRs to be closed, at which point I'm pushing a commit that removes all the code (leaving only a README that points at the monorepo) and then hitting the Archive button (which makes it read-only). I then move the repo to the `agoric-labs` organization.

The following repos have not yet been archived:

- [ ] cosmic-swingset
- [x] ERTP

When those are done, I'll close this issue.

**Comment by Chris-Hibbert** [comment]
I have WIP I'd like to migrate to the monorepo, but it includes new files, so @warner's [comment](https://github.com/Agoric/agoric-sdk/issues/267#issuecomment-560162687) doesn't seem to apply. It's also not yet a PR. 

Is the easiest path to turn my changes into a patch, and apply them in the monorepo?

**Comment by warner** [comment]
yep, if you don't need to preserve the separation between multiple commits, then a simple patch/apply is by far the easiest way to migrate them. `git diff >foo.diff`, and  then `patch -p1 <foo.diff` from the new directory.

**Comment by dckc** [comment]
The top README says:

> When the `yarn install` is done, the top-level `node_modules/` will contain
> all the shared dependencies, and each subproject's `node_modules/` should
> contain only the dependencies that are unique to that subproject

but `packages/cosmic-swingset/node_modules` is empty, for me.

This conficts with my earlier approach to xs manifests. (e.g. #57 )

**Comment by dckc** [comment]
oic.
> only the dependencies that are unique to that subproject

hm.

**Comment by warner** [comment]
yeah, in the monorepo, everything that can, will go into the shared top-level `node_modules`.
Something like `packages/cosmic-swingset/node_modules/` will be empty unless `cosmic-swingset` depends upon version X of some package Y, and something else in the monorepo depends upon version Z of the same package Y (and I believe the top-level `node_modules` won't have Y at all, in that case).

None our code should have imports with `node_modules/` in the specifier. But of course many/most of the `import foo` lines are referring implicitly to `node_modules/foo.js` or `../../node_modules/foo.js`.

FWIW, yarn has a "focus" mode to basically turn off the intra-monorepo links and work on one package/subdirectory at a time.

**Comment by warner** [comment]
ok I think we're all up and running on the monorepo now, closing this
