### ISSUE TITLE
agoric init eslint config doesn't allow BigInt literals (10n)

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2695]
## Describe the bug
The eslint configuration produced by `agoric init` conflicts with use of BigInt literals such as `10n`.

## To Reproduce
1. `agoric init capfundme; cd capfundme; agoric install`
3. Write a contract test using a BigInt literal such as `10n`
4. vs-code and `eslint` report errors

vs-code says:
```
BigInt literals are not available when targeting lower than ES2020.
```

eslint says:
```
/home/connolly/projects/capfundme/contract/test/test-contract.js
  42:98  error  Parsing error: Identifier directly after number
```

## Expected behavior
No errors.

## Platform Environment

linux. Node.js v14.16.0

 - what version of the Agoric-SDK are you using?
not sure; I switched branches a couple times since I ran `agoric init`.

_not sure who to assign this to... feel free to re-assign, @michaelfig_

**Comment by katelynsills** [comment]
The solution to this is to change [dapp-fungible-faucet](https://github.com/Agoric/dapp-fungible-faucet)'s jsconfig.json to `"target": "esnext"`

**Comment by dckc** [comment]
I don't see a `jsconfig.json` that repo. What clue am I missing?

**Comment by katelynsills** [comment]
Ah, good point. We need to add one for checking the JSDoc typescript annotations. That alone might take care of it, or there might be a similar setting just for ESLint. I'm not sure. But it's dapp-fungible-faucet that is being used as the default template for `agoric init`

**Comment by michaelfig** [comment]
Can I toss this to you, @katelynsills?  It probably just needs an eslint upgrade and the jsconfig.json addition you mentioned.

**Comment by katelynsills** [comment]
Sure thing!
