### ISSUE TITLE
build ed25519 signing device

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#27]
For the sending side of our solo-to-solo and solo-to-chain comms paths, we'll need the ability to generate signatures on the message bodies (since secrets are involved, signing can only be done from a solo machine, not from a chain). Ed25519 is my favorite algorithm, but the implementation I'd like to use (from libsodium) is written in C and accessed through some Node.js FFI binding, making it unusable from within a confined SES context. This is a great place for a device, which can safely invoke the external FFI library and then synchronously returning the signature. This device isn't adding any authority (the signature algorithm is just manipulating data which the vat already has, and the vat is Turing-complete), but for performance and safety against timing sidechannels we want to use a low-level language for the implementation, and that's not available from within our confined code environment.

For the receiving side of many paths, we need the ability to verify the signatures (which *can* be done safely/correctly/meaningfully from within a chain-based machine). This should also be implemented as a device, perhaps the same one.

In the longer run, we're going to want to move the signing key out into another process, in the hopes that this will provide us with some protection against Spectre/Meltdown -style attacks. In this case, the device could own the UNIX-domain socket or named pipe we used to talk to the signing process.

**Comment by erights** [comment]
@warner OMG that would be so cool!

**Comment by warner** [comment]
This doesn't really make sense anymore.. we haven't thought about the solo node for years (there is too much precious client state to retain robustly in the face of the unreliable computers that host them). By the time we need this, we'll probably have some better approach in mind. Closing this as too stale to be useful.
