### ISSUE TITLE
"Module level directives cause errors when bundled, 'use jessie' was ignored."

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2704]
## Describe the bug
`'use jessie'` seems to lead to warnings; perhaps in a bundling step?

## To Reproduce
in `packages/zoe`, run `yarn test:xs-unit`. There are probably simpler ways, but that's the way it came up just now.

## Additional context

This warning is most likely a consequence of #2606.

cc @michaelfig @erights @katelynsills

**Comment by dckc** [comment]
@michaelfig notes plans to migrate from `use jessie` to an import declaration.

**Comment by dckc** [comment]
fixed in #2938

**Comment by erights** [comment]
In light of https://github.com/Agoric/agoric-sdk/pull/2938 , should this be closed?
