### ISSUE TITLE
Intermittent build failures under CI

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#2725]
While working on #2718 I got the following CI error in job `build (12.14.1)`. Both text and screenshot are the same occurrence. Then, without changing anything, I hit the "rerun all jobs" button. This time `build (12.14.1)` succeeded.

```
Post job cleanup.
/usr/bin/tar -cz -f /home/runner/work/_temp/a4134451-66e3-4344-9396-781fa8f76473/cache.tgz -C /home/runner/work/agoric-sdk/agoric-sdk .
Warning: read ECONNRESET
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
  errno: -9,
  code: 'EBADF',
  syscall: 'read'
}
```

![Screen Shot 2021-03-25 at 8 51 43 PM](https://user-images.githubusercontent.com/273868/112574747-30599280-8dac-11eb-9344-5576c886082a.png)

**Comment by dckc** [comment]
Looks like github cache management. It's not 100% reliable. I recommend closing this.
