### ISSUE TITLE
Consider making the brand the first arg of `amountMath.make`

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2735]
## What is the Problem Being Solved?

It's only in seeing this statement that makes me think that `amountMath.make` should have the brand first. 
```javascript 
amountMath.make(10n ** Nat(decimalPlaces), collateralBrand),
```
The `make` and `getEmpty` operations require a brand (they are both form of `make`). The brand at the  end can get lost if the expression is larger, and really is a thing that would otherwise be curried. Thus the brand should be the first arg.  

## Description of the Design

Change `amountMath.make` to have the brand as a required first argument.

For temporary backward compatibility, test that the first argument is a brand-like thing, and report an informative "Reverse the args, this is deprecated" in order to enable incremental migration.

**Comment by erights** [comment]
Closed by https://github.com/Agoric/agoric-sdk/pull/2765
