### ISSUE TITLE
ObserveIterator should .catch() and log

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2751]
## What is the Problem Being Solved?

An observer's `updateState()` method might throw, which would get swallowed in the iterator, and be hard to diagnose.

## Description of the Design

`observeIterator()` in `asynchIterableAdaptor.js` calls client-supplied code, and it should add a .catch() that logs the error. The observer's contract shouldn't allow it to let errors escape. (according to @erights)

## Security Considerations

Errors can get lost. Exposing them would be better.

## Test Plan

There are good tests in the Notifier package. It should be possible to test for this condition.

**Comment by dckc** [comment]
Since [unhandled rejections now have good support in the platform](https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#unhandledrejectiontrapping-options), perhaps this is obsolete?

**Comment by Chris-Hibbert** [comment]
> Since [unhandled rejections now have good support in the platform](https://github.com/endojs/endo/blob/master/packages/ses/docs/lockdown.md#unhandledrejectiontrapping-options), perhaps this is obsolete?

I defer to @erights

**Comment by erights** [comment]
Yes, the platform now should do the right thing for that case. But could someone check that it does?

In any case, since the platform should do it, observeIterator should not, so this bug can be closed.

**Comment by dckc** [comment]
> Yes, the platform now should do the right thing for that case. But could someone check that it does?

The following test shows that it does. `ava` exits with a failure code, though, so I'm not inclined to make this a permanent test.

```
test('observeIterator - unhandled rejections look ok', async t => {
  const { publication, subscription } = makeSubscriptionKit();

  const todo = observeIteration(subscription, {
    updateState: async _s => assert.fail('bad news'),
  });
  publication.updateState(123);
  publication.finish(0);
  await todo;
  t.pass();
});
```

```
agoric-sdk/packages/notifier$ yarn test test/test-notifier-adaptor.js -m '*unhandled*' -v
yarn run v1.22.19
$ ava test/test-notifier-adaptor.js -m '*unhandled*' -v

  ✔ observeIterator - unhandled rejections look ok

  Unhandled rejection in test/test-notifier-adaptor.js



SES_UNHANDLED_REJECTION: (Error#1)
  ─

  1 test passed
  1 unhandled rejection
error Command failed with exit code 1.
```
