### ISSUE TITLE
convert board IDs to bech32 addresses

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#2759]
To support transfers using existing wallets like keplr

**Comment by katelynsills** [comment]
Is this happening in this timeframe? If not, can we change the milestone?

**Comment by dckc** [comment]
> Is this happening in this timeframe?

I hope so; that is: I hope https://github.com/Agoric/dapp-pegasus/pull/26 is roughly on target.

**Comment by dckc** [comment]
I gather this dapp is out of the critical path for now.

**Comment by dckc** [comment]
see also
 - cosmic-swingset meeting notes 2021-04-07
 - [keplr](https://github.com/chainapsis/keplr-extension) hacking Apr 8 , #2847

**Comment by dckc** [comment]
obsolete in favor of #2847
