### ISSUE TITLE
xsnap swingset worker does not support metering

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#2837]
## To Reproduce
1. in `packages/zoe` run `yarn test:xs-worker`
4. See `xsnap worker does not support enableInternalMetering` and `TODO: support metered with xs-worker; using local as work-around`

**Comment by dckc** [comment]
@warner I meant to get your OK on postponing this part before closing #2605 ...

when I said all the zoe tests are passing on XS, I neglected to say that's only the unit tests and not the swingset tests. I postponed running the zoe swingset tests on XS because they seem to rely on metering in XS.

**Comment by dckc** [comment]
oh... maybe this is a dup of #2322

**Comment by dckc** [comment]
`yarn test:xs-worker` in `packages/zoe` works now: `18 tests passed`.

Are we there yet? Shall I close this, @warner ? Or should we add `test:xs-worker` to `test:xs` in `packages/zoe/package.json`?

Or do you want to use this issue to track allocation?

**Comment by warner** [comment]
We're tracking allocation now, right? If so, then yes let's close this. If not, let's leave it open until we're protecting against runaway allocation.

**Comment by dckc** [comment]
> We're tracking allocation now, right?

Yes.
