### ISSUE TITLE
testnet/devnet/stage network names/purposes

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2840]
## What is the Problem Being Solved?

* A: one validator, unpublished, 1/day, currently "stage"
* B: many validators, 1/betarelease then 1/updaterelease (1.1, 1.2, etc), currently "devnet"
* C: "incentivized testnet", 1/phase, currently "testnet"
  * C is moved to code tested on B once stable enough and graduates
* and "beta" is an alias for "devnet" (A)
  * ~~will become "devnet" (B) as soon as that's released with beta software~~
  * may change to point at "testnet" (C) after incentivized testnet project is complete
* once mainnet is released, maybe C is replaced with mainnet, but retain A+B

audiences:
* 1: us: want latest, don't care about stability A
* 2: community we're trying to teach B
  * docs point to this under the name of "beta"
  * beta releases: announce upgrades, need to redeploy
  * slower to avoid churn, don't push them too fast
  * upgrades no faster than 1/wk, more like 1/mo or slower
* 3: people who want to be validators B
  * also participants in I.T. who want to experiment
  * no faster than 1/wk, probably slower
* 4: people who participate in the incentivized testnet C
  * upgraded once per phase, well scheduled
* 5: mainnet (later)

**Comment by michaelfig** [comment]
This is implemented.  I'm closing, but this issue is still relevant for duckumentation porpoises.
