### ISSUE TITLE
ERTP Types: Amounts should be parameterized

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2845]
## What is the Problem Being Solved?

As @dckc put it: {NatValue | SetValue} Value is awkward. Amount should probably be Amount<V> where V is a type parameter that could be NatValue or SetValue. And likewise, instead of any[], SetValue should be SetValue<T>

@michaelfig said: I have tried fixing this in the past, but the main missing feature in JSDoc is that there are no default values for type parameters.  That makes the parameterised Amount much more verbose and harder to use than the non-parameterised version. Ergonomics may require dipping into some .d.ts definitions.

**Comment by dckc** [comment]
@turadg and co addressed this in 

 - #4880
 - #4736
 - #4551
