### ISSUE TITLE
Ratios: functions to add ratios and multiply ratios

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2850]
## What is the Problem Being Solved?

In building dapp-token-economy/treasury, there were times when I wanted to add ratios together. For instance, to add a 2% buffer on top of a requirement of 150% collateralization without knowing the denominator of the collateralizationRatio ahead of time. (this ended up not getting into production, but you can imagine the use case). Also, @dtribble added a `composeRatio` function that he uses in swap. It'd be nice to add both addition and multiplication of ratios to the library.

**Comment by Chris-Hibbert** [comment]
for the first case, would it be more helpful to be able to add 2% to a value that might be 5% or might be 250 basis points or to multiple the value by 102%?

In both cases, it sounds like we the first argument to determine the brands of the result, and the second argument should be treated as something closer to a pure number (even though we don't have unit-less ratios.)

**Comment by katelynsills** [comment]
> for the first case, would it be more helpful to be able to add 2% to a value that might be 5% or might be 250 basis points or to multiple the value by 102%?

Hmm, I think these are different operations, but maybe I am misunderstanding what you meant. For example, adding 2% to 5/100 is 7% but multiplying 5/100 by 102% is 5.1%. Can you explain more about what you meant here?

> In both cases, it sounds like we the first argument to determine the brands of the result, and the second argument should be treated as something closer to a pure number (even though we don't have unit-less ratios.)

I think we should enforce that these are all the same brand, at least until we have use-cases that show others. So numerator and denominator for all the arguments should the name brand for these new methods, I think.

**Comment by Chris-Hibbert** [comment]
> I think we should enforce that these are all the same brand, at least until we have use-cases that show others. So numerator and denominator for all the arguments should the name brand for these new methods, I think.

That seems fine to me.

> adding 2% to 5/100 is 7% but multiplying 5/100 by 102% is 5.1%. Can you explain more about what you meant here?

That's the distinction I was trying to get at.

Would we have cases where we wanted to add 2/100 to a number that might be 5/100 or might be 250/10000, or would we be more likely to multiply an unknown ratio by 102% in order to add a buffer?

In your original example, adding 2% gets 152%, while multiplying by 102% gets 153%. The latter seems more like adding 2% buffer to me.

I'll add methods to do addition and multiplication, and people can decide what operation they want to invoke.
