### ISSUE TITLE
Treasury: planning for withdrawals from AMM pools

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2851]
The Treasury/StablecoinMachine creates an AMM pool for each collateral currency. When funds are tight, or to extract earned value, it has the ability to withdraw liquidity from those pools. To decide how much to extract it needs to rank them by available value.

The useful metrics are
 *  how much has been collected in fees?
    *  (and how much of this have we already extracted)
 *  How much have other people contributed in liquidity?
 *  How much has the pool value grown because of an increase in value of the collateral?
    *   (and how volatile is this value?)

We can track fees either by having the AMM track and publish this explicitly, or by comparing x*y=y when the treasury endowed the AMM with the product of the treasury's present share of the pools.

We can compare the treasury's Liquidity tokens with the pools Liquidity Tokens outstanding to see how much others have contributed.

The change in value of the pool due to the collateral's value is simply the ratio of the treasury's current share of RUN tokens compared to the initial deposit. The equilibrium that the pools tend toward is that the total value of each token held is equal. 
If the treasury's liquidity-proportional share of the RUN pool has twice as many RUN now as the treasury initially deposited, the pool as a whole is worth twice as much

The pools have APIs to retrieve `LiquiditySupply`, `CentralAmount`, and `SecondaryAmount`. The treasury knows how many liquidity tokens it has so its share of the value in the pool is just the proportion of its tokens to the total `LiquiditySupply`.  

My proposed ranking of these criteria is 
 * extract value where fee growth is high
 * If no one else has contributed liquidity, be more reluctant to extract value
 * track the long-term volatility of value of each collateral. Be more willing to extract value when there's long-term stable growth in the value of the collateral.

**Comment by rowgraus** [comment]
Per conversation today, active management of Treasury-owned assets - if any - will be primarily left to governance at first.

This issue can be de-prioritized until later Beta phase

**Comment by Chris-Hibbert** [comment]
Some references:  

 * see also #3792 
 * [Treasury Accounting](https://docs.google.com/document/d/1XNYf51EZHNpoodXMbpdFRjkloIXLnWcRaGGoHnc2c3E/edit)

**Comment by Chris-Hibbert** [comment]
[`vats/src/bootstrap.js` collects fees](https://github.com/Agoric/agoric-sdk/blob/b508984d05723f7b02f5e8677182b0cd466a5e5c/packages/vats/src/bootstrap.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L229) from the Treasury and AMM, and passes it on to the bank.

**Comment by Chris-Hibbert** [comment]
This issue is no longer relevant. Vaults are no longer the owners of the AMM pools. The concerns expressed here now apply to other parts of the economy, and we have issues for adding the appropriate monitoring.
