### ISSUE TITLE
Treasury: clean up new collateral addition

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2877]
## What is the Problem Being Solved?

The Treasury code mints a Governance token, which isn't part of the design, and doesn't explicitly touch received Liquidity tokens.

## Description of the Design

Drop the vestigial Governance token. create a seat to own the Liquidity tokens

## Security Considerations

None.

## Test Plan

basic testing.

**Comment by rowgraus** [comment]
Moving to Product Backlog.  Important change but from a product perspective not explicitly necessary for Staking Dynamics phase or Rewards Beta.

If the LP token change here is inextricably linked with extracting AMM rewards then it's worth revisiting how much of this to address.

**Comment by dckc** [comment]
In #4026 we have:

```
  // todo(hibbert): set up an initial AMM pool with RUN and BLD
  // const liqSeat = createLiquidityPool(...);
```

This issue seems like a good-enough place to track that.

**Comment by dckc** [comment]
or... should we track that somewhere else, since #4026 seems to address the original scope of this issue: "governance tokens in Vaults are no longer supported". Maybe that's only part of getting rid of them.

**Comment by Chris-Hibbert** [comment]
This issue is obsolete, so I'll add closing it to #4026.

The liquidity tokens spoken of above were the ones from the AMM that the Treasury used to receive as part of creating the pools. Since it no longer creates those pools, there aren't any tokens to hold onto.

**Comment by Chris-Hibbert** [comment]
The explicit TODO referenced just above here is now done in bootstrap.js in that same PR.
