### ISSUE TITLE
cosmic-swingset does not rebuild Go code during 'yarn build'

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2884]
## What is the Problem Being Solved?

In #2882, I switch my `agoric-sdk` branch, ran `yarn && yarn build` (thinking that would rebuild anything that needed it), then attempted to start a local chain (`agoric start local-chain` in a dapp directory, specifically https://github.com/Agoric/testnet-load-generator). The chain node paniced during startup, because of a mismatch between the JS code (which was new) and the golang/cosmos-sdk code (which was old).

@michaelfig reminded me that we don't automatically build the golang code during `yarn build`, because lots of folks use it only for the JS code. We don't want to require people to have Go installed just to do contract development: we only need Go to build cosmic-swingset, and you only need to build that if you're going to be running a chain. The more-common `agoric start` mode of operation uses a fake chain that doesn't require any Go code at all, and it'd be shame to make that pathway more difficult.

However, it's entirely non-obvious that one must do `yarn && yarn build && cd packages/cosmic-swingset && make` to update that image. We want things to be as automatic as possible, so even needing to do `yarn` and/or `yarn build` after the source changes is a bit of a drag. But there's plenty of precedent in the JS/yarn world for needing that much, and it would be lovely if we could avoid needing any more than that.

## Description of the Design

So I'll propose that we change the `build` target in `packages/cosmic-swingset` to look around for evidence that a `make` has been run before: the presence of the helper binary might be the right test. If present, `yarn build` there will run `make`. Else, `yarn build` will continue to be an `exit 0`.

That way, if you've ever done something that causes the Go code to be built, from that point onwards doing a `yarn build` will cause it to be rebuilt. That would have avoided the confusion and crash that I experienced.

@michaelfig does that sound reasonable? What file could I test for that would indicate a build had been previously done? Armed with that knowledge, I can make a PR for you to look at.

**Comment by michaelfig** [comment]
It's an excellent thing to solve.  The reason I proposed always building on `agoric start local-chain` was that the make overwrites files outside of the monorepo which may be very surprising when just doing a yarn build.

Fixing Agoric start only to build files in the tree, and use them there instead of installing them would be my preference.  That's different than the validator usage which should be much the same as it is today.

**Comment by dckc** [comment]
doing `yarn build` without go is a feature: For JS devs, go is not among the [documented dependencies](https://agoric.com/documentation/getting-started/before-using-agoric.html). The [validator guide](https://github.com/Agoric/agoric-sdk/wiki/Validator-Guide) documents installing go.
