### ISSUE TITLE
Evaluate the risk of integrating Cosmos 0.43 prior to Staking Dynamics phase

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2901]
Epoch staking (PR: https://github.com/cosmos/cosmos-sdk/pull/9043) may be included in Cosmos 0.43 release.  If we wish to include it, we need to assess the risks of adopting 0.43 including possible changes to other modules.

If we determine that risk is low, we may need to lobby for the Epoch Staking PR to be included - which is a time sensitive item.  This ticket is gating that action.

Acceptance criteria is answering the following questions:
1) Which modules are touched by the 0.43 release?
2) Which changes to those modules are at risk for bugs?
3) For each change: what is an appropriate test plan?
4) For each change: can we be confident in time for Staking Dynamics code freeze (4/28)?
5) Does the change touch a critical dependency for other work we are doing for the phase?

**Comment by michaelfig** [comment]
I don't see epoch staking in https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0-alpha1 .  My suspicion is that this upgrade is not useful to us yet.  Also, there are SO MANY breaking changes, more than we can take on before code freeze.

@dtribble @rowgraus

**Comment by rowgraus** [comment]
Seems right to me.  Closing issue.
