### ISSUE TITLE
Staking Design: Cosmos-SDK vs. JS

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2904]
Design ticket for how to integrate the relevant Cosmos-SDK modules with what we are doing in JS.  Based on notes from meeting with Zaki, relevant Cosmos modules are:

Staking
Distribution
Mint
Slashing

Acceptance criteria for this ticket is a set of specific tasks for JS work and plumbing into Cosmos.

**Comment by Chris-Hibbert** [comment]
@michaelfig wrote:

It's better not to focus on the plumbing, and instead have an abstract ocap-based notion of which upcalls are made from the Golang side.  Have another look at https://github.com/cosmos/cosmos-sdk/tree/v0.42.4/x/distribution/spec/ but don't get bogged down in detail.  Really the only inputs to the distribution mechanism are 05_hooks.md (called from other modules), and 04_messages.md (called by transactions sent to the chain).

If you can define an object that has methods corresponding to each of these hooks+messages, then I can take care of the glue code to allow you to register that object with a special vat, which will arrange to call the methods when those hooks/messages are triggered.
You may find some of these inputs are not necessary.  If so, feel free to ignore them.

**Comment by dckc** [comment]
Is this fixed in #3025? That is: is there more to this than #2960?

**Comment by Chris-Hibbert** [comment]
> Is this fixed in #3025? That is: is there more to this than #2960?

Those two deal with making purses the funds can be deposited into. There's also getting funds from the treasury and depositing them into those purses. see #2933, #3001, #3014.

**Comment by michaelfig** [comment]
This is now handled by `x/distribution` and our new "bank purses" `x/vpurse`.
