### ISSUE TITLE
use run-queue to schedule vat creation

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2911]
## What is the Problem Being Solved?

I thought of a single fix that will address both #2908 (deterministic synchronization of vat creation) and #2910 (tolerating syscalls during vat creation): we use the run-queue to schedule vat creation.

## Description of the Design

Currently, the run-queue has two types of events: `message` (or maybe `deliver`, I forget) to cause `dispatch.deliver` of some message to some vat (or to get queued on a promise), and `notify` to cause `dispatch.notify` to inform a vat of an earlier promise being resolved. Each run-queue event runs within its own crank, committing to the database at the end (by flushing the "crank buffer").

For this fix, I'd add a third event type, `create-vat`. During the crank which handles `create-vat`, we will:
* ask `vatManagerFactory` to start up the vat
  * once a worker is ready, the manager will deliver the source bundle to the worker
  * as that is evaluated, startup-time syscalls might run
    * so the manager must be ready for them by the time it sends the bundle to the worker
  * that returns a Promise which doesn't fire until the startup phase is done and the vat is idle
* wait for that Promise to fire
* commit state

We'd change the vatAdmin device to enqueue the `create-vat` event, rather than immediately using `loadVat.js` `build()`. The event would include both the pre-allocated `vatID` and the `managerOptions` (which includes the source bundle).

For now, that event body will be pretty large, because the source bundle is typically a megabyte or so (the ZCF code bundle is 840kB). That's not a huge deal, but we can reduce it by introducing the first stage of the #46 "blob store". In this early stage, we store blobs (source bundle strings) under their SHA512 hash in the kerneldb (key = `b.${HASH}`). The vatAdmin device would store the blob (if not already present), the `create-vat` event would hold the SHA512 hash, and `build()` would fetch the blob from the DB. We can defer userspace access to blobs (via a c-list managed "blobcap") for later.

## Performance Considerations

This will introduce an additional delay between the parent/client vat requesting the creation of a new vat, and the new root object being delivered to them. The current delay pattern is:

* client vat does syscall.send to `vatAdmin` requesting the creation, getting a result promise in return
* that message must ride the queue/escalators
* vatAdmin uses the device to create the vat
  * for `managerType=local`, this happens in the same turn. For `subprocess-xsnap`, this takes a couple seconds
  * (HERE)
* when vat creation finishes, the device enqueues a message to the vatAdminVat announcing the success
* that message must ride the queue/escalators
* when vatAdminVat receives that message, it resolves the result promise
* that notification rides the queue/escalators
* the notification arrives in the client vat, carrying the new root object

In this new scheme, we introduce an additional "ride the queue/escalators" at the point marked (HERE).

When the swingset is unloaded, this won't matter. When the escalators are busy, this could be a significant delay. We should probably plan to put these `create-vat` events on some high-priority queue. In addition, this is a good opportunity/reminder to think about how to assign the CPU costs of vat creation: which meter should the `create-vat` event draw from?

**Comment by FUDCo** [comment]
Given that syscalls during startup aren't strictly necessary (we worked around it for the comms vat, after all), does the event sitting on the run queue (i.e., the event that gets a crank to itself to be processed) need to be the complete vat creation or merely the wait for its completion?  If the latter, then when vat workers are run in separated processes some of the time consuming stuff could be overlapped with normal message processing and nobody would be the wiser.  The visible sequence of events would be the same but it would run faster.

**Comment by FUDCo** [comment]
Isn't the large event body problem described here the same problem we have now with current dynamic vat creation flow and so the same tricks we do now to mitigate the cost should work here as well?  In particular, it seems like the `create-vat` event is pretty much just the same as the `createVat` message to the vat admin vat, the only difference being that it gets handled directly by some kernel machinery instead of by a vat.  Given that access to the vat admin vat is itself a closely held capability, couldn't this all be done by just changing what syscalls the vat admin vat is allowed to do when it's processing a `createVat` message?

**Comment by warner** [comment]
> Given that syscalls during startup aren't strictly necessary (we worked around it for the comms vat, after all), does the event sitting on the run queue (i.e., the event that gets a crank to itself to be processed) need to be the complete vat creation or merely the wait for its completion? If the latter, then when vat workers are run in separated processes some of the time consuming stuff could be overlapped with normal message processing and nobody would be the wiser. The visible sequence of events would be the same but it would run faster.

I suspect they *are* strictly necessary (see #2910). If that weren't true, and if there were no state changes or activity happening while the vats were starting up, then yeah, we could overlap them (and that might save a bit of runtime).

> Isn't the large event body problem described here the same problem we have now with current dynamic vat creation flow

Probably.. I'm thinking about the ~1MB message that makes multiple appearances. The biggest change I imagine this issue causing is because we currently serialize the run-queue with a simple `db.set('runQueue', JSON.stringify(runQueue))`, because 1: it's normally empty between blocks, 2: each entry is normally a hundred bytes or so. When we add `create-vat` events, those will each include (for now, before some sort of blobstore) a MB of contract bundle. OTOH, I guess we're already doing that with all the contract-bundle-bearing messages going submitter to zoe to vatAdminVat, etc. So it probably isn't worth putting a lot of energy into avoiding just one more copy, for now.

>  Given that access to the vat admin vat is itself a closely held capability, couldn't this all be done by just changing what syscalls the vat admin vat is allowed to do when it's processing a createVat message?

Hmm. In the current implementation (which we did pretty early in SwingSet's history, so we shouldn't treat it as gospel), the only thing special about the vatAdminVat is its access to the vat-creation device node. There are no special syscalls involved, just `syscall.invoke(vatAdminNode, 'create', bundle, options)`. It's the device that gets access to anything magical.

That `syscall.invoke` is necessarily synchronous, because it gets to return data (and must do so immediately, rather than returning a Promise or something: the syscall interface is purely data). So it cannot wait for the new vat to be completely created; the best it can do is return a data-only handle which can be correlated with some later message. The immediate parts of vat creation (which were all of them, back when we only had `managerType = 'local'`, which is why I missed this until now) happen within the vatAdminVat crank that made that `syscall.invoke`, so e.g. if vat creation failed badly enough to cause the crank to be aborted, any state changes that were made by the partially-launched vat would be unwound, along with everything else that happened in the vatAdminVat during that crank.
