### ISSUE TITLE
Load generator creates vaults and makes trades on AMM to create rewards flow

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2930]
@rowgraus  to define the appropriate rate

**Comment by dckc** [comment]
Is this fixed as of https://github.com/Agoric/testnet-load-generator/commit/3246e6309150df38b07c1554b42c7dd415611866 ?

**Comment by katelynsills** [comment]
@warner, can we close this? Or can I remove my assignment?

**Comment by warner** [comment]
Yep, I think this is good enough to satisfy our initial goals.
