### ISSUE TITLE
xs-worker doesn't tolerate BigInts in console.log()

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2936]
## Describe the bug

In trying to get the XS worker usable for all vats, one problem I ran into was a vat that did `console.log()` of a BigInt. The xsnap supervisor is currently sending the log arguments to the supervisor with the same JSON.stringify it uses for all other messages (namely syscalls). This fails (somewhat opaquely) when vat code logs something that can't be serialized this way.

For the local worker, the vat's `console.log` is routed to two places:

https://github.com/Agoric/agoric-sdk/blob/fa68a8af6864d04a73fbc9dc70f63fb3d4225c1a/packages/SwingSet/src/kernel/kernel.js#L146-L155

The first is `makeConsole()`, which returns an instance of `anylogger`. The second is the `kernelSlot.vatConsole`, which wraps the log arguments and ultimately puts them into a serialized JSON object written to the slog file. That serialization special-cases any BigInts:

https://github.com/Agoric/agoric-sdk/blob/fa68a8af6864d04a73fbc9dc70f63fb3d4225c1a/packages/SwingSet/src/controller.js#L124-L136

For the XS worker, we need to handle this somehow. It's probably sufficient, for now, to just special-case BigInt (i.e. not use a full marshal, and accept the loss of fidelity for debug logs).

That probably means changing this code:

https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/vatManager/supervisor-subprocess-xsnap.js#L166-L168

to pre-transform `args`, like:

```js
port.send(['console', level, tag, ...(JSON.parse(JSON.stringify(args, (_, val) => { if (typeof(val) === 'bigint') { return Number(val); } return val; })))]);
```

In the long run, we need to nail down what exactly we're willing to tolerate in console.log calls, what precisely is the set of values that might appear in deliveries and syscalls, and make sure all our manager-worker communication pathways can support that full set. Our deliveries and syscalls are fairly conservative, and were designed to be JSON serializable, so it's really `console.log` that's the outlier.

## Testing

We should add a `console.log(0n)` to our test vat (in `test/workers/vat-target.js`) to exercise this.

**Comment by dckc** [comment]
> ... In the long run, we need to nail down what exactly we're willing to tolerate in console.log calls. ...

Shall I open an issue?

Or was that more of a rhetorical "need" in the sense of "would ideally"?

**Comment by warner** [comment]
> Shall I open an issue?

done

**Comment by erights** [comment]
On what to change it to, try replacing
```js
... JSON.stringify(stuff) ...
```
with something like
```js
const { quote: q } = assert;
... `${q(stuff)} ...
```
It was designed for purposes like this --- strings useful for human diagnostics. Anything semantically closer to `JSON.stringify` will drop too much information on the floor.

**Comment by erights** [comment]
The algorithm it uses to stringify is at https://github.com/endojs/endo/blob/a7222d745ddc831167996ffaf30ccd7e036fe726/packages/ses/src/error/stringify-utils.js#L22 . Like your suggestion above, it calls `JSON.stringify` with a replacer. But a much more informative replacer.

**Comment by warner** [comment]
It would be nice to retain whatever structure we can, so I wouldn't want to entirely flatten/stringify the arguments.

@erights this is a case where the serializer (the XS worker child process) wants to deliver full-fidelity information to the unserializer (the kernel process): both sides are as privileged as we get. Is there a way to use `details` here that enables full data retention?

@dckc I'm going to hand this one to you. The patch I started with is https://github.com/Agoric/agoric-sdk/commit/f55e733b9d575472a2f82eb66bbcf32bd849f0c6 (which includes a test). Please see if you can adapt @erights 's approach to it.

**Comment by erights** [comment]
I don't understand. The full fidelity approach is marshal. But this is about logging. What role does any kind of unserialization have in logging?

**Comment by dckc** [comment]
The code is trying to pass the individual `console.log` args from one process to another without lumping them all together... though f55e733 lumps them together and parses them back out only to lump them back together for transport, after which they get parsed apart again.

**Comment by warner** [comment]
Oh, I should mention that we must not `harden` the `console.log` arguments.. that would be awfully surprising for developers (especially when they're debugging something and add temporary logging of intermediate results, like a list that is still being mutated). Which means we can't just use `marshal` to deliver the arguments from worker process to kernel process, as simple and elegant as that would be.

**Comment by erights** [comment]
You can certainly use `${q(stuff)}` on each argument separately. But this just preserves the separateness of the arguments. Beyond that, I still don't understand. What are you unserializing them to? What are you trying preserve of the original meaning? For what purpose?
