### ISSUE TITLE
remove tildot support

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#2951]
## What is the Problem Being Solved?

In #2503 I think we came to a consensus that we should remove support for tildot (`target~.method(args)`), and write `E(target).method(args)` instead. The parser is hard to manager.

If we indeed have consensus on that, the tasks are:

* change `bundleSource` to remove the tildot transform we apply during `rollup()`
* in swingset, remove `vatPowers.transformTildot`
  * in `controller.js` where it provides `transformTildot` in `kernelEndowments`
  * this changes `kernel.js` where it builds `allVatPowers`
  * and also `liveSlots.js` where it builds `baseVP`

We'll also remove a couple of test cases.

@erights @Chris-Hibbert I think you two were driving the decision-making process on #2503, should I proceed to remove tildot support now?

**Comment by erights** [comment]
Remove tildot. We should use `E.G` when appropriate to get promises for properties without stalling.

**Comment by erights** [comment]
Or rather, `E.get`

**Comment by Chris-Hibbert** [comment]
We did decide to drop support for tildot.
