### ISSUE TITLE
Virtual purses to bridge cosmos-sdk tokens

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#2960]
We need a way to share token balances between the cosmos-sdk layer (`bank` module balances) and the Agoric VM layer (ERTP).

This proposal is to use "virtual" purses whose balances are maintained in the cosmos-sdk layer, but which may also be manipulated and observed from the ERTP layer.  This is simpler than general virtual purses, especially since the user already trusts the correctness of both of these layers (rather than a new, untrusted third-party).

#2101 describes the mechanism that we will use to airdrop these trusted purses from the on-chain `faucet` into the user's wallets.

We will implement the Golang `x/virtual-purse` which will provide all the functionality needed to implement a Purse-like object in JS with an eventually-consistent JS balance.  This is safe, because withdrawal requests will only succeed based on synchronous cosmos-sdk `bank` balances:

1. `x/virtual-purse` will accept "burn" messages from the `bridge` device when an ERTP withdrawal is made.  This will burn cosmos-sdk balances:
```json
{
  "type": "VPURSE_GRAB",
  "sender": "agoric1...",
  "denom": "ubld",
  "amount": "1000000000"
}
```
the synchronous mint `bridge` result will be a `VPURSE_BALANCE_UPDATE` if successfully withdrawn, otherwise an error is thrown if insufficient funds (in which case no assets will be burnt).

2. `x/virtual-purse` will accept "mint" messages from the `bridge` device when an ERTP deposit is made:
```json
{
  "type": "VPURSE_GIVE",
  "recipient": "agoric1...",
  "denom": "urun",
  "amount": "1234"
}
```
the synchronous mint `bridge` result will be a `VPURSE_BALANCE_UPDATE` if successfully deposited, otherwise an error is thrown.
3. send balance updates to the `bridge` device when the `x/bank` module emits a transfer event (events are scanned and detected in `END_BLOCK`).
```json
{
  "type": "VPURSE_BALANCE_UPDATE",
  "updated": [
    {
      "address": "agoric1...",
      "denom": "urun",
      "amount": "1234"
   },
   {
      "address": "agoric1...",
      "denom": "ubld",
      "amount": "9191"
    },
  ]
}
```

**Comment by michaelfig** [comment]
@katelynsills, @dtribble here is the API between JS and cosmos-sdk interfaces.

**Comment by katelynsills** [comment]
This sounds good, but one question about burning and minting: Have we ruled out simply escrowing out of reach and un-escrowing instead? I'm thinking about the future where we might do something similar to NFTs. NFTs must have unique identifiers in the value of the amount, and usually, we would expect that a mint cannot make another NFT with the same identifier as one that was previously burned (although ERTP doesn't currently enforce this because it would require a lot of bookkeeping). So I think burning and minting the same tokens doesn't line up very well with how we've been thinking about NFTs. It'd be nice to use the same API and methodology for both fungible and non-fungible tokens. 

None of the above is blocking, though, just something that might be an improvement for the future.

**Comment by katelynsills** [comment]
Also, a nitpick, can we call the bigint `value`, since that's more accurate? Or is `amount` a Cosmos standard?

```
{
  "type": "VPURSE_BURN_IF_AVAILABLE",
  "address": "agoric1...",
  "denom": "ubld",
  "value": "1000000000"
}
```

**Comment by michaelfig** [comment]
> Have we ruled out simply escrowing out of reach and un-escrowing instead?

Oh, that's something I should have documented.  I was a fan of escrow/unescrow, but the problem is that `RUN` is minted in JS, so it is possible that there is not enough `urun` on the Cosmos side to unescrow if newly-minted `RUN` is intended to be moved to `urun`.

> I'm thinking about the future where we might do something similar to NFTs.

NFTs are still a research project for cosmos-sdk.  But you're right, there is room for improvement, and I don't intend to write this protocol in stone.  It's more like the minimum protocol we need to implement for the BLD-ubld and RUN-urun cases.

**Comment by michaelfig** [comment]
> Also, a nitpick, can we call the bigint `value`, since that's more accurate? Or is `amount` a Cosmos standard?

I was trying to standardise on the terms used in the IBC spec's ICS20-1 protocol for fungible token transfer https://github.com/cosmos/ibc/blob/master/spec/app/ics-020-fungible-token-transfer/README.md#data-structures

So, I'll update the other properties to match that.

**Comment by michaelfig** [comment]
We also need the following for initialising the purse's balance from the bank:
```json
{
  "type": "VPURSE_GET_BALANCE",
  "address": "agoric1...",
  "denom": "ubld"
}
```
