### ISSUE TITLE
Zoe feature: guaranteed refund

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#2976]
## What is the Problem Being Solved?

The user wants a refund no matter what, and can use offer safety to guarantee a refund if they specify a `want` that is known to be impossible to satisfy. 

This could be an issuer within Zoe that Zoe knows about, or there could be a change to the `proposal` to state this declaratively.

**Comment by Tartuffo** [comment]
We are not going to do this.
