### ISSUE TITLE
xsnap test failure snapstore › build temp file; compress to cache file

### ISSUE THREAD

**Issue by kriskowal** [Agoric/agoric-sdk#2981]
## Description

As of ref `3588c2d8d08b8523e308189286ad8638f604f821` of agoric-sdk, on a Mac, with Node.js 14.5.0, I’m observing two test failures.

```
{ debug: false, qty: 31000 }
123
123
memory full
memory full
memory full
memory full
too much computation
memory full
memory full
memory full
too much computation
memory full
{ debug: false, qty: 4000000000 }
not enough keys
{ debug: true, qty: 31000 }
{ debug: true, qty: 4000000000 }
not enough keys
  snapstore › build temp file; compress to cache file

  Difference:

  - '1f8b08000000000000134b4c4a0600c241243503000000'
  + '1f8b08000000000000034b4c4a0600c241243503000000'



  snapstore › bootstrap, save, compress

  raw snapshots are large-ish

  Difference:

  - 858
  + 857

  ─

  2 tests failed
  1 known failure
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## To Reproduce

1. On `agoric-sdk` run `git checkout 3588c2d8d08b8523e308189286ad8638f604f821`
2. `yarn install`
3. `cd packages/xsnap`
4. `yarn test`
5. See error

## Expected behavior

Passing tests

## Platform Environment
 - Mac and Node.js 14
- `git describe --tags --always` reveals `agoricdev-2-116-g3588c2d8d`

**Comment by dckc** [comment]
>   raw snapshots are large-ish
>   - 858
>   + 857

Yes, I see this intermittently. Until we tackle deterministic snapshots (#2776 ) I'm inclined to disable that test.

More on the other separately...

**Comment by dckc** [comment]
>   snapstore › build temp file; compress to cache file
> 
>   - '1f8b08000000000000134b4c4a0600c241243503000000'
>   + '1f8b08000000000000034b4c4a0600c241243503000000'

srsly? node's gzip results vary across platforms? Shoot me now. Or shoot them. You pick.

**Comment by kriskowal** [comment]
> > snapstore › build temp file; compress to cache file
> > 
> > * '1f8b08000000000000134b4c4a0600c241243503000000'
> > 
> > 
> > * '1f8b08000000000000034b4c4a0600c241243503000000'
> 
> srsly? node's gzip results vary across platforms? Shoot me now. Or shoot them. You pick.

It does seem strange. Stranger that it’s off-by-just-one byte.
