### ISSUE TITLE
Not getting enhanced stack traces

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#2992]
## Describe the bug

In recent work on Zoe contracts, I've noticed that I'm getting lousy stack trace info, or none at all. My tests fail, but I have to manually set breakpoints and hunt around for the location that something went wrong.  Among other things, I also see cases where I can step through ava test assertions, and verify that the test should fail, but the test continues running and fails for unrelated reasons sometime later.

## To Reproduce

https://github.com/Agoric/agoric-sdk/pull/2966/files#diff-ef3d02b0104386935d4a26278647b501b495f2a9283fb5173a2b2f18f79cf672R975

This PR captures the state where I had the problem. @michaelfig pointed out that it's not rebased to master, which caused other problems, but shouldn't be related to the stack trace issues.

To see the issue, run  `test-newSwap-swap.js`. There are console.log() calls on lines 975 and 997. the first is before an actual failure in tradeAndCheck that isn't reported until after the code passes the test on line 999 without complaint.  Neither produces very much in the way of a stack.

## Expected behavior

When a test fails and exceptions are thrown, we should see great error reports and helpful stack traces.

## Platform Environment
 - what OS are you using? what version of Node.js?
On MacOS.  If relevant, I can look up the version later. I'm not at that machine now.

 - is there anything special/unusual about your platform?
 Nothing unusual.

 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

**Comment by dckc** [comment]
@Chris-Hibbert Is this still a problem? I suspect it was fixed in #2578 but might have regressed somewhat with the introduction of endo zip archives.

@kriskowal this is probably a good one to check as part of #3899 .

**Comment by Chris-Hibbert** [comment]
This does seem to be fixed. The stack traces I get now have all the info I'm interested in.
