### ISSUE TITLE
global mutable state in PrivateName

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#30]
bootPN is global mutable state.

Why design it that way? What is the argument that this doesn't make the system vulnerable?

**Comment by erights** [comment]
@dckc is this still an issue? Where is the object in question?

**Comment by dckc** [comment]
I can't find any evidence that it ever existed. Odd. Oh well.

```
agoric-sdk/packages/SwingSet$ git grep bootPN $(git rev-list --all)
```
