### ISSUE TITLE
Distribute rewards from Treasury to Bank accounts

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3001]
## What is the Problem Being Solved?

Distribution of rewards from Treasury to stakers

## Description of the Design

As an interim solution that injects RUN into the economy, until we can get the info that would allow us to mirror the staking rewards, we'll register accounts from all users, and pay them all equally.

Each epoch, funds will be made available from the Treasury. (see #3002) This contract will have a list of accounts that were registered, and will pay them equally. We can be more selective later.

**Comment by Chris-Hibbert** [comment]
The API we're talking about has the bank providing two methods. 

The first is `getAccountsNotifier()`, which returns a notifier whose state is an array of account strings. Each time it fires, the distributor will extract fees from the Treasury, divide by N, and in batches of 100 or so every second or so, call the second method `depositMultiple()`, which takes an array of account identifier strings, and an array of payments and deposits them respectively.

This is a short-term stand-in for a distribution module , which will know all the validator and delegator addresses, and will follow  a stream of event notifications of changes to delegations and slashing decisions, etc. to make decisions about how much to award to each delegator.

**Comment by michaelfig** [comment]
> The first is `getAccountsNotifier()`, which returns a notifier whose state is an array of account strings. Each time it fires, the distributor will extract fees from the Treasury, divide by N, and in batches of 100 or so every second or so, call the second method [...]

I would prefer that the distributor extract fees when a periodic timer fires instead of when the accounts notifier fires.  The accounts notifier only fires once per client provisioning, which is a fairly rare occurrence.

Here's some pseudocode, hopefully for clarity:

```js
// on startup:
const accountsNotifier = E(bankDepositFacet).getAccountsNotifier();
// ... wait for timer to fire
await waitForTimerToFire();
// after the timer fires, get the latest accountNames array and distribute:
const accountNames = await E.get(E(accountsNotifier).getUpdateSince()).value;
const payments = await Promise.all(accountNames.map(...someMagic));
await E(bankDepositFacet).depositMultiple(accountNames, payments);
```

Everything else about this description looks good.
