### ISSUE TITLE
catch up to low/medium priority security issues

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3007]
see https://github.com/Agoric/agoric-sdk/security/dependabot 

cc @erights @rowgraus @dtribble

**Comment by tyg** [comment]
Not quite sure what I need to add here, but in the documentation repo at the very top, I get a dependabot alert. Opening it up, it shows one item,
 is-svg
high severity
 Mar 20, 2021 by GitHub
yarn.lock

https://github.com/Agoric/documentation/security/dependabot

**Comment by dckc** [comment]
Thanks, @tyg ; that's right on target.

@kriskowal and I plan to work on this next week.

**Comment by Chris-Hibbert** [comment]
I received dependabot notifications for repos that I don't feel ownership of. I asked and didn't get anyone else to acknowledge that they had also been notified.  Recording here for general attention.

 * 5/10: [Agoric/layer-cake] [Bump lodash](https://github.com/Agoric/layer-cake/pull/11) from 4.17.20 to 4.17.21 (#11)
 * 5/10: [Agoric/zoe-sketchbook] [Bump lodash](https://github.com/Agoric/zoe-sketchbook/pull/10) from 4.17.19 to 4.17.21 (#10)
 * 5/11: [Agoric/layer-cake] [Bump hosted-git-info](https://github.com/Agoric/layer-cake/pull/12) from 2.8.8 to 2.8.9 (#12)
 * 5/11:  [Agoric/zoe-sketchbook] [Bump hosted-git-info](https://github.com/Agoric/zoe-sketchbook/pull/11) from 2.8.8 to 2.8.9 (#11)

**Comment by dckc** [comment]
> I received dependabot notifications ...

In discussion with @kriskowal , I merged these.

**Comment by dckc** [comment]
> see https://github.com/Agoric/agoric-sdk/security/dependabot

The bot was griping about `template/ui/package.json` which no longer exists, so @kriskowal and I dismissed all of these.

@kriskowal did land one upgrade: #3231 for handlebars

**Comment by dckc** [comment]
@katelynsills , I looked at this with @kriskowal ...

> ... in the documentation repo at the very top, I get a dependabot alert. ...
> 
> https://github.com/Agoric/documentation/security/dependabot

A couple more have been added there in the mean time. Unfortunately, the bot ran into conflicts when it tried to upgrade is-svg etc. Do you see a straightforward fix?

**Comment by katelynsills** [comment]
> A couple more have been added there in the mean time. Unfortunately, the bot ran into conflicts when it tried to upgrade is-svg etc. Do you see a straightforward fix?

Thanks for pursuing this! I will take a look

**Comment by kriskowal** [comment]
We have an ongoing process now for catching up. I’m content to close this tracker.
