### ISSUE TITLE
Evaluate improvements to protocol fee calculation

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3018]
## What is the Problem Being Solved?

There has been some discussion on how the system/protocol fees should be calculated in #2944 and #2971. This issue is a place to continue that discussion.

## Description of the Design

The first version of our `autoswap` and `multipoolAutoswap` followed the model of [uniswap V1](https://github.com/runtimeverification/verified-smart-contracts/blob/uniswap/uniswap/x-y-k.pdf) in charging fees. Since then Uniswap has introduced [V2](https://uniswap.org/whitepaper.pdf) and [V3](https://uniswap.org/whitepaper-v3.pdf) ([code](https://github.com/Uniswap/uniswap-v3-core/blob/main/contracts/libraries/SwapMath.sol)), which use different models, and SushiSwap ([code](https://github.com/sushiswap/sushiswap/blob/master/contracts/SushiMaker.sol#L237)) was introduced with a variant.

We have experimented with various models in #2921. Another is planned. @katelynsills and @Chris-Hibbert have captured some approaches in an internal doc "AMM fees in RUN".

## Security Considerations

Not primarily a security issue

## Test Plan

Tests in the experiment and in any new code.

**Comment by dtribble** [comment]
@btulloh also proposed that we simply require the protocol fee to be provided as a separate payment.

**Comment by Chris-Hibbert** [comment]
#3771 and #3791 implement a new model for calculating and charging protocol fees

**Comment by Chris-Hibbert** [comment]
This issue is obsolete.
