### ISSUE TITLE
Make the Treasury more independent of the AMM it uses

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3019]
## What is the Problem Being Solved?

[@dtribble commented](https://github.com/Agoric/agoric-sdk/pull/3010/files#r624916562) that the Treasury has to know a lot of detail about the AMM in order to start it up and interact with it. 

## Description of the Design

We should abstract away some of the details and give the Treasury a more generic interface to starting and interacting with the AMM.

## Security Considerations

Should be a clean refactoring.

## Test Plan

There aren't very many tests of the treasury that exercise the AMM's use. We'll have to add more to validate this work.

**Comment by Chris-Hibbert** [comment]
Current thoughts are more along the lines of "extract starting up the AMM out of the Treasury entirely".  The Treasury needs to have an AMM for any currency pair it wants to lend against in order to enable liquidation, but it doesn't have to be the creator.

Adding a new type of collateral could require that the relevant AMM pool be specified on creation. The Treasury would want to be able to inject liquidity, or at least ensure that the market was sufficiently supplied.

**Comment by dckc** [comment]
I'd like to understand the scope of this better... "more independent"? How much more?

A "clean refactoring" has no observable changes, right? Then the **enhancement** label seems inappropriate.

Something tells me this is actually a _problem_; that is: there is something we should be able to do that we cannot with the current arrangement. Is that the case? If so, what is it that we cannot do?

**Comment by Chris-Hibbert** [comment]
> I'd like to understand the scope of this better... "more independent"? How much more?

> Something tells me this is actually a problem; that is: there is something we should be able to do that we cannot with the current arrangement. Is that the case? If so, what is it that we cannot do?

The main driver is that the Treasury can't currently make use of an AMM that was created before the relevant pool. 

> A "clean refactoring" has no observable changes, right? Then the enhancement label seems inappropriate.

That's a fair charge. I'll drop the `enhancement` label. The goal is to enable enhancement by separating the evolution of the AMM and the Treasury.

That logic undercuts my implication under 'Security Considerations' that the consequence doesn't have significant implications because it doesn't change behavior much. I think I would now write that splitting the two apart will make it easier to design and analyze the security architecture. I don't think splitting them adds vulnerabilities.
