### ISSUE TITLE
Investigate Mechanisms in Zoe to prevent zcfSeat.exit misuse

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3027]
## What is the Problem Being Solved?

See https://github.com/Agoric/agoric-sdk/issues/3026 for a detail description of what happens when `zcfSeat.exit` is thrown instead of `zcfSeat.fail`. 

## Description of the Design

TBD.

**Comment by Tartuffo** [comment]
@erights The specific linked item was closed, but the class of issue may remain.  Is this a Mainnet-1 issue?

**Comment by erights** [comment]
I see #3026 was closed by a documentation update https://github.com/Agoric/documentation/issues/494 rather a change to the code. Indeed, I don't know what I'd do to the code to fix this, or problems like it. I don't know what further investigation is warranted, though I could imagine mitigating such problems with new linting rules. I'm closing this.
