### ISSUE TITLE
swingset transcript replay doesn't catch incomplete syscalls

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3043]
Our transcript replay code works by making the original delivery to the vat, while the vat's `syscall` handle is replaced by an object that compares the calls it makes against the ones previously recorded in the transcript. If these diverge in any way, the replay is halted, and an "anacrophobia error" is emitted.

This code works by making a copy of the recorded syscalls when the delivery begins, in `playbackSyscalls`. As the vat tries to make syscalls, we shift the first element off this list and compare it against what the vat is doing.

However, we don't do anything special at the end of the delivery. In particular, we ought to be checking the shifted list and make sure it's empty. Because we aren't doing that check, any missing suffix of syscalls won't be flagged as an error. If the vat does *new* syscalls, that will be caught (comparing `undefined` from the historical record against `(not undefined)` from the present). But if the vat fails to do the last syscall, or the last N syscalls, or if the vat simply doesn't do any syscalls at all, all of those misbehaviors will go uncaught.

The fix is to add another check at the end of the delivery (i.e .add `transcriptManager.finishReplayDelivery()`) and have it assert that `playbackSyscalls.length === 0`.

With this in place, failures like #3021 (where the vattp vat is somehow failing to send all of the messages it was supposed to), *if they are nondeterministic* (and somehow statistical) might be caught during a restart of the original chain.

cc @FUDCo

**Comment by FUDCo** [comment]
Closed by #3059
