### ISSUE TITLE
consensus failures during phase3 ("staking dynamics") testnet

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3057]
We've seen multiple sporadic reports of testnet nodes experience a consensus failure. It feels like a non-determinism somewhere. Most folks have addressed it by resetting their node and relaunching.

I experienced the same with the monitoring node, and did the same reset process to resume progress. I have a slog trace of both, so I'll be examining that to see if the divergence occurred at the swingset layer, and where.

Here's a catalog of which block and what AppHashes were reported by folks on Discord:

who | when | block | expected | got
--- | --- | --- | --- | ---
warner | 1200pm thu | 1754 | 7E2B60E9BDE56F90944BD9B620F3CFB45FF8950A781D1E66626861DAF67690FC | 61B941F39A81A31749C3F130B2972F3E8878932446FC87EBF6C232A86E0A1A22
novy | ~2:23pm thu | ? | 96A18549E7ACD1F977F6265C8271432E2649AFC74A82DD53BE87FC6D9921777C | 0918EC1B23CFFD3C7FA30F8381CDC3EF8034DF9DA0CE734EBD79D0EC96E279E7
mabalaru | <2:26pm thu | ? | ? | ?
goginn | ~3.13am fri | ? | 251A0E17277C24D3DD66BF83A57687A3B55A748A53C9892D40BAA0243DB29ACA | 156DCBDF7B0D2A4FC4EC2C0D17B6410F9B1D4F5ED99E084E88257A7FD6B70108
d1 | ~4:33am fri | 3516 | 92C9C548244D94840DC7E519FB7BDF0F18A4DD091647780E649DB8E1636BA875 | 75748C3E3652E763FF692C126082E2D3D2DAFF18E2304B5B4388C649BEED1770
kristaps | ~6:25am fri | 1754 | B7DA72ADCFF13FF054040479E5A26359A8DC6EF34FFD5FA3FEAC709B2DB6F703 | 61B941F39A81A31749C3F130B2972F3E8878932446FC87EBF6C232A86E0A1A22
jjangg96 | ~8:46am fri | ? | C2C52AA6C154C081D93D7064FE78D537825167BFAE3085115CE43B755C3A3B33 | F738BFAA0F41DEB4CEA3E2121C7411BD5FED3B9392AF4B80ABE902518C9B06BD
oxes | ~9:42am fri | ? | ? | ?

**Comment by rowgraus** [comment]
Should be fixed in latest release (vat shutdown problems)
