### ISSUE TITLE
Allow initial supply of non-mintable bank assets

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#3068]
## What is the Problem Being Solved?

The `home.bank` does not have access to mint ERTP RUN.  It can only escrow and unescrow RUN when it detects a bank purse `deposit` or `withdraw`.  However, when the chain starts, there is an initial supply of `urun`, usually from exporting an earlier chain.

Currently, the only way we can accommodate the current design is to zero out all the `genesis.json` `urun` allocations.  This loses all the exported balances, which is suboptimal.

## Description of the Design

This initial `urun` supply should be mirrored in ERTP RUN by having the treasury transfer its value in ERTP assets to the bank on chain start.  Such a transfer is similar to the "bootstrap transfer", but instead of restricting the transfer to a single bootstrap account, it can take advantage of the `urun` allocations performed in `genesis.json`.

This is less centralised and generalises the "bootstrap transfer" into an "initial bank supply", which is much more flexible.

We should then remove the "bootstrap transfer" machinery, as its use will be obsolete.

## Security Considerations

We will be more explicitly trusting the `urun` allocations given in `genesis.json`.  However, that should be an improvement and a step towards proper chain upgrades.

## Test Plan

Allocate a few different accounts with `ag-chain-cosmos add-genesis-account` and assign them initial `urun` values.  Verify that the created "bank supply" payment is exactly the sum of those allocations, and that the bank balances of those accounts is correct.

**Comment by michaelfig** [comment]
@dtribble, @katelynsills, @rowgraus PTAL once the immediate fires are out.

**Comment by dtribble** [comment]
We would require an invariant check that the amounts in there are covered by the treasury, i.e. backed by collateral as opposed to a number invented by governance.

**Comment by michaelfig** [comment]
> We would require an invariant check that the amounts in there are covered by the treasury, i.e. backed by collateral as opposed to a number invented by governance.

This is only happening on the initial `genesis.json`, as a simple replacement for a singleton "bootstrap" account used by `app_state.vpurse.bootstrap_address` and `app_state.vpurse.bootstrap_value`.

Instead, I propose sending all the values for `app_state.bank.supply` to the chain bootstrap.  Then the bootstrap can still tell the treasury the equivalent of what used to be `app_state.vpurse.boostrap_value` since we need that amount minted to honour the genesis account balances.  The benefit is that we won't be constrained to only a single genesis account with hardcoded `"urun"` balances.
