### ISSUE TITLE
"system" vats should not be limited by the compute meter

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3074]
We observed the zoe vat get killed by the compute meter. We're still trying to figure out why: it looks like one particular crank (the first `notify` (promise resolution) after a `splitMany` call) was taking more and more compute meter to finish, until it rose above the 10M threshold we apply to all vats.

We're working on making it take less time, but the fact that a meter was applied to zoe at all raised an important point: it wasn't our intent to enforce meters on static vats. The metering accidentally got applied when we moved zoe (and everything except comms) off to an xsnap worker.

The task is to change the way we spin up xsnap to remove the compute meter from static vats. This might want to be a `managerOptions`, except we must prevent already-metered dynamic vats from effectively escaping their meter by asking the vatAdmin to create a new dynamic vat with a larger threshold than they themselves were operating under. (this will become more coherent when we have metercaps or something). It's probably better for now to put a `computeLimit` in the `staticManagerOptions`, but specifically exclude it from `dynamicManagerOptions`, and set the defaults for both to different values. @dckc tells me that a compute limit of `0` will disable that meter.

These limits really want to be set on a per-crank basis (#2980), but for now it'll be enough to get control over the `xsnap` command-line `argv` field that sets the compute meter limit.

**Comment by dckc** [comment]
> ... @dckc tells me that a compute limit of `0` will disable that meter.

Right... for example, when we test abnormal termination:

```js
test('abnormal termination', async t => {
  const vat = xsnap({ ...xsnapOptions, meteringLimit: 0 });
  const hang = t.throwsAsync(vat.evaluate(`for (;;) {}`), {
    instanceOf: Error,
    message: 'xsnap test worker exited due to signal SIGTERM',
  });

  // Allow the evaluate command to flush.
  await delay(10);
  await vat.terminate();
  await hang;
});
```
https://github.com/Agoric/agoric-sdk/blob/master/packages/xsnap/test/test-xsnap.js#L365-L376
