### ISSUE TITLE
phase3 testnet (act 1): zoe died, then chain killed by LMDB size limit

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3086]
The phase3 ("staking dynamics") incentivized testnet ran for 4 days ("act 1") before dying. The last block (54569) experienced a termination of vat-zoe due to a metering fault. The block itself could not be committed because the DB transaction grew the LMDB storage beyond the pre-configured 2 GiB limit, which caused the chain to halt.

The fatal delivery to vat-zoe was a `dispatch.notify` that resolved a `paymentP` promise to a Payment object. This notification resumed an earlier delivery to `combine()`.

The full set of deliveries just before and after the `combine()` call are usually:

```
% ./block-timeline.py blocks-with-combine/block-52870.slog |grep -C5 combine
                          name    compute   ccompute   syscalls   elapsed       T+
                  v17:<notify>     11_909  6_024_116      0sys     0.009s   4.139s
                  v17:<notify>     17_150  6_041_266      0sys     0.012s   4.170s
            v11:getUpdateSince     17_396  6_058_662      0sys     0.013s   4.203s
                  v11:<notify>     58_383  6_117_045      3sys     0.818s   5.038s
                   v3:<notify>  1_183_540  7_300_585      5sys     0.522s   5.594s
                   v11:combine     44_536  7_345_121      2sys     0.044s   5.644s
                 v11:splitMany    686_234  8_031_355      1sys     0.307s   5.954s
                  v11:<notify>  9_533_842 17_565_197    359sys     5.506s  11.463s
                   v3:<notify>     21_006 17_586_203      0sys     0.005s  11.490s
                   v3:<notify>  1_227_215 18_813_418      2sys     0.363s  11.868s
            v16:getUpdateSince     28_484 18_841_902      1sys     0.004s  11.888s
```

(v11 is Zoe)

That trace was from block 52870. The next block which involves `combine()` is 53446, which has the same shape except the amount of work being done per-block is larger:

```
                          name    compute   ccompute   syscalls   elapsed       T+
                  v17:<notify>     11_909  5_936_075      0sys     0.015s   6.803s
                  v17:<notify>     17_150  5_953_225      0sys     0.012s   7.176s
            v11:getUpdateSince     17_396  5_970_621      0sys     0.006s   7.193s
                  v11:<notify>     58_383  6_029_004      3sys     0.052s   7.248s
                   v3:<notify>  1_193_274  7_222_278      5sys     0.432s   7.684s
                   v11:combine     44_536  7_266_814      2sys     0.023s   7.711s
                 v11:splitMany    692_098  7_958_912      1sys     0.673s   8.388s
                  v11:<notify>  9_615_741 17_574_653    362sys     6.161s  14.552s
                   v3:<notify>     21_006 17_595_659      0sys     0.006s  14.585s
                   v3:<notify>  1_237_879 18_833_538      2sys     0.462s  15.066s
            v16:getUpdateSince     28_484 18_862_022      1sys     0.026s  15.110s
```

Block 54003 sees:

```
                          name    compute   ccompute   syscalls   elapsed       T+
                  v17:<notify>     11_909  5_940_038      0sys     0.004s   6.225s
                  v17:<notify>     17_150  5_957_188      0sys     0.014s   6.325s
            v11:getUpdateSince     17_396  5_974_584      0sys     0.039s   6.413s
                  v11:<notify>     58_383  6_032_967      3sys     0.087s   6.552s
                   v3:<notify>  1_222_476  7_255_443      5sys     3.510s  10.082s
                   v11:combine     44_536  7_299_979      2sys     0.021s  10.108s
                 v11:splitMany    709_690  8_009_669      1sys     0.420s  10.531s
                  v11:<notify>  9_861_438 17_871_107    371sys     5.438s  15.976s
                   v3:<notify>     21_006 17_892_113      0sys     0.005s  16.015s
                   v3:<notify>  1_269_871 19_161_984      2sys     0.411s  16.439s
            v16:getUpdateSince     28_484 19_190_468      1sys     0.005s  16.461s
```

The last (incomplete) block, 54569, sees:
```
                          name    compute   ccompute   syscalls   elapsed       T+
                  v17:<notify>     11_909  6_117_873      0sys     0.005s   5.395s
                  v17:<notify>     17_150  6_135_023      0sys     0.007s   5.405s
            v11:getUpdateSince     17_396  6_152_419      0sys     0.006s   5.420s
                  v11:<notify>     58_383  6_210_802      3sys     0.024s   5.445s
                   v3:<notify>  1_241_944  7_452_746      5sys     0.232s   5.680s
                   v11:combine     44_536  7_497_282      2sys     0.027s   5.710s
                 v11:splitMany    721_418  8_218_700      1sys     0.467s   6.180s
                  v11:<notify>          0  8_218_700    376sys     6.738s  12.920s
                  v17:<notify>     27_885  8_246_585      1sys     0.146s  25.365s
                  v17:<notify>     14_818  8_261_403      0sys     0.014s  25.390s
                  v17:<notify>     27_885  8_289_288      1sys     0.029s  25.449s
                  v17:<notify>     14_818  8_304_106      0sys     0.015s  25.485s
                  ...
```

Clearly the `v11:<notify>` delivery is using more and more compute meter each time, and in the fatal block it exceeded the 10M threshold, killing the delivery. After that, the rest of the block is mostly notification of Promise subscribers about rejections due to the vat being terminated (all the `v17:<notify>` are rejections).

The overall operation seems to be something like:

* `combine()` a `Promise<Payment>` and a regular `Payment` into a single `Payment`
  * this gives the caller a `Promise<Payment>`
* take that `Promise<Payment>` and pass it to `splitMany()`, to break that `Payment` up into about 115 smaller payments
* resolve a Promise to a big array of those Payments,
  * that probably triggers some other vat to deposit them

`combine()` is split into two phases by a `then`:

```js
    combine: (fromPaymentsPArray, optTotalAmount = undefined) => {
      return Promise.all(fromPaymentsPArray).then(fromPaymentsArray => { // <--- split here
        fromPaymentsArray.every(assertKnownPayment);
        const totalPaymentsBalance = fromPaymentsArray
          .map(paymentLedger.get)
          .reduce(add, emptyAmount);
        assertAmountEqual(totalPaymentsBalance, optTotalAmount);
        // Commit point.
        const [payment] = reallocate(fromPaymentsArray, [totalPaymentsBalance]);
        return payment;
      });
    },
```

The fatal `v11:<notify>` is the resolution which triggers the second phase of `combine()`. The `splitMany` is pipelined surprisingly effectively, and when the second phase of `combine()` finishes, it also enables a second phase of `splitMany` to finish.

This pipelining is great, in one way, because it reduces latency that would otherwise require an additional trip through the kernel (it would be more critical if these messages were separated by a higher-latency link like chain-to-solo).

The pipelining was surprising (to me), because I assumed that the only code triggered by the resolution would be in `combine`, so I thought all the other activity was a bug. But in fact vat-zoe recognized the `splitMany` argument as a local promise, and was able to run the rest of `splitMany()` in the same crank. @FUDCo and I were able to confirm that all of the additional syscalls observed in the crank are accounted for by the rest of `splitMany` running.

Finally, the pipelining increases the uncertainty of how much work will be done in any given crank, particularly cranks which begin with a promise resolution `<notify>`, which raises some interesting questions of how we should perform (and charge for) metering. Other chains have encountered this issue at a similar phase in their lifecycle: Ethereum contracts moved to a "withdraw()" model where users must trigger (and pay for the gas costs of) specific (smaller) operations themselves.

We need to explore some different approaches here, maybe by adding a deliver-to-self operation that forces a resolution to go through the kernel even if it could be handled entirely locally. This would allow a vat to break up larger cranks into smaller ones, each of which might finish below the metering limit.

We're still not sure why the crank used so much meter (and, more concerningly, wallclock time: we were already exceeding our block-time budget in the earlier blocks when it was using less). The second phase of `splitMany` calls `reallocate` (just like `combine` does), but asks it to create about 115 new Payment objects:

```js
    ...
    // commit point
    payments.forEach(payment => paymentLedger.delete(payment));

    const newPayments = newPaymentBalances.map(balance => {
      const newPayment = makePayment();
      paymentLedger.init(newPayment, balance);
      return newPayment;
    });
```

Payments are virtual objects. Each one causes about three secondary-storage syscalls. The creation of the Payment object causes a new `Representative` (and associated state object) to be created, which gets pushed onto the LRU cache, which pushes something else off, so we usually see a `vatstoreSet` at this point for the state object that got evicted. Then there's a `paymentLedger.init(newPayment, balance)` (where `paymentLedger` is a `makeWeakStore`: like a WeakMap but which can be indexed by virtual object Representatives), which uses one `vatstoreGet` to assert that the key doesn't already exist, followed by a `vatstoreSet` to record the serialized balance. 

We see a new batch of these three syscalls (one batch per output Payment) happen at 19ms intervals. I've measured a single `syscall.vatstoreGet` at 306us, so the overhead of calling out to the kernel process (over the message pipe) doesn't account for the speed. Marshaling the data is probably a factor, I measured the difference between `weakstore.set(key,0)` and `weakstore.set(key,{})` at 54us, and between `{}` and `{foo:{}}` at 88us, but it's hard to imagine that serializing a single Amount could explain the remaining 15-sh milliseconds. In the last-successful block, that one crank performed GC 9 time, which might explain the overall wallclock time (and any "jank" or bursts of latency), but not the growth in meter count (I don't think GC counts towards the compute meter), nor any consistent slowdown of every operation. If there are a large number of objects in existence (which seems likely but we don't yet have a measure), that might slow down operations like `harden()`'s big WeakMap (but we don't yet have a measurement of how much time we spend in `harden`).

## Actual Chain Halt

Killing Zoe does not leave us with a usable chain, however that's not what actually killed the testnet. In the same block, the DB grew beyond the initial 2GiB limit, which threw an error while flushing the crank buffer.

An analysis of the DB (https://github.com/Agoric/agoric-sdk/issues/3065#issuecomment-837484381) shows that about 98% of it is consumed with transcript entries. #3065 will move these into a separate set of linear files, reserving LMDB for the random-access key-value it was made for, and #3073 will grow the DB when necessary. In addition, GC will delete clist and kernel table entries when possible, so I expect to see another few orders of magnitude size reduction once that feature is complete.

## Directions to explore

I'd like to know why the simple loop in `reallocate` took 18ms for each cycle, that seems really high. I'm going to start by looking at the syscalls from a much earlier block, and see if it took that much time then. I'm also going to look for jank between syscalls to see if GC happened. If an earlier block was significantly faster, then I'm going to suspect the sheer number of objects in play. I don't see how this could affect `paymentLedger`, which isn't held in RAM, but I can imagine `harden()` being affected.

Short of actually finishing GC (which I'd love to get back to..), I might be able to write a tool that analyzes this trace to see which objects actually get used in the remaining trace, and inject GC calls in the places where a kernel GC implementation would have injected them (if the rest of GC were complete). Then I could implement just the receiving side of that GC work and see if it helps speed up the replayed zoe vat.

**Comment by rowgraus** [comment]
Handled via transcripts - duplicate ticket.  Closing
