### ISSUE TITLE
add queryDevice

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#31]
@dtribble  pointed out that in a cosmos-sdk environment, we need a way to query the current block height (to produce timers). This information is available in a "context" object which is passed as an argument to our cosmos-sdk "handler". I think it is also available to our storage handlers.

I'm thinking that in SwingSet we add a new "query" device. From the outside, you configure this device with a callback function that can return a JSON-serializable record. From the inside, the device offers a single method, `query(handler)`, which invokes the callback function (through a stringifying membrane), then does `SO(handler).gotValue(data)`. That queues a sendOnly message to the client's handler object, which puts it on the run-queue, which handles the nondeterminism problem (it's as if some remote caller spontaneously decided to send us a "this is the result" message, but they did it in response to our prompting). The `query()` method itself returns nothing.

In a replicated environment, we require the callback to return a value that is a deterministic function of the state of the machine. A current block height is fine, but e.g. the public key of the current validator node is not (all replicas would invoke `query(handler)` at the same time, all would see a call to `gotValue()` queued at the same time, but the values of `data` would be different, and the replicas would diverge. If we really wanted to enable this, there's probably a way for the block proposer to provide a value, which all validators then follow.

Then, in the cosmic-swingset chain-side host loop, we create an instance of the QueryDevice named "blockheight", and connect a callback function that can look inside the context object for the current block height.

From the vat side, the bootstrap function would have access to `devices.blockheight`, and could dole it out to whatever other functions ought to have access to a clock (and more importantly *not* hand it out to everyone else).

**Comment by erights** [comment]
@Chris-Hibbert @warner this is obsolete now, right? I'm closing but assigning the two of you in case I'm missing something.
