### ISSUE TITLE
Release new version of ERTP with Zoe removed

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#312]
We need to release a new version of ERTP with Zoe removed. This is a breaking change since we had dependencies using `@agoric/ertp/core/zoe/` which no longer exists.

ERTP currently has version 0.1.12. I will do a minor version bump to 0.2.0 as recommended by @warner unless @michaelfig has strong feelings about doing something else

**Comment by michaelfig** [comment]
Sounds good.

**Comment by DavidBruant** [comment]
> ERTP currently has version 0.1.12. I will do a minor version bump to 0.2.0

I think there is no "minor bump" within 0.y.z

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. (...)

https://semver.org/#spec-item-4

If ERTP is used by other things, it might make sense to consider the API public and bump to 1.0.0

**Comment by katelynsills** [comment]
Good point about 0.y.z being for initial development. I think we're still not ready to release 1.0.0.

**Comment by katelynsills** [comment]
Closed by #314 and subsequent release
