### ISSUE TITLE
Usage of types from smart contracts

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3155]
@mhofman: What are the best practices for users to type their facets so that code hinting works?

@katelynsills: The best practice that I know of, which is not great, is that contract developer exports their types with the contract as part of the JS package (for our built-in contracts, currently this would be something like `@agoric/zoe/src/contracts/contractName/types.js`) and then the downstream user of the contract can import the types. 

This needs improvement.

_Originally posted by @katelynsills in https://github.com/Agoric/dapp-fungible-faucet/pull/21#discussion_r637262568_

**Comment by Tartuffo** [comment]
Vague
