### ISSUE TITLE
Undocumented format change in function parseVatSlot 

### ISSUE THREAD

**Issue by andrey-kuprianov** [Agoric/agoric-sdk#3174]
_Surfaced from @informalsystems Agoric Audit of Agoric/agoric-sdk/SwingSet hash 23ed67c070a6ea04fb305d469283107b1d3d65f3_

Function [parseVatSlot](https://github.com/Agoric/agoric-sdk/blob/23ed67c070a6ea04fb305d469283107b1d3d65f3/packages/SwingSet/src/parseVatSlots.js#L22-L76) is documented to parse a string and return the object with this signature:

```js
/**
 * Parse a vat slot reference string into a vat slot object:
 *   {
 *      type: STRING, // 'object', 'device', 'promise'
 *      allocatedByVat: BOOL, // true=>allocated by vat, false=>by the kernel
 *      id: Nat
 *   }
*/
```

At the same time, the function actually accepts the extended format `{ type, allocatedByVat, virtual, id, subid }` with `id` and `subid` separated by `/`:

```js
  const delim = idSuffix.indexOf('/');
  let id;
  let subid;
  let virtual = false;
  if (delim > 0) {
    assert(type === 'object' && allocatedByVat, X`invalid vatSlot ${s}`);
    virtual = true;
    id = Nat(BigInt(idSuffix.substr(0, delim)));
    subid = Nat(BigInt(idSuffix.slice(delim + 1)));
  } else {
    id = Nat(BigInt(idSuffix));
  }

  return { type, allocatedByVat, virtual, id, subid };
```

Moreover, the non-extended format seems to be used everywhere in the documentation as well.

This may pose multiple problems:
 
 - User of that function or of the documentation will be unaware of the extended format. E.g., they may implement their own parsing for the non-extended format, for example, and then the input data in the extended format will crash them.
 - The Vat slots seem to play one of the central roles in the whole system, as they are part of CapData structure. Allowing two incompatible format for that may be the source of non-determinism.

It should be noted that this issue would be easily caught by migrating the code base to TypeScript; see issue #3173.

**Recommendation**
 - update the documentation to reflect the extended format
 - inspect all call sites of `parseVatSlot` function to ensure that the extended format doesn't pose problems.

**Comment by FUDCo** [comment]
It appears that this issue is based on a slightly older commit.  The documentation in question was added as part of #4742 and that work included going over the various call sites for a consistency check.

Closing.
