### ISSUE TITLE
Contract-embeddable library for managed parameters  (Governance)

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3186]
## What is the Problem Being Solved?

Part of Governance Epic

Build a library that can be embedded in Zoe contracts to manage parameter values that can be set from outside by governance.

It should be data driven as much as possible.

**Comment by zarutian** [comment]
Just thinking out loud here.

A Parameter would be some value, usually something that could pass throug E Data guard unscathed, that could only changed by goverence. Boiling it down, it sounds like an E's VarSlot with a readonly facet and a readwrite facet. The former facet is held by the smart contract and does not need to be closely held. The latter facet is held by whatever governance mechanism used.

Where would the aforesaid VarSlots live? most likely in the vat running the smart contract being parameterized but it would not be out of the question that they live elsewhere. (An example would be akin to LIBOR rate etc)

Most likely one smart contract would have (quite) a few Parameters so it is prudent of having some sort of parameters manager or some such that takes in readonly VarSlot facets, assigns a petname to each and provides an accessor function/closure of the form param('<parameter petname>') to be used inside the smart contract's code. (It could also be a proxy to allow for param.rate or such usage)

On the right track here or at least close?

**Comment by Chris-Hibbert** [comment]
> Where would the aforesaid VarSlots live? most likely in the vat running the smart contract being parameterized but it would not be out of the question that they live elsewhere. (An example would be akin to LIBOR rate etc)

We expect to usually put it in the managed contract so access to it is a synchronous operation. We'd rather the updates to the parameters be async than accesses.

Our expectation is that these parameters are specific to each contract and don't need to be shared or widely accessible. There may be a few or several, but we won't necessarily know at the start which ones governance will want to change. So we'll add as many as plausible for the contracts we want to manage. The larger task here is building the governance system that would be able to hold the management facet and change the parameters after a vote or other management decision.

**Comment by dtribble** [comment]
Rather than having governable params be entries in a map, conceptually, have them be discrete, typed cellsl e.g.,
```
const chargingPeriodParam = gov.natParam(CHARGING_PERIOD_KEY, loanParams.chargingPeriod);
const recordingPeriodParam = gov.natParam(RECORDING_PERIOD_KEY, loanParams.recordingPeriod);
```
and then usage would be `chargingPeriodParam.value()` or some such.
