### ISSUE TITLE
Support lock-up certificates (Governance)

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3190]
## What is the Problem Being Solved?

We want access in Javascript to the shares owned by stakers.

## Description of the Design

Add an API to `home.bank` that supports requests for a `certificate` that vouches for stakers, and reveals their share, address, and the end of the current lock-up period.

**Comment by rowgraus** [comment]
Is 'lockup' in this case defined as Unbonding time only?

**Comment by Chris-Hibbert** [comment]
Currently yes, but we've had (non-in-depth) discussions about allowing the stakers to commit to a longer period, so the certs could last longer.

**Comment by Chris-Hibbert** [comment]
The attestation contract (#3475) takes care of the needed functionality.
