### ISSUE TITLE
Units are possibly useless

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#323]
While [creating a guide for creating specific assets](https://github.com/Agoric/documentation/pull/68), i've had the occasion to read and manipulate most of the ERTP API

I'm currently arriving at the conclusion that between extents and units, there might be one that is superfluous and i think it's units (with minor changes)

## Context

Currently, units are used in `mint.mint(units)`, `assay.makeUnits(extents)`, `assay.claim/burnExactly(units, payment)` (although that's being questioned #104 ), `purse/payment.getBalance()` (returns units), `purse.depositExactly/withdraw(units)`
Units are also used as a means to describe an asset without necessarily holding it in the pixel gallery

Creating units is possible to everyone with access to the assay (which is intended to be public and accessible via any valid payment anyway) via `assay.makeUnits(anyValidExtent)`, so it's basically a public capability

Creating units offers 3 security-related guarantees
https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/core/unitOps.js#L46-L54
1. the extent is valid
2. a brand check (in `coerce`, which is used in lots of places)
3. the `label` is the specific one provided at mint creation time

https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/core/mint.js#L250-L252

Given that creating a unit from an extent is a public capability, i don't see how the brand check adds any security value. If someone wants to create a unit, they can just create a valid extent and do whatever they want

Also, it sounds like a good share of time of the pixel mint is spent recovering the extents from the units (themselves coming from `getBalance`) to manipulate them directly

https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/more/pixels/gallery.js#L68-L70

https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/more/pixels/gallery.js#L112

https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/more/pixels/gallery.js#L123-L127

https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/more/pixels/gallery.js#L131

And the [checks that guard against inappropriate units](https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/more/pixels/gallery.js#L58-L66) already guard against inapproriate extents since units are as untrustworthy as extents are (and if other checks don't, they should)

Finally, a good share of the unitOps API really is just [conveniences around extentOps](https://github.com/Agoric/agoric-sdk/blob/f1b9dcae7d22aa7adc6222a42a0727ea29c055f3/packages/ERTP/core/unitOps.js#L61-L121)

## Current conclusion

I think units can be replaced by extents everywhere without loss of security or developer experience convenience 
I anticipate the developer experience would actually improve

If units disappear, the label part of the units would no longer be there, but i don't think unit labels offer more authenticity-related guarantees than purses/payments do, so i don't think this is a loss

... if units can indeed go, this opens the possibility for renaming extents (sorry to reopen this topic :-/)

**Comment by katelynsills** [comment]
Hi David, the reason for using units is to protect against developer/user error. If only extents are used, it is very easy to accidentally confuse the types of digital assets. For instance, if I want to transfer 1,000,000 moola, it's nice to have an extra check such that if I say `simoleanPurse.withdraw(moola1000000)` it fails, where as if I only did `simoleanPurse.withdraw(1000000)` it would work and I would lose a million simoleans.

**Comment by DavidBruant** [comment]
> simoleanPurse.withdraw(1000000)

Units do protect against an error for `withdrawAll()` though. If you've withdrawn from the wrong purse with withdrawAll, nothing can help you.
If a solution is needed at the withdraw call level, maybe using the assay as an additional argument could work: `simoleanPurse.withdraw(1000000, moola)` (where `moola` is the assay)

> If only extents are used, it is very easy to accidentally confuse the types of digital assets

I acknowledge that confusing types of digital assets may be a concern, but i'm not sure about the solution

Given it's more annoying to write units than extents, it's very possible people will create a convenience function:
```js
function withdrawByExtent(purse, extent){
    return purse.withdraw(purse.getAssay().makeUnits(extent))
}
```

And the confusion will be equally easy leading with a call to `withdrawByExtent(simoleanPurse, 1000000)` by mistake

I feel like the solution of units only shifts the problem one step further but doesn't solve it

To solve the problem, the question i would ask is: if i wanted to manipulate moola, how did i end up with a simolean purse?
A different version of this question would be: if i managed to successfully create/get the correct unit, why did i fail with the purse?

Maybe a different approach could be to create a "PurseCollection" API. This is the place where one actor (human or smart contract) would store all their purses. It could be some sort of weakmap key'ed on assays. This way, when you want to withdraw moolas, you first get the moolaAssay and then:
`myPurseCollection.get(moolaAssay).withdraw(1000000)`
Maybe PurseCollection could help with sorting too: 
`myPurseCollection.deposit(anyPayment)` would do the right thing: either create a new purse because the assay is new or deposit the payment in the existing purse of the same assay

If you have any doubt on the purse you're holding, go back to the purse collection and query with the correct assay

**Comment by katelynsills** [comment]
> Units do protect against an error for withdrawAll() though. If you've withdrawn from the wrong purse with withdrawAll, nothing can help you.

That's true, that `withdrawAll` takes no arguments and therefore there's no additional check of whether you mean the right thing. I think that is why I would recommend using `withdraw` for anything valuable. `Withdraw` with units does protect users/developers from costly mistakes about the kind of digital asset. 

> simoleanPurse.withdraw(1000000, moola)

This is essentially how it works now except it's in one parameter, units. Units is the extent + assay plus an allegedName, which we might be able to remove. 

> Maybe a different approach could be to create a "PurseCollection" API. 

You might be interested in the [first draft of a wallet backend](https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/lib/ag-solo/vats/lib-wallet.js#L18), which is a collection of purses. 

We aren't going to switch to using extents over units, but I think it's important for us to figure out how make units as easy to use as possible so that people do not use their own mechanisms, as you pointed out.

**Comment by katelynsills** [comment]
For organizational purposes, I'm going to close this as a 'won't fix' for now, but I think the points made in the original post are very important and we should keep in mind that telling users to do things one way when the API allows for a different (easier-looking) way is an anti-pattern that we should avoid.
