### ISSUE TITLE
top-level 'yarn test' fails on packages/ui-components

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3248]
## Describe the bug

Running a top-level `yarn && yarn build && yarn test` results in a failure on `packages/ui-components`:

```
  Uncaught exception in packages/ui-components/test/components/test-NatAmountInput.js

  /home/warner/stuff/agoric/agoric-sdk/packages/ui-components/test/components/test-NatAmountInput.js:27
      <NatAmountInput
      ^

  SyntaxError: Invalid or unexpected token
```

Running `cd packages/ui-components && yarn test` is successful.

I think the problem is that the `ui-components` tests depends upon the following command (from `packages/ui-components/package.json`):

```
  "scripts": {
    "test": "BABEL_ENV='test' ava",
```

whereas the top-level package.json has a `yarn test` script which tells AVA to run all `test-*.js` in the entire tree:

```
  "scripts": {
  ...
    "test": "ava",
```

Making the top-level `yarn test` bypass `yarn workspaces test` and invoking AVA directly means that individual packages cannot override their configuration, which I think is what the `ui-components` tests need to tolerate/convert the special syntax they use.

I suspect the fix will be to revert the top-level `package.json` test script, but I'll leave that up to folks who know better.

This wasn't caught by CI because CI doesn't use a top-level `yarn test`, instead it runs multiple parallel jobs that test one (or a few) packages each, for speed.

**Comment by katelynsills** [comment]
Thanks @michaelfig  for tackling this
