### ISSUE TITLE
Category error: RUN is a coin, not a role

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#3252]
From https://github.com/Agoric/agoric-sdk/pull/3184#discussion_r642734708

Our keywords generally name the roles that the assets play in the contract, like `Collateral`. `RUN` and `BLD` are the names of specific coins. The treasury should be a reusable abstraction that people can use, for example, to create an equivalent arrangement involving their own staking token and stablecoin, or whatever. 

Naming the keyword here 'RUN' reminds me of the bit of browser history where some applications would check if they were running on a particular browser, so browsers starting claiming to be the browser the applications were looking for. Instead, the page should have been coded to be browser independent. I would hate to see others use our treasury code where they have to say something like `want.RUN: fooCoin(88)` and explain that their fooCoin is used in the `RUN` role of the treasury. Is `RUN` a role or a coin? We shouldn't try to have that both ways.

**Comment by erights** [comment]
@Chris-Hibbert @turadg is this still relevant?

**Comment by turadg** [comment]
I think not. For Inter Protocol contracts We've moved to semantics keywords like `Minted`
