### ISSUE TITLE
vat warehouse eviction vs failed-delivery rollback

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3279]
In #2784 I [noted](https://github.com/Agoric/agoric-sdk/pull/2784#pullrequestreview-679089149) that we have a potential bug / race between two sets of state changes, and when exactly they get committed. The concerning sequence is:

* vatB is resident in memory, and the DB contains keys for the previous snapshot (call it "snapshot1") plus the transcript for any deliveries made since then
* delivery for vatA is given to the Vat Warehouse
* to page in vatA, the warehouse must page out (`evict()`) vatB
  * the warehouse chooses to make a vatB snapshot2 at eviction time, rather than e.g. after the previous vatB delivery
  * to commit to snapshot2, the warehouse updates two DB keys, one for the vatB snapshot2 name, the other to increment the vatB transcript replay starting index (just copying it from the finishing index, effectively truncating the transcript)
* now the vatA delivery is made, which updates a bunch of vatA keys (plus the run-queue, anything that happens during the delivery)
* but, the vatA delivery failed, e.g. a metering fault
* the kernel sees the failing `VatDeliveryResult` and unwinds the crank (`abortCrank()`) to discard the partial vatA changes
  * oops, that also unwound the vatB snapshot2+transcript-start keys
* no other delivery to vatB happens for a while
* the block is committed by the host
* the host process exits
* the host process is restarted
* a delivery for vatB is given the the warehouse
* the warehouse pages in vatB, whose DB keys still refer to snapshot1

Now that I look at it, this may be weird but not incorrect. By unwinding the snapshot2 action, we're effectively not taking a snapshot2. When vatB is paged in during the second process, it will wake up in the earlier state (snapshot1), but the snapshot name and transcript index values still match each other. The consequence is that we must re-do some work that we could have avoided (we wasted the time it took to make snapshot2), but it ought to still do the right thing.

To clean this up and avoid the lost work, I'm thinking that the Vat Warehouse API should get another method, let's call it `tidy()` for now. The warehouse would defer doing any sort of meta work (eviction or snapshots) until `tidy()` is called, so e.g. `vw.deliverToVat()` is allowed to page in a vat, but not evict any, and the warehouse is allowed to temporarily exceed it's max-vats-in-memory policy. The kernel gets back the delivery results, either commits or unwinds the crank's DB changes (which are now only related to the delivery, not any other work), and *then* calls `vw.tidy()`. Then the vat warehouse can do whatever DB changes it needs without fear of interaction with unwindable cranks. The kernel would commit the warehouse's DB changes (with `commitCrank()`) right away, as soon as `tidy()` returns.

This might also fit in with a warehouse policy of e.g. making a snapshot after a vat's transcript grows to 100 deliveries, rather than (or in addition to) making one at eviction time. The `vw.deliverToVat()` call could keep a scoreboard of deliveries and do a snapshot-and-keep-resident action if the most recent one had built up a backlog. This could keep the restart time down in the face of a crash/restart (especially if a few vats are busy/popular enough that they never fall out of the LRU cache and thus never qualify for an `evict()` snapshot).

**Comment by dckc** [comment]
notes on discussion with @FUDCo , @warner 

> ...
>  - the warehouse chooses to make a vatB snapshot2 at eviction time

This doesn't happen. We don't snapshot on eviction. **Eviction doesn't modify the kernelDB.**

maybeSaveSnapshot() happens before commitCrank()

```js
      if (!didAbort) {
        kernelKeeper.processRefcounts();
        kernelKeeper.saveStats();
        // eslint-disable-next-line no-use-before-define
        await vatWarehouse.maybeSaveSnapshot();
      }
      commitCrank();
```

Snapshotting on eviction might have some aesthetic and perhaps performance improvements; we could reconsider after doing some measurements.

@warner has an intuition that the vat warehouse should pay attention to wallclock time and have a budget (_incompletely transcribed_). But lacking info about when future deliveries are coming, this would be tricky.

block driven (host-driven) snapshotting is an idea from @dtribble from other discussions. (_IOU an issue?_) e.g. `controller.theBlockHasFinished()`.
