### ISSUE TITLE
split vatKeeper.getSourceAndOptions into smaller pieces

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3280]
## What is the Problem Being Solved?

As noted in [#2784](https://github.com/Agoric/agoric-sdk/pull/2784#pullrequestreview-679084623), the Vat Warehouse sometimes needs to know whether pipelining is enabled for a vat or not. Currently it must call `vatKeeper.getSourceAndOptions()` to get the `options` bundle that contains `{ enablePipelining }`, and ignores the megabyte-or-so source bundle that comes back too.

The task is to add a `vatKeeper.getOptions()` that only retrieves the `${vatID}.options` key, and not the `${vatID}.source` key too. And then update Vat Warehouse to use it instead of `getSourceAndOptions`.

## Test Plan

Simple unit test in `test-state.js`.

**Comment by dckc** [comment]
I added a checkbox in #2277 , which is assigned to me for the stress test milestone, to track this. I'm fine with this separate issue, but now I'm unsure who has the ball. Did you mean to assign this to me? Or did you mean for it to have lower priority, so it's not on the critical path for stress test? (if it's not critical for this milestone, I don't need to know who has the ball.)

**Comment by dckc** [comment]
The questions are perhaps more relevant for other issues; I can just do this one in less time than it takes to bother with them...

**Comment by warner** [comment]
I meant it to have lower priority.. just a "nice to have". If you're fixing it as a side-effect of other work, awesome. If not, it can wait.
