### ISSUE TITLE
add kernelKeeper.provideVatKeeper(), remove getVatKeeper/allocateVatKeeper

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3281]
## What is the Problem Being Solved?

As [noted](https://github.com/Agoric/agoric-sdk/pull/2784#discussion_r647858037) during the #2784 "Vat Warehouse" PR review, the split between `kernelKeeper.allocateVatKeeper()` (which must be called exactly once per kernel process) and `kernelKeeper.getVatKeeper()` (which must be called *after* `allocateVatKeeper`) is awkward. The Vat Warehouse uses `kk.getVatKeeper() || kk.allocateVatKeeper()` as a pseudo "provide" function (where we use `provideFoo()` as our standard name for a function that either creates and returns a new Foo, or returns a previously-created Foo). However `vatTranslator.js` only calls `getVatKeeper()`, which makes it dependent upon someone else having called `allocate` first, which is fragile and likely to break under maintenance.

## Description of the Design

* add `kernelKeeper.provideVatKeeper()`, which can use the existing internal ephemeral `vatKeepers` table as a cache
* remove `kernelKeeper.getVatKeeper()` and `allocateVatKeeper()`
* replace all calls to either function with `provideVatKeeper()`

## Performance Considerations

This approach is fine for now, but as our system grows biggest (in particular as we get a larger number of short-lived vats), the internal ephemeral `vatKeepers` table will grow too much: it will contain a `vatKeeper` for every vat that was ever used during the lifetime of the kernel process, whereas we only need them for active vats (vats which are paged in by the Vat Warehouse).

One fix would be to add a `kernelKeeper.evictVatKeeper()` method, and have Vat Warehouse call it when evicting a vat from memory.

A different fix would be to have `kernelKeeper` apply an LRU policy to its internal cache, to drop some vatKeepers.

I'm currently in favor of the `evictVatKeeper` approach, as it would basically retain a 1:1 relationship between Vat Warehouse paged-in vats and `kernelKeeper` "paged-in" `vatKeeper` instances, without binding the two together very tightly (`evictVatKeeper` is more of a hint, since any call to `provideVatKeeper` will just make a new one).

It's worth remembering that `vatKeeper`s are just a convenience: they no longer contain any state in RAM, they just close over the `vatID` in a way that makes the API easier to use. If managing them becomes awkward, we could remove them in favor of a big batch of new `kernelKeeper` methods that all take a `vatID` as their first argument.

## Test Plan

Normal unit test in `test-state.js`.

**Comment by dckc** [comment]
`kk.getVatKeeper()` was used to check that a vat existed and wasn't terminated. I guess I should add a `kk.hasRunningVat(vatID)`?

**Comment by dckc** [comment]
> ...
> It's worth remembering that `vatKeeper`s are just a convenience: they no longer contain any state in RAM ...

not quite. there's some associated transcript state. That is: `vk.closeTranscript()` has to be called whenever one is evicted.

**Comment by warner** [comment]
Hm, yeah we should make a clear distinction between "the vat is defined and not terminated", and "the vat is currently paged in", with most code not caring about the latter. We need some precise jargon for this, else we're going to get ourselves (and others) confused.

Some of the "is the vat alive" checks are because we have a message to send to the vat, and if it's dead we're going to reject a result promise with an error instead. In other cases, if it's dead we just ignore the message.

I'm wondering if it'd be more appropriate for this "is it alive" check to be owned by the vat warehouse, rather than the kernelKeeper. The ultimate data source is the kernelKeeper, of course. I suppose the deciding factor should be who's doing the asking and whether it's more convenient for them to hold a kernelKeeper or the vatWarehouse object.

How about "kk.isVatAlive(vatID)` for now? "Alive" vs "dead" can be the durable-state distinction, a property of the DB: vats become "alive" during `initializeSwingSet` (for static vats) or `createDynamicVat`, and become "dead" when they are terminated (`syscall.exit`, illegal syscall, or metering fault). Then the Vat Warehouse manages the somewhat-ephemeral state distinction between "online" and "offline".

> not quite. there's some associated transcript state. That is: vk.closeTranscript() has to be called whenever one is evicted.

Oh, good point. But, it's not exactly state that's owned by the vatKeeper, right? VatKeepers don't close over any mutable objects or hold any precious (per-VatKeeper) authorities, just the generic `streamStore`. Whoever is managing a vat (i.e. VatWarehouse) is responsible for calling *a* `vk.closeTranscript()` when the vat is evicted, but it doesn't matter whether they use an old VatKeeper or a brand new one: both will pass through to `streamStore.closeStream()`.
