### ISSUE TITLE
Attestation Contract Regarding Lien

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3282]
We will need a generic solution for minting attestations of lockup for external assets.

The potential use cases:
* BLD is bonded on the Go side, and JavaScript smart contracts want to use this bonded BLD as collateral, but need assurance that the BLD will remain locked (not 'unbonded').
* assets from another chain
* off-chain assets such as gold or real estate

For more information, see https://github.com/Agoric/dapp-token-economy/issues/282

**Comment by zarutian** [comment]
Let us see, what would such attestations look like?

An ERTP nft whose Amount values are records (objects) of the form:
```js
const attestationValue = harden({
  minted: { timestamp, timerService },
  ...
});
```
with probably more in it.
