### ISSUE TITLE
Low-level (Cosmos) Keplr wallet integration

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#3290]
Create a simple way for people to install Keplr and add support for Agoric chains to it.

https://docs.keplr.app/api/suggest-chain.html describes how to suggest a chain from a website.

https://github.com/luniehq/lunie-light is a Keplr and Ledger-compatible staking frontend, with https://wallet.e-money.com/welcome is an example of how it can be used.

We would want to serve `devnet.wallet.agoric.com`, `mainnet.wallet.agoric.com`, etc. to suggest the appropriate chain to Keplr, and host the Lunie Light interface to enable a staking UI.

**Comment by rowgraus** [comment]
Confirmed basic functions working on Devnet.  However, staking interaction on Lunie Light interface failed.  Michael indicated this was a devnet-specific issue as not all RPC nodes are accessible.

@michaelfig does the testnet integration depend on any configuration parameters of the actual testnet?  When we upgrade the chain will we need to rev anything on this?

**Comment by michaelfig** [comment]
> @michaelfig does the testnet integration depend on any configuration parameters of the actual testnet? When we upgrade the chain will we need to rev anything on this?

If it works the way it's documented, then probably people will have to visit the wallet.agoric.app page again after an upgrade, but not have to drop the existing configuration.
