### ISSUE TITLE
Extent configuration is limited to what's exposed in extentOpsLib.js

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#330]
Follow-up to https://github.com/Agoric/documentation/pull/68#discussion_r357591999

This prevents configuration of a custom listExtentOps without having to change extentOpsLib.js
Changing extentOpsLib.js can work for the Agoric team but doesn't seem to work for people outside of the Agoric team

This ties back to what i wrote in https://github.com/Agoric/agoric-sdk/issues/80#issuecomment-561240691

I would recommand:
- going [back](https://github.com/Agoric/ERTP/pull/151/files#diff-6984dbce8a1e881c656281384f5e3ae0) to the "extentOps" setup where the extentOps is passed directly as an object. The responsability to provide the correct object is left to the mint creator
- delete `config/extentOpsLib.js` altogether
- change the pixel mint so that is creates its provides its extentOps and passes it directly (following the mint API change)

My head is in this code, so i feel capable to can make a pull request for this if there is agreement on the proposed solution

**Comment by katelynsills** [comment]
A couple of things:

1. We are vulnerable to bad and malicious extentOps, so only vetted and known extentOps should be able to be used, so the library concept isn't any more restrictive than how much we must already be for security. If people want different extentOps, they must be vetted and added to the library.
2. In our SwingSet environment, we cannot pass by copy objects that have methods between vats. We can't pass methods between vats. We can't therefore pass pre-made extentOps objects between vats. To get around this, we pass the things that can be passed-by-copy and recreate the extentOps in the other vat. 

I haven't looked recently at whether we have the same problems now given the extentOpsLib. It could be that the reasons we had to break down the extentOps and build them back up are no longer entirely pertinent now that we can import things from other files (we weren't able to do so before!).

Let's make sure any new solution is tested in the Swingset tests where there actually are distinct vats and analyzed from the perspective of malicious extentOps.

**Comment by DavidBruant** [comment]
> so the library concept isn't any more restrictive than how much we must already be for security. If people want different extentOps, they must be vetted and added to the library.

oh ok, i had misunderstood the intention around extentOps configurability 
Thanks for clarifying!

**Comment by katelynsills** [comment]
Closing this issue because we want to keep extentOpsLib.js
