### ISSUE TITLE
[ERTP] Feedback on listExtentOps.js

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#331]
Feedback on this version : https://github.com/Agoric/agoric-sdk/blob/e4b7c868858329928c7fb25f4cac881d81458a99/packages/ERTP/core/config/extentOps/listExtentOps.js

- `listExtentOps.includes` has O(n*m) (~quadratic) behavior: in the worst case (the one returning `true`), its own code loops over all `part` elements to call `includesElement`. And each call to `includesElement` loops over all of `whole` elements 
- `listExtentOps.includes` is called in `listExtentOps.equals` (twice!) and in `listExtentOps.without` so these will also suffer from the perf problem 
- There is something that feels redundant in having to provide both `isElementEqual` and `compareElements`. The former can be derived from the latter (`(a, b) => compareElements(a, b) === 0`)

**Comment by katelynsills** [comment]
Yup, this is absolutely right. We should be able to improve this for most things by having algorithms based on sorted arrays. I [started the work on this](https://github.com/Agoric/ERTP/compare/ordered-pixelList) but never finished it. 

I seem to remember there being a use case in which the extents weren't necessarily sortable. I can't remember what it was though. So perhaps we could create the sorted version and then be able to fall back on the non-sorted, non-efficient for that specific use case if it comes up again

**Comment by DavidBruant** [comment]
One approch to solve all the perf problems i listed above is to make `includesElement` constant time (or log(n)) and this seems possible if the underlying storage is a sorted array

**Comment by erights** [comment]
Or O(1) is the underlying storage is a `Set`

**Comment by DavidBruant** [comment]
I don't think a Set as underlying storage is relevant
The elements of the collections are extents for which equality is comparison by value and Sets do not compare by value. In a Set, `extentOps.with(new Set([{a:1}]), new Set([{a:1}]))` will result in a Set with 2 elements while, i think it should be a set with a single element (because the extents represent the same extent IIRC)

**Comment by katelynsills** [comment]
> The elements of the collections are extents for which equality is comparison by value and Sets do not compare by value.

Yes, that's right. I had forgotten, but this was one of the main obstacles that led to ListExtentOps being in terms of arrays.

**Comment by erights** [comment]
@DavidBruant @katelynsills good point
