### ISSUE TITLE
Possible loss of VAT termination events

### ISSUE THREAD

**Issue by andrey-kuprianov** [Agoric/agoric-sdk#3315]
_Surfaced from @informalsystems audit of Agoric/agoric-sdk/SwingSet/kernel at hash 5e1024e44622f26e16870ce1f03c25e8a4ee6afa_

The function [setTerminationTrigger](https://github.com/Agoric/agoric-sdk/blob/5e1024e44622f26e16870ce1f03c25e8a4ee6afa/packages/SwingSet/src/kernel/kernel.js#L352) is as follows:

```js
  function setTerminationTrigger(vatID, shouldAbortCrank, shouldReject, info) {
    if (shouldAbortCrank) {
      assert(shouldReject);
    }
    if (!terminationTrigger || shouldAbortCrank) {
      terminationTrigger = { vatID, shouldAbortCrank, shouldReject, info };
    }
  }
```

It can be seen that if `terminationTrigger` is set already, then the second call to that function will not have any effect, i.e. the second termination event will get lost; this seems like a dangerous scenario.

We have not checked all possible sequences of events that may lead to the problem, in particular because this involves the Liveslots code, which are outside of the audit scope. One potential problematic sequence is when a vat requests to [exit](https://github.com/Agoric/agoric-sdk/blob/5e1024e44622f26e16870ce1f03c25e8a4ee6afa/packages/SwingSet/src/kernel/kernelSyscall.js#L42), which calls `setTerminationTrigger(vatID, false, !!isFailure, info)`, in particular setting the `shouldAbortCrank` to `false`; then a letter call to `setTerminationTrigger` with `shouldAbortCrank` set to `true` will get ignored.

While this probably doesn't constitute an error with the current code base, it may become a source of a bug at later stages, when more calls to `setTerminationTrigger` are added.

**Recommendation**: modify the code of [setTerminationTrigger](https://github.com/Agoric/agoric-sdk/blob/5e1024e44622f26e16870ce1f03c25e8a4ee6afa/packages/SwingSet/src/kernel/kernel.js#L352) to check whether the termination trigger has been set already, to compare vat ids and other parameters, and to take the appropriate action upon second function invocation.

**Comment by Tartuffo** [comment]
Closing in favor of #5731.
