### ISSUE TITLE
Zoe: make the contract instance available within a contract

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3330]
## What is the Problem Being Solved?

From inside a managed contract, I want to be able to call out to a legible contract manager and give it my contract instance (to include in a ballot question). 

## Description of the Design

We can already get the contract instance by creating a throw-away invitation and looking inside it, but it would be nicer to add a method to zcf to tell a contract its own instance.

Alternatively, the instance could be passed as an extra parameter to `start`.

## Security Considerations

None.

## Test Plan

the usual

**Comment by zarutian** [comment]
I approove of this.
No longer does one have to do:
```js
  // somewhere inside the contracts start()
  const selfP = (() => {
    const zoe = zcf.getZoeService();
    const tmpInvitation = zcf.makeInvitation(seat => seat.exit(), "tmpInvitation");
    const instanceP = E.get(E(zoe).getInvitationDetails(tmpInvitation)).instance;
    E(E(zoe).offer(tmpInvitation, {})).tryExit();
    return instanceP;
  })();
```
to get the instance of the contract.
I propose `zcf.getInstance();` as the way to do it.

**Comment by katelynsills** [comment]
This is a nice to have for Testnet: Stress Test Phase. It is more urgent than #3344
