### ISSUE TITLE
Promise.resolve(x)!==x for HandledPromises

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#334]
The cosmic-swingset REPL code looks basically like this:

```js
r = evaluateProgram(text);
if (Promise.resolve(r) === r) {
  r.then(resolution => notifyFrontend(resolution), rejection => notifyFrontend(..));
} else {
  notifyFrontend(r);
}
```

We're seeing that `Promise.resolve(r) === r` *fail* when `r` is a HandledPromise. This seems to be the root cause of #333 (the results of a `~.` tildot call are presented as `{}`, which I'm guessing is the stringification of the Promise/HandledPromise object). I think the tildot calls are actually being executed, it's just that their results are not being recognized as Promises by the repl code, so it thinks they're all done, and it tells the frontend to update the display with a stringification of that promise, which comes out as `{}` (indistinguishable from an empty object). And because it doesn't realize they're promises, it doesn't wire up a `.then` to update the display later when it finally does resolve.

@erights MarkM says this is because HandlePromise is a subclass of Promise. He's working on a fix now.

CC @michaelfig

**Comment by warner** [comment]
Also the unit tests should get some coverage of `Promise.resolve(x)===x`.

**Comment by erights** [comment]
This is my fault. @michaelfig asked me to review #110 . I was feeling overwhelmed at the time at advised him to proceed without my review. Had I not done so, I likely would have caught this.

In any case, in progress at #336
