### ISSUE TITLE
evaluateProgram on tildot expression should not do sendOnly

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#335]
@erights pointed out a problem in our defintion of wavy-dot that was caught by @waldemarhorwat . Our transformation algorithm (which expands e.g. `x~.foo(arg)` into `HandledPromise.applyMethod(x, 'foo', [arg])`) looks at the context in which the `~.` appears, to decide whether the Promise it returns gets used or not. If not, the tildot expands into a different form (`applyMethodSendOnly`?) that doesn't return a Promise at all. This helps our promise-pipelining code be smarter about not allocating memory or communication-layer references for unused results. This algorithm knows the difference between cases where it gets used (like `p = x~.foo(arg)` or `x~.foo(arg).then(...)`) and cases where it gets dropped (like `unrelated(); x~.foo(arg); unrelated()`). In many contexts, a bare `x~.foo(arg)` is dropping the Promise.

However `evaluateProgram` provides a context in which the last expression-statement does *not* throw away its result, so e.g. `unrelated(); x~.foo(arg)` in a "program" context should *keep* the Promise (and return it from the act of evaluation).

I'll ask @erights to expand on this, but I believe he said that a 90% solution is to make `evaluateProgram` treat the last expression-statement specially, and assume that the promise will be retained (preventing the use of `applyMethodSendOnly`). The full solution involves more cases.

We thought this might be involved with #333, but now we think #334 is more likely.

CC @michaelfig

**Comment by erights** [comment]
@warner 's summary didn't quite capture my position. The transformation shouldn't know or care how the resulting string gets evaluated. If it is syntactically supposed to be an evaluable script/program, then we must assume that its completion value is obtained. Thus, we must avoid the `*SendOnly` optimization when a tildot expression appears in completion value position.

The 90% solution is to avoid the `*SendOnly` optimization only when the tildot expression is an expression statement that appears as the last statement in the program.

Modules have no observable completion value, so we don't need this special case for module code at all.

**Comment by erights** [comment]
Closing as we no longer expect to work on `~.` . If we pick this up again, we can reopen.
