### ISSUE TITLE
Create editable voting scripts for Committee Members

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3354]
We will need to create "deploy" scripts that exercise the voting capabilities. Validators should be able to edit the scripts to make their choice and then run them to vote using objects from their wallet.

**Comment by Tartuffo** [comment]
@Chris-Hibbert Still need this, and if so, for Mainnet 1?

**Comment by Tartuffo** [comment]
Only for committee members, so not MN-1.

**Comment by dckc** [comment]
In the context of #4348 I was wondering how to exercise voting invitations. For example, can deploy scripts get at offer results from offers approved by the wallet front-end?

[wallet API docs](https://agoric.com/documentation/guides/wallet/api.html#wallet-api-commands) suggest not.

@dtribble answered:
> The answer should be "yes". So if not, that should be added to the wallet API accessible to home.

I'm inclined to see how the demo (#4348) goes before making further plans.

**Comment by dckc** [comment]
> ... can deploy scripts get at offer results from offers approved by the wallet front-end?
> > The answer should be "yes".

and in fact, it is: https://github.com/Agoric/documentation/issues/671 shows how.

**Comment by dckc** [comment]
Voting by Validators is handled by normal cosmos tools (agd, keplr, ...)

For committee members, we know how to do this in at least one case:

 - [README-debtLimit.md](https://gist.github.com/dckc/7733f85be2c25a1a47b639e4b94816ac#file-readme-debtlimit-md)
 - [vote-raise-debt-limit.js](https://gist.github.com/dckc/7733f85be2c25a1a47b639e4b94816ac#file-vote-raise-debt-limit-js)

We also have a WIP demo GUI https://github.com/Agoric/agoric-sdk/issues/3924#issuecomment-1126091670
