### ISSUE TITLE
test-vault intermittent failure

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3365]
I'm seeing occasional failures of `packages/treasury/test/test-vault.js`:

```
bad collateral

  test/test-vault.js:173

   172:
   173:   t.deepEqual(
   174:     vault.getCollateralAmount(),

  vault should hold 50 Collateral

  Difference:

    {
      brand: Object @Alleged: Collateral brand {
        getAllegedName: Function getAllegedName {},
        getDisplayInfo: Function getDisplayInfo {},
        isMyIssuer: Function isMyIssuer {},
      },
  -   value: 69n,
  +   value: 50n,
    }

  › test/test-vault.js:173:5
```

The failures happen under `yarn test -vs test/test-vault.js -m "bad collateral"`, as well as without the `-m` (there are two tests in the file).

@Chris-Hibbert suggested there might be race conditions within the test file. I see a bunch of module-level mutable state that looks suspicious:

```js
let testJig;
const setJig = jig => {
  testJig = jig;
};

const { makeFar, makeNear: makeRemote } = makeLoopback('zoeTest');

/** @type {ERef<ZoeService>} */
const zoe = makeFar(makeZoe(makeFakeVatAdmin(setJig, makeRemote).admin));
```

and especially:
```js

const helperContract = launch(zoe, vaultRoot);

test('first', async t => {
  const { creatorSeat, creatorFacet } = await helperContract;
  ...
```

I know AVA likes to parallelize as much as possible, so I think the presence of a shared `testJig` is dangerous. In particular, I'm guessing the shared `vault` is being updated in parallel by both tests, so any balance measurements will depend upon timing and interleaving.

Who owns this test? @michaelfig @katelynsills @Chris-Hibbert ? Would anyone mind if I changed both test functions to use `test.serial`?

**Comment by katelynsills** [comment]
Feel free to change it to serial. I think @Chris-Hibbert owns the test though

**Comment by Chris-Hibbert** [comment]
The structure of this test pre-dates me, though I've definitely made changes. @dtribble, do you write tests named `first`?

The fact that `helperContract` is built once and used in both tests is very suspicious. It looks like `test.before()` can build a unique copy for each test.
```
test.before('build vault', ot => {
  ot.context.helperContract = launch(zoe, vaultRoot);
})
```
will set up a `helperContract` that can be accessed in each test as `t.context.helperContract`.

**Comment by Tartuffo** [comment]
Seems to be performing as expected.
