### ISSUE TITLE
Wallet transfer support needs to use Nats

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#3368]
## Describe the bug
When sending an amount that would have a `value` larger than Number.MAX_SAFE_INTEGER, the wallet transfer operation fails.

## To Reproduce
1. Spin up the chain. 
2. In the wallet transfer function, send an amount that would correspond to 10^19th units. (e.g., 1Eth or 1T RUN)
 
That would be 1T RUN, but only 1 Eth!

## Expected behavior
The transfer is requested successfully (even if it fails due to not having enough money)

## Platform Environment
 - what OS are you using? what version of Node.js? Node v14.16.0
 - is there anything special/unusual about your platform? NO
 - what version of the Agoric-SDK are you using? @agoric/access-token@0.4.1-31-g3e0692679
 - 
## Additional context
@dckc found this while debugging snapshots

NOTE: I haven't repro'd in my environment, but have verified that bad code path.

**Comment by dckc** [comment]
I also reported this as #3367
