### ISSUE TITLE
Add code owners

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#3382]
## What is the Problem Being Solved?

We need to tell github about codeowners so that bugs and reviews are automatically assigned

**Comment by dckc** [comment]
Ironically, this issue wasn't assigned to anyone.

I'll start the ball moving by nominating folks off the top of my head. @warner or @michaelfig or @katelynsills whenever you find time to move the ball forward a bit more (even by just re-assigning to someone else), I'd appreciate it.

| package | owner(s) |
| --- | --- |
| access-token | @michaelfig | 
| acorn-eventual-send | ??? | 
| agoric-cli | @michaelfig @warner | 
| assert | @erights | 
bundle-source | @warner
captp | @michaelfig
cosmic-swingset | @michaelfig
dapp-svelte-wallet | @samsiegart , @michaelfig 
deployment | @michaelfig 
deploy-script-support | @katelynsills 
ERTP | @katelynsills @erights 
eslint-config | @michaelfig @kriskowal 
eslint-plugin | @michaelfig
eventual-send | @michaelfig @erights 
governance | @Chris-Hibbert 
import-bundle | @warner 
import-manager | ???
install-metering-and-ses | ??? (should die?)
install-ses | @warner @erights 
marshal | @erights 
notifier | ???
pegasus | ???
produce-promise | ???
promise-kit | @warner 
registrar | ???
same-structure | @erights 
sharing-service | ???
solo | @michaelfig @warner 
sparse-ints | ???
spawner | ???
stat-logger | @FUDCo 
store | @FUDCo @warner 
SwingSet | @warner @FUDCo
swingset-runner | @FUDCo 
swing-store-simple | @FUDCo 
tame-metering | ???
transform-eventual-send | @michaelfig 
transform-metering | @michaelfig 
treasury | @Chris-Hibbert 
ui-components | @katelynsills @samsiegart 
vats | @warner @michaelfig 
weak-store | ???
xsnap | @dckc 
zoe | @katelynsills 

Stuff I don't know:

How is this actually configured? I haven't looked up the docs.

Can code have multiple owners?

**Comment by katelynsills** [comment]
Thanks for moving this forward @dckc. I sent Dean a tentative first draft back in June, so I think he has the latest version that he was working on. We should try to find that.

**Comment by michaelfig** [comment]
My request is to reference different `@Agoric/codeowner-SOMENAME` Github teams in the `CODEOWNERS` file so that we can dynamically change them without having to check in a new text file.

**Comment by michaelfig** [comment]
We probably need at least two codeowners per assignment so that one codeowner can get a review from another one.

Here's a sketch I made of `.github/CODEOWNERS` before I saw @katelynsills comment.  Take it as a suggestion for how I think things could be organised by team role instead of naming individuals.

```
# Default code owners when not specified.  We prefer to explicitly specify
# owners for all subdirectories.
* @Agoric/codeowner-default

/* @Agoric/codeowner-tooling # Only files directly contained in the toplevel directory.
/.github/ @Agoric/codeowner-tooling
/docker/ @Agoric/codeowner-tooling
/patches/ @Agoric/codeowner-tooling
/scripts/ @Agoric/codeowner-tooling

# Golang parts of the repo.
/go.* @Agoric/codeowner-golang
/golang/ @Agoric/codeowner-golang

# Explicit owners.
/packages/ERTP/ @Agoric/codeowner-contract
/packages/SwingSet/ @Agoric/codeowner-kernel
/packages/access-token/ @Agoric/codeowner-solo
/packages/agoric-cli/ @Agoric/codeowner-solo
/packages/assert/ @Agoric/codeowner-lib
/packages/bundle-source/ @Agoric/codeowner-endo
/packages/captp/ @Agoric/codeowner-lib
/packages/cosmic-swingset/ @Agoric/codeowner-chain
/packages/dapp-svelte-wallet/ @Agoric/codeowner-dapp
/packages/deploy-script-support/ @Agoric/codeowner-dapp
/packages/deployment/ @Agoric/codeowner-chain
/packages/eslint-config/ @Agoric/codeowner-tooling
/packages/eslint-plugin/ @Agoric/codeowner-tooling
/packages/eventual-send/ @Agoric/codeowner-lib
/packages/governance/ @Agoric/codeowner-contract
/packages/import-bundle/ @Agoric/codeowner-lib
/packages/import-manager/ @Agoric/codeowner-dapp
/packages/install-metering-and-ses/ @Agoric/codeowner-lib
/packages/install-ses/ @Agoric/codeowner-lib
/packages/marshal/ @Agoric/codeowner-lib
/packages/notifier/ @Agoric/codeowner-lib
/packages/pegasus/ @Agoric/codeowner-contract
/packages/promise-kit/ @Agoric/codeowner-lib
/packages/registrar/ @Agoric/codeowner-chain
/packages/same-structure/ @Agoric/codeowner-lib
/packages/sharing-service/ @Agoric/codeowner-chain
/packages/solo/ @Agoric/codeowner-solo
/packages/sparse-ints/ @Agoric/codeowner-lib
/packages/spawner/ @Agoric/codeowner-chain
/packages/stat-logger/ @Agoric/codeowner-kernel
/packages/store/ @Agoric/codeowner-kernel
/packages/swing-store/ @Agoric/codeowner-kernel
/packages/swing-store-lmdb/ @Agoric/codeowner-kernel
/packages/swing-store-simple/ @Agoric/codeowner-kernel
/packages/swingset-runner/ @Agoric/codeowner-kernel
/packages/tame-metering/ @Agoric/codeowner-lib
/packages/transform-metering/ @Agoric/codeowner-lib
/packages/treasury/ @Agoric/codeowner-contract
/packages/ui-components/ @Agoric/codeowner-dapp
/packages/vats/ @Agoric/codeowner-chain @Agoric/codeowner-solo
/packages/wallet/ @Agoric/codeowner-dapp
/packages/wallet-connection/ @Agoric/codeowner-dapp
/packages/xsnap/ @Agoric/codeowner-kernel
/packages/zoe @Agoric/codeowner-contract
```

**Comment by dckc** [comment]
@Tartuffo perhaps while you're organizing MN-1, it would be cost-effective to assign code owners?

**Comment by Tartuffo** [comment]
Ah, this is great!  I'll take this on.

**Comment by Tartuffo** [comment]
We've decided to largely turn off CODEOWNERS until we have a better solution.  There will be one remaining entry for /packages/run-protocol.
