### ISSUE TITLE
Generate unlocking schedules for the Cosmos vesting module

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#3421]
## What is the Problem Being Solved?

The cosmos "vesting" module supports programmatic release of tokens for a given recipient. The unlocking schedule enumerates each release. In order to be able to generate these efficiently and accurately, we need a script that generates that schedule.

**Comment by JimLarson** [comment]
Per our conversation, the script should take the following inputs:

- Total amount (and denomination) to be distributed.
- Number of months the vesting should span.
- Day of month and time of day that vesting should occur.
- Start time of the schedule
- One or more "cliff" dates that delay all vesting before that date.
- Until #3422 lands, anticipated submission time of the schedule.

We should also do the reverse translation of a vesting schedule file back to date strings, given a start time, as a way of checking the results.

**Comment by JimLarson** [comment]
Note, the vesting file format is specified around line 100 in https://github.com/agoric-labs/cosmos-sdk/blob/release/0.43.x/x/auth/vesting/client/cli/tx.go.

**Comment by JimLarson** [comment]
Implemented in https://github.com/agoric-labs/cosmos-sdk/pull/69
