### ISSUE TITLE
Use `Fatalf` when Golang tests should abort

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#3425]
Make this `Fatalf` then - if we get here then `gotMsg` and `gotNonce` are likely garbage and we shouldn't compare further.

_Originally posted by @JimLarson in https://github.com/Agoric/agoric-sdk/pull/3423#discussion_r659394679_

**Comment by ivanlei** [comment]
Fixed by @michaelfig in #3435
