### ISSUE TITLE
ERTP: should we add a "destroyLedgerWithFailure"?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#3434]
Currently, this is adequately explained by the inline TODO comment at https://github.com/Agoric/agoric-sdk/blob/30290bf85427fced63b54707b2ae8297773f6972/packages/ERTP/src/paymentLedger.js#L34 from PR #3287 

```js
  const destroyLedgerWithFailure = reason => {
    // TODO destroy ledger state.
    // We need to defensively destroy the ledger state because:
    // If the `optTerminateWithFailure` is absent or returns,
    // the most violent termination we can fall back to is to throw. However,
    // by itself, a throw does not make the ledger state unreachable. Just in
    // case both
    //   * optTerminateWithFailure returns
    //   * the ledger was still reached after it was may have been corrupted
    // we must ensure that the corrupted state it was left in cannot be
    // mistaken for working state.
```

Made into issue as suggested at https://github.com/Agoric/agoric-sdk/pull/3287#discussion_r661043299

**Comment by katelynsills** [comment]
This feature has been removed entirely and instead, the function `optShutdownWithFailure` is used, for example, to shutdown the vat. I'll edit the issue to ask whether the feature is still a TODO.

**Comment by erights** [comment]
Given the shift to `optShutdownWithFailure` and #3287 , I'm closing this as fixed.
