### ISSUE TITLE
vbank balance updates might take too long to process

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3461]
## What is the Problem Being Solved?

A casual look at the testnet-phase4 ("stress test") slogfile corpus suggests that vbank balance updates (sent from the cosmos-sdk `Bank` module up to swingset and `vat-bank`) may take a considerable amount of time to process. During the testnet, several participants contributed cosmos-level load by transferring tokens to a large (1000s) of new addresses. The Bank module announces all these balance changes to swingset, most of which are ignored because the addresses were not registered (so no `Notifier` exists to be updated), however the time it takes to do that is non-trivial.

The task is to study this corpus and work out the timing relationship between the number of balances being updated and the runtime required by the update messages. Then we should look for ways to improve that runtime:
* improve the efficiency of the processing somehow
* avoid sending messages for unregistered addresses (which would require tracking the registered/unregistered state on the cosmos-sdk Bank module side)
* spreading the messages out across a larger span of time
  * the number of balances mentioned in each message
  * maybe somehow taking advantage of the upcoming escalator scheduler to allow the updates to be interleaved among higher-priority messages

cc @michaelfig @JimLarson

**Comment by Tartuffo** [comment]
@JimLarson This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract.  Or, if this is accurately labeled by an area label we should be covering in one of our weekly meetings, please LMK.

**Comment by JimLarson** [comment]
@warner this ticket, and any data that might have inspired it, are 7 months behind the current product. Is the troublesome scenario covered by our current load tests?

**Comment by JimLarson** [comment]
Waiting to hear whether we have data on this still being a problem or not. Adding an estimate for design-only for coming up with a plan for filtering the notifications to just the interested parties.

**Comment by Tartuffo** [comment]
This is a duplicate (in terms of underlying cause and needs for fixing) as https://github.com/Agoric/agoric-sdk/issues/3629
