### ISSUE TITLE
Txn Gas - implement fees to cover end-to-end at all levels

### ISSUE THREAD

**Issue by JimLarson** [Agoric/agoric-sdk#3466]
## What is the Problem Being Solved?

Per 2021-07-07 kernel/swingset meeting.

Need mechanisms at all levels to provide E2E flow control, DoS prevention.

We have fees once we hit the kernel escalator queues, but we need to cover the steps before then.

Compared to Ethereum and Cosmos, we have much more of a delayed cost.

**Comment by dckc** [comment]
overtaken by #3752 (and perhaps #3764 )
