### ISSUE TITLE
Mempool flow control

### ISSUE THREAD

**Issue by JimLarson** [Agoric/agoric-sdk#3467]
## What is the Problem Being Solved?

Per 2021-0707 kernel/swingset meeting.

We've seen the mempool fill up with 5K pending entries. Need some backpressure, especially E2E backpressure from swingset escalator. Must pay at least median fee of what's on the queue.

For admission to mempool, must have a cosmos account with a `urun` balance.

**Comment by dckc** [comment]
#3944 is merged but SwingSet doesn't use it yet. @mhofman does this look close to scheduling stuff that you're thinking about?

**Comment by dckc** [comment]
@Tartuffo closed this based on @michaelfig noting we charge for messages. @warner expressed some questing about adaptive back-pressure. @Tartuffo agreed to set up a meeting to discuss.
