### ISSUE TITLE
Rename cosmos-sdk "vesting"

### ISSUE THREAD

**Issue by JimLarson** [Agoric/agoric-sdk#3469]
## What is the Problem Being Solved?

The term "vesting" describes a change of ownership over time and is subject to "clawback" of the unvested property. The cosmos-sdk vesting accounts more properly implement "lockup" - a release of restrictions over time but with the same ownership, and where locked tokens can still be used, e.g. for staking or liens, just not transferred.

This is a known and long-standing bug in cosmos-sdk.

## Description of the Design

Rename "vest" and "vesting" throughout namespaces, filenames, command names, documentation, etc. Some conversions might be:

- unvested --> locked
- vested --> unlocked
- vesting --> lockup

Might need to retain deprecated API entry points for compatibility for a while, including command-line tools.

**Comment by Tartuffo** [comment]
@JimLarson Is this done?

**Comment by JimLarson** [comment]
We never pulled the trigger on this, since it's such an extensive change.

We might be able to address this as part of upstreaming our clawback vesting work, depending on how large of a refactoring makes sense for the existing code.

Covered by Cosmos issue [#10662](https://github.com/cosmos/cosmos-sdk/issues/10662)

**Comment by ivanlei** [comment]
This is an antique plan lost to the sands of time.

**Comment by JimLarson** [comment]
Coincidentally, yesterday they noted in the upstream Cosmos issue that this will be addressed in their next release. They are renaming "vesting" to "lockup". That wording might have come from our involvement in the Auth working group.
