### ISSUE TITLE
Off by one blockHeight in slog for genesis block

### ISSUE THREAD

**Issue by mhofman** [Agoric/agoric-sdk#3470]
## Describe the bug
When starting a node with a genesis block at a specific `blockHeight`, the slog file contains 2 `cosmic-swingset-end-block` sections (`start` to `finish`) for the initial block (e.g. `15425` for the first restart of testnet phase 4).

It seems that first section contains the reactions to the vat replay, and the second has the first cosmos driven deliveries, so the first section should be numbered differently.

## To Reproduce
1. Create a genesis from an existing chain state.
2. Start a node from that genesis
3. Let the chain start producing blocks

## Expected behavior
No duplicate block numbers in slog files

## Platform Environment
N/A

## Additional context
Observed in all slogs for node starting at genesis collected during testnet 4.

## Screenshots
```
{"time":1624681768.567772,"type":"cosmic-swingset-end-block-finish","blockHeight":15425,"blockTime":1624734000}
{"time":1624734002.3602827,"type":"cosmic-swingset-begin-block","blockHeight":15425,"blockTime":1624734000}
{"time":1624734002.4302108,"type":"cosmic-swingset-end-block-start","blockHeight":15425,"blockTime":1624734000}
```

**Comment by michaelfig** [comment]
This is a relic of how Cosmos SDK reports block heights, and how `golang/cosmos/x/swingset/genesis.go` initialises the chain.  When the chain uses a non-zero `initial_height`, then the `InitGenesis` happens before any network activity via a synthetic `END_BLOCK` message (and the Cosmos SDK reports the block as the `initial_height` while that is happening), then when the voting happens, the Cosmos SDK reuses the same height as the actual `BEGIN_BLOCK` and `END_BLOCK`.

`initial_height` of `"0"` is special-cased in the SDK.  For that, the `InitGenesis` happens at height `"0"` and the first consensus block is height `"1"`.

The correct fix is probably to introduce a different message type for the block manager to use, say `INIT_GENESIS`.  That would be sent to run the kernel to complete bootstrap before any network activity.  Then the next consensus block would report the same `initial_height`, but the previous work could be ignored if you only care about the following `BEGIN_BLOCK`/`END_BLOCK`.

@warner, opinions?
