### ISSUE TITLE
Treasury returns funds to borrower in offerResult

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3497]
## Describe the bug

Treasury (`vault.js`) returns leftover RUN to the borrower after the loan is closed in a promise in the offerResult. Any RUN that needs to be returned should just  be in the payout.

## Expected behavior

test `price drop` in `test-stablecoin.js` [shows the issue](https://github.com/Agoric/agoric-sdk/blob/006d030974a4ce6475d2fe9f3b4406c66702d442/packages/treasury/test/test-stablecoin.js#L381). `liquidationPayout` shouldn't be necessary. Those funds should be included in the seat payout.

## Additional context

#3495

We should use a local `emptySeatKit` in `closeHook()` rather than using the shared `vaultSeat` for transferring the runDebt.

**Comment by Chris-Hibbert** [comment]
When `close()`ing a loan, the leftover `RUN` is returned in the payout of the close seat. The promise in the offerResult for the `openLoan()` call is used only for proceeds from liquidation. Since liquidation is unsolicited, there's no corresponding seat through which to return any proceeds.  

The original seat from the `openLoan()` seat is closed when the loan proceeds are returned. It wouldn't do any good to keep the seat open, since the proposal specifies the amount of the requested loan. The contract can't reduce that amount later, so the seat is obsolete at that point.

I don't think we can make the GC issue that @warner was running into go away as simply as we'd hoped.

**Comment by katelynsills** [comment]
> leftover RUN is returned in the payout of the close seat. The promise in the offerResult for the openLoan() call is used only for proceeds from liquidation.

I think I'm missing something here. Is there something that would stop us from giving the proceeds from liquidation through a seat? A better pattern would be to have the user get an extra invitation to get their liquidation proceeds, and then get paid through the normal payout process. 

But we might not need a new invitation, if the seat in the closeVault offerHandler can do double-duty. Can we talk through why either of these options (the closeVault seat, or a new liquidation proceeds seat) doesn't work?

**Comment by katelynsills** [comment]
I'm going to take myself off as an assignee. @Chris-Hibbert  and I discussed how another invitation could be made specifically for paying out the liquidation proceeds, and how another invitation (adjustBalances, closeVault) could be used for paying out the liquidation proceeds as well their normal uses.
