### ISSUE TITLE
[agoric-cli] Simplify dependencies on ERTP and Zoe

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#350]
`agoric-cli` depends on ERTP and Zoe for two uses:

1. The `package.json` in `packages/agoric-cli/template/contract/package.json` that gets copied in the user's directory needs ERTP and Zoe to allow the user to write and run Zoe contracts.
2. The latest Zoe contracts are used as examples for the user.

I'm a little worried that when I release a new version of Zoe, agoric-cli will not be updated properly. There are a couple of things that make this difficult:

1. `packages/agoric-cli/template/contract/package.json` as written is a malformed `package.json` since it has a magic string (-@DIR@-) that gets replaced. Because it's malformed, I can't use `yarn add @agoric/zoe` or any automatic command. It has to be manually updated, which seems prone to error.
2. Even though `packages/agoric-cli/template/contract/package.json` depends on ERTP and Zoe, `packages/agoric-cli/package.json` does not, which hides the dependency. This means automatic checks and things like Brian's dependency charts will miss this dependency. 
3. As the Zoe contracts are updated, the versions that users get as examples must be manually copied over, which will likely be forgotten. 

I talked through these solutions with Brian:

1. ERTP and Zoe could be dependencies of `packages/agoric-cli/package.json`, and `packages/agoric-cli/template/contract/package.json` could be built automatically from  `packages/agoric-cli/package.json` and not checked in.
2. Before `agoric-cli` is published to npm, a build step could be to copy over all of the files in `@agoric/zoe/contracts` into an `examples/` folder that is included in the `npm pack` step as the published version. Then when the user calls `agoric init` and goes through the process of creating their own demo directory, those example contracts are copied. 

@warner Is this everything?

@michaelfig What do you think?

**Comment by michaelfig** [comment]
Sounds reasonable... I am more than willing to review a PR that does this, but I will probably not get to implementing new features in agoric-cli until the new year.

**Comment by katelynsills** [comment]
Ok great! I can take the first stab at this

**Comment by katelynsills** [comment]
I think this is stale. Closing.
