### ISSUE TITLE
Governance-controllable RUN debt-limit per collateral type in Vault Factory & getRUN contract

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3501]
## What is the Problem Being Solved?
Allow governance to set and modify a cap to the amount of RUN that may be issued against a *specific* collateral type (vaults AND getRUN).

Attempts to mint additional RUN beyond the debt limit cap should fail
UIs should be able to show a user before attempting to make a transaction if it would fail for this reason

## Description of the Design
Parameter that gives a total limit - per collateral type - of the RUN that is available to be minted.  Any attempts to mint RUN which would go above the limit for that collateral type should fail.  

However, other functions on a vault which *do not* increase RUN should succeed (i.e., even if we have surpassed the debt limit on the collateral for my vault, I should be able to perform vault actions like closing vault or adding collateral, which do not increase the debt)

Limit needs to be adjustable by governance

**Comment by rowgraus** [comment]
This ticket is specific to a total debt limit per collateral type.  We may choose to implement a rate limit as well and this design should be upwards compatible with that.

Initial proposed design: A wrapper on the ZCF mint adjustable with governance

Notes from discussion:
* Overall goal: limit the RUN debt outstanding vs. a given collateral type
* Could be implemented as a wrapper around the RUN mint
* For accounting purposes, need an accurate view of RUN outstanding (RUN minted - RUN burned).  Treasury will be burning RUN to pay down debt

Question:
* How does this interact with burning RUN -> implications of doing this on a per-collateral basis
* Does normal API of mint need to include the ability to find out the amount outstanding?  Does this work with NFTs.  Can give the aggregate total for all the amounts
* How tightly coupled to Zoe do we make the ability to find out the amount of RUN outstanding

**Comment by Chris-Hibbert** [comment]
Discussion at the Zoe meeting today considered the possibility of adding the limitations at the mint layer, but concluded that introducing governance control into ERTP is probably a mistake.  

Given current designs, it appears that adding library support in governance for managing limitations on how much the fee purse can issue in each contract instance.

**Comment by rowgraus** [comment]
Notes from conversation: 
UI should be able to display the debt limit and not allow user to take an action which would fail.
Once we have gotten over the debt limit, no further RUN can be borrowed

**Comment by Chris-Hibbert** [comment]
@samsiegart  Can the UI calculate this based on the information they currently get from the contract?  If not, what additional info is needed, and which channels would be convenient for this?  What state changes should prompt new updates?  If this represents changing state in the contract, I'd expect to use a Notifier or Subscription to feed the UI.  
@turadg

**Comment by samsiegart** [comment]
> @samsiegart Can the UI calculate this based on the information they currently get from the contract?

I think so. These are the terms we can get from the contract https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/src/runLoC.js#L17-L22, and this is what we can get from the UI notifier https://github.com/Agoric/agoric-sdk/blob/dc-run-loc/packages/treasury/src/runLoC.js#L72-L77. Debt limit should be able to be derived from those.

**Comment by Tartuffo** [comment]
@turadg We need an estimate for this.

**Comment by turadg** [comment]
@Tartuffo done. 1 for change and 1 for test

**Comment by rowgraus** [comment]
Note, from other issue (now closed): When we are over debt limit, users should still be able to perform normal vault functions *other* than taking out more debt.  Top level ticket description modified to reflect this

**Comment by turadg** [comment]
Reopening to do the same for RUNStake cc @dckc

**Comment by Tartuffo** [comment]
@samsiegart + @rowgraus  please create a new ticket for the UI side of this.
