### ISSUE TITLE
Governance facet for the allowed assets in the Treasury

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3502]

**Comment by Tartuffo** [comment]
@rowgraus @Chris-Hibbert After various meetings, this ended up with a MN-1 tag *AND* in the Product Backlog pipeline.  Please modify appropriately for what it should actually be.

**Comment by Chris-Hibbert** [comment]
I think this stands for the ability of Governance to add new assets that Vaults will accept as collateral. If so, it should be in Mainnet 1. It already has the label, so I'm moving it to that pipeline.

**Comment by Tartuffo** [comment]
@Chris-Hibbert We need an estimate for this Restival ticket.

**Comment by Tartuffo** [comment]
Closed in favor of #3924.
