### ISSUE TITLE
Why do these method names begin with upper case?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#3503]
https://github.com/Agoric/agoric-sdk/blob/4a72860f7213f9c2acf93a0db6e960e7c4a4c48d/packages/treasury/src/vaultManager.js#L235-L236

**Comment by katelynsills** [comment]
It's part of the semi-standard invitationMaker pattern. This pattern is going to change in the near future, so we haven't documented this pattern for that reason, but you can see its usage here: https://github.com/Agoric/agoric-sdk/blob/4a72860f7213f9c2acf93a0db6e960e7c4a4c48d/packages/dapp-svelte-wallet/api/src/findOrMakeInvitation.js#L78

The new pattern is that the wallet gives a proxy-like object to the dapps which the dapps can call directly. When a dapp calls a method like `makeInvitation` on the object, the wallet (and therefore user) can decide whether they want the call to be passed onto the real object within the wallet. 

I think we can close this issue.

**Comment by erights** [comment]
Thanks
