### ISSUE TITLE
Zoe needs synchronous access to a timeAuthority

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3516]
In order for Zoe to translate a fee quote from relative terms to absolute terms just in time, and in order to know whether a given quote has expired, Zoe needs synchronous access to a timeAuthority.

[TODO: fill in more details re: why Zoe needs synchronous access and asynchronous access won't do]

**Comment by zarutian** [comment]
Hmm... is it just the hasExpired check that needs this or is there more to it?

As someone who had looked way too much into game netcode, I want to point out that _now_ is rather streachy. This means that given a timeAuthority is always some round trip delay away timewise.

I imagine that Zoes current usage of a [timeAuthority](https://github.com/Agoric/agoric-sdk/blob/master/packages/cosmic-swingset/TimerService.md) is something like this:

```js
const nowP = E(timer).getCurrentTimestamp();
const now = await nowP;
if (quote.expiry < now) {
  // reject the quote
}
```

What we might need is something like
```js
/**
 * @callback lessThanNow
 * @param {timeStamp} timestamp
 * @return {boolean}
 */
 /**
  * @callback greaterThanNow
  * @param {timeStamp} timestamp
  * @return {boolean}
 */
/**
 * TimerService
 * @prop {lessThaNow} lessThanNow
 * @prop {greaterThanNow} greaterThanNow
 */
const expiredP = E(timerService).greaterThanNow(quote.expiry);
const expired = await expiredP;
if (expired) {
  // quote expired, reject it
}
```

**Comment by katelynsills** [comment]
This may not be the case. Closing for now until this becomes an issue again

**Comment by zarutian** [comment]
I am wondering if it is time to [update](https://gist.github.com/zarutian/b457a10b27e136532d331a32c25fcce1) timerService?

**Comment by katelynsills** [comment]
Wow this gist looks extensive! I'd love to include this kind of work, but I could use some help understanding it. If you would like, could you write up an issue of what needs to be changed in your opinion + a PR for this? 

> I am wondering if it is time to [update](https://gist.github.com/zarutian/b457a10b27e136532d331a32c25fcce1) timerService?
