### ISSUE TITLE
Deploy script for Validators to vote in JS

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3553]

**Comment by Tartuffo** [comment]
@Chris-Hibbert This is in the "Up Next" pipeline, but does not have a MN-1 label.  If it is needed for MN-1, please label, otherwise move from "Up Next" to "Product Backlog".  I'm asking because I want "Up Next" to really reflect the things we plan to work on for MN-1.

**Comment by Chris-Hibbert** [comment]
@rowgraus  can we close this? If not, please add more detail.

**Comment by Tartuffo** [comment]
Moving this to MN-1 Backlog.  @rowgraus please close if done.

**Comment by ivanlei** [comment]
Not current plan of record.
