### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by taquila123** [Agoric/agoric-sdk#3568]
## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by zarutian** [comment]
Oy! Ya forgot to fill in the form, ya know.

**Comment by zarutian** [comment]
Common, my metaphorical ears are sun burning from being agog. What is the bug?

**Comment by katelynsills** [comment]
Thanks for shepherding this @zarutian. I think we can close this as irrelevant.
