### ISSUE TITLE
add run-policy to cosmic-swingset

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3582]
## What is the Problem Being Solved?

Once #3459 is done, we hope to have an idea of what sort of computron limit to apply to each block. Once #3580 has landed, we'll have a way to apply it. At that point, the task will be to update cosmic-swingset:
* create a `computronCounter` run-policy object at the beginning of each cycle
* use `c.run(policy)` instead of the current `for()` loop that calls `c.step()` some maximum number of times

For the solo machine, we can either leave the existing mechanism in place (drain the queue each time), or add a `wallClockWaiter` to limit the work-until-commit duration to something like 2-5 seconds.

## Test Plan

I think this will have to be tested manually, with a load generator cranked high enough to cause the run-queue to remain full for a while.

**Comment by dckc** [comment]
> Once #3459 is done, we hope to have an idea of what sort of computron limit to apply to each block.

[Examination of one busy block](https://github.com/Agoric/agoric-sdk/issues/3459#issuecomment-892186890) suggests an **8-10M computron** limit.

**Comment by dckc** [comment]
@warner you mentioned making the threshold configurable via governance. Is that required?

_p.s. no, not required, from discussion with @michaelfig._
