### ISSUE TITLE
Complete the end to end of ATOM/USD price feed

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3595]
Taken and edited from: https://github.com/Agoric/agoric-sdk/issues/3595#issuecomment-1072706254

We do not presume economy (vaults / AMM) but `startPriceAuthority` in bootstrap populates home.priceAuthority with a price authority registry.

User bob wants to know the price of ATOM in our system.

NodeCoordinator submits a proposal to BLDer DAO, who approves:
- instantiating aggregator contract with ATOM-USD oracle brands (`E(home.agoricNames).lookup('oracleBrand', 'ATOM')` and `E(home.agoricNames).lookup('oracleBrand', 'USD')`)
- adding aggregator priceAuthority to the price authority registry for ATOM-USD pair
- sending oracle invitations to NodeOp1's and 2's deposit facet

NodeOp1 registers an oracle node with the aggregator:
- NodeOp1 deploys oracle handler plugin
- NodeOp1 runs flux-notifier script to create fluxNotifier and use oracle invitation to register it with the aggregator

So bob can get a price:
- Bob submits a price query to home.priceAuthority
- NodeOp1's oracle plugin polls the price, reports it to the aggregator
- Likewise NodeOp2..N.
- Aggregator computes price and publishes via home.priceAuthority

**Comment by dckc** [comment]
@michaelfig tells me this is pending availability of oracles.

p.s. The Pegasus contract has been imported into agoric-sdk.  `dapp-pegasus` is just a placeholder for when we have a Pegasus UI.

p.p.s. search keyword: IBC

**Comment by Tartuffo** [comment]
Need to get this into good enough state to be handed over to Oracle providers.

**Comment by dckc** [comment]
interviewed @michaelfig to get a story:

do not presume economy (vaults / AMM)
but `startPriceAuthority` in bootstrap populates home.priceAuthority

User bob wants to know the price of Atom in our system.

NodeCoordinator who installs aggregator contract, oracle contract. (proposes to BLDer DAO, who approves...)
Proposal includes adding price authority for Atom/USD from aggregator to the price authority registry.

NodeCoordinator uses creator facet to get invitations; hands out to NodeOp1 and 2 via deposit facet.

NodeOp1 deploys script that uses invitation to register themselves with the aggregator.

atom/USD aggregator is registered with home.priceAuthority
So bob can get a price:
NodeOp1 puts finger in wind, chooses 23 USD/Atom as a price, uses registered widget to submit price.
Likewise NodeOp2..N.
Aggregator computes price.

**Comment by michaelfig** [comment]
End-to-end is done as described.
