### ISSUE TITLE
Combined coercion and test may not do what you expect

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#36]
https://github.com/Agoric/SwingSet/blob/350516d97a28e0d32c5cefe261c27a20a47a5639/src/kernel/liveSlots.js#L235

At the top of a proxy handler `get` trap:

```js
        if (`${p}` !== p) {
          return undefined;
        }
```

where `p` is the property name. I think, but haven't checked, that by the time a property name gets to the `get` trap it has already been coerced to a string or symbol. If `p` is a string, the test will always fail, i.e., the two operands will be the same. If `p` is a symbol, the coercion will always throw. Under no circumstances will this return `undefined`, unless the `get` traps is invoked by something other than the proxy trapping mechanism.

When is it intended for this code to return `undefined`?

**Comment by erights** [comment]
Hi @warner I suspect you already fixed this and can close it out. Yes?

**Comment by warner** [comment]
probably, and in any case this ticket is really stale.. closing it
