### ISSUE TITLE
prototype caching/construction of bundles on filesystem

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3609]
## What is the Problem Being Solved?

We have a lot of generated bundles in our system. Within swingset itself, we've got the main kernel bundle and a pair (SES/lockdown and a supervisor) for `xsnap` instances. Swingset has a number of "system vats" (timer, vat-admin, comms) which are used in most every application. Zoe has ZCF. All of our main contracts (treasury, etc) have a contract bundle.

All of these start as an entry-point file (with some default export), which then references plenty of others via `import` statements. They get converted into a serializable "bundle" artifact via the `bundleSource()` tool. They then take various pathways into the code, but all wind up as the argument of an `importBundle()` call.

During unit tests, we generally run `bundleSource()` as late as possible, during the individual test program, so that any code changes are incorporated into the test's execution. We mostly avoid requiring a distinct "build" step because of the expensive confusion incurred by forgetting to run it ("I'm changing my code but it doesn't have any effect!").

But bundling the source takes a long time, nearly 3 seconds for the full set of kernel bundles (it took significantly longer when we were applying the metering transform too). I've changed a lot of kernel tests to make these bundles in a `test.before` block (amortized among all tests in the same file). The Zoe tests resorted to a separate `yarn build` step (included in `yarn test`) to make it faster: this is one of the few cases where the bundle is written to disk, and imported/read by each test which needs it, rather than being built in only in RAM.

After doing some measurements to see whether it's currently justified or not, what I'd like to consider is a `make`-like tool to generate the bundles on-demand but keeps them on disk, with intelligent dependency checking to avoid rebuilds unless necessary. The hope would be to construct each bundle exactly once per code change, removing the overhead when iterating on a test that doesn't change the files that make up the bundle.

It's possible that the new Endo zipfile-based bundler will be faster than `rollup`, making this unnecessary. On the other hand it might be slower.

cc @kriskowal 

## Description of the Design

I'm thinking about something like:

* `bundleSource` exports a function that takes an entry point filename and an output bundle filename, and returns a Promise for a bundle object
  * despite the shared written-bundle location, it is safe to call this function simultaneously from multiple (parallel) AVA tests
* the function will use the output bundle file (and a couple of related+nearby files) to coordinate simultaneous callers
  * if instance 1 is first on the scene, it will leave a marker to claim the construction process
  * all other instances will recognize the marker and wait for instance 1 to finish building the bundle
  * the marker might be a file (some sort of exclusive-open thing) or a named pipe through which the subsequent instances can talk to the builder
* the first time the bundle is built, the bundling process will keep track of all the files it looked at to generate the bundle
  * this probably needs to include pathnames it examined and found missing, if that can influence the build
  * when the bundle is created, the builder also writes an auxilliary "dependencies" file with the full list of examined pathnames and their hashed contents and/or timestamps (or a special "did not exist" marker)
* if the tool is asked to build a bundle and sees the file already present, it instead reads the dependencies file, and checks to see whether they've changed
  * if nothing has changed, the pre-existing bundle is used as-is
  * if anything has changed, the bundle is reconstructed
* changing source files during the bundling process will cause corruption, but the same was true before 

## Security Considerations

If the construction process is sound, this shouldn't change the security properties of the generated bundle at all.

## Test Plan

Unit tests that involve touching and modifying files on disk, while calling the bundling function multiple times in parallel.

**Comment by dckc** [comment]
yesterday @turadg stubbed his toe pretty badly on this one

**Comment by turadg** [comment]
The problem statement resembles what is often solved by "incremental builds". https://github.com/lerna/lerna/issues/1946 explores incremental build tooling with Lerna. There's an abundance of tools that support a DAG of packages (e.g. Nx, Rush, Turborepo) so I think that'd be a good step forward.

The bundle files are basically build artifacts of the packages containing the corresponding contract. Right now the building concern is mixed across packages. E.g. https://github.com/Agoric/agoric-sdk/commit/ad1e0430bbe378e2922613b55a59e63f65cf5def#diff-70acae73c5220a7f854d1099ba67b86af0928b9c41083995335d551b30147c74 in `@agoric/run-protocol` has 4 bundles from `@agoric/governance`. If we cleaned up the package boundaries, existing tooling could detect when the assets have to be rebuilt.

If we get the package DAG clean we can some of the monorepo build tools and get other benefits. So here's a rough proposal:

1. move all contracts into a consistent path, like `src/contracts`
2. create a simple command that bundles each file in `src/contracts` into a bundle with a conventional name. e.g. `src/contracts/someFoo.js` bundles as `dist/contracts/bundle-someFoo.js`.
3. update tests to build their local contracts and rely on artifacts for contracts from other packages
4. refactor packages to eliminate cyclic dependencies that block incremental build of package graph
5. adopt a monorepo build tool

Reaching step 3 I think would solve the problem I ran into. And taking this approach would open up further optimizations like cloud asset caching.

**Comment by dckc** [comment]
I like most of the plan, but I doubt moving everything to start with is cost-effective. For example, the kernel bundle is not a contract. I'd rather have something in `package.json` that enumerates the bundle sources than a conventional path.

**Comment by turadg** [comment]
Today @warner and I both ran into a CI failure that didn't happen locally until we ran `yarn build`. There was no indication that that was necessary. Ideally the local tests would know when built assets under test are stale.

In the meantime a good practice is to `yarn install && yarn build` at root when the system is behaving unexpectedly.

**Comment by dckc** [comment]
`agoric start` spends about 25 seconds before "Launching SwingSet". I think this is dominated by bundling the kernel and vats. So good safe caching would make my life a _lot_ easier as I'm doing a lot of integration testing. It would also help with DevEx for dapp devs.

```
% agoric start dev --reset -v
...
2022-02-10T02:46:54.910Z ag-solo: init: ag-solo initialized in dev
...
2022-02-10T02:47:19.234Z launch-chain: Launching SwingSet kernel
```

**Comment by turadg** [comment]
Another way to reduce the time waiting is to make the builds much faster. @kriskowal is build speed optimization or benchmarking on the Endo roadmap?

**Comment by kriskowal** [comment]
@turadg, Yes, we can thread a cache through `bundle-source` and continue allowing the machinery behind that to build the dependency graph for cache keys and invalidation. This issue tracks that work.

**Comment by dckc** [comment]
#5123 includes a prototype of bundle caching (#3609). I started The Right Way, in `@endo/bundle-source` with `tool.js`. That worked for command-line usage. But then I wanted to use it within tests. To avoid endo releases in the iteration cycle, I copied the code to agoric-sdk as `packages/run-protocol/test/bundleTool.js`.

The prototype lacks tests. @michaelfig found a failure mode where bad metadata gets written if some expected files are missing.

And I think it has limitations around relative / absolute / package-relative path handling.

**Comment by dckc** [comment]
The diagnostics in the `run-protocol` prototype are evidently not good enough. For example:

```
Error: Archive failed sanity check: should contain at least a compartment map file and one module file.
```

was what we got for a filename collision (1 bundle filename was being used by 2 different contracts).

I suspect this was some form of safety failure. Part of the diagnosis was finding meta files with empty contents.

**Comment by michaelfig** [comment]
The failure mode I observed with @dckc was that if the entrypoint file (root) of the bundle was nonexistent, a mostly-empty zip file was written without an error.

**Comment by dckc** [comment]
@dtribble notes a possible interaction with `ava watch`: if a bundle is `import`ed, and the bundle is re-built by one test, the `import`ing test will get triggered.

**Comment by warner** [comment]
> The failure mode I observed with @dckc was that if the entrypoint file (root) of the bundle was nonexistent, a mostly-empty zip file was written without an error.

Yeah, that's #5713 , which is actually https://github.com/endojs/endo/issues/1206 , and needs Endo changes to get fixed.

**Comment by Tartuffo** [comment]
Closing this, as we've done the critical work for launch.  @dckc please talk with @warner if you disagree.

**Comment by dckc** [comment]
I updated the title to reflect that what we/I built is a prototype that is known to be not completely safe.
