### ISSUE TITLE
Remove internal Zoe docs and provide updated documentation

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3616]
The current internal documentation in Zoe (https://github.com/Agoric/agoric-sdk/tree/master/packages/zoe/docs) is outdated. In the interests of clarity, I would like to remove the outdated docs and supplement later with additional, updated documentation.

**Comment by dckc** [comment]
tab dump from brainstorm with @erights and @Chris-Hibbert 

Reasoning about Risk and Trust in an Open World - Agoric: https://papers.agoric.com/papers/reasoning-about-risk-and-trust-in-an-open-world/abstract/
reasoning-about-risk-and-trust-in-an-open-world.pdf: https://papers.agoric.com/assets/pdf/papers/reasoning-about-risk-and-trust-in-an-open-world.pdf
Zoe Contract Facet | Beta: https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcfmint-mintgains-gains-zcfseat
agoric-sdk/types.js at cdf58e696bca3e662d876212d86bad68b3e47c10 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/blob/cdf58e696bca3e662d876212d86bad68b3e47c10/packages/zoe/src/contractFacet/types.js#L156
TypeScript + JSDoc = better-docs. better-docs was created as a simple… | by Wojciech Krysiak | Medium: https://wojciechkrysiak.medium.com/typescript-jsdoc-better-docs-7c03b6ea04df
microsoft/tsdoc: A doc comment standard for TypeScript: https://github.com/microsoft/tsdoc
TSDoc: https://tsdoc.org/
How to use with npm run · jsdoc2md/jsdoc-to-markdown Wiki: https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-use-with-npm-run
Unable to parse function receiving a functions array · Issue #198 · jsdoc2md/jsdoc-to-markdown: https://github.com/jsdoc2md/jsdoc-to-markdown/issues/198
agoric-sdk/internal-types.js at cdf58e696bca3e662d876212d86bad68b3e47c10 · Agoric/agoric-sdk: https://github.com/Agoric/agoric-sdk/blob/cdf58e696bca3e662d876212d86bad68b3e47c10/packages/zoe/src/contractFacet/internal-types.js#L20

## jsdoc-to-markdown evaluation: no free lunch

https://gist.github.com/dckc/c07949615815d483d5749b94c2ce3729
