### ISSUE TITLE
Update moduleFormat so that `require` is not needed as an endowment

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#362]
There is a suspicious `require` endowment needed in:

_Posted by @erights in https://github.com/Agoric/agoric-sdk/pull/355_
> `const zoe = makeZoe({ require });`

As @michaelfig says below, when we upgrade the moduleFormat, we should not need to pass `require` anymore.

**Comment by michaelfig** [comment]
`require` under SwingSet on SES is a crafted endowment to give access to `@agoric/harden` and `@agoric/evaluate` with specific exports.  It is safe in that context.

This will change when we migrate our `moduleFormat` from `getExport` to something else, dropping the need for the endowment in exchange for per-module globals instead.  This is part of a wider design that still needs approval and implementation.

**Comment by katelynsills** [comment]
@erights does this need to stay open or can we close it given Michael's answer?

**Comment by dckc** [comment]
Is the change @michaelfig refers to captured in an open issue? I'd prefer to see that before this is closed.

**Comment by michaelfig** [comment]
Let's not close this yet.  I'll remember to reference this issue when we start discussing least-authority linkage formats.

**Comment by warner** [comment]
This will be fixed by the new-SES PR (#1201), and it changes all occurrences of `makeZoe()` with the `evaluate`-less one.

**Comment by warner** [comment]
This landed, and `makeZoe()` no longer needs a `{ require }` endowment. It has code to tolerate its presence, but I removed it from all the instances I could find (including the three off-repo dapps).

Apart from @michaelfig 's least-authority linkage format question, I think the remaining issue here is that `importBundle` must still provide a `require` to the code created by `bundleSource`, even if that code does not have have an "external" items left to `require()`. We still `require('@agoric/harden')` in a lot of code, but if/once #1214 changes that, then our vat and contract bundles should not have any `require` needs anymore, and I'd like to change `importBundle` to stop providing the `require` endowment.

So I think this task now lies within `bundle-source`, not Zoe, so I'm going to assign it to @michaelfig as the owner of that package.

**Comment by warner** [comment]
@michaelfig did you change `bundle-source` to not emit bundles that need `require` yet? I just ran a test in which swingset no longer provides a `require` endowment to vat code, and it failed:

```
UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
    at getExportWithNestedEvaluate (/bundled-source-preamble.js:106:39)
    at importBundle (/home/warner/stuff/agoric/agoric-sdk/packages/import-bundle/src/index.js:57:45)
    at loadStaticVat (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/src/controller.js:187:25)
    at async buildVatController (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/src/controller.js:231:23)
    at async Test.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/test/test-controller.js:28:22)
```

I think this was closed in error.. I'll reopen it. I think we need that bundle-source fix before we can close it.

**Comment by michaelfig** [comment]
> @michaelfig did you change `bundle-source` to not emit bundles that need `require` yet? I just ran a test in which swingset no longer provides a `require` endowment to vat code, and it failed:
> 
> ```
> UnhandledPromiseRejectionWarning: ReferenceError: require is not defined
>     at getExportWithNestedEvaluate (/bundled-source-preamble.js:106:39)
>     at importBundle (/home/warner/stuff/agoric/agoric-sdk/packages/import-bundle/src/index.js:57:45)
>     at loadStaticVat (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/src/controller.js:187:25)
>     at async buildVatController (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/src/controller.js:231:23)
>     at async Test.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/SwingSet/test/test-controller.js:28:22)
> ```
> 
> I think this was closed in error.. I'll reopen it. I think we need that bundle-source fix before we can close it.

AFK: I won't be able to get to this right away, but IIRC, it's a one-line change to bundle-source:

```js
   { require }
```

to

```js
   { require: typeof require === 'undefined' ? undefined : require }
```

Or equivalent.
