### ISSUE TITLE
Cosmos staking layer report number of outstanding shares to enable quorum enforcement

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3627]
## What is the Problem Being Solved?

When holding a vote, it's common to enforce a quorum requirement: a minimum number of votes before an election can be considered valid. This is usually base on a percentage of the electorate. In order to support this with open-ended electorates like holders of staking tokens, we have to be able to learn how many tokens are extant.

## Description of the Design

The cosmos layer should make the number of current staking tokens accessible to the governance layer. The ballot counter will want to ask at the time the votes are being counted, and will want a prompt answer.  

API TBD.

## Security Considerations

The count should be reliable. At the moment, the only required consumer is governance, but I can imagine that the number of shares outstanding ought to be reported publicly somewhere.

## Test Plan

TBD at the cosmos layer.  Governance will treat it as a reliable service.

**Comment by dckc** [comment]
@Chris-Hibbert this doesn't seem to be cited from the Epics you're tracking. Is it something that can wait for someday?

@michaelfig and @JimLarson see some reasonably straightforward designs involving when stake is snapshotted; assign it to @JimLarson if you see a need for it in our plans, please.

**Comment by Chris-Hibbert** [comment]
As I understand the approach currently planned, staking attestations for governance will only indicate that shares are held, but not how many. In order to count votes, the javascript voteCounter will have to request holdings when it wants them. I think that means it should also get the current outstanding shares at the same time.

@JimLarson, please ensure that info is available from cosmos to bubble up to the contract.

**Comment by Tartuffo** [comment]
We should have the lien module query ready, for Governance.  We are planning Cosmos stake-weighted votes that have JS impact (#4352).  So this is not MN-1.

**Comment by aj-agoric** [comment]
Backlogging as discussed in today's Triage meeting.

**Comment by aj-agoric** [comment]
@Chris-Hibbert  is this still a need or have we solved this elsewhere?

**Comment by Chris-Hibbert** [comment]
This is obsolete. The underlying requirements are long gone.
