### ISSUE TITLE
vat enumeration non-deterministic?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#363]
Using node, I got:

```
Assigned VatID v1 for Genesis vat exchange
Assigned VatID v2 for Genesis vat host
Assigned VatID v3 for Genesis vat http
```

with xs, I got:

```
Assigned VatID v1 for Genesis vat zoe
Assigned VatID v2 for Genesis vat wallet
Assigned VatID v3 for Genesis vat mints
```

(I'm not sure the order is consistent in node either.)

I suppose this is due to non-determinism in directory listings.

@dtribble tells me this non-determinism shouldn't be exposed. We should sort them or some such.

**Comment by dckc** [comment]
I see the vats are put in a Map; is js Map enumeration deterministic? Is this perhaps an xs bug?

**Comment by erights** [comment]
JS Map enumeration is deterministic.
