### ISSUE TITLE
automate submission / collection for slog files

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3630]

**Comment by dckc** [comment]
@dtribble suggested two goals:
  1. use [logrotate](https://linux.die.net/man/8/logrotate) or the like to split up logs
      - @ski any recommendations?
      - @warner suggested that where we look for a filename, we also look for a file descriptor (e.g. `&4`) for integration with systemd / syslog
  2. facilitate upload to normalized storage rather that using download from ad-hoc storage
      - I'm inclined to organize something with our google cloud platform account

**Comment by dckc** [comment]
broke ground: https://github.com/Agoric/testnet-notes/tree/subm f0545ca

**Comment by dckc** [comment]
The https://submit.agoric.app/ tool seems to meet submission requirements as of https://github.com/Agoric/testnet-notes/pull/35 `ab698ff `.

Let's track the operation part as #3779.
