### ISSUE TITLE
[ERTP] What is the plural of units?

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#364]
Normally, if I have an array of "X" I would describe it as "Xs". or "somethingXs".

What is the plural of "units"? The code uses "units" for what you'd expect: a labeled extent. But it also uses "units" for arrays of units.

Note that the singular cannot be changed to "unit" because it represents some quantity of something.

**Comment by katelynsills** [comment]
I've been using `unitsArray` sometimes, but I'm not very happy with it.

**Comment by Chris-Hibbert** [comment]
Yeah, I was about to suggest unitsList, unitsSet, etc. Even if it's not very satisfying, it's far better than having the singular and plural spelled the same.

**Comment by erights** [comment]
About to be closed, since the plural of collective noun "amount" is "amounts"

**Comment by katelynsills** [comment]
Closing because we no longer use 'units'
