### ISSUE TITLE
Wallet should show the invitation details for the invitation to be used in an offer, in the offer inbox

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3650]
## What is the Problem Being Solved?

Invitations can be very valuable assets, and so the wallet should show information about the invitation used in an offer, when the user decides to approve or disapprove the offer. (Eventually, we would like the user to be able to switch out the invitation for another one, but at the very least, disapproving the offer should be possible based on the information about the invitation.)

In the next few days, the invitation details (the amount.value for the invitation) will have a fee and an expiration as well as the usual `instance` and `installation`. We will specifically need the fee and the expiration displayed in the offer inbox, but no particular formatting is necessary. As long as the user can read the fee as a brand petname and value and the expiration as a bigint, that is fine for this stage. Even just the invitation details as a JSON string printed might be sufficient. 

"dehydrating" in the wallet which replaces objects with the user's petnames, might be useful here.

**Comment by michaelfig** [comment]
> In the next few days, the invitation details (the amount.value for the invitation) will have a fee and an expiration

Can we call it `expiry` for brevity?

**Comment by katelynsills** [comment]
> Can we call it `expiry` for brevity?

I think that's British/Canadian English and not so much American, but yes, that's fine with me!

**Comment by michaelfig** [comment]
> > Can we call it `expiry` for brevity?
> 
> I think that's British/Canadian English and not so much American, but yes, that's fine with me!

Heh, you caught me.  I try to write American English when it comes to code, but this one slipped through.  :blush:
