### ISSUE TITLE
intermittent failure in test-gc-vat.js

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3666]
## Describe the bug

Both @katelynsills and @kriskowal have reported the following intermittent CI failure affecting current trunk:

```
✔ workers › worker › local vat manager (1m 8.1s)
Logging sent error stack (Error#1)
Error#1: oops

  at Alleged: root.one (packages/SwingSet/test/workers/vat-target.js:57:18)

Error#1 ERROR_NOTE: Sent as error:liveSlots:demo-vatID#70001
  ✔ workers › worker › xs vat manager (1m 8.3s)
  ✔ workers › worker › node-subprocess vat manager (1m 8.5s)
  ─

  gc › gc-vat › drop presence (export drops)

  Difference:

  - 'drop'
  + 'two'

  › dropPresence (file://test/gc/test-gc-vat.js:62:5)
  › processImmediate (internal/timers.js:437:9)
```

**Comment by warner** [comment]
https://github.com/Agoric/agoric-sdk/pull/3319/checks?check_run_id=3312997967 is one instance

**Comment by warner** [comment]
In this test, we've got a bootstrap vat that looks like:
```js
export function buildRootObject() {
  let A = Far('A', { hello() {} });
  let B = Far('B', { hello() {} });
  let target;
  let zoe;

  return Far('root', {
    async bootstrap(vats) {
      target = vats.target;
      zoe = vats.zoe;
    },
    async one() {
      await E(target).two(A, B);
    },
    drop() {
      A = null;
      B = null;
    },
```

The test lets `bootstrap()` do a `c.run()` to completion, which ought to drop all the other members of `vats` that it isn't using, and resolve the result promise (to `undefined`). Then we push a `one()` and a `drop()` onto the run-queue, then call `c.step()` twice. Then we look at the top of the run-queue and expect to see the `two()` that was emitted by `one()`. The expected sequence of events is:

* push `one()` and `drop()`. rq: `[one, drop]`
* first `c.step()`, should deliver `one()`, which sends `two()`, and does not resolve the result promise yet. rq: `[drop, two]`
* second `c.step()`, should deliver `drop`, pushing GC events and resolving result promise. rq: `[two, resolve(two)]` (GC events go onto higher-priority GC-actions queue)

the most likely explanation I can come up with for seeing `drop` instead of `two` at the top of the run-queue is that the `one()` delivery caused an unexpected GC event to be pushed, which would have stolen the second `c.step()`, leaving the original `drop` on the queue. The bootstrap vat runs under V8, not XS (which was maybe a bad idea).

I can't imagine it releasing A or B early, so I'd guess it's releasing one of the unused vats late. Running the test locally, I see the `bootstrap()` delivery dropping+retiring four objects, which should be vatAdmin, comms, vattp, and timer (all of which are automatically added by the kernel setup process). One possibility is that, for whatever reason, V8 decided to hold on to `vats` longer, sometimes, and those drops go out on the `one` crank instead of the `bootstrap` crank.

I'll start by logging more information in the case of a failure, specifically the full run-queue captured just after the first `c.step()`, to see what was on the front (i.e. what is consumed by the second `c.step()`).

**Comment by dckc** [comment]
if this is still a problem, please re-open it.
