### ISSUE TITLE
remove deprecated Ratio mulitpyBy and divideBy

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3676]
## What is the Problem Being Solved?

in #3138, we described how to support rounding modes in ratio computations. 
#3677 implemented the new functions and deprecated the old. The next step is to remove uses of the old functions and then we'll be able to remove the deprecated functions.

## Description of the Design

convert existing contracts to new functions
 * [ ] `callSpread`
 * [ ] `treasury`
 * [ ] `loan`
 * [ ] `newSwap`

Then remove the deprecated functions from `ratio.js`

## Security Considerations

only more reliable calculations

## Test Plan

Nothing special.

**Comment by Tartuffo** [comment]
@Chris-Hibbert After various meetings, this ended up with a MN-1 tag *AND* in the Product Backlog pipeline (not MN-1 Backlog).  Please modify appropriately for what it should actually be.

**Comment by Tartuffo** [comment]
Only the tests still refer to this.  So remove the deprecation and the functions.
