### ISSUE TITLE
[ERTP] makeUniExtentOps misdesigned to take a non-pass-by-copy argument.

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#368]
From https://github.com/Agoric/agoric-sdk/pull/122#pullrequestreview-336126845

The inviteConfig describes the extentOps as

```js
    extentOpsName: 'inviteExtentOps',
    extentOpsArgs: [insistOptDescription],
```

which is therefore how the inviteAssay describes it. But this doesn't remote correctly. The problem is that the `extentOpsArgs` must be transmitted by copy, but insistOptDescription is a function. The real problem is the `makeUniExtentOps` function, which I designed to take a function argument.

This problem should have prevented the Fred scenario from working, since it would prevent a remote invite from being traded. Why didn't we encounter this error? Attn @katelynsills

**Comment by katelynsills** [comment]
Both of these functions are imported from files, not passed through vats. Each vat, if using them directly, can import their own local version.

**Comment by erights** [comment]
At https://github.com/Agoric/agoric-sdk/blob/102-zoe-invites-part-1/packages/zoe/state.js#L191-L195 , substituting `xxx` for elided code, we see

```js
            const extentOpsDescP = E(assay).getExtentOps();
            xxx

            const synchronousRecordP = Promise.all([
              xxx
              extentOpsDescP,
              xxx
            ]).then(([xxx, { name, extentOpsArgs = [] }, xxx]) => {
```

This gets a remote promise for the extentOpsDescP from a remote assay. It then waits for the promise to fulfill to a local record that pattern matches against the record pattern, which only happens if the promise's fulfillment is a pass-by-copy record. The `name` is a string, which is trivially pass-by-copy. The `extentOpsArgs` is a pass-by-copy array. 

However, the array contains a non-passable function. It should fail at https://github.com/Agoric/agoric-sdk/blob/102-zoe-invites-part-1/packages/marshal/marshal.js#L92

**Comment by katelynsills** [comment]
Whoops, I should make sure I wake up and get coffee before replying. You're right. This would break for any extentOps that are made by passing a function as an argument. 

We don't encounter this error in Zoe because the basic tests that we have now use the basic mint setup. We don't have any tests yet that do anything more complex.

**Comment by katelynsills** [comment]
If a vat (other than the Zoe vat) attempts to make a local version of the Zoe invite unitOps, an error will be thrown when one of the `extentOpsArgs` is a function. 

Currently, none of our tests do this (Swingset tests for higher order contracts work), but Zoe will break as soon as we have Zoe instances that use invites from other Zoe instances which are in other vats. Zoe will also break if we escrow any nonfungible assets whose `extentOpsArgs` include functions.
