### ISSUE TITLE
run ERTP, Zoe unit tests on XS

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#370]
Add package scripts that, for each unit test script:
  - use rollup / bundleSource to link modules, leaving `ava` as an external
  - start an xsnap; feed it the SES shim; provide an ava work-alike via `require`
  - run the tests
  - report the results

#### formerly...

The `tape-xs` repo has not only a tape work-alike package but also a bit of tooling around it for building manifests and test runners. https://github.com/dckc/tape-xs

Earlier I thought all our tape test scripts needed changes, but I found an approach that works for at least a couple packages: https://github.com/Agoric/agoric-sdk/issues/49#issuecomment-568671973

For those two packages, the tests are completely automated with no changes to the test scripts:
https://github.com/dckc/agoric-sdk/blob/xs-lite/.github/workflows/ag-solo-xs.yml
https://github.com/dckc/agoric-sdk/commit/817d413c65488ca4543f3fb192fa3ef73a935044/checks?check_suite_id=375331754

Currently that workflow installs a release from the `dckc/tape-xs` repo. Perhaps tape-xs should be part of agoric-sdk? I don't know if it fits under `packages/` but before making a `tools/` directory or some such, I'd like to hear from others. @warner ? @dtribble ?

**Comment by michaelfig** [comment]
As I suggested over e-mail, I think tape-xs should move to become a top-level repository in the agoric-labs org.  It will probably be @warner's call to decide when we make it part of agoric-sdk, which is more for what we're actually deploying to the testnet and having people try for themselves.

**Comment by dckc** [comment]
agoric-labs is fine by me.

I'm not in any rush to move it; I'll stand by to hear more.

**Comment by katelynsills** [comment]
Can we close this as we've moved to AVA?

**Comment by erights** [comment]
I see one remaining import of something from tape in agoric-sdk and two in SES-shim.

**Comment by dckc** [comment]
broke ground on design discussed with @warner today:

https://github.com/Agoric/agoric-sdk/blob/370-xs-ava/packages/xsnap/src/avaXS.js 0bfcc65

**Comment by dckc** [comment]
@dtribble @warner @erights here's a sort of status report after going over all the zoe unit tests with XS. (ERTP seems OK).

```json

  "ava-xs": {
    "exclude": [
      "# eek! SIGSEGV in GC https://github.com/Moddable-OpenSource/moddable/issues/592",
      "test-loan-e2e.js",

      "# another SEGV, but not in --debug so I cannot get a stack trace",
      "contracts/test-callSpread-calculation",

      "# test-ratio uses _ which is not supported yet",
      "test-ratio",
      "test-percentSupport",

      "# trouble locating zcfTesterContract using __dirname",
      "loan/test-addCollateral",
      "loan/test-borrow",
      "loan/test-close",
      "loan/test-lend",
      "loan/test-liquidate",
      "contracts/test-autoswapPool",
      "test-zoe.js",

      "# bad plan: 4 still to go",
      "contracts/test-barter",
      "contracts/test-simpleExchange",

      "# ReferenceError#1: get 25961: undefined variable",
      "test-offerSafety",

      "# no function",
      "test-zoeHelpersWZcf.js",
```
  -- https://github.com/Agoric/agoric-sdk/blob/370-xs-ava-zoe/packages/zoe/package.json#L75-L102 5dd135e

@Chris-Hibbert says "Feel free to drop the underscore!"; they should wait until #2503 is done.

I aim to teach `ava-xs` to count tests more usefully; currently it counts assertions, not `test(title, t => {...})` things nor test scripts. :-/

It currently reports:
```
{ totalTests: 1279, stats: { ok: 1279, 'not ok': 0, SKIP: 0 } }
```

a full list of the test scripts that are run vs. those that are skipped is in
https://gist.github.com/dckc/6b9c1309b099468986830c444a4fbc59

that SEGV issue again, as a link:
https://github.com/Moddable-OpenSource/moddable/issues/592

**Comment by dckc** [comment]
7edc570 postpone _ in underscores until #2503 is done

**Comment by dckc** [comment]
## ava implicitly awaits using a subprocess

>       "# bad plan: 4 still to go",
>       "contracts/test-barter",
>       "contracts/test-simpleExchange",

`test-barter.js` doesn't `await` its calls to `assertPayoutAmount`. so ava-xs thinks the test didn't do as many assertions as it planned to (10).

@Chris-Hibbert recommends switching to `await` since it's less magic.

We haven't given xsnap the power to spawn subprocesses, and we don't plan to. So **making sure you await all outstanding turns** is especially important in any use of the ava API that's intended to be used on XS as well.

fixed in fa52b11

see also:
  - [ava docs on when to use plan](https://github.com/avajs/ava/blob/main/docs/recipes/when-to-use-plan.md)
  - [Promises](https://github.com/Agoric/agoric-sdk/wiki/agoric-sdk-unit-testing#promises) in [agoric sdk unit testing](https://github.com/Agoric/agoric-sdk/wiki/agoric-sdk-unit-testing)
  - #761

**Comment by dtribble** [comment]
Yes, The preferred style is indeed to use top-level `await` for tests, and drop the `plan` usage.  Using `plan` to wait until a test winds up is bad async hygiene. Is there any issues with that?

**Comment by dckc** [comment]
The main issue I see is that it's hard to tell that `t.plan()` is not best practice:

```
agoric-sdk$ find . -name 'test-*.js' | xargs grep t.plan|wc -l
139
agoric-sdk$ find . -name 'test-*.js' | xargs grep -l t.plan|wc -l
32
```

If we're agreed not to use it, let me know and I'll add a "please excuse outdated use of t.plan; see #761 " comment in those 32 test files.

Also... I'm not sure I understand what you mean by "using `plan to wait". `plan` doesn't do any waiting for you; it just's just a double-check that the test is working as intended.

**Comment by dtribble** [comment]
I am doing the changes to zoe tests for this.

**Comment by dckc** [comment]
## __dirname work-aound for bundling zcfTesterContract

As of d11f26ff , the following are running now. We're up to running 42 test scripts (1460 assertions), SKIPping only 5 non-swingset scripts. (Bad news: excluded another due to SEGV.)

>       "# trouble locating zcfTesterContract using __dirname",
>       "loan/test-addCollateral",
>       "loan/test-borrow",
>       "loan/test-close",
>       "loan/test-lend",
>       "loan/test-liquidate",
>       "contracts/test-autoswapPool",
>       "test-zoe.js",

ref #66

**Comment by dckc** [comment]
@warner and I just did some work trying to diagnose this SEGV in test-scriptedOracle.js:
https://gist.github.com/dckc/555d15bf02f6421e9a6922a5416471e0

we saw it happen, but then we changed something -- not sure what -- and now we can't reproduce it.

Ugh.
