### ISSUE TITLE
Dapp scaffold versioning

### ISSUE THREAD

**Issue by kriskowal** [Agoric/agoric-sdk#3705]
## What is the Problem Being Solved?

Working copies that contain an installation of the Agoric SDK CLI should continue to work properly in the face of product evolution. Particularly, we would like freshly scaffolded applications to take advantage of new features of the Agoric SDK CLI without breaking older installations. The motivating use case is the #3686, which would allow new dapps to use Node.js ESM (NESM) instead of emulated `node -r esm` ESM (RESM).

Current installations of Agoric CLI use the `HEAD` of the `dapp-fungible-faucet` as a scaffold template. Changing `dapp-fungible-faucet` to use NESM would therefore break current installations when they attempt to `agoric init new-dapp`. So, we cannot land a new scaffolding change https://github.com/Agoric/dapp-fungible-faucet/pull/26 to `HEAD`.

## Description of the Design

To unblock interdependent progress between the `agoric` command and the dapp scaffold template, we can begin versioning the template and including the version tag into the `agoric init` command. Since the current `HEAD` branch on `dapp-fungible-faucet` cannot be changed without breaking existing installations, we could also change the default branch name to something like `dev`.

## Security Considerations

I don’t expect much change to our posture, but there is a slight shift in the trade-off between burden on maintainers and defense against supply chain attacks. Versioning the scaffold and hard-coding the version in the CLI might actually mitigate a supply chain attack on the template, but not in a coherent way since the attacker is just as likely to gain control of the agoric CLI proper.

## Test Plan

Some combination of manual and automated regression testing should suffice. We should at least manually verify that old installations of agoric CLI continue to be able to initialize new dapps using the old (current) default branch of dapp-fungible-faucet, and that the new version uses the tagged version instead.

**Comment by Tartuffo** [comment]
@kriskowal This does not have an area label that is covered by our weekly tech / planning meetings.  Can you assign the proper label?  We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract,

**Comment by kriskowal** [comment]
I took a swing and added `installation-bundling`, but @michaelfig might have more context on where this is relevant.

**Comment by michaelfig** [comment]
> I took a swing and added `installation-bundling`, but @michaelfig might have more context on where this is relevant.

I added `agoric-cli` also.  @Tartuffo can we deal with `agoric-cli` also in a dapp/wallet meeting (still to be scheduled)?

**Comment by Tartuffo** [comment]
@kriskowal Is this really necessary for MN-1?

**Comment by kriskowal** [comment]
I think we can hope that the worst is behind us for this since the solution is worse than the problem (having to maintain the version pin in `agoric-cli` to match the last stable release of `dapp-fungible-faucet`.)
