### ISSUE TITLE
docs say Ubuntu 18.04 but ci runs on 20.04

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3709]
## Describe the bug

Trying to run the `agoric` cli on Ubuntu 18.04 results in `/usr/bin/env: invalid option --'S'`

## To Reproduce
1. Run Ubuntu 18.04.5
2. Follow the directions in https://agoric.com/documentation/getting-started/before-using-agoric.html

```
 user|project_dir $ agoric 
   /usr/bin/env: invalid option --'S'
```

## Platform Environment
 - what OS are you using? what version of Node.js? Ubuntu 18.04.5 , Node: 14.17.5
 - is there anything special/unusual about your platform? It's a little old.
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`) agoricstage-7-24-g29b9c5282

## Additional context

Looks like the `-S` is new a week or so ago:
https://github.com/Agoric/agoric-sdk/blame/master/packages/agoric-cli/lib/entrypoint.js#L1
https://github.com/Agoric/agoric-sdk/commit/d9a40194ad5bd0d05bcc8ef2a7de57b9d651e5be

And we don't test Ubuntu 18.04:
> Operating System: Ubuntu 20.04.2
-- https://github.com/Agoric/agoric-sdk/runs/3345379077?check_suite_focus=t

This is a reasonably well known portability issue.

[/usr/bin/env: invalid option \-\- 'S' \- Environments / Linux \- Travis CI Community](https://travis-ci.community/t/usr-bin-env-invalid-option-s/7121).

https://en.wikipedia.org/wiki/Shebang_(Unix)#Character_interpretation

cc @kriskowal @warner @katelynsills

**Comment by dckc** [comment]
looks like there's already a fix: #3708

**Comment by dckc** [comment]
There remains a question of whether we still support Ubuntu 18.04. It's not the newest LTS, but it'sn ot EOL either: https://ubuntu.com/about/release-cycle

**Comment by dckc** [comment]
#3708 addresses the particular symptoms here but not the root cause: we don't test 18.04 in ci.

Let's either test 18.04 in ci or update our getting started docs to say that it's too old.

**Comment by dckc** [comment]
A bit of discussion suggests it's cost-effective to support 18.04 for a bit longer. So I plan to update the ci script.

**Comment by turadg** [comment]
CI runs 18 currently so I think this issue is stale. Also https://github.com/Agoric/agoric-sdk/pull/3708 changed the CLI usage. Closing.
