### ISSUE TITLE
Explicit user-facing states for Vaults

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#3712]
Background
As part of updates to the vault contract, we have discussed having explicit states for vaults which might simplify design.  These states would be user-facing.

To discuss:
States required for a vault

**Comment by Tartuffo** [comment]
@rowgraus We need an estimate for this.

**Comment by Tartuffo** [comment]
Need discussion with @rowgraus @Chris-Hibbert .

**Comment by Chris-Hibbert** [comment]
@turadg  you had a list of three vault states, including liquidating.  Would you add those here?   Are those all the states we're concerned about?

**Comment by turadg** [comment]
> you had a list of three vault states, including liquidating

When we spoke I was referring to states of a VaultManager, but that's obviated by being able to delete while iterating.

> Are those all the states we're concerned about?

This ticket seems to be about Vaults per se, which have these three states: ACTIVE, LIQUIDATING, CLOSED

https://github.com/Agoric/agoric-sdk/blob/master/packages/run-protocol/src/vaultFactory/vault.js#L29-L40

I believe the consumer of that is UI, not the vault manager.

**Comment by dtribble** [comment]
I think that we need to record whether the vault was closed normally or via liquidation. Also it will have a transferring state. So I think the states are:
- ACTIVE - vault is in use and can be changed
- LIQUIDATING - vault is being liquidated by the vault manager, and cannot be changed by the user
- CLOSED - vault was closed by the user and all assets have been paid out
- LIQUIDATED - vault was closed by the manager and ... what's up with the assets?
- TRANSFER - vault is converted to user state

**Comment by dtribble** [comment]
Work better defined in #4539

**Comment by Tartuffo** [comment]
I set the estimate to 0, since the work will be done on #4539 and don't want to count this closed ticket as "work done".
