### ISSUE TITLE
Vault UI suggests a collateralization ratio for opening a vault that the contract rejects

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3738]
## Describe the bug

@michaelfig and @dtribble tried to open a vault by contributing 20_000_000 BLD (so 20_000_000 x 1_000_000 uBLD) in collateral. Their proposal had a want of 370921101734666n uRUN. However, the contract rejected that proposal with the message:

```
Error: Requested {"brand":"[Alleged: RUN brand]","value":"[370921101734666n]"} exceeds max {"value":"[222864717005509n]","brand":"[Alleged: RUN brand]"}
```

This is an error thrown in line 108 (`assertSufficientCollateral`) in vault.js. It is checking that the ratio is higher than the liquidation margin, which is 125n / 100n. 

Some things to look into: what is the price of BLD in RUN? Does it differ between the UI and the contract? Does the UI and the contract use the same price authority? We should be able to derive the price of BLD that the contract believes by plugging in the "max" value from the error message. (I was getting values of 13 RUN / BLD, but I need to double check those calculations). 

On chain currently, the price is 27.86 RUN/BLD

<img width="899" alt="market price" src="https://user-images.githubusercontent.com/2441069/130303381-dc20be65-1f0d-48e5-8227-ddc948a51139.png">

**Comment by katelynsills** [comment]
For what it is worth, the price on chain currently is 28.00 (compared to the 27.86 earlier). Unless we're coincidentally hitting the same point in wild swings up and down, this seems to indicate the price as understood by the UI is relatively stable, so we can probably discount "wild price swings" as an explanation. I will take another look at various points today to be sure, though.

**Comment by katelynsills** [comment]
The front end sends the following query: It sends a message "getPriceGivenAvailableInput" to the public facet of the AMM with 1_000_000 uBLD (1 BLD). The return value is "amountOut": 28_009_296 uRUN or approximately 28 RUN.

<img width="589" alt="Screen Shot 2021-08-23 at 2 10 05 PM" src="https://user-images.githubusercontent.com/2441069/130519893-0bbb5867-ca48-4162-8122-0f94a68a8d7f.png">

**Comment by katelynsills** [comment]
Ok, I think I've solved it. It's because the UI uses a "market price" and scales linearly, but the actual price is a price for an AMM trade, which does not scale linearly, but becomes increasingly expensive as the trade gets larger.

Both the Treasury UI and the Treasury contract are using the same priceAuthorities: the AMM priceAuthorities. This can be seen in [bootstrap.js](https://github.com/Agoric/agoric-sdk/blob/7bd027a879f98a9a3f30429ee1b54e6057efec42/packages/vats/src/bootstrap.js#L438) where the treasury is given a single priceAuthority that is the result of registering the price authorities from the AMM. 

Where the Treasury UI and the Treasury contract diverge is that the UI uses a "market price": the value of 1 BLD (1_000_00 uBLD) in RUN. The UI multiplies by the market price, which assumes that the actual price scales linearly. 

However, the actual price authority does not scale linearly. On the AMM, the larger the trades, the worse the price, as you are moving away from the center of the curve and towards the asymptotic edges. 

I was able to confirm this by querying the on-chain AMM with the 20_000_000 x 1_000_000 uBLD that had been attempted earlier. The price was around 14 RUN / BLD, as compared to the "market price" for 1 BLD, which was 28 RUN/BLD.

```js
E(multipoolAutoswapPublicFacet).getPriceGivenAvailableInput({ brand: bldBrand, value: 1000000n }, runBrand);

// {"amountIn":{"brand":[Object Alleged: BLD brand]{},"value":1000000n},"amountOut":{"brand":[Object Alleged: RUN brand]{},"value":28009292n}}

E(multipoolAutoswapPublicFacet).getPriceGivenAvailableInput({ brand: bldBrand, value: 20000000n*1000000n }, runBrand);

// {"amountIn":{"brand":[Object Alleged: BLD brand]{},"value":20000000000000n},"amountOut":{"brand":[Object Alleged: RUN brand]{},"value":280030453689241n}}
```

The Treasury contract gets the current price of all the collateral (not the market price), so it would reject an offer where the expected loan is made with the market price, if the market price is far off.

**Comment by katelynsills** [comment]
A potential fix would be to add a step in the Treasury UI that does a round-trip to the chain to get the actual value of the collateral. We should figure out where this can be done such that the waiting doesn't ruin the user experience.

Or, we could switch to a different priceAuthority, one which scales more linearly, and keep the market price methodology on the frontend.

**Comment by erights** [comment]
Or provide enough "current" curve info that the client can better conservatively approximate what the price would be.

**Comment by Tartuffo** [comment]
@samsiegart Can you see if this can be closed?

**Comment by samsiegart** [comment]
@Chris-Hibbert To summarize, this happens because opening a vault with a large amount of collateral causes the price to slip. Did we change that in the past 6 months or does that still happen?

**Comment by Chris-Hibbert** [comment]
This hasn't changed. 

I think the bug is here:
> Where the Treasury UI and the Treasury contract diverge is that the UI uses a "market price": the value of 1 BLD (1_000_00 uBLD) in RUN. The UI multiplies by the market price, which assumes that the actual price scales linearly.

If the UI doesn't have enough slop in its proposal to allow the slippage to take place, then it should request a price quote from the AMM that does include slippage.  `E(multipoolAutoswapPublicFacet).getPriceGivenAvailableInput()` will give the right answer if the amount to be sold is included, but not by requesting the price of 1 unit and multiplying.

**Comment by samsiegart** [comment]
Discussion from eng-sync: we don't want to get the collateral price based on our AMM curve, we want to rely on the oracles to determine collateral prices. `assertSufficientCollateral` should take this into account (it may already, just not on a local environment?), so the UI should continue using the linear price calculation.

**Comment by dtribble** [comment]
I think this is now addressed via 
* use separate oracle for determining what vaults to create
* use linear, external oracle
* eliminating the "initial collateralization"
