### ISSUE TITLE
Combine a timeAuthority and time into an amount-like record

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#3748]
Just as amounts pair a quantity with a brand that gives it meaning, we should likewise pair a time with the timeAuthority that gives it meaning. This would show up first in the exit portion of a proposal.

**Comment by erights** [comment]
Also governance. See https://github.com/Agoric/agoric-sdk/blob/attacker-guide-3575/packages/governance/docs/AttackGuide.md#use-a-timer-that-is-controlled-by-a-party-to-the-vote

**Comment by erights** [comment]
thus establishing the similarity but non-equivalence of time vs money ;)

**Comment by katelynsills** [comment]
I think we need to rethink the API of a timeAuthority for this to work. If the timeAuthority is widely held, then anyone can call `setWakeup`, which is quite costly for the timeAuthority and the chain in general. I think we need a way to reduce the consequences of making a timeAuthority widely held.

**Comment by erights** [comment]
Good point. Do we need a brand-like object, paralleling the split of issue vs brand?

**Comment by erights** [comment]
Started at https://github.com/Agoric/agoric-sdk/pull/3749

**Comment by zarutian** [comment]
to keep in line with Temporal, perhaps call it RelativeInstant or some such?

**Comment by erights** [comment]
Fixed at https://github.com/Agoric/agoric-sdk/pull/5821 . Closing.
