### ISSUE TITLE
why use async callbacks in web.js?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#376]
Callbacks should never be `async` functions, according to [a nodejs talk](https://www.youtube.com/watch?v=e3Nh350b6S4) I recently watched.

https://github.com/Agoric/agoric-sdk/blob/8e45d50605d567810497c164e28748db5a86f6c5/packages/cosmic-swingset/lib/ag-solo/web.js#L134

**Comment by michaelfig** [comment]
Actually, in that video the speaker glosses over an aside where he says that if you're using try-catch then this pattern is kosher.  I wanted to share the error handling both of the awaited call and the synchronous code.

Do you have a clearer way of doing this?

**Comment by dckc** [comment]
I'm satisfied to know that you had reason to do it and considered the consequences.
