### ISSUE TITLE
Need to improve error message for a payment being sent instead of paymentKeywordRecord

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3765]
## What is the Problem Being Solved?

If a payment is sent in `zoe.offer` instead of a payment keyword record, the error message is not helpful:

```
  Error {
    message: 'keyword "getAllegedBrand" must be ascii and must start with a capital letter.',
  }

  › makeError (node_modules/ses/dist/ses.cjs:2572:17)
  › fail (node_modules/ses/dist/ses.cjs:2700:20)
  › baseAssert (node_modules/ses/dist/ses.cjs:2718:13)
  › assertKeywordName (node_modules/@agoric/zoe/src/cleanProposal.js:31:3)
  › Array.forEach (<anonymous>)
  › cleanKeywords (node_modules/@agoric/zoe/src/cleanProposal.js:103:12)
  › depositPayments (node_modules/@agoric/zoe/src/zoeService/escrowStorage.js:68:29)
  › Alleged: zoeService.offer (node_modules/@agoric/zoe/src/zoeService/offer/offer.js:39:37)
``` 
We should improve the error message through asserting that the paymentKeywordRecord is a copyRecord before proceeding.

**Comment by Tartuffo** [comment]
@dckc This does not have an area label that is covered by our weekly tech / planning meetings. Can you assign the proper label? We cover: agd, agoric-cosmos, amm, core economy, cosmic-swingset, endo, getrun, governance, installation-bundling, metering, run-protocol, staking, swingset, swingset-runner, token economy, wallet, zoe contract.  Or, if this is accurately labeled by an area label we should be covering in one of our weekly meetings, please LMK.

**Comment by dckc** [comment]
The Zoe label isn't covered by the Zoe/ERTP meeting?

**Comment by Tartuffo** [comment]
Yep, never mind.

**Comment by dckc** [comment]
The message got somewhat better since this was reported:

```
"keywordRecord" "[Alleged: Token payment]" must be a pass-by-copy record, not "remotable"
```

I'm looking into what it takes to improve on that...

**Comment by dckc** [comment]
Looking at the new / current message again, it has has both `keywordRecord` and `payment`, which is pretty good.

The test I made to reproduce this seems worth keeping, so I'm putting it into a PR.
