### ISSUE TITLE
objects-as-closures pattern allocates per method, per object

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3768]
## Describe the bug

The overhead in XS (and other typical JS implementations) of the objects-as-closures pattern is an allocation per method (K) per object instance (N), i.e. O(K*N).

The pattern is designed to use only O(K+N) storage.

## To Reproduce

TBD

@warner suggested that we should supply some examples to help measure the overhead / cost.

## Additional context

The optimization was discussed with Moddable in a meeting today, Aug 26. @erights sketched an optimization. We have a recording and some detailed notes.

cc @phoddie

**Comment by warner** [comment]
While still true, most of our code is now written using Exos, which keep all their behavior methods in a single prototype object, which removes the `per method` multipler. So the cost is now something like O(number_of_methods) *plus* O(number_of_objects). So I'm going to close this now.
