### ISSUE TITLE
Treasury: vault updateUIState() should take the new state as a parameter

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3772]
## What is the Problem Being Solved?

Simplification.

Most fo the places where `updateUiState()` is being called, we set the vault's state immediately before. That should be a single operation. For the callers that don't change the state, no argument should leave the state unchanged.

## Description of the Design

[Suggested by](https://github.com/Agoric/agoric-sdk/pull/3656#discussion_r690672054) @dtribble

## Security Considerations

Simpler code is easier to maintain.

## Test Plan

No change in behavior is expected.

**Comment by dtribble** [comment]
There's now multiple independent state values that get updated, and we only want to notify after they al change. So keeping this manual is fine, but it needs to not be async.

**Comment by dtribble** [comment]
Already addressed by removing the price information that was fetched async.
