### ISSUE TITLE
Treasury: merge liquidationSeat into vaultSeat

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3773]
## What is the Problem Being Solved?

The Treasury's vault has a separate seat to hold the liquidation payout. This is unnecessary and requires extra work on the part of the borrower.

## Description of the Design

give liquidation the ability to deposit to the vaultSeat. Then the borrower doesn't need an extra seat. They do still need the ability to be notified when liquidation happens.

## Security Considerations

minimal

## Test Plan

refactoring existing tests should be sufficient.

**Comment by Tartuffo** [comment]
Implement with #4344
