### ISSUE TITLE
slogfiles grow without bound, contrary to devops norms a la logrotate

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#3779]
## Describe the bug

By setting `$SLOGFILE` or `$SOLO_SLOGFILE`, operators can produce detailed diagnostics about swingset events. Unfortunately, these files grow without bound, which is awkward for the node operators and for data analysis.

## Expected behavior

[logrotate](https://linux.die.net/man/8/logrotate) is a norm for splitting logfiles into manageable pieces.

Ideally, these files would be split on block boundaries.

## Additional context

originally noted in #3630

cc @rowgraus @warner @FUDCo

**Comment by dckc** [comment]
@michaelfig I'm inclined to take the **SwingSet** label off this one, leaving it on the **cosmic-swingset** agenda.

**Comment by dckc** [comment]
adding @dtribble in a customer role assignment

**Comment by dckc** [comment]
In order to investigate what seems like unnecessary round-trips in the governance demo (#3869), I looked into the options here and found a couple that seem workable plus others that I would rather avoid:

## named pipe + multilog / svlogd

This option appeals to me:

> Have each worker log to stdout, but connect each stdout to a utility that automatically spools and rotates logs based on size or time. [multilog](https://cr.yp.to/daemontools/multilog.html) and [svlogd](http://smarden.org/runit/svlogd.8.html) are examples of such. -- [pilcrow Feb '13](https://stackoverflow.com/a/15123148/7963)

## add log rotation to swingset slogger with `logrotate-stream` npm package

[logrotate\-stream \- npm](https://www.npmjs.com/package/logrotate-stream) seems to be designed just for this case. It would only need to go in the controller, not the kernel, right?


## ad-hoc script with named pipes: let's not

I suppose this is possible...

 - [linux \- Rotate logs of a dumb non\-interactive application \- Server Fault](https://serverfault.com/questions/189477/rotate-logs-of-a-dumb-non-interactive-application)

... but the docs for multilog make it clear that there are _lots_ of corner cases...

## file descriptor + systemd: unlikely

I went to flesh out the idea o f using `SLOGFILE=&7` to mean: log to file descriptor 7, with the expectation that systemd / journald would listen there and provided log rotation. But I don't see any support for anything like that in [systemd\.unit docs](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) nor [systemd\-journald\.service](https://man7.org/linux/man-pages/man8/systemd-journald-varlink.socket.8.html).

 - [daemontools \- Can systemd manage a pipeline? \- Server Fault](https://serverfault.com/questions/791395/can-systemd-manage-a-pipeline)
 - [logging \- How can I send a message to the systemd journal from the command line? \- Server Fault](https://serverfault.com/questions/573946/how-can-i-send-a-message-to-the-systemd-journal-from-the-command-line)

**Comment by Tartuffo** [comment]
Solved by @michaelfig (Flight Recorder #3742)
