### ISSUE TITLE
[Zoe] Use E() in Zoe unit tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#378]
Mark pointed out that we should be using `E()` in the Zoe unit tests, since `E()` can be used for local eventual-sends as well and we should be trying to make the unit tests match the Swingset tests as closely as possible.

**Comment by erights** [comment]
Just a terminology nitpick:

... since `E()` can be used for local eventual-sends as well ...

**Comment by katelynsills** [comment]
Thanks for the correction! I was looking for the right phrase, so glad to find it.

**Comment by erights** [comment]
@katelynsills I think this is done, so closing. But assigning the two of us in case I'm wrong.

**Comment by katelynsills** [comment]
I went through all the issues with the ERTP/Zoe label and closed the ones I thought could be closed, so unless I miss something, nearly all issues with those labels that are open, I think should remain open. 

For this one in particular, we haven't done this task. Many of the tests still don't use E().

**Comment by katelynsills** [comment]
This was completed in https://github.com/Agoric/agoric-sdk/pull/3319
