### ISSUE TITLE
Run protocol accounting for contract-dependent values

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#3792]
## What is the Problem Being Solved?

We need a list of statistics to be collected across the treasury and the AMM for
 * managing debt (liquidations and shortfalls)
 * tracking issued RUN and BLD
 * tracking the use of RUN in the economy (e.g. execution fees)
 * tracking collateral in Vaults

## Description of the Design

This is about collecting documentation. Design will follow

## Security Considerations

It's about tracking flows and holdings so we can monitor the economy.

**Comment by Tartuffo** [comment]
@Chris-Hibbert Please review with @rowgraus and @btulloh

**Comment by Tartuffo** [comment]
This might be handoff-able to @turadg and/or @dckc .  We gave a rough time-box estimate of 5.

**Comment by Tartuffo** [comment]
Superseded by #4639.

**Comment by btulloh** [comment]
I don't think this issue should be closed, at least it is not superseded by #4639. This refers to the internal accounting for RUN debt that the protocol incurs when it mints RUN. This is needed to track bad debt that needs to be covered by liquidation and reserves.

**Comment by Tartuffo** [comment]
@dckc @Chris-Hibbert Who should be the assignee on this?

**Comment by Chris-Hibbert** [comment]
Let's make it me.  I'll add some accounting in #4188, and after Restival spend some time writing down (and making issues) for what needs to be done in AMM and Vaults.

**Comment by rowgraus** [comment]
@dtribble @btulloh @Chris-Hibbert 

We need RUN Protocol accounting to happen *somewhere* in Mainnet 1.  However, it's plausible that these don't need to be written in contracts and could instead be done with third party tools working off of eventing.  Which would mean this isn't blocking and could be built post launch or as a bounty.

The question is: aside from debt limits, which I believe we are handling elsewhere, is there any reason I'm missing for why we need this built into contracts?

**Comment by btulloh** [comment]
I'm trying to distinguish between two different things.
1. An external view via third-party tools. This could be done as a bounty, but we need it at launch of the RUN protocol, not post-launch. This is needed for external monitoring of what is happening. I don't like the idea of flying blind. 
2. An internal view of the overall solvency, which might trigger onchain actions. Perhaps what we currently have is sufficient, but it is not clear to me where everything is being tracked. For example, how does the protocol know that its assets are worth less than its liabilities, and therefore it needs to issue BLD to bring it back to solvency.  The liabilities are the RUN outstanding. The protocol has multiple ways of issuing and burning RUN. Its assets are the dollar values of the PCV held by the protocol, plus the dollar values of the UCV held in vaults. My question is does the protocol need a way to sum across these different pools of assets and liabilities, and if so, do we have currently have a way to do that.

**Comment by turadg** [comment]
Per Run Proto meeting today we've scoped this ticket to accounting that's necessary for the logic of the contracts. https://github.com/Agoric/agoric-sdk/issues/4482 is for what can be tracked off-chain.

**Comment by Tartuffo** [comment]
@rowgraus has this been handled, and can we close this issue?

**Comment by Chris-Hibbert** [comment]
duplicate with #4639, #5300, #4648, #4649, #5352
