### ISSUE TITLE
Treasury and Wallet UX Improvements

### ISSUE THREAD

**Issue by samsiegart** [Agoric/agoric-sdk#3793]
## What is the Problem Being Solved?

Improving the overall UX of the Treasury and Wallet apps.

## Description of the Design

 After some mocks and discussion we've come up with a few ideas for the Wallet app:

- [x] Use a nav menu instead of links in app bar for navigation
- [x] Reorganize content into the following views:
      - Inbox
      - Purses
      - Dapps 
      - Contacts
      - Issuers
      - History
- [x] Change inbox view to be just a list of recent offers, payments, and dapp connections requiring attention, all meshed together.
- [x] Make purses view just contain the list of purses with their actions.
- [x] Make dapps view just contain the list of connected dapps with their actions, and also add the ability to remove them.
- [x] Similar as above for moving contacts and issuers components into their own views.
- [ ] Make minor styling improvements across most components including the app bar.
- [x] ~~Add currencies icon to app bar which shows a popover menu displaying a list of all assets and their balances.~~
- [x] ~~Make history view a list of all past offers and payments, with the ability to filter by dapp.~~

Tagging @rowgraus @michaelfig @dtribble @katelynsills 

## Test Plan

These changes will be incrementally merged behind a feature flag (either a url param or hardcoded boolean). Changes will be reviewed and tested manually as they're made and eventually the flag will be enabled by default.

**Comment by dckc** [comment]
This is done to the satisfaction of @rowgraus . Nice work, @samsiegart !
