### ISSUE TITLE
AMM trades fail - Error#125: rights were not conserved for brand [object Alleged: RUN brand]

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#3800]
Trades on the AMM were getting rejected with surprising errors. 

From the analysis below:

TLDR: The stagedAllocations weren't being cleared after an offer safety error, so future offers were working with a poolSeat that already had a stagedAllocation (one corresponding to a previous offer). The contract code could fix this by clearing the staged allocations in case of an error, but we probably want Zoe to do it instead. We need to spend some time thinking through how we should clean up state after errors (offer safety, rights conservation, staged allocations not included in reallocate, etc).

I'm splitting out this surprising rights-conservation error from the original ticket.

Kate said:

This looks like a "swap" on the AMM was being performed. Do we know what was being traded?

_Originally posted by @katelynsills in https://github.com/Agoric/testnet-notes/issues/26#issuecomment-904247565_

----

## Fee details are still available

Note that the [AMM Trade Part 1: Make a trade on the AMM and get charged a fee](https://validate.agoric.com/612c3319809948e69e81bc8c05529312) task does not require that the trade goes through. Only that metering fees are charged, which happens even if the trade is refunded.

**Comment by Tartuffo** [comment]
@Chris-Hibbert is this fixed?

**Comment by Chris-Hibbert** [comment]
This is an instance of "Stateful seats and staged allocations" (#3850), which @erights is working on.

**Comment by Tartuffo** [comment]
@erights @Chris-Hibbert So is this a dup that should be closed, or should we leave it and #3850 open

**Comment by erights** [comment]
Closing this while I continue work on #3850
