### ISSUE TITLE
Improve testnet support for external validators

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#381]
There are some improvements needed for the testnet to better support external validators:

* Make genesis.json available from https://testnet.agoric.com/genesis.json
* Transfer stake from the bootstrap staker account according to public keys and stake amounts described by node0:/home/ag-chain-cosmos/cosmos-stakers.txt
* Make the persistent peer node IDs, IPs, and ports, available from https://testnet.agoric.com/network-config

**Comment by awrelll** [comment]
looks good !
