### ISSUE TITLE
[ERTP] Design Changes (to be split up into issues per task)

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#385]
1. Rename `assay` to `issuer`
2. Rename `mint` to `issuerAdmin`
3. As part of the process of making an issuer and issuerAdmin, create a `brand` object. The brand is shared by the issuer, issuerAdmin, purses, and payments of a particular kind. See item 4 for why this is helpful for removing an anti-pattern of use. The brand should have a method that takes an issuer as a parameter and returns a boolean, stating whether the issuer belongs to that brand. This is to avoid issuers picking up another issuers brand and passing themselves off as that brand.  
4. Move nearly all of the methods from purses and payments to the `issuer`. The only methods that should remain are `getMemo` (to get a string message for that particular payment or purse), and `getAllegedBrand`, which returns an object which is the `brand`.  In particular, we want to remove the `getAssay/getIssuer` pattern that we have seen, where a person receives a payment that should not be relied on, and then they get their assay/issuer (which they normally should be able to rely on) *from* the untrusted payment. Being able to get an object that you should be able to rely on from an object that you should not be able to rely on is an anti-pattern. 
5. Rename `units` to `amount`
6. Rename `unitOps` to `amountOperations`
7. In `amountOperations`, we want to simplify as much as possible so that it is very clear that an `amount` is merely a branded extent/quantity etc. This means getting rid of the description for now. We should also clarify the use of a WeakSet as a cache so that it is known to be nothing special, just a performance enhancement. 
7. Rename `extent` to ?? (unbrandedAmount, quantity)?
8. In what was formerly unitOps, rename `with` to `add`
9. In unitOps, Rename `without` to `subtractNonNeg` or something similar. (Note: we cannot use `subtract` on its own because our version is not set subtraction. If the left does not contain the right, we must throw an error. For natural numbers as in the case of fungible tokens, we throw if the subtraction results in a negative number.)
10. In unitOps, rename `includes` to `isGTE`

**Comment by katelynsills** [comment]
There's an experimental branch that has some of these changes: https://github.com/Agoric/agoric-sdk/tree/branded-operations-strip-for-parts

It has other changes that we probably don't want and needs to be stripped for parts.

**Comment by dtribble** [comment]
A couple of naming convention proposals:
- "alleged" methods use that instead of `get`, so `allegedBrand` rather than `getAllegedBrand`
- the extentOps methods should _sound_ internal, e.g., `doAdd`
- name unitOps unitMath, to resonate with Math, which is known to have helper functions that are math-oriented.

**Comment by katelynsills** [comment]
Naming changes based on design session Feb 11:

`assay` -> `issuer`
`mint` remains the same, but we mention it is just a facet of `issuer`
`unitOps` -> `math`
`extentOps` -> `mathHelpers`
extentOps function names -> "do" prefix
units -> amount
extent renames the same

**Comment by erights** [comment]
I was thinking `unitOps` -> `amountMath`. I'm not comfortable with unqualified `math`.

**Comment by katelynsills** [comment]
> I was thinking `unitOps` -> `amountMath`. I'm not comfortable with unqualified `math`.

Good point. You're right. That's what we had said
