### ISSUE TITLE
[ERTP] the second argument of makeMint could be directly the configuration

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#388]
https://github.com/Agoric/agoric-sdk/blob/b133ab0557af00edc960f66a0df87a366ecf2393/packages/ERTP/core/mint.js#L21-L35

In this code, `makeConfig` is called without argument, so it's not clear to me what the benefit of this function call is. And this function call is the first thing that happens during the `makeMint` call (unrelated `insist` aside)

An alternative could be: the caller of `makeMint` passes the config directly

**Comment by katelynsills** [comment]
Very good point. I can't think of anything currently that requires it to be a function. I think previously, there seemed to be more of a chance that we could pass pure functions than a chance that we could import from other files, so that mistaken assumption was probably warping this design choice.
