### ISSUE TITLE
[ERTP] The payment resulting from a call to assay.combine is not customized

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#390]
https://github.com/Agoric/agoric-sdk/blob/b133ab0557af00edc960f66a0df87a366ecf2393/packages/ERTP/core/mint.js#L145-L171

I do not see a call to `makePaymentTrait` suggesting the resulting payment does not have the custom methods.

Note also that there is somewhat duplicated code between these places:

https://github.com/Agoric/agoric-sdk/blob/b133ab0557af00edc960f66a0df87a366ecf2393/packages/ERTP/core/mint.js#L57-L77

https://github.com/Agoric/agoric-sdk/blob/b133ab0557af00edc960f66a0df87a366ecf2393/packages/ERTP/core/mint.js#L94-L113

**Comment by katelynsills** [comment]
Good catch, we should be calling `makePaymentTrait` there.

**Comment by DavidBruant** [comment]
I'm currently working on #375 
So i'll be fixing this one along the way
I will also factorize the payment making into an internal function to de-duplicate the code

**Comment by katelynsills** [comment]
Closed by #389
