### ISSUE TITLE
[ERTP] Shelve contractHost in favor of Zoe

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#394]
Now that we have Zoe, we are no longer using contractHost for running smart contracts. We will still want to use something like contractHost for spawning new vats with some code. However, I think this should be a separate engineering task. 

We had previously discussed moving the contractHost code as is into the `/test` folder under ERTP so it was available for tests and further work but not easily viewable/useable by users.

- [ ] Rename contractHost to vatSpawner
- [ ] Move vatSpawner and related files to a folder under /test so that we make sure they continuously work with our changes to ERTP but that they are not easily available for users to mistakenly use. Then, when we are ready to make the vatSpawner accessible to users, we can easily do that.
- [ ] Rewrite the pixel gallery demo to use Zoe (probably, atomic swap)

**Comment by katelynsills** [comment]
More discussion at https://github.com/Agoric/agoric-sdk/issues/95, specifically:

> https://github.com/Agoric/agoric-sdk/issues/95#issuecomment-553652775

**Comment by erights** [comment]
> However, I think this should be a separate engineering task.

How different would that be from the contractHost? I haven't looked in awhile, but my sense is we're better off just maintaining the contractHost, as it is already close to the spawner we need.

**Comment by katelynsills** [comment]
Just discussed in person and concluded that we should:

1. Rename `contractHost` to `vatSpawner`
2. Move `vatSpawner` and related files to a folder under `/test` so that we make sure they continuously work with our changes to ERTP but that they are not easily available for users to mistakenly use. Then, when we are ready to make the vatSpawner accessible to users, we can easily do that.

**Comment by katelynsills** [comment]
Closed by #486, remainder of this issue moved to #495
