### ISSUE TITLE
implement metering transform for portable gas model

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#398]
A long time ago, in a galaxy far, far away, I was discussing with @erights [how to implement a gas model](https://groups.google.com/forum/#!topic/google-caja-discuss/swKiyyJ8hRw) for Javascript under SES.

The following is a proposed design for a `transform-metering` component:

```js
const { burnId, stackMeterId, meteringTransform } = makeMeteringTransform(maxStackDepth = undefined, overrideBurnId = undefined, overrideStackMeterId = undefined);
```

If `maxStackDepth` is not `undefined`, it is an integer that deterministically limits how deep the stack can grow in the transformed code.  This should be somewhat less than the platform's stack limit (minus the host environment's stack depth and the depth of any unmetered code that can execute), or the code can behave nondeterministically.

The returned `burnId` property is the same as `overrideBurnId`, or if it is `undefined`, a generated identifier.  That identifier is prevented from being shadowed by metered code, and should be set as a function endowment that deterministically decrements the amount of gas by the number of units specified by its nonnegative integer argument, burning all the gas for any other specified argument.  The function should throw when the gas is exhausted (and also throw when called anytime after the gas is exhausted to ensure computation stops and control is returned to the host).

The returned `meteringTransform` is an SES transform that injects calls to `[[burnId]](1)` in the following locations:

1. At the beginning of every function.
2. At the beginning of every `catch` and `finally` block.
3. At the beginning of every `for`, `while`, and `do` loop body.
4. Before every `continue` statement.

If the `maxStackDepth` is configured, the transform additionally surrounds function bodies with:

```js
try {
  [[stackMeterId]](1); // consume a stack frame
  ... // original function body here.
} finally {
  [[stackMeterId]](-1); // release a stack frame
}
```

The `stackMeterId` can be overridden with `overrideStackMeterId`.  In all cases, that identifier is endowed by the transform and prevented from being shadowed by metered code.  If the stack depth is exceeded, the `burnId` function is called with a `true` argument to indicate that all gas should be burned.

**Comment by michaelfig** [comment]
Note that as @dtribble pointed out:
> We expect to instrument the XS runtime in the typical case, and so would not need the rewrite.

This proposal, therefore, is to allow non-instrumented runtimes to be able to meter gas.  We can do better if we have an instrumented runtime.

**Comment by mappum** [comment]
Just want to drop this here since we worked on this a while ago: https://github.com/nomic-io/modbox/blob/master/src/instrument.js

Our instrumentation solution probably has some issues and is certainly not efficient, but it accomplished what you're describing by simply wrapping every expression in a call to a "burn" function. For instance, `if (a > b) foo(123)` would be transformed to `if (burn(burn(a) > burn(b))) burn(foo(burn(123)))`.

In reality, the identifier would be random instead of `burn` so that malicious code can't shadow the burn handler.

This solution works for a lot of code, but it isn't complete since there are expensive operations which aren't sufficiently costly, for example `new Array(1e6).map(Object.create)`. That could be fixed by wrapping built-in functions to invoke the burn handler, but you have to wrap all of them.

**Comment by michaelfig** [comment]
Thanks so much for pointing me there.  I saw nomic-io/metering, but had forgotten about modbox.  It is indeed my goal to be both efficient and robust.  Precision is not my goal.  Your approach is definitely appealing, though.

Out of curiosity, would it make sense to wrap methods like `map`, `reduce`, `forEach`, `indexOf`, `includes` that contain implicit loops to be wrapped in something that burns gas commensurate with the number of iterations (i.e. algorithmic complexity) before they execute?

I realize that's a kind of blacklisting approach, but that means we don't really need to wrap every built-in function, just the unmetered loops.

@erights, thoughts on what approach you'd recommend for deterministic, coarse-grained prevention of runaway processes?

**Comment by michaelfig** [comment]
Both approaches probably need to do with-on-a-proxy so that global functions can be distorted as necessary.

This suggests that distortion of globals may be a useful feature for an Evaluator.  @jfparadis do you have thoughts on this?

**Comment by michaelfig** [comment]
The proposed design has changed.  The above PR (#421) is the current direction but still needs documentation and tests.
