### ISSUE TITLE
Update Yarn

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#3997]
## What is the Problem Being Solved?

We get a warning message when doing `yarn install`
`warning Your current version of Yarn is out of date. The latest version is "1.22.15", while you're on "1.22.5".`

## Description of the Design

Either upgrade to `1.22.15` or ensure that Yarn 2 works (we've gotten reports that it does)

## Security Considerations
No longer on an outdated version.

## Test Plan
Manual testing

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.

**Comment by katelynsills** [comment]
Thank so much for taking this on @mohitsaxenaknoldus! I'm assigning it to you (We can only officially assign people within our Github organization, so the "assignee" will remain blank). Feel free to let me know if you have any questions.

**Comment by mohitsaxenaknoldus** [comment]
> Thank so much for taking this on @mohitsaxenaknoldus! I'm assigning it to you (We can only officially assign people within our Github organization, so the "assignee" will remain blank). Feel free to let me know if you have any questions.

Thanks! I've raised the PR: https://github.com/Agoric/agoric-sdk/pull/4007
