### ISSUE TITLE
[ERTP] Move /more into its own folder under /packages

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#417]
We have a number of things under ERTP that don't seem to really belong there. 

Under `/more` we have:
* imports - an "import manager" which creates an object that can be imported. This is used by ERTP directly and needs to be put under /utils or something similar.
* pixels - a demo of non-fungible rights in ERTP that needs to be reworked. This is used in the testnet.
* registrar - a map that assigns string keys to objects - used in testnet. 
* sharing - the "sharing service" for sending objects in a way that can be picked up by another entity - available but not used heavily in the testnet. 

The follow should be moved to a new package, perhaps called `ertp-demo`:
* pixels
* registrar
* sharing

Also, under `util/`, we have files such as `insist.js` which are used by several Agoric packages (I think Swingset has its own copy) and should probably be taken out of ERTP and put in their own Agoric utilities package.

Ideally, ERTP should only have `mint.js` and the files that are needed for `mint.js`, such as `unitOps.js`.

**Comment by erights** [comment]
Agree especially about util/ and insist. Once this insist is reusable, the other insist, which is incompatibly different, should just go away. FWIW, I started experimenting with some improvements to `insist` at https://github.com/Agoric/agoric-sdk/tree/78-better-insist-abstractions . WIP.

AFAICT, everything in util/ should be reusable outside of ERTP, and so should be placed somewhere else.

**Comment by katelynsills** [comment]
Closed by #486
