### ISSUE TITLE
add queue-to-self facility/syntax

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#42]
https://github.com/Agoric/cosmic-swingset/issues/64 needs some sort of way for vat code to send a message to itself, but queued through the kernel run-queue so that any message currently on the run-queue will be retired before the message-to-self is delivered.

For the upcoming Agoric/SwingSet#88 API rewrite, this is straightforward at the syscall API level: just a `syscall.send(target=o+NN, msg=..)`, which means it is aimed at an object exported by the vat itself. This will be put onto the runqueue and eventually delivered as `dispatch.deliver(target=o+NN, msg=..)`.

The trick is how to represent this to vat-code via the liveSlots layer. It's somewhat like `my_object ! foo()` except that only goes through the promise queue, which is not long enough (it short-circuits the kernel run-queue). Maybe `my_object !! foo()`, or `E.queueThroughKernel(my_object).foo()`.

Another (overlapping) option to solve the original problem, would be a syntax that returns a Promise that won't resolve until the run-queue has been flushed. Export a promise to the kernel, subscribe to it, then immediately resolve it. The notification will be queued on the run-queue, so the `dispatch.notify()` won't arrive until after the rest of the run-queue has been flushed.

**Comment by warner** [comment]
@michaelfig hey, did you intend for your PR to close this one? I think we'd need some additional facility or syntax beyond tildot to signal this case.

I'm worried that the monorepo conversion has caused some collision between Issue numbers, as evidenced by dckc's unrelated PR listed above.

**Comment by warner** [comment]
I'm guessing not

**Comment by warner** [comment]
FYI [`https://github.com/Agoric/eventual-send/issues/42`](https://github.com/Agoric/eventual-send/issues/42) got moved to [`https://github.com/Agoric/agoric-sdk/issues/5`](https://github.com/Agoric/agoric-sdk/issues/5), so maybe #5 is what you meant to close.

**Comment by michaelfig** [comment]
Yes, the monorepo conversion has messed up all the intra-repository issue references. ☹️

**Comment by erights** [comment]
@warner I'm closing this as done or obsolete, but assigning you in case I'm wrong.
