### ISSUE TITLE
I (MarkM) still need to review bondingCurve for roundoff handling

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#428]
I LGTMed https://github.com/Agoric/agoric-sdk/pull/380 without doing a careful review of bondingCurve.js for how it handles rounding, and how well it corresponds to the Runtime Verification paper verifying the `x*y=k` bonding curve specs and algorithms.

**Comment by erights** [comment]
So this issue is a reminder that I need to get back to this sometime after that PR is merged.

**Comment by erights** [comment]
Looking at the paper again, I don't find anything that directly matches my flawed memory of what I found disturbing. The closest is the difference between the inequalities of Theorem 8 and the inequalities of Theorem 11. It is interesting that despite these inequalities, Theorem 12 has the same symmetry as Theorem 10.

If we verify that our implementation has the same difference in inequalities but the same symmetry, that would take care of my worries and we should close this.

Reassigning to @Chris-Hibbert who's agreed to take on this code.

**Comment by Chris-Hibbert** [comment]
Theorem 8 and Theorem 11 have to be conservative in opposite directions. Thm 8 is computing "how much Y should I pay for X?" (after fees), while Thm 11 is computing "how much X should I charge for Y?" (after fees). 8 rounds prices up, and 11 rounds proceeds down.

Each line of theorem 10 says the (theoretical) pricing functions give consistent answers regardless of whether you ask "how much would I get for P?" or "how much would I have to pay to get Q?". If the client would have to pay $B to get $C at the current rates, then if they asked how much they'd get for $B, the answer would be the same. Theorem 12 is says that the code (vs. the spec) does some rounding, so the answers may not be exactly the same.

I'll add some test cases to show that the price quotes are consistent.
