### ISSUE TITLE
rework kernel setup process

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#435]
We need to change the way a Swingset kernel is built, to accomodate both the new SES scheme ("fix the one shared world" instead of "create a new safe world") and the XS scheme (the world is born safe).

When I started Swingset, I wasn't really thinking clearly about the "host": the code that creates/configures a Swingset kernel, its initial vats and devices, and then provokes the kernel into doing work. These days, I consider Swingset to be a library, a facility that is used by host authors to built an ocap-based application. The host author has certain obligations to provide Swingset with things it needs to do its work. And in the new approach, one of those obligations is to construct and provide a safe SES environment where the kernel can do its work.

So I'm thinking of three docs:

* "care and feeding of a Swingset": describes what the host must provide to a Swingset when building it: configuration data (genesis vats/devices), a SES environment, a HostDB object to store kernel state. This also describes how to cycle the kernel in a way that keeps the saved state coherent (checkpointed only at the end of blocks), and how/when to release outgoing messages (to prevent "hangover inconsistency")
* how to build a (new) SES environment under Node.js, and load the kernel/vats correctly. I expect to learn more about the new SES this week, but I imagine this will involve importing some SES library from npm and running some "make my world safe" function, with some options. Then I expect a SES call to create a `Compartment` that loads the initial Swingset module. I wouldn't be surprised if it only works with modules (so if we have any CJS-shaped dependencies, we may still have to use `rollup`). I also wouldn't be surprised if we have to build a module map / manifest / module loader policy before loading the compartment. This document also needs to talk about SES-vs-non-SES (if we still need non-SES for debugging), and how Vat functions should be defined (to enable as much debugging information as possible: do we provide a source filename so non-SES mode can do a plain `require`? or is a string with an attached sourcemap sufficient?).
* the third document should describe what to do under XS. I suspect the SES setup step is much much shorter, possibly empty, but this depends upon how SES and XS co-evolve. I expect the module-map setup to be larger, possibly requiring custom tools to crawl the Swingset (and host app) module tree and putting everything into a JSON file before the XS compiler is executed.

**Comment by jfparadis** [comment]
@warner, some notes:
- for your docs 2 and 3, we have a few layers, 
    - a SES shim (minimal on XS)
    - devices 
    - a runtime 
    - a build process. 

I think we need to reason it as separate layers for each platforms, but most importantly keep the docs structured the same way.

- For your doc 1, we can go in two steps, 
    - step 1 babel + rollup (single bundle)
    - step 2 babel + custom transform (multiple files). 

I think it makes sense to start with the bundle since we don't support commonjs  in the module-transforms and neither does XS.

**Comment by dckc** [comment]
When you say "we have a few layers" do you mean we already have them? If so, where is the SES shim on XS? Do you mean https://github.com/dckc/agoric-sdk/blob/xs-build-lite/packages/cosmic-swingset/lib/xs-npm/ses.js 338b6a1 ?

**Comment by jfparadis** [comment]
@dckc The layers exits, but not labeled as such. And the SES shim on XS could be something more like this https://gist.github.com/jfparadis/21c16afae0716781754ac8a980db1db2

In my mind, you file is more like a version to version adapter, it maps what SwingSet expects (SES shim for node V1) to the engine available (SES on XS V1). I expect there will always be such a file to allow version independence. I really like your adapter, I wished we structured code like that more often!

**Comment by warner** [comment]
The main Swingset constructor (currently named `buildVatController`) wants to get:

* a list of Genesis Vats, each with a `name` (which gets passed to the `bootstrap()` function), `options` (currently limited to `enablePipelining`), and something that points to a `setup()` function
  * for `setup`, `buildVatController` currently accepts a pathname and is responsible for either doing `require` (in non-SES mode), or calling `buildSourceBundle` to convert the pathname into a single rollup'ed string (in SES mode). The benefit of `require` is that provides all the expected debugging information, but of course it's not running under SES.
* a list of Genesis Devices, each with `name`, `options` (empty), a pointer to a `setup` function (again a pathname right now), and a set of endowments that should be made available to the `setup` function
* an "arguments" object (currently spelled `argv`), which we currently use to tell the new swingset what mode it should run in `scenario3-client`/etc
* a `hostStorage` object, which must implement a particular "StorageAPI". The kernel calls this all the time to read/write the clists, object/promise tables, and transcripts.

The object it returns provides two main methods. `step` executes just one thing off the run-queue, and `run` keeps executing until the run-queue is empty. Both return a Promise that fires after the execution is done. While these execute, the `hostStorage` object will be used to read and write various bits of kernel state, and device endowments might be invoked.

**Comment by dckc** [comment]
...
>   * for `setup`, `buildVatController` currently accepts a pathname and is responsible for either doing `require` (in non-SES mode), or calling `buildSourceBundle` to convert the pathname into a single rollup'ed string (in SES mode).

I'd like to see `import()` used in place of `require()` and `buildSourceBundle`. It looks like the SES API is headed that way:

https://github.com/Agoric/agoric-sdk/issues/426#issuecomment-577349802

**Comment by warner** [comment]
yeah, although specifically we want the static form `import buildKernel from '@agoric/swingset-vat'`, rather than the dynamic form `const buildKernel = import('@agoric/swingset-vat')`. The latter will probably be denied entirely, because in some engines it maps to the platform's importer, which can reach for any URL and cause network access.

**Comment by dckc** [comment]
Rather than deny it entirely, I think we can provide a `loader()` that works like `import()` except that it only loads pure modules.

I worked out some of the details: https://gist.github.com/dckc/cbbd3e8469723b342cc90799ace7a287

**Comment by warner** [comment]
This is pretty much done.
