### ISSUE TITLE
[agoric-cli, Zoe] myFirstDapp should be simpleExchange (the DEX)

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#440]
"myFirstDapp.js" is currently a hollowed-out version of `autoswap.js`. Since `autoswap.js` is our most complicated contract, it doesn't work very well for tutorials for beginners. We should rewrite myFirstDapp so that it's a hollowed-out version of `simpleExchange.js` instead. `simpleExchange.js` is a decentralized exchange (DEX) with a very naive order book (arrays of orders which are iterated over to find matches). We can seed the DEX with a number of orders to start with, in the same way that we started off autoswap with liquidity. 

We would also need to [change the UI ](https://github.com/Agoric/agoric-sdk/issues/541)(take the autoswap-frontend, copy it, and modify it to display an order book in addition to being able to make offers.)

Remaining tasks

 - [x] add a public function to display book orders   (update to use units)
 - [x] add a public function to describe a live book offer
 - [ ] update agoric-cli to integrate and initialize the myFirstDapp simple exchange

**Comment by DavidBruant** [comment]
Is this issue closed as a consequence of #555 being merged?

**Comment by katelynsills** [comment]
I think this part is still undone but I could just not be caught up:

> update agoric-cli to integrate and initialize the myFirstDapp simple exchange

**Comment by Chris-Hibbert** [comment]
The basic framework is in place, but we're still working on features to support the frontend.

**Comment by Chris-Hibbert** [comment]
We're still working on the frontend, but [that's a separate issue. ]( https://github.com/Agoric/agoric-sdk/issues/541)
