### ISSUE TITLE
[cosmic-swingset] Sending OfferRules from Dapp UI Can't Handle the Assay Presences

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#448]
Now that I'm working in cosmic-swingset, I remember that there was a pretty horrible gap in functionality that JF was able to get around for the hackathon, but it'd be great to solve now that we have more time.

Our original design was that the autoswap UI (and other dapp UI) would be able to propose offerRules and send them to your wallet UI which sends it to the wallet on your ag-solo (@jfparadis, please correct me if wrong). 

But, that communication path can't handle presences, so this design doesn't help us much since our offerRules have units in them, which have assay presences. JF had a great temporary solution: replace these presences with the registrar keys for those same assays when sending, then rehydrate on the other side.

Is there any work to be able to "send" presences with the same functionality that we have between vats in swingset? My guess is that this requires something like CapTP over the "bridge" between the autoswap-frontend and wallet-frontend, but I'm sure I don't fully understand it.

**Comment by katelynsills** [comment]
Mark noted that in the upcoming [ERTP v0.3.0](https://github.com/Agoric/agoric-sdk/projects/2?card_filter_query=milestone%3A%22ertp+0.3.0%22), we plan to remove nearly all methods from payments. The only remaining methods would be `getMemo` for getting a string memo, and `getAllegedBrand` for getting a brand presence. Neither of these methods should be order-dependent in a way that would make 3-party handoff difficult.

(When a payment is used up, it is deleted from the weakmap of payments, but the object still remains if anyone has a reference to it. Therefore, it is reasonably safe to assume that these methods can be called in any order. )

Mark says: 
 "Ok, since 
* the restriction is useful, 
* we may already satisfy it in the next ERTP, 
* or at least we're close

we should keep it in mind as a design constraint. Then we'd have a uniform ocap/captp fabric at least for the payments and amounts needed for most ERTP communications, and perhaps all ERTP communications where we really need 3-party handoff."

**Comment by erights** [comment]
The restriction being that we invent some way to mark an object as having an order-invariant API, and, for now, we only support 3-party handoff for such objects. This might give us everything we need in the short to medium term while postponing the message ordering issues that make general 3-party handoff so hard (wormholeOp).
