### ISSUE TITLE
detecting an empty vat promise queue (end of "crank")

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#45]
This test seems to be failing on xs (now that my tape work-alike is actually working):

https://github.com/Agoric/SwingSet/blob/7cd651107a31ba84d9b9f11610d72b5477035fd9/test/test-queue-priority.js#L5

```json
{"actual":[1,2,3,5,6,4],"expected":[1,2,3,4,5,6]}
```

What's the justification for that test? Is the queue priority specified?

In what way does SwingSet rely on the queue priority?

cc @warner @phoddie

**Comment by dckc** [comment]
### preempting queued callbacks looks tricky with glib

I found that the xs `lin` platform uses the [glib main loop API](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html). At first, this made me think addressing this issue is a matter of specifying `G_PRIORITY_HIGH` when queuing promise jobs.

But `g_main_context_iteration ()` works like this:
> Runs a single iteration for the given main loop. This involves checking to see if any event sources are ready to be processed, then if no events sources are ready and may_block is TRUE, waiting for a source to become ready, then dispatching the highest priority events sources that are ready.

Recall the test code:

```js
  const log = [];
  setImmediate(() => log.push(1));
  setImmediate(() => {
    log.push(2);
    Promise.resolve().then(() => log.push(4));
    log.push(3);
  });
  setImmediate(() => log.push(5));
  setImmediate(() => log.push(6));

  t.deepEqual(log, [1, 2, 3, 4, 5, 6]);
```

By the time the `push(4)` is queued, glib has already prepared to dispatch 5 and 6 and using `G_PRIORITY_HIGH` doesn't preempt that.

I was going to say this can't be done with glib, but they do break down `g_main_context_iteration` in such a way that parts of it can be replaced:

> Customizing the main loop iteration
> Single iterations of a GMainContext can be run with g_main_context_iteration(). In some cases, more detailed control of exactly how the details of the main loop work is desired, for instance, when integrating the GMainLoop with an external main loop. In such cases, you can call the component functions of g_main_context_iteration() directly. These functions are g_main_context_prepare(), g_main_context_query(), g_main_context_check() and g_main_context_dispatch().

So we could make a customized version of `g_main_context_dispatch` that handles this sort of preemption. But it's around [100 lines of pretty tricky looking code](https://github.com/GNOME/glib/blob/mainline/glib/gmain.c#L3215-L3304).

**Comment by michaelfig** [comment]
Can we do something like:
```js
const waitForPromises = inXS
  ? cb => setTimeout(cb, 1) // or other XS primitive?
  : cb => setImmediate(cb);
```

because AFAICT, `setImmediate` is only used by SwingSet to detect when no more promises will run.  Or maybe some other primitive to execute only when the promise queue is done, not necessarily futzing with the relative priorities of the existing methods?

**Comment by dckc** [comment]
yes, @michaelfig , something like that. @warner and I chatted about this and now I think I understand the requirements better. It need not involve `setTimeout` at all. I updated the issue title as such.

**Comment by phoddie** [comment]
This seems complicated. Are you trying to implement the proposed behavior where settled promises always take priority over host callbacks?

I believe you are working on Linux? If so, it would seem easier to modify your Linux host in lin_xs.c. The promises callbacks are invoked when fxQueuePromiseJobsCallback calls fxRunPromiseJobs. fxRunPromiseJobs calls all promises settled when it begins execution, but not those settled during its execution.

Maybe something like this will do what you want?

	gboolean fxQueuePromiseJobsCallback(void *it)
	{
		txMachine* the = it;
		do {
			fxRunPromiseJobs(the);
		} while (mxPendingJobs.value.reference->next);
		return G_SOURCE_REMOVE;
	}

**Comment by dckc** [comment]
Thanks, @phoddie . Something like that may very well work.

But the core of the issue is not really priority of promises vs. host callbacks. It's about detecting when the promise queue of a "vat" under the control of a "kernel" is empty. The "kernel" was using `setTimeout()` to queue something that would only come back after the "vat" was done with all the promises it wanted to queue for itself.

**Comment by phoddie** [comment]
> But the core of the issue is not really priority of promises vs. host callbacks. It's about detecting when the promise queue of a "vat" under the control of a "kernel" is empty. The "kernel" was using setTimeout() to queue something that would only come back after the "vat" was done with all the promises it wanted to queue for itself.
> 
How do you do that in a browser?

**Comment by dckc** [comment]
Browsers presumably work like node. The original test passes in chrome (with `const setImmediate = f => setTimeout(f, 0)`).

**Comment by phoddie** [comment]
I guess I'm not following the goals here well enough.

I more-or-less understand how JavaScript behaves and how the XS host provides parts of that. I don't know about vats and kernels and the needs they have from promises.

I apologize for jumping in. I'll stand aside on this one.

**Comment by dckc** [comment]
Yeah; I put "vat" and "kernel" in quotes because they're somewhat local terms of art.

There are some docs in https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet/docs but I'm not sure even those are up to date.

No need to apologize; I think you may well have helped.  But standing aside is fine too.

**Comment by dckc** [comment]
On xs, I'm getting:
```
# Exception: replay: cannot coerce undefined to object!
```

I traced it to empty `playbackSyscalls` at `s = playbackSyscalls.shift()`:
https://github.com/Agoric/agoric-sdk/blob/f833610831e687c65a28a0069dc58e74b18d7321/packages/SwingSet/src/kernel/vatManager.js#L214-L216

Is it possible this queue priority stuff is to blame?

**Comment by dckc** [comment]
fixed in #2194

**Comment by dckc** [comment]
double-check that the `setImmediate` queue is empty too in xsnap
(from discussion with @warner)

**Comment by dckc** [comment]
Oh yeah... we turned off `setImmediate` in the current xsnap. I wonder if/how liveslots is going to work without it. I'll press on and see...
