### ISSUE TITLE
Stop exposing 'map' in the API returned from buildStorageInMemory()

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#460]
buildStorageInMemory() has a side API to expose the map used in its underlying implementation, so that cosmic swingset can efficiently iterate it to persistent storage.  This is a modularity violation that should go away once the default storage is persistent directly (and hence cosmic swingset will not be using the in-memory version of the storage API).  See issue [#454](https://github.com/Agoric/agoric-sdk/pull/454/#discussion_r370962542)

**Comment by warner** [comment]
This is probably done, and irrelevant anyways because it's only used in test code.
