### ISSUE TITLE
Should our policy on doc comments be minimalistic or maximalistic

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#464]
@Chris-Hibbert raises a worthwhile question in a code review, which goes beyond the scope of just the fragment of code being reviewed:

My attitude toward javadoc comments on methods and classes is that it's a great idea to include them for anything intended to be used beyond the current file, and anything important internally. However, parameter doc and return value doc are often noise. BuildBlockBuffer (above) and this function return something interesting, and are worth documenting. basedir here is not so helpful, and I might have omitted it. I think that's a matter of personal taste.

What's your theory?

**Comment by katelynsills** [comment]
For what it's worth, VS Code is able to pick up jsdoc style comments and display them such that while you are typing out the function, you'll get any comments in regards to parameters and return values, i.e. `memo`: "used as the payment memo field"  So, I like the maximalistic jsdoc style myself.

Also, it's easier to automatically generate API documentation from the jsdoc style comments.

**Comment by erights** [comment]
I like to use javadoc comments to explain an API from the caller's pov --- what it does, not how it does it. This is often the first attempt to write down a spec of the external behavior it is supposed to uphold.

I like to use non-javadoc style comments in code to explain how the code works, or anything else that users of the module don't need to know from the outside.

In Java, when multiple pieces of code implement the same specified behavior, we create an interface (or a very abstract superclass) and put the common spec there. This also unburdens the implementation code from these lengthy explanations. Unlike Java, JavaScript has no interface declarations. I really like where the chainmail / idl / *.d.ts file experiments are taking us: Separate *.d.ts typescript interface declarations with both types and behavioral specifications. Kept separate to keep the implementation code uncluttered.

**Comment by katelynsills** [comment]
I think we've decided on maximalist comments but in the types.js and internal-types.js files.

**Comment by Chris-Hibbert** [comment]
I'm mostly satisfied by the level of detail we've settled on for interface (and other) types even though it's outside the source file. vsCode seems to be cajoling enough people that we're keeping it up to date, at least as far as describing types, if not behavior.

I think this issue can be closed.
