### ISSUE TITLE
sharing tests with xs works better with modules

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#49]
@warner @katelynsills ,

The top-level script environment with xs is different from node. There _might_ be a way to run test scripts unchanged, but my approach so far is to import them from a main module (and preload stuff like `console.log` ...). This only works if they're modules rather than scripts.

For example:

turn test-marshal script into module
https://github.com/dckc/SwingSet/commit/8bf4116679d57fd3ce80fee589101024d485f891

turn test-kernel into module
https://github.com/dckc/SwingSet/commit/2604eaf026c2e40d3f2742cd283cb956d6d66ada

I didn't indent all the calls to `test()` so this doesn't pass `lint-check`. I'd like to get some feedback before I do that sort of thing.

I appended a few lines so that they still work as tape scripts in node:

```js
if (typeof require !== 'undefined' && typeof module !== 'undefined') {
  runTests();
}
```

for reference: my current top level main, manifest, and preload, which handles all of test-marshal and test-kernel:
https://github.com/dckc/SwingSet/blob/xs-platform/test-xs-main.js
https://github.com/dckc/SwingSet/blob/xs-platform/test-xs-manifest.json
https://github.com/dckc/SwingSet/blob/xs-platform/preload.js

**Comment by dckc** [comment]
I see more tests being written with calls to tape's `test()` at the top level. None of those will work on xs. I guess I need to communicate some more.

**Comment by katelynsills** [comment]
One thing that might work is using Rollup's `plugin-replace` to add the code that you need to the top and bottom of each test. [The 'integration-test' folder in Nat uses this approach to test Nat in different scenarios in the browser](https://github.com/Agoric/nat/tree/master/integration-test/transform-tests/config):

```
import replace from '@rollup/plugin-replace';

export default [
  {
    input: '../test/test.js',
    output: {
      file: 'transform-tests/output/test.cjs.js',
      format: 'cjs',
    },
    external: ['@agoric/nat', 'tape'],
    plugins: [
      replace({
        delimiters: ['', ''],
        "import Nat from '../src/index';": "import Nat from '@agoric/nat';",
      }),
    ],
  },
];
```

This should allow you to use the tests without having to change the contents of the tests manually. If you make it part of your build step, it should work for any updated tests as well.

**Comment by dckc** [comment]
Is there normally a build step for running tests?

(I'm back to this issue because new tests continue to roll in that use `test()` as ambient authority. https://github.com/Agoric/agoric-sdk/commit/d1890e239bb65d7962830a437e6295599dc0e2cc )

**Comment by dckc** [comment]
in discussion with @jfparadis today I realized I could probably run our `tape()` style tests without change. I think I'll give it a try...

**Comment by dckc** [comment]
it works! I can run the main `eventual-send` test script un-modified on xs.

https://github.com/dckc/tape-xs d6a1f19

IOU an explanation of how. perhaps in the README

cc @erights
