### ISSUE TITLE
[Zoe] zoe.chainmail concerns

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#496]
This Issue is updating the concerns mentioned in #98 by @DavidBruant  for the current Zoe chainmail.

- [x] Explain what a "handle" is (an empty object as an id) and why we use it rather than a numeric id.
- [x] Define an instanceRecord struct and the other record structs from state.js
- [x] Explain why it is helpful to have an installation and install step separately (To have a unique identifier for specific contract code that can be referenced and reused. For example, once you have looked at the atomicSwap contract and saved the installationHandle for that code, you can look at any future invite and know for certain that if it used that installationHandle when the instance was created, it used code you examined.)

**Comment by katelynsills** [comment]
@DavidBruant, is this something you could take on? If so, comment below (apparently commenting [is necessary](https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)?) and I'll assign the task to you.

**Comment by DavidBruant** [comment]
>  Explain what a "handle" is (an empty object as an id) and why we use it rather than a numeric id.

I added a defintion to the documentation glossary. See https://github.com/Agoric/documentation/pull/109

I think it'll be enough, no need to add something to the chainmail about this

**Comment by katelynsills** [comment]
Sounds good. What do you think about the other two task items? Also, @tyg is working on related issues writing up his Intro to Zoe.

**Comment by DavidBruant** [comment]
>  Define an instanceRecord struct and the other record structs from state.js

I addressed this in #878 

> Explain why it is helpful to have an installation and install step separately

I'm going to write something somewhere and when the intro to zoe is merged, we can figure out where the best place is for this

**Comment by katelynsills** [comment]
Sounds great!
