### ISSUE TITLE
Expose key PSM economic data via subscription

### ISSUE THREAD

**Issue by turadg** [Agoric/agoric-sdk#4968]
## What is the Problem Being Solved?

Users and economic committee need to know metrics like total value locked.

## Description of the Design

TBD akin to the list in https://github.com/Agoric/agoric-sdk/issues/4649

## Security Considerations
TBD
## Test Plan
TBD

**Comment by Tartuffo** [comment]
@turadg is the Vault side of this covered by #4649?  We probably need a separate PSM issue that is a sub-issue of Epic  #4639.  You could change this ticket to be about exposing PSM economic data.
