### ISSUE TITLE
CI: does the cache save us time?

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#502]
If you look at the timings on https://github.com/Agoric/agoric-sdk/pull/489/checks?check_run_id=426471769 , it looks like we're spending 5 minutes hashing the `go.sum` and `yarn.lock` files to conclude that nothing has changed and thus we don't need to save the cache.

I'm guessing that the sheer number of files in go/pkg/mod and node_modules means anything which traverses `**/` is going to take forever, so we might want to change those to 1: only hash the single top-level yarn.lock (since there shouldn't be any others), 2: is there a similar top-level go.sum we could hash instead of finding all 67 of them?, 3: do we really need to invalidate these caches when those checksum files change anyways?

The caches in question are only about 90MB each, so I'm not sure we're saving time overall there. Maybe we should just omit the cache actions from our `.github/actions/test-all-packages.yml`?

**Comment by michaelfig** [comment]
1 and 2 are absolutely right... Only the top-level `yarn.lock` and `packages/cosmic-swingset/go.sum` are needed.

I'll put together a PR and benchmark it.

Thanks for raising this, @warner

**Comment by michaelfig** [comment]
This behaviour was fixed in actions/runner#268 but it has not yet been deployed to Github.  I'm looking to find an ETA for when Github's Actions will deploy the fix.

**Comment by michaelfig** [comment]
At @dtribble's request, I have disabled the cache in https://github.com/Agoric/agoric-sdk/commits/4cae3360d645a1ebe8dd707fa07e75b6a446e9c3

Leaving this issue open to revisit (and revert that commit) once Github Actions have deployed the fix described above.  If it's past 2020-04-01, try doing that!

**Comment by michaelfig** [comment]
Now the cache saves us time!
