### ISSUE TITLE
add simpler way to create comms/vattp vats

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#51]
We shouldn't have to put stub `vat-comms.js` or `vat-vattp.js` files into basedirs to create the comms layer. Instead there should just be some `config` flag that says "yes I want comms" and it should make the necessary vats (using standardized names so the bootstrap code can wire them up correctly).

It might be nice to wire up the comms and vattp vats automatically too. Doing that will reduce the amount of boilerplate in `bootstrap.js`, leaving just the initial ingress/egress calls (which we should find a way to simplify too).

**Comment by warner** [comment]
@Chris-Hibbert I think this is done now, please close if you agree

**Comment by Chris-Hibbert** [comment]
I don't think so. Leaving it open as there's work to do to make creation of these vats happen by default the way we now do with the vatAdmin vat and device.
