### ISSUE TITLE
[Zoe, ERTP] Zoe and UniExtentOps are incompatible, get rid of UniExtentOps?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#510]
Zoe has a purse for each known assay and tries to put the payments for that assay into the purse. UniExtentOps, by design, errors on a `with` operation if the purse is non-empty, which is what occurs when a second payment is deposited into a purse. So, anything using UniExtentOps is not compatible with Zoe if we ever expect more than one of them to be escrowed with Zoe at any one time.

I think we want to use something like the ListExtentOps instead, but currently the ListExtentOps has incredibly bad performance.

**Comment by erights** [comment]
Given, https://github.com/tc39/proposal-readonly-collections , could we use FixesSets instead of arrays? Would that fix the performance issues of ListExtentOps. Should all current ListExtentOps become SetExtentOps? Do we ever currently use the list to provide anything other than set-like semantics?

**Comment by DavidBruant** [comment]
I feel like ListExtentOps is strictly more useful than UniExtentOps. The only difference i see is that ListExtentOps enables the payment/purse to hold several different rights of the same assay while UniExtentOps only allows for one.
ListExtentOps is to NatExtentOps what UniExtentOps would be to "OneExtentOps" (ops that restricts a purse/payment to only contain a single unit of a fungible asset)
I'm unable to think of a concrete use case where this limitation is useful at the mint configuration level. Among other things, nothing prevents someone from storing their multiple payments/purses in a JavaScript array/set, so the limitation is easily bypassed

Getting rid of UniExtentOps feels fair

---

> Do we ever currently use the list to provide anything other than set-like semantics?

Not in the current implementation

> Should all current ListExtentOps become SetExtentOps?

This seems fair

---

One reason for the bad performance is quadratic complexity in the current implementation. For previous discussion on the topic: https://github.com/Agoric/agoric-sdk/issues/331
This seems solvable via a refactoring (possibly also modifying the `makeListExtentOps` arguments)
Is there another reason why the perf is bad?

**Comment by katelynsills** [comment]
I think we can probably use a set for most non-fungible cases, since they are probably unique, but not all cases. 

For instance, perhaps the asset kind is partially fungible. In our seats example, we might have specific, unique seat extents, such as 'A1', but we might also have 'general' seating where you are allowed in the standing area.  All general seats are fungible with each other, but seats aren't generally fungible. So, we can either fudge the representation to add a unique identifier so it can be used in a set, or we need to use an array still. 

@erights is FixesSets something we could use this week or next week? If not, we would probably need to use arrays for the Zoe Alpha Release.

**Comment by katelynsills** [comment]
> This seems solvable via a refactoring (possibly also modifying the `makeListExtentOps` arguments)
> Is there another reason why the perf is bad?

Probably it's lack of attention and a need for refactoring, but the worst case scenario for lists is probably when we can't sort the extents because they're "handles" or empty objects. If we can't sort them in some reliable order, it's hard to optimize.

**Comment by DavidBruant** [comment]
> For instance, perhaps the asset kind is partially fungible. In our seats example, we might have specific, unique seat extents, such as 'A1', but we might also have 'general' seating where you are allowed in the standing area. All general seats are fungible with each other, but seats aren't generally fungible. So, we can either fudge the representation to add a unique identifier so it can be used in a set, or we need to use an array still.

Can this use case be solved with ListExtentOps or should a new different ExtentOps be created for this purpose?

**Comment by katelynsills** [comment]
> Can this use case be solved with ListExtentOps or should a new different ExtentOps be created for this purpose?

It can be solved with ListExtentOps. We probably want a specialized extentOps for partially fungible digital assets at some point, but if we don't absolutely need it in an MVP sense, let's not do it now.

**Comment by erights** [comment]
> @erights is FixesSets something we could use this week or next week? If not, we would probably need to use arrays for the Zoe Alpha Release.

Even if we figure out how to use sets, I would not consider it for the Zoe Alpha timeframe. I was suggesting only longer term.
