### ISSUE TITLE
swingset JS-engine heap snapshots

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#511]
To restart a Swingset vat in a reasonable amount of time, we need a way to capture the full object graph of a vat (the "heap snapshot") and save it to disk, then later reload that snapshot into memory and pick up where we left off. We currently simulate this by recording all the inbound messages (calls to the `dispatch` object, like `dispatch.deliver`), which are pure data, and then replay them one at a time at restart time. This takes O(N) space and time, where N is the number of messages that have been sent.

We need engine support to create a snapshot that takes O(A) space and time, where A is the size of the active set: the objects reachable from the vat-side export tables. This is not something that can be done from pure Javascript. We probably need this snapshot to be deterministic.

We expect to extend XS to get this functionality: it's not too much different than the way XS starts up (running some "pre-init" code on the build host, then serializing the resulting object graph into tables that are written out to C code). XS currently reloads the snapshot with the help of a C compiler, so we'd need to change that part.

**Comment by zarutian** [comment]
>  This is not something that can be done from pure Javascript

Not easily but it can be [done](https://github.com/NeilFraser/JS-Interpreter/blob/master/demos/serialize.js) but not from inside of the same js environ.

**Comment by dckc** [comment]
@phoddie any chance I missed an easier way to do this?

I see [fxPrintHeap](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/tools/xslSlot.c#L853-L901) but it assumes that `the->context` is a `txLinker*`. It's called from `main()` in xsl.c:
https://github.com/Moddable-OpenSource/moddable/blob/public/xs/tools/xsl.c#L545

I don't see any way to reuse any of that code, so it looks like we'll have to copy and adapt it... all the code that prints `gxPreparation` and its parts (stack, heap, names, ...). It looks like about 50 lines of code in `xsl.c` and most of `xslSlot.c`, which weighs in at 1250 lines.

I had hoped to find some API that I could call to make a tiny demo of a writing a snapshot to a file and reading it back in, but it looks like I need to adapt some ~1500 lines of code (or some working subset of it) to get off the ground.

Hmm... I see [fxCloneMachine](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsAPI.c#L1508-L1636), which seems to walk the whole machine state. Maybe that would be another approach? It's more like 125 lines.

**Comment by phoddie** [comment]
fxCloneMachine is a runtime operation that creates a new VM on top of a shared (frozen) VM. It is what we use to instantiate a VM from the frozen VM in ROM/flash. It isn't what you want.

The code in xsl.c creates the C source code to build that frozen VM. As you observed, it is not a trivial process. The good news is that it is complete and it works -- we use it every day.

However, what it does is not exactly a snapshot. We only ever use that VM as read-only data. I believe you want to continue executing that VM. In that case, there's some new work to instantiate the VM around it, rather than using fxCloneMachine.

**Comment by dckc** [comment]
First, I was making this harder than it is. We don't require snapshot/restore of the xs machine; just a graph of objects, modulo some exits. @warner suggested: `data = magicSnapshot(start, [exits])`.

Next, @erights suggested ...
> debuggers have omnicient access to data that is insulated from inadvertant side effects. I certainly don't want to traverse one JSON RPC at a time. But there's something receiving and acting on those messages. Maybe that's a place to stand to do a transitive complete side-effect-free snapshot of an object graph starting at a root?

"The port of xsbug defaults to 5002 by convention." according to [XS Platforms docs](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20Platforms.md).

So I fired up `nc -l -p 5002` and launched `moddable/examples/helloworld$ mcconfig -d -m`. And lo, nc received and reported:

```xml
<xsbug><login name="mc" value="XS"/></xsbug>
```

Based on some poring over `xsDebug.c`, I uttered `<select />` and voila, I got a dump of the globals and modules. I think locals are available, but none were in scope:

```xml
<xsbug><global><property flags="+cEw_" name="Array" value="@00007FEC26BBF8C0"/><property flags="+cEw_" name="ArrayBuffer" value="@00007FEC26BC2300"/><property flags="+cEw_" name="Atomics" value="@00007FEC26BC3F20"/><property flags="+cEw_" name="BigInt" value="@00007FEC26BC0660"/><property flags="+cEw_" name="BigInt64Array" value="@00007FEC26BC3100"/><property flags="+cEw_" name="BigUint64Array" value="@00007FEC26BC3220"/><property flags="+cEw_" name="Boolean" value="@00007FEC26BC01C0"/><property flags="+cEw_" name="DataView" value="@00007FEC26BC28C0"/><property flags="+cEw_" name="Date" value="@00007FEC26BC0D80"/><property flags="+cEw_" name="Error" value="@00007FEC26BC1AE0"/><property flags="+cEw_" name="EvalError" value="@00007FEC26BC1BE0"/><property flags="+cEw_" name="FinalizationGroup" value="@00007FEC26BC5800"/><property flags="+cEw_" name="Float32Array" value="@00007FEC26BC3340"/><property flags="+cEw_" name="Float64Array" value="@00007FEC26BC3460"/><property flags="+cEw_" name="Int16Array" value="@00007FEC26BC36A0"/><property flags="+cEw_" name="Int32Array" value="@00007FEC26BC37C0"/><property flags="+cEw_" name="Int8Array" value="@00007FEC26BC3580"/><property flags="+cEw_" name="JSON" value="@00007FEC26BC2180"/><property flags="+cEw_" name="Map" value="@00007FEC26BC4D60"/><property flags="+cEw_" name="Math" value="@00007FEC26BC0E80"/><property flags="+cEw_" name="Number" value="@00007FEC26BC0360"/><property flags="+cEw_" name="Object" value="@00007FEC26BBE940"/><property flags="+cEw_" name="Promise" value="@00007FEC26BC41A0"/><property flags="+cEw_" name="Proxy" value="@00007FEC26BC4900"/><property flags="+cEw_" name="RangeError" value="@00007FEC26BC1CE0"/><property flags="+cEw_" name="ReferenceError" value="@00007FEC26BC1DE0"/><property flags="+cEw_" name="Reflect" value="@00007FEC26BC4980"/><property flags="+cEw_" name="RegExp" value="@00007FEC26BC1880"/><property flags="+cEw_" name="Set" value="@00007FEC26BC5180"/><property flags="+cEw_" name="SharedArrayBuffer" value="@00007FEC26BC3E00"/><property flags="+cEw_" name="String" value="@00007FEC26BBFFC0"/><property flags="+cEw_" name="Symbol" value="@00007FEC26BC45E0"/><property flags="+cEw_" name="SyntaxError" value="@00007FEC26BC1EE0"/><property flags="+cEw_" name="TypeError" value="@00007FEC26BC1FE0"/><property flags="+cEw_" name="TypedArray" value="@00007FEC26BC2F60"/><property flags="+cEw_" name="URIError" value="@00007FEC26BC20E0"/><property flags="+cEw_" name="Uint16Array" value="@00007FEC26BC3A00"/><property flags="+cEw_" name="Uint32Array" value="@00007FEC26BC3B20"/><property flags="+cEw_" name="Uint8Array" value="@00007FEC26BC38E0"/><property flags="+cEw_" name="Uint8ClampedArray" value="@00007FEC26BC3C40"/><property flags="+cEw_" name="WeakMap" value="@00007FEC26BC5480"/><property flags="+cEw_" name="WeakRef" value="@00007FEC26BC56C0"/><property flags="+cEw_" name="WeakSet" value="@00007FEC26BC55C0"/><property flags="+cEw_" name="decodeURI" value="@00007FEC26BBE360"/><property flags="+cEw_" name="decodeURIComponent" value="@00007FEC26BBE3A0"/><property flags="+cEw_" name="encodeURI" value="@00007FEC26BBE3E0"/><property flags="+cEw_" name="encodeURIComponent" value="@00007FEC26BBE420"/><property flags="+cEw_" name="escape" value="@00007FEC26BBE460"/><property flags="+cEw_" name="isFinite" value="@00007FEC26BBE240"/><property flags="+cEw_" name="isNaN" value="@00007FEC26BBE2A0"/><property flags="+cEw_" name="parseFloat" value="@00007FEC26BBE2E0"/><property flags="+cEw_" name="parseInt" value="@00007FEC26BBE320"/><property flags="+cEw_" name="trace" value="@00007FEC26BBE520"/><property flags="+cEw_" name="unescape" value="@00007FEC26BBE4E0"/><property flags=" CEW_" name="Infinity" value="Infinity"/><property flags=" CEW_" name="NaN" value="NaN"/><property flags=" CEW_" name="undefined" value="undefined"/><property flags="+cEw_" name="Compartment" value="@00007FEC26BC5AC0"/><property flags="+cEw_" name="Function" value="@00007FEC26BBED60"/><property flags="+cEw_" name="eval" value="@00007FEC26BBE4A0"/><property flags="+cEw_" name="global" value="@0000560650FCE210"/><property flags="+cEw_" name="globalThis" value="@0000560650FCE210"/></global><grammar><node flags="+CEWM" name="/Resource.xsb" value="@00007FEC26BC67E0"/><node flags="+CEWM" name="/instrumentation.xsb" value="@00007FEC26BC65C0"/><node flags="+CEWM" name="/mc/config.xsb" value="@00007FEC26BC6640"/></grammar></xsbug>
```

I think `value="@00007FEC26BBF8C0"` refers to an actual address in memory. I'll continue to poke around...

I did notice a call to `fxEchoPropert` was guarded by `if (key->value.key.string[0] != '#')`; so the debugger seems to filter private class fields.

**Comment by phoddie** [comment]
The communication between xsbug and the the host does provide a great deal of information about the running machine, as you would expect. There's no attempt, however, to make that comprehensive. For example, the contents of ArrayBuffer and TypedArray are not displayed, maps and sets are not inspectable, etc. That can be changed, of course, but we have to sensitive about code size as the xsDebug.c code is installed on the microcontroller, which often has very constrained flash memory (1 MB or not uncommon, and less happens). You can could have more debugging capabilities as a compile time option, of course. That said, I'm not sure this avenue is ultimately easier, just different.

**Comment by dckc** [comment]
Yes, the debugger's approach to walking the machine state is largely analogous to the the linker's. `fxPrintSlot` is pretty similar to [fxEchoProperty](https://github.com/Moddable-OpenSource/moddable/blob/public/xs/sources/xsDebug.c#L1230-L1384). And the debugger's approach is, as you note, incomplete, unlike the linker.

But for somebody learning his way around the elephant, it's nice to have views from more than one angle.

**Comment by dckc** [comment]
ugh! this is driving me bonkers. @warner @michaelfig @jfparadis  help?! Here's hoping we can screen-share and you can show me what sort of insanity I'm suffering from.

some `slot->kind` is getting reset from `XS_ARRAY_BUFFER_KIND` (17) to 0 (undefined) when I call `xsSetArrayBufferLength`. I stepped thru with gdb and I can't find where things go wrong.

In the gist below, 9b2c6b8 seems to work fine, but when I try to snapshot a larger string (c37acf0), things go haywire. The gist includes all my debug prints in the README in both versions.

https://gist.github.com/dckc/52e43c8238e6202a0b90e157f0d74ae8

**Comment by phoddie** [comment]
Is it possible that slot is being garbage collected? `xsSetArrayBufferLength` allocates memory so it could trigger GC.

**Comment by dckc** [comment]
Thank you!

I switched from using a local C stack variable for my ArrayBuffer to `xsVar(0)` and that `slot->kind` no longer gets clobbered.

**Comment by dckc** [comment]
I'm working on serializing an array of two strings. It ends up tracing into prototypes and such, grabbing large parts of the runtime... lots of motivation for the `exits` arg.

Meanwhile, I had to deal with circular structures; I think I have a solution.

But I'm struggling to get my decoder (which is in .js for now) in sync with the encoder. Details, details...

 - 62a09c8 toward snapshot of complex objects (WIP)

p.s.

 - df184d5 found Array.prototype when walking heap

**Comment by dckc** [comment]
A basic array of scalars works now. And cycles.

I think I got `exits` working. It involves checking references against instances... which I think is kosher...

I started a PR, but there's some syncing to do on the base branch: https://github.com/agoric-labs/moddable/pull/2

**Comment by dckc** [comment]
@warner what's a good way to get a small but realistic test case for vat state?

p.s. got some clues; short version: https://github.com/Agoric/agoric-sdk/blob/master/packages/SwingSet/src/kernel/vatManager.js#L272

I think `data = magicSnapshot(start, [exits])` is mostly working, though I used a class constructor because that seems to be the most straightforward way to call C from JS in xs.

```js
        const s1 = new Snapshot();
        const rawbuf = s1.dump(root, exits);
```

**Comment by phoddie** [comment]
Congratulations on the progress. You can have a native function that is not associated with a class:

```
function snapshot(root, exists) @ "xs_snapshot";
```

**Comment by dckc** [comment]
How do I declare those from the js side using @? I didn't see any examples
nor documentation.

**Comment by dckc** [comment]
Oops. I see you answered that part too.

**Comment by phoddie** [comment]
The [examples for defining native functions](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#syntax-extension) in the XS in C document only shows an example of functions in a class. That is the most common case, but it works for stand-alone functions too.

If the documentation had included an example of a standalone native function, would that have helped here?

**Comment by dckc** [comment]
Yes; that bit of documentation is one of the places that gave me the impression that a class was the only supported syntax.

**Comment by phoddie** [comment]
Fair enough. The following text has been added to the next push of the XS in C document:

> Standalone functions -- functions that are not part of a class -- can also be implemented in C. The `@` syntax extension is used where the function body normally appears. 
> 
> ```
> 	function restart() @ "xs_restart";
> ```
> 
> The value of `xsThis` in the implementation of `xs_restart` matches the receiver, which is `xsGlobal` in the following invocation.
> 
> ```javascript
> 	restart();
> ```

It turns out there is at least one use of a standalone native function in the Moddable SDK, in the [webConfigWifi](https://github.com/Moddable-OpenSource/moddable/blob/f2e2ed271fca035f756b2b41c6e736e1a4cc8f6f/examples/network/wifi/webConfigWifi/main.js#L242) example.

**Comment by dckc** [comment]
next challenge: functions.

making slow progress...

**Comment by dckc** [comment]
if a function comes from a module in ROM, re-connecting it to the ROM seems tricky. I think I'm going to assume that ROM functions are all in exits.

**Comment by dckc** [comment]
got functions working in a few cases!

https://github.com/dckc/moddable/blob/0be772add377ee0e839e6f4efe84206574867dd5/examples/js/snapshot/main.js#L75-L90

I'm not quite sure how to put the toothpaste back in the tube when it comes to bytecode and closures, but I think I serialized the relevant pieces.

**Comment by dckc** [comment]
#### Restoring data from snapshots works in several cases.

I sat down to work on functions but first I verified my assumption that I could restore scalars, arrays, and such. It was of course more work than I expected but not too bad. (no new C code...)

 - 01a11e9 rebuild after deserializing, up to cycles (functions TODO) …

I invested in static type annotations on behalf of future-me and collaborators (since current-me could barely read the code written by two-weeks-ago-me).

#### How to restore functions from snapshots?

As to restoring functions, ` fxNewFunctionInstance` from `xsFunction.c` looks promising; I suppose I need to do what it does...

**Comment by dckc** [comment]
Array.fill ... dense

**Comment by dckc** [comment]
I saw another project using https://github.com/protobuf-c/protobuf-c lately; not sure which...

**Comment by dckc** [comment]
@warner and I were brainstorming about this and that and he mentioned that compiling vats to wasm could allow us to snapshot wasm instances.

That sounds possibly more straightforward than the spelunking thru the xs internals that I've done to date.

A little searching shows somebody else has tried this and had reasonably good luck with it: [wasm-persist](https://github.com/dfinity-side-projects/wasm-persist):
> This allows you to hibernate a WebAssembly instance and later start it up again at the exact place you left off.

hmm...
> This only snapshots globals, memory(s), tables.

I wonder if that would suffice.

Some research:
https://acmsocc.github.io/2019/slides/socc19-slides-s1-jeong.pdf

> Proto-Faaslets are a way to restore the execution state of a function without rerunning the code that got it to that state.
https://github.com/lsds/faasm/blob/master/docs/proto_faaslets.md

hm. Maybe it's not obvious how to do this after all.

**Comment by erights** [comment]
Event loop concurrency --- the turn model --- saves us here. We only need to snapshot when the stack is empty. Fortunately, IIRC, the stack is the only WASM state that cannot be snapshotted.

**Comment by warner** [comment]
The Moddable folks have pointed us at an `xsnap` tool which knows how to write the heap out to a file after executing a program, and how to load the heap from a file before executon. I've been working on providing them with a dataset to exercise a realistic portion of the engine. The tool is in:

https://github.com/Agoric/agoric-sdk/tree/xs-snap-generator/packages/xs-vat-worker/build-xsnap

This contains a tool which converts a "slog" trace into a sequence of files that ought to be executable by the xsnap tool. The first file sets things up, the second delivers a single message, the third delivers the next message, etc. The idea is to run each file with "xsnap -r state.xsnap FILENAME -w state.xsnap" to chain the state along.

I don't know exactly how to get SES set up in the XS world. Our usual "import @agoric/install-ses" (which imports the SES shim and then calls lockdown()) doesn't seem to work. So I disabled that, adding a simple "harden = Object.freeze", to see how far I could get without it. The Makefile has two different options (make output-node vs make output-xsnap) to set up one option or the other.

Currently when I attempt to load the first file, it goes into an infinite loop reading a single module over and over. I'm wondering if I've exceeded a size limit somewhere. The module contains about 80kB of JS, and is more or less the bare minimum we need to exercise a vat.

To rebuild the files, you'll need to checkout the agoric-sdk tree, do the usual 'yarn' and 'yarn build' at the top level, then:

* cd packages/xs-vat-worker/build-xsnap
* make clean-output output-xsnap run-xsnap

(again, assuming that "xsnap" is already in your $PATH)

**Comment by michaelfig** [comment]
> I don't know exactly how to get SES set up in the XS world. Our usual "import @agoric/install-ses" (which imports the SES shim and then calls lockdown()) doesn't seem to work. So I disabled that, adding a simple "harden = Object.freeze", to see how far I could get without it.

That solution would be insufficient for `@agoric/marshal`.  @erights probably knows what is necessary here.

**Comment by erights** [comment]
>  That solution would be insufficient for `@agoric/marshal`. @erights probably knows what is necessary here.

@warner, marshal requires that objects be already hardened, so simply `harden = Object.freeze` will not work. We *cannot* use XS's two argument `Object.freeze(obj, true)` because that does something else which does not work for us. (@dckc already tried). We need at least a working `harden`.

@dckc, how far have you gotten running our SES system on XS-SES? What version of our SES system did you start from?

@kriskowal, I suspect we'll need to do some surgery on `lockdown` and `harden` so that they can start within the SES world XS already gives us. Does that seem right? What else do you expect @warner needs immediately besides `harden`? 

@warner, If it's only `harden`, then we may already be there. You can just do what `lockdown` does to create `harden`, call `makeHardener`.

**Comment by dckc** [comment]
> @warner, marshal requires that objects be already hardened, so simply `harden = Object.freeze` will not work.

No? Not in any cases? `harden({})` and `freeze({})` mean the same thing, provided `Object.prototype` is frozen, right?

> @dckc, how far have you gotten running our SES system on XS-SES? What version of our SES system did you start from?

I haven't tried. I did some emulation back in Dec 2019 https://github.com/Agoric/SES-shim/issues/184#issuecomment-557992025 . Then the Compartment API seemed to make that unnecessary.

Currently, I just use `const { freeze: harden } = Object;` and leave a pointer to https://github.com/Agoric/SES-shim/issues/104

SES seems full of "patch legacy stuff" that isn't relevant to XS. @kriskowal closed the "SES on moddable's XS" issue https://github.com/Agoric/SES-shim/issues/184 . Looks like follow-up is intended to go in https://github.com/Agoric/SES-shim/issues/400

**Comment by dckc** [comment]
@warner writes:
> * make clean-output output-xsnap run-xsnap

I get `Error: Could not resolve './bundle-simpleExchange'` ; i.e.

```
connolly@jambox:~/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap$ make clean-output output-xsnap run-xsnap
rm -rf output
...
(node:29790) UnhandledPromiseRejectionWarning: Error: Could not resolve './bundle-simpleExchange' from ../../swingset-runner/demo/exchangeBenchmark/bootstrap.js
...
```

**Comment by dckc** [comment]
Ah right... Chip told Warner how to make `./bundle-simpleExchange`:

```
connolly@jambox:~/projects/agoric/agoric-sdk/packages/swingset-runner/demo/exchangeBenchmark$ node -r esm prepareContracts.js
contracts prepared
```

**Comment by dckc** [comment]
@warner writes:
> Currently when I attempt to load the first file, it goes into an infinite loop reading a single module over and over. I'm wondering if I've exceeded a size limit somewhere. The module contains about 80kB of JS, and is more or less the bare minimum we need to exercise a vat.

80kB? I get 241571 bytes. In any case, it looks like a 64kB limit was in place.

```diff
connolly@jambox:~/projects/xs-snap$ git diff
diff --git a/xsnap/sources/xsnap.c b/xsnap/sources/xsnap.c
index a3a38ae..2e788c1 100644
--- a/xsnap/sources/xsnap.c
+++ b/xsnap/sources/xsnap.c
@@ -126,7 +126,7 @@ int main(int argc, char* argv[])
                4096*3,                         /* keyCount */
                1993,                           /* nameModulo */
                127,                            /* symbolModulo */
-               64 * 1024,                      /* parserBufferSize */
+               1024 * 1024,                    /* parserBufferSize */
                1993,                           /* parserTableModulo */
        };
        xsCreation* creation = &_creation;
```

next challenge:

```
# exception: (host): import vatSourceBundle not found!
```

**Comment by warner** [comment]
> > @warner, marshal requires that objects be already hardened, so simply `harden = Object.freeze` will not work.

Yeah, I'm only using `Object.freeze` as a placeholder to get the demo to work. It's certainly not sufficient.

> No? Not in any cases? `harden({})` and `freeze({})` mean the same thing, provided `Object.prototype` is frozen, right?

Nope. `harden` recursively follows enumerable properties (but you're right, it doesn't follow the `.prototype`, although it does assert that the prototype is hardened). `Object.freeze` is shallow.

**Comment by dckc** [comment]
But in the case of an empty object `{}` shallow and deep mean the same thing, no?

**Comment by warner** [comment]
Oh, yes, you're right, I misread you and thought you were talking about `harden()` and `freeze()`, rather than `harden({})` and `freeze({})`. Yes, a frozen empty plain object has all the properties of a hardened empty plain object, except for not being a member of the internal `WeakMap` that `harden` uses to keep track of what has been hardened.

**Comment by dckc** [comment]
@phoddie and co made it as far as `HandledPromise`...

**Comment by dckc** [comment]
I got a bit further:

 - 12c12ea provide HandledPromise, harden via Compartment constructor (WIP)

Now the `make clean-output output-xsnap run-xsnap` seems to work:

```
...
finished buildDeliveries
xsnap -m output/build.js
sendUplink gotBundle
sendUplink dispatchReady
did setBundle
```

but then...

```
; xsnap -m output/build.js -w state.xsnap
sendUplink gotBundle
sendUplink dispatchReady
did setBundle

; xsnap -m output/deliver-0.js -r state.xsnap -w state.xsnap
.../output/bundle-functions.js:2834: exception: throw!
.../output/bundle-functions.js:856: exception: throw!
.../output/bundle-functions.js:1546: exception: throw!
.../output/bundle-functions.js:163: exception: ?.complain: no function!
.../output/bundle-functions.js:2868: exception: throw!
.../output/deliver-0.js:284: exception: throw!
# exception: throw!
# exception: throw!
.../output/bundle-functions.js:163: exception: ?.complain: no function!
```

where bundle-functions.js:2834 is
```js
      throw Error(`ERROR: too few syscalls`);
```

on the node side, I wonder what the expected behavior is. `deliver-0.js` seems to work, but if I add `deliver-1.js`, I get `ERROR: too many syscalls` followed by `did deliverAndVerifySyscalls` twice as we might expect. Same thing happens if add `deliver-2.js`.


```
; make clean-output output-node run-node
rm -rf output
node -r esm ./convert-slog-to-xsnap.js slog.out v1 --node output
run slog.out v1 --node output
{"type":"create-vat","vatID":"v1","dynamic":false,"description":"static name=alice (from source bundle)","vatSourceBundle":{"source":"function getExportWithNestedEvaluate(filePrefix) {\n  'use strict'
got vatSourceBundle
did buildInit
got complete delivery 0 with 6 syscalls
got complete delivery 1 with 0 syscalls
got complete delivery 2 with 0 syscalls
...
got complete delivery 69 with 1 syscalls
finished buildDeliveries
# this only runs the setup step
node -r esm output/build.js
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'gotBundle' ]
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'dispatchReady' ]
did setBundle

; node -r esm -e "import './output/build.js'; import './output/deliver-0.js'" 
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'gotBundle' ]
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'dispatchReady' ]
did setBundle
did deliverAndVerifySyscalls

;  node -r esm -e "import './output/build.js'; import './output/deliver-0.js'; import './output/deliver-1.js'; import './output/deliver-2.js'" 
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'gotBundle' ]
sendUplink Array <Array <[Object: null prototype] {}>>(1) [ 'dispatchReady' ]
did setBundle
(node:15150) UnhandledPromiseRejectionWarning: Error: ERROR: too many syscalls
  at doSyscall (/home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:2814:11)
  at Object.reject (/home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:2896:28)
  at /home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:2148:15
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15150) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15150) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
did deliverAndVerifySyscalls
did deliverAndVerifySyscalls
did deliverAndVerifySyscalls
```

**Comment by warner** [comment]
@dckc and I tracked down the next problem: a function given to `setImmediate` is called before a function given to `Promise.resolve().then()`. We use `setImmediate` to effectively sense when the ready-promise queue is empty:

```js
export function waitUntilQuiescent() {
  // the delivery might cause some number of (native) Promises to be
  // created and resolved, so we use the IO queue to detect when the
  // Promise queue is empty. The IO queue (setImmediate and setTimeout) is
  // lower-priority than the Promise queue on browsers and Node 11, but on
  // Node 10 it is higher. So this trick requires Node 11.
  // https://jsblog.insiderattack.net/new-changes-to-timers-and-microtasks-from-node-v11-0-0-and-above-68d112743eb3
  const { promise: queueEmptyP, resolve } = makePromiseKit();
  setImmediate(() => resolve());
  return queueEmptyP;
}
```

We (the kernel) expect all the syscalls to happen before the system becomes quiescent. At that point, the vat should have no way to regain control until the next delivery is made (it might have callbacks attached to unresolved Promises, but the kernel won't resolve those: the kernel doesn't even have references to any vat-made Promises). We rely upon this property to keep each vat's execution from overlapping with that of other vats.

If the queue priorities are inverted, the kernel cannot know when the vat is done moving.

**Comment by phoddie** [comment]
If I understand correctly (and I really might not!) you are overloading `setImmediate`  to detect some condition about promises. And, xsnap does not implement the behavior you were expecting from `setImmediate`.

Since we completely control the runtime in xsnap, perhaps it would make more sense to have an explicit function to trigger a callback on the condition you want?

**Comment by dckc** [comment]
The condition that the SwingSet kernel needs to detect is: the promise queue is empty. If you can advise us how to do that in the XS world, that would be great, @phoddie .

(originally raised as #45 )

**Comment by dckc** [comment]
It looks like you did give some advice in https://github.com/Agoric/agoric-sdk/issues/45#issuecomment-562802459 @phoddie

**Comment by phoddie** [comment]
Sure. Will get back to you tomorrow.

**Comment by zarutian** [comment]
import { makePromiseKit } from "@agoric/promise-kit";
    const alwaysActive = () => {
      const { promise, resolve } = makePromiseKit();
      promise.then(alwaysActive); // .then callbacks always run in next turn of the event loop.
      resolve(null);
    }
    alwaysActive();

which means that a vat might never become quiescent.

**Comment by michaelfig** [comment]
> which means that a vat might never become quiescent.

Metering will kill this loop.

**Comment by dckc** [comment]
@phoddie thanks for the `setTimer` update e8199b101298 ; with that, our "end of crank" test passes:

```
$ xsnap crankTest.js 
[1,2,3,4,5,6]
```

next challenge:
```
throw new Error(
          `Cannot pass non-frozen objects like ${val}. Use harden()`,
        );
```

for more on that, see https://github.com/Agoric/SES-shim/issues/104

**Comment by dckc** [comment]
Thanks to the moddable array fix (https://github.com/Moddable-OpenSource/moddable/issues/479#issuecomment-713754037 748fda93 ) I got further last Weds...

```
~/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap$ make  run-xsnap >,out 2>&1

~/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap$ ls -l ,out
-rw-rw-r-- 1 connolly connolly 92025 Oct 21 12:54 ,out
```

`,out` contains:

```
...
============== harden(a function called makeLocalAmountMath)
enqueue(val, undefined)
enqueue(val, unknown.length)
enqueue(val, unknown.name)
/home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:141: exception: ?.toString: this is no Function instance!
a prototype of something is not already in the fringeset (and .toString failed)
a prototype of something is not already in the fringeset (and .toString failed)
the prototype: /home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:150: exception: ?.toString: this is no Function instance!
// console.log might be missing in restrictive SES realms
?.toString: this is no Function instance
/home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/bundle-functions.js:157: exception: throw!
/home/connolly/projects/agoric/agoric-sdk/packages/xs-vat-worker/build-xsnap/output/build.js:7: exception: throw!
```

**Comment by dckc** [comment]
The problem above was with `AsyncFunction`, one of the "anonymous intrinsics". @warner helped me find `getAnonymousIntrinsics()` which let us get a little further. c206eaa

current challenge: `doProcess: vat.promise[p+5] fulfilledToPresence failed: Error: unknown promiseID 'p+5'`

**Comment by dckc** [comment]
With the fix to the [snapshotting maps issue](https://github.com/Moddable-OpenSource/moddable/issues/488) we get thru all 70 deliveries!

https://gist.github.com/dckc/2687721039b49c29558cbad9cb9e7baa

**Comment by warner** [comment]
@dckc awesome. Let's try it with `v3` (vat-zoe) instead of `v1` (vat-alice, use `make list-vats` to confirm which one is which), that should exercise even more code.

**Comment by dckc** [comment]
When I try with v3 (vat-zoe) I get a failure in `mustBeSameStructure` when running `deliver-8.js`. body=`["zcf"]` vs body=`...sourcemap...`.

xsbug shows:

![Screenshot from 2020-11-01 15-57-17](https://user-images.githubusercontent.com/150986/97816493-5050b400-1c5b-11eb-9397-5b15850ad940.png)

And you're right: I hadn't pushed the changes we were using the other day: c206eaab3d1

They're at https://github.com/dckc/agoric-sdk/tree/xs-snap-generator now. (I can't seem to push to Agoric/agoric-sdk).

The tweaks for v3 and a couple others I just made today are in cf6636a5ee98 .

**Comment by dckc** [comment]
The vatSourceBundle for the zoe vat also weighs in at 681K, so I had to tweak xsnap:

```diff
~/projects/xs-snap/xsnap/makefiles/lin$ git diff
diff --git a/xsnap/sources/xsnap.c b/xsnap/sources/xsnap.c
index 81e0f4f..dab5f68 100644
--- a/xsnap/sources/xsnap.c
+++ b/xsnap/sources/xsnap.c
@@ -129,7 +129,7 @@ int main(int argc, char* argv[])
                4096*3,                         /* keyCount */
                1993,                           /* nameModulo */
                127,                            /* symbolModulo */
-               256 * 1024,                     /* parserBufferSize */
+               1024 * 1024,                    /* parserBufferSize */
                1993,                           /* parserTableModulo */
        };
        xsCreation* creation = &_creation;
```

**Comment by dckc** [comment]
- [ ] xsnap doesn't use `manifest.json` build style; how to connect the little bits of FFI in development so far?
   - [ ] UTF-8 TextEncoder / TextDecoder https://github.com/agoric-labs/moddable/pull/3#event-3874607663
   - [ ] netstring (IOU pointer)

**Comment by phoddie** [comment]
`xsnap` is not a runtime for the Moddable SDK, so it doesn't implement support for the Moddable SDK's manifests. JavaScript modules are loaded from source code into `xsnap` using the `-m` option.

**Comment by dckc** [comment]
Right, but my question is not about JavaScript modules but bits of C called
via FFI. It's not a huge mystery... Just a bit if engineering to work out.

**Comment by phoddie** [comment]
I see. `xsnap` already has several JavaScript functions that are bound to native C implementations. `fx_print` is a good example:
- It is implemented using the [XS in C](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md) API.
- It is added to the globals of the VM using the internal XS function  `fxNextHostFunctionProperty` for convenience. You could also do this using public function in the XS in C API.
- It is added to the `gxSnapshotCallbacks` array to be able to rebind the function when the snapshot is reloaded.

**Comment by dckc** [comment]
I think #2194 shows we've got this working.

**Comment by dckc** [comment]
After talking with @rowgraus , I'm re-opening to represent the relevant end-user feature here: folks running validator nodes can use snapshots to save time when resuming their node. This means not just having a low-level snapshot mechanism, but having the rest of SwingSet , contracts, etc. integrated with it.

It's likely that @rowgraus and/or @dtribble will create another issue to represent this "Epic" in order to integrate with some other tools.

**Comment by dckc** [comment]
#2138 represents the end-user feature here.
