### ISSUE TITLE
'npm publish' runs twice

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#53]
My recipe for making a new swingset release is:

* switch to a new VM
* git clone
* git submodule update (not actually necessary for swingset, but used by our other projects)
* npm run build
* npm pack (just to doublecheck)
* npm publish

What I've noticed is that `npm publish` tries to publish the package twice. The first time, I give it the TOTP code and it uploads the generated tarball as expected. But then it repeats and rebuilds the tarball and then asks me for the TOTP code again. At this point I just SIGINT out, since the package was uploaded just fine the first time through. But it'd be nice to figure out why this is recursing or otherwise re-doing some step.

**Comment by katelynsills** [comment]
I think this can be closed as @michaelfig uses a different method now for publishing releases
