### ISSUE TITLE
[eventual-send]? t.plan doesn't seem to work with E()

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#531]
`tape-promise`'s `t.plan` doesn't seem to count tests that run in a subsequent turn of the event loop if the promise was made using `E`:

```
import test from 'tape-promise/tape';
import { E } from '@agoric/eventual-send';

test.only('t.plan with E', t => {
  try {
    t.plan(1);
    const obj = { get37: () => 37 };
    E(obj)
      .get37()
      .then(thirtySeven => {
        t.ok(thirtySeven === 37`equal to 37`);
      });
  } catch (e) {
    t.assert(false, e);
  } finally {
    t.end();
  }
});
```

Gives:

```
t.plan with E


    ✖ plan != count
    ----------------
      operator: fail
      expected: 1
      actual:   0
```

Tape-promise should support something like this, given [their tests.](https://github.com/jprichardson/tape-promise/blob/master/tests/async.test.js)

I think this is an eventual-send issue but I'm not sure. Also, it may be that we don't want to bother fixing this, which is ok. I wanted to make an issue in case it comes up again.

**Comment by erights** [comment]
Completely aside from the topic of this issue: Why does anyone use `t.plan`? It seems like a maintanence nightmare compared to `t.end()`. And you already have a `t.end()` in your code above.

**Comment by michaelfig** [comment]
@katelynsills you need to make sure the finally block doesn't run until the E promise settles:
```js
test.only('t.plan with E', async t => {
  try {
    t.plan(1);
    const obj = { get37: () => 37 };
    await E(obj)
      .get37()
      .then(thirtySeven => {
        t.ok(thirtySeven === 37`equal to 37`);
      });
  } catch (e) {
    t.assert(false, e);
  } finally {
    t.end();
  }
});
```

**Comment by erights** [comment]
Try making the arrow function an async arrow function, i.e. `async t => ...`. Since the function doesn't explicitly return anything, as an async function it will implicitly immediately return a pending promise. On normal termination of the function body, it will fulfill that promise with `undefined`.

**Comment by erights** [comment]
@michaelfig has the full answer. What he said. Ignore mine.

**Comment by katelynsills** [comment]
> @katelynsills you need to make sure the finally block doesn't run until the E promise settles:

Thanks!!

**Comment by katelynsills** [comment]
Just checked, and the underlying problem was definitely that I had forgotten that try/catch wouldn't work with promises which need a `.catch()` instead. D'oh. Thanks @michaelfig and @erights
