### ISSUE TITLE
[cosmic-swingset] Move wallet to REPL page on local solo

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#539]
Splitting #509 into two issues: one for wallet UI, one for autoswap UI. Feel free to edit this description.

**Comment by jfparadis** [comment]
@michaelfig Is there a commit related to this?

**Comment by michaelfig** [comment]
> @michaelfig Is there a commit related to this?

Sorry, I should have closed it in the commit instead of manually.  https://github.com/Agoric/agoric-sdk/commit/a193e874ea373f5e6345568479ce620401147db2
