### ISSUE TITLE
more efficient/transactional state storage

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#54]
Over in cosmic-swingset, https://github.com/Agoric/cosmic-swingset/issues/65 has been collecting ideas to improve the way we store the kernel state. Most of that work needs to happen here, in SwingSet, with an eye towards providing an API that cosmic-swingset can connect to.

**Comment by warner** [comment]
Notes from today's conversation with Chris:

We're trying to address a use case where external users (in aggregate) have access to a "large number" (one zillion, in metric units, written `1Z`) of Purses and Payments in some Issuer Vat. We have a lot of tables whose cardinality will be 1Z:

* the Comms Vat has a bunch of c-lists (one per remote machine), and union of all their entries point to 1Z object imports (`o-1234`)
* the Comms Vat's transcript contains 1Z messages, whose earlier delivery is what created those entries
* the kernel-side c-list for the Comms Vat has 1Z entries mapping `o-1234` to kernel objects like `ko5678`
* the kernel object table tracks the owner of 1Z objects: `ko5678 -> vat[issuer]`
* the kernel-side c-list for the Issuer Vat has 1Z entries mapping `ko5678` to vat exports like `o+9876`
* the Issuer Vat, in it's current transcript-based orthogonal-persistent form, has a javascript `Map` with 1Z entries that map vat exports like `o+9876` to javascript Purse/Payment objects with various methods on them
* the Issuer Vat has 1Z Purse/Payment objects
* the Issuer Vat's transcript contains the 1Z messages that originally created and retrieved Purses/Payments

There are smaller tables too: the Comms Vat is talking to lots of remote machines, but not 1Z of them.

And there are other use cases that are slightly easier to deal with: 1Z messages to/from a Vat which doesn't create separate objects for each one (e.g. a simple counter: the only state is a single integer, but the transcript is very long). We could solve this case with specialized state management for the transcript, but it wouldn't help the more general "1Z objects" case.

![IMG_6048](https://user-images.githubusercontent.com/27146/71118289-65d10280-219d-11ea-88f1-c44f7e904a13.jpg)

(the half-box on the left is the Comms Vat, the half-box on the right is the Issuer Vat, and the kernel is in the middle)

Our job is to move all of these zillion-sized tables off to secondary storage: on disk, not in RAM.

## Synchronous Host/Kernel `HostDB` API

Our plan is to stick with a synchronous HostDB API:

* `bool = has(key)`
* `value = get(key)` (or `undefined`)
* `set(key, value)`
* `del(key)`

(our `HostDB` API also defines a `iter = getKeys(start, end)`, which is currently only used for debugging; we may or may not keep this around)

To implement this in Node, we will need to write an FFI extension to provide bindings to the LevelDB C++ interface, as the `abstract-leveldown` ecosystem is entirely async. An alternative is to write low-level C++ code that splits a Node process into two threads, with the SwingSet kernel+vats in one (where HostDB calls block waiting for a queue/semaphore), and the leveldown code in the other (where each Promise triggers a semaphore write when it resolves). This alternative might give us access to more of the ecosystem, but would involve more surgery. I think we should start with the basic blocking LevelDB bindings.

We then extend the syscall interface (available to vats) with the same API. The low-level ("liveslots") code in each Vat gets access to a key-value store that is scoped to that one Vat, which obeys the usual Crank/Block transaction rules. This does not increase the authority of the Vat: it is not (directly) available to high-layer objects within the Vat, and cannot be used to communicate with other Vats.

Notably, the `syscall.get` API returns synchronously: the kernel routes this call all the way through to the host right away (if necessary, as there are a Crank Buffer and a Block Buffer in the way, which might satisfy the read first). This allows the Vat to use secondary storage as if it were RAM, without additional turns or ordering concerns, but not obligating it to hold all state in RAM at all times.

## Delivery Processing

At the start of each "Crank", the kernel pulls the next message off the run-queue by reading a key from the HostDB. (The entire run-queue is currently stored in a single key, because it has the highest churn rate, and because the quiescent state is empty, but we might want to revisit this some day). This kernel message is translated into a Vat message:

* Look up the target in the kernel object/promise table, to find out which Vat is responsible for it (the exporter of an object, or the decider of a promise), or if the message should be appended to an in-kernel promise queue. This should always succeed.
* If the target is an unresolved Promise that does not have a Decider registered (i.e. the owner of the Promise is willing to participate in promise pipelining), the message is added to the promise table's queue without further processing. This causes writes to the promise table.
* If the target is a resolved Promise that is not a legal delivery target (resolved-to-data, or rejected), an error resolution is constructed and queued to resolve the result promise, if any. This causes writes to the run-queue.
* Otherwise the message will be delivered to a Vat, so we look up the target in the target Vat's c-list. This should also succeed, because a kernel object reference wouldn't be added to the kernel object table without first being exported by some Vat.
* Look up all the message slots in the target Vat's c-list, adding new imports as necessary. Each slot which the kernel object table records as being owned by the target Vat should also be present in the Vat's c-list (this should be true for the same reason as above). This step will cause c-list writes for newly-imported object/promise references.

These steps take place before the Vat is invoked, so the kernel could take as long as it wants to perform the HostDB lookups and writes. The host does not know ahead of time what keys will be read, so for this phase the kernel is in control.

## Syscall Processing

The kernel then submits the Vat message for delivery to a Vat, by calling `dispatch.deliver()` or some flavor of `dispatch.notify`, and waits for it to complete (by waiting for a `setImmediate` callback to fire, which ensures the Promise queue has been drained, and the Vat can no longer get control until the next `dispatch`). During this time, the Vat can make syscalls by invoking `syscall.send`, `syscall.resolve`, or one of the new storage APIs (`has/get/set/del`).

The `syscall.send` and `syscall.resolve` calls are queued for later. The storage API calls are handled to the Crank Buffer, which keeps a local copy of any state modification until the end of the Crank (whereupon they are either flushed to the Block Buffer, if the delivery succeeded, or discarded, if the vat was terminated). Storage APIs get an immediate answer, which may require the kernel invoke the HostDB to get answers from disk.

When the Crank is finished and the Vat gives up control to the kernel, we examine the queued `send/resolve` calls for legality. Each call has a `slots` vector that can name imported (`o-12` or `p-12`) and exported (`o+13` or `p+13`) objects and promises. `send` calls have a `target` that must name an import, and `resolve` calls have a `target` that must name an unresolved Promise for which this Vat is the Decider. The kernel looks up the imports and targets in the Vat's c-list, which queries the HostDB (through the buffers). If any are missing, or if `resolve` references the wrong kind of Promise, the Vat is terminated (for illegal access). The Crank Buffer is discarded (including all changes made via the Storage API), the Vat itself is deleted, we (somehow) cauterize all exports, and we (somehow) decref all imports to allow the owning Vats to GC their objects. We must still remove the delivery from the run-queue, so this run-queue write should happen after the crank buffer is abandoned.

If all imports are present and all targets are legal, the Crank will succeed, so the kernel proceeds to execute each queued send/resolve syscall in the same order they were made. The c-list is queried for each target and slot (using the HostDB as before), and any new exports are added (causing HostDB writes into the Crank Buffer). The translated message is appended to the run-queue. At this point, the Crank is complete, and the crank buffer (including all Storage API changes) gets written out to the Block Buffer.

Neither the kernel object/promise tables, nor any c-lists, are kept in memory: all entries are fetched from the HostDB on demand. This removes three of the 1Z-sized tables.

## Transcript Processing

While the Vat runs, all the syscalls it makes (both send/resolve and Storage API) are logged by writing keys into the crank buffer. This "transcript entry" contains one delivery and zero or more syscalls. If the crank succeeds, these writes will be flushed to the Block Buffer, and will eventually land on disk when the block is complete.

When the kernel starts, it will rebuild each Vat, one at a time. After loading the Vat's initial code, the kernel will start fetching transcript entries, one at a time. It must have all the syscalls (specifically the return values of the StorageAPI calls) in memory before it can invoke the Vat's `dispatch` method. The method is invoked, and the syscalls it makes are compared against the transcript. If any mismatch is detected, the Vat is terminated (for anachrophobic behavior). No syscalls are actually executed, so the replay does not require access to c-lists or Storage API keys.

Once the delivery is complete, the transcript entry is forgotten, and the next one is fetched from the HostDB. No HostDB writes take place during the replay phase.

In the future, we may implement "demand paging" of Vats, where we defer loading a Vat (and replaying its transcript) into memory until someone sends it a message. We might also "page out" idle Vats, by dropping their `dispatch` object, allowing GC to free all their in-memory objects. This will result in transcripts being read after kernel startup.

This removes two of the 1Z-sized tables (the transcripts on both comms and issuer).

## Large-Scale Vats

To complete the RAM scaling story, we must also avoid keeping 1Z objects in any of the Vats' heaps.

The Comms Vat is responsible for looking up incoming "remote object reference" identifiers (like `ro+13`) in the per-remote-machine c-list table. Legal remote references are translated into vat import identifiers (like `o-14`), which can be put into a syscall. Rather than keeping a `Map` in RAM, we have the Comms Vat do a `get()` syscall for each of these lookups. This avoids keeping 1Z entries in a Javascript `Map` in RAM, or 1Z strings pointed to by the Map.

The Comms Vat might also avoid using its heap for *any* state, keeping absolutely everything in kernel-provided secondary storage. If done properly, this would remove the need for orthogonal persistence, and the Vat could elect to turn off transcript creation and replay. This would save 1Z deliveries at restart time, at least for the Comms Vat.

The Issuer Vat keeps track of a balance and Assay for each Purse and Payment referenced by incoming object identifiers. This is currently managed by a `Map` in the "liveslots" layer, which maps from exported object reference (`o+13`) to a pass-by-presence Javascript object (e.g. the Purse). This object has some methods like `deposit` and `withdraw` and `getBalance`. It may close over access to a larger table, and/or it may be a key in a `WeakMap`, to support things like confirming the Purse and Payment come from the same Issuer.

To avoid 1Z entries in RAM, neither of these maps can be used. Instead, we must rewrite the Issuer to perform `get()` lookups on demand, and `set()` calls to record the consequences.

This means a big change to the programming model for Vats that need to handle large numbers of objects. We've brainstormed about ways to avoid the change. One possibility is a magic WeakMap-like object that responds to `get()` and `set()` by issuing storage-API syscalls. We would need some way for the high-level Vat code to build and configure this object, which would be in cahoots with the low-level Liveslots layer. Certain incoming method arguments would be short-lived marker objects, recognized by the WeakMap and used to determine the `o+14`-style key that should be passed to `get()`.

We will also need changes like this to support schema/code upgrade.


## Browser-Hosted Storage

Web browsers offer somewhat-durable storage in the form of APIs like IndexedDB, which are strictly asynchronous. However all secondary storage for Vats must be kept in RAM, because the kernel must respond to `get()` syscalls synchronously, and we have no means to extend the browser with synchronous APIs.

The simplest design is thus to keep all HostDB data in a plain `Map`, in RAM. At startup, all keys are read from IndexedDB (asynchronously) to populate this Map, after which the kernel is started and can read from the Map synchronously. At the end of each Block, the modified/deleted keys are written to IndexedDB (for the next reboot or page-load), then used to update the `Map` (for reads that happen before the next reload).

As noted below, many items (kernel c-lists, object tables, and transcripts) could be handled better, because our programming model doesn't obligate us to provide synchronous access to them. If we allow the host to distinguish the keys used to store transcript items, we could have it drop all transcript entries from the Map just after replay has finished, and write new transcript items only to IndexedDB (not the Map). If we extended the HostDB interface to allow async access (either returning a Promise, or arranging for later delivery of the requested keys), then we could omit all these items from the Map, and have the kernel perform these lookups between Vat invocations, where they can take as long as they need.

But the basic rule will probably be that Browser-hosted SwingSet machines cannot scale to anything involving a zillion objects. It may be possible for them to handle 1Z transcript entries without a large RAM footprint, but not large numbers of concurrent objects.


## Rejected/Future Alternatives

Transcript replay is controlled by the kernel, not the Vat, so we could afford to have an async HostDB interface for the subset of keys that hold the transcript. One possibility would be a HostDB API that returns a Promise (although the SES split between kernel realm and primal realm makes this worrisome). Another would be a callback-based interface (slightly easier to membrane). A third would be for the kernel to request access to a range of keys, and then (on a later turn) the host could call a kernel API to supply the values (in order). The kernel should prevent reentrant calls while waiting for this response, just like it should prohibit a `kernel.run()` while waiting for the `setImmediate` to fire.

`send`/`resolve` syscalls are processed after the Vat yields control back to the kernel, so we could afford an async HostDB interface for the c-list and kernel-object/promise tables. We have the same API choices as for the transcript replay phase.

However neither helps with Vat access to secondary storage to avoid keeping large tables in RAM. This must either be synchronous (necessitating a synchronous HostDB API), or we would have to change the Vat dispatch API to have a two-phase prepare/commit scheme. In this scheme, the `prepare()` function gets the message and a table of key/values pairs, and it returns additional keys that will be needed. Once it stops asking for more, the `commit()` function is invoked with the same values. `prepare` doesn't get access to mutable state, and may be invoked multiple times. `commit()` gets run exactly once, and must succeed, with only the keys/values that `prepare` said it needs. All syscalls would have empty return values, and thus could be queued for processing after the delivery completes. This seems like a big change to the programming model, and maybe not a good fit for the kind of code we want to host. On the other hand, our planned approach for large scale vats is already a change to the model.

Dean had an idea about using composite identifiers like `ko12.abc`, where the kernel treats `ko12.abc` and `ko12.xyz` the same way, but delivers the `.abc` all the way through to the target Vat. The idea was to avoid the 3Z table entries (1Z in the comms-vat clist, 1Z in the kernel object table, and the third 1Z in the Issuer-vat clist). Imagine taking the set of "small" objects being granted and drawing a big circle around them (named "ko12"): the kernel only knows about the big circle, leaving the 1Z details to the vats on either side. I think this effectively gives the comms-vat full access to the big circle, possibly everything ever exported by the issuer vat. If we're comfortable doing that, then a simpler approach is to just let `ko12` point to an Issuer object with an API that takes `"abc"` or `"xyz"` as an argument: hoist the object representation out of the kernel and into the Vats, letting them deal with the access control issues. So I'm not sure that composite identifiers solves or simplifies anything.

Dean seemed to feel that the Storage API should be done through Devices, rather than being provided directly by the kernel. I want to explore this more, but currently I think:

* Secondary storage is a pretty fundamental thing to provide to computation: Linux provides `sbrk()` as a system call, not a device node.
* Letting the kernel observe `get()` and `set()` might make it easier to meter storage usage and deduct gas
* The kernel knows when a Crank is finished, and Devices do not, so it may be easier to get transactionality right by having the kernel's Crank Buffer hold Storage writes
* Related to that, secondary storage for a Vat evolves at the same pace as the kernel's c-lists for that Vat, so storing them both in the same place should make it easier to keep them in sync
* A possible counter-argument is if we think platform-level tables, like the cosmos-sdk "Bank" module and its ledger, should be managed through this Storage API. I'm inclined to say no, and use a Device to manage them.

The HostDB API might benefit from an iterator-based range query. We currently walk e.g. transcripts by incrementing a counter and querying `has()` to see if that key is present. If so, we do a `get()` and use the resulting key. When we implement Vat termination, we will need a similar mechanism to delete all keys associated with a Vat. This approach imposes some requirements on our choice of keys, to enable this kind of manual enumeration. A fancier API could remove this requirement and make this cheaper, enabling the host side to pre-fetch multiple keys (and LevelDB's on-disk structure supports very efficient range queries). However the SES primal/kernel-realm split requires us to wrap iterators carefully, and this may preclude some other HostDB API approaches in the future (WASM import functions, etc).

The Storage API syscalls we offer to Vats might benefit from a range query as well, although this interface is even harder to augment, since we need to record everything for the transcript, and the syscall boundary is even more likely to wind up crossing languages eventually.

To benefit from the `leveldown` ecosystem, and also enable large-scale Vats in a browser environment (with IndexedDB), we would need to change our execution model to tolerate async retrieval of Vat state.

**Comment by michaelfig** [comment]
I think the "split into two threads and use a semaphore to block one" alternative is actually not that hard.  Node.js already has the notion of worker threads (https://nodejs.org/api/worker_threads.html), which takes care of the threading and communication.  For synchronization, I'd turn to the power of *nix, and use a filesystem FIFO as the semaphore.  No need for FFI.

Fundamentally, for communication, our main thread just needs to call [receiveMessageOnPort](https://nodejs.org/api/worker_threads.html#worker_threads_worker_receivemessageonport_port) at the right time to poll the message port, and block if the message is not available.

I have a sample of how all this works together: https://gist.github.com/michaelfig/6d199ea95eab3ebdb918359612123a3e

**Comment by warner** [comment]
Hmm. Ok, so in one sense, the host can do whatever it likes as long as it provides the right (sync) API. So the kernel would be unaware of the complexity of multiple threads. *Host* authors would be obligated to know about it (although for Node.js-specific environments we could hide that complexity in a library). The host is also responsible for managing the block-level transactionality: choosing when to update the durable state from which the next incarnation will restart, keeping it aligned with any other stored state (e.g. cosmos-sdk blocks), and withholding externally-visible messages until the state that generated them has been recorded (hangover inconsistency).

I'd be worried about performance.. we're basically serializing all reads and writes and shipping them through the kernel to the other thread, deserializing them again, then delivering them to the leveldown storage backend. Maybe not a big deal but I'd want to keep it in mind.

I suspect we could reduce the complexity a little bit by using `pipe(2)` rather than a FIFO, and not involve the filesystem at all. I also suspect we could fork off a separate process to manage the storage, instead of using Node's worker APIs. That might also make it more obvious for a non-Node host author to figure out how to satify the synchronous HostDB API.

Do you think the worker/multiprocess approach is feasible to integrate into the golang/cosmic-swingset world? There are even more threads going on there. An FFI interface might be a simpler component to use.

And we need to figure out a clean way to do this in an XS world. For that, I think we have do an FFI equivalent anyways, since all host authorities are coming from C code.

On the whole I'm more inclined to do an FFI thing, but maybe this trick would let us put that off for a while.

**Comment by michaelfig** [comment]
> Do you think the worker/multiprocess approach is feasible to integrate into the golang/cosmic-swingset world? There are even more threads going on there. An FFI interface might be a simpler component to use.

It's not really any more complex than adding a single additional worker thread.  Multiprocess would need the same thing, backed by a socket/IPC of some sort.
We'd still need synchronous access to it, and the point of this hack is to keep the logic for the database access in Javascript.

For XS, I'd suggest multiprocess, with a blocking interprocess message-passing C primitive rather than implementing a Worker interface for it, nor having to write everything in C.  We can do all kinds of cheating (such as shared memory) if we find this is too slow.

> I suspect we could reduce the complexity a little bit by using pipe(2) rather than a FIFO, and not involve the filesystem at all.

I've only seen pipe(2) available as the `node-pipe2` FFI extension, and couldn't get it to work.  I think some magic with libuv is happening that prevents me from using `fs.writeSync` and `fs.readSync` successfully, whereas going all the way to the filesystem is reliable.

I'm thinking that writing FFI for a simple block/unblock mechanism (such as C++17 semaphore) that is processwide would be even better than trying to wrangle with FIFOs or file descriptors, especially to port to Windows.

Thanks for your comments.

**Comment by warner** [comment]
We'll need to decide how to break down this task. The `HostDB` stuff is already in place, but it's backed by a all-RAM `Map` instance which gets written out to disk after each crank/block.

**Comment by warner** [comment]
`HostDB` is now implemented (outside of tests) by a LevelDB backend, which offers a synchronous JS API.

The "reduce large tables" task is covered by a number of smaller tickets:

* #455 (virtual objects) to move liveslots entries from RAM to disk
* #1872 (GC) to delete unreferenced liveslots/clist/kernel-table entries, as well as comms tables
* #2273 #2277 XS snapshots to replay less of transcript, and maybe truncate it someday

So I think we can close this now.
