### ISSUE TITLE
[ERTP] Basic non-fungible use case in ERTP tests (event tickets)

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#545]
For Zoe Alpha, we need a basic non-fungible use case in the ERTP tests. We can start with the documentation that @DavidBruant wrote for [event tickets](https://github.com/Agoric/documentation/blob/master/main/ertp/guide/create-non-fungible-tokens.md).

This non-fungible use case would probably use the `natListExtentOps` or `handleExtentOps` from the Minimum Extent Ops (#521). If we want to use strings rather than Nats or handles, we could do that, but we will have to spend time implementing the strListExtentOps (#538) as part of Zoe Alpha.

This is a precursor to #543, which is taking this example and putting it in a Zoe contract to deploy to the testnet.

**Comment by DavidBruant** [comment]
I'm going to go with `handleExtentOps` because it feels the most relevant to the use case. Also the concept and the code is new, so it'll be a good occasion to exercise it
I'm going to create a branch/PR on top of `no-config-add-brand`. I'll rebase regularly as this branch changes

**Comment by katelynsills** [comment]
Closed by #558
