### ISSUE TITLE
Should we add the documentation repo to agoric-sdk?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#549]
@warner and I discussed adding the documentation repo to agoric-sdk. There are pros and cons and we're not currently sure what direction we should go. We currently use Github Pages for the documentation site and rely on the fact that the repo is named `documentation` to correctly route `agoric.com/documentation` to the site.

**Comment by DavidBruant** [comment]
I've been thinking about it for some time
it has pros and cons, but as far as i'm concerned, the pros outweigh the cons

**Comment by erights** [comment]
@tyg @katelynsills It seems we've long decided the answer is no, so I'm closing. But assigning you two in case I'm wrong.
