### ISSUE TITLE
test to show that withSES === false is insecure?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#56]
In my work on SES (#126) I have all the `withSES === false` tests more or less working. For work on the `withSES === true` case, it would be helpful to have tests that show why `withSES === false` is insecure.

context: https://github.com/Agoric/SwingSet/issues/126#issuecomment-529257717

**Comment by warner** [comment]
We've removed `withSES` entirely.. all code that uses swingset, `Compartment`, or `import-bundle` is now all-SES all-the-time.
