### ISSUE TITLE
In #523, payment name in .claim is not inherited from claimed payment

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#560]
Filing this as a separate issue, becasue #523 is already heavy and this issue is more on the cosmetic side of things. I came across this issue while working on #558 

Relevant parts of the PR:

https://github.com/Agoric/agoric-sdk/pull/523/files?file-filters%5B%5D=.js#diff-4da41f1a720659b82b67c95e50a5187fL230

https://github.com/Agoric/agoric-sdk/pull/523/files?file-filters%5B%5D=.js&hide-deleted-files=true#diff-908a78b44aa919e08b9a20e447667f9cR166

**Comment by katelynsills** [comment]
Was that feature useful to you? If so let's add it back in.

**Comment by DavidBruant** [comment]
I used the payment memo as asset description (which is an arguable use, see #559 ). When claiming the payment, i was surprised to see "payment" as the memo for the new payment (the description was gone). I had the extract the memo to put it back in the new payment

https://github.com/Agoric/agoric-sdk/pull/558/files#diff-5fa60e98a7f71f0fe78d3b5283aee64dR140

So in this case, it would have been useful

**Comment by katelynsills** [comment]
Ok, I'm convinced it's useful. Thanks. I will alter the PR to get it into Zoe Alpha.

**Comment by katelynsills** [comment]
Closing this since we eliminated payment memo/name
