### ISSUE TITLE
use .eslintrc.json/.cjs rather than .eslintrc.js

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#565]
To support #527, we need to make sure all our `.js` files are ES6-module format (with `import` and `export`), rather than CommonJS format (with `require` and `exports.foo=` and `module.exports=`). This includes the config files we use for ESLint, which so far have been CommonJS format.

The task is to rewrite them into JSON, and rename them to `.json` instead of `.js`. I'm pretty sure this includes our new `.eslintrc-jessie.js` files, but I'm not entirely sure how those get composed or loaded.

- [ ] acorn-eventual-send
- [ ] agoric-cli
- [ ] assert
- [ ] autoswap-frontend
- [ ] bundle-source
- [ ] captp
- [ ] cosmic-swingset
- [ ] default-evaluate-options
- [ ] deployment
- [ ] ERTP
- [ ] evaluate
- [ ] eventual-send
- [ ] import-manager
- [ ] make-promise
- [ ] marshal
- [ ] pixel-demo
- [ ] registrar
- [ ] same-structure
- [ ] sharing-service
- [ ] sparse-ints
- [ ] spawner
- [ ] store
- [ ] SwingSet
- [ ] swingset-runner
- [ ] tame-metering
- [ ] transform-eventual-send
- [ ] transform-metering
- [ ] wallet-frontend
- [ ] weak-store
- [ ] zoe

**Comment by warner** [comment]
@michaelfig pointed out that we can just rename the files to `.eslintrc.cjs` instead, and keep using the CommonJS syntax. Also that our Jessie linting will require more than the JSON-based configuration.

**Comment by katelynsills** [comment]
Can we close this? I couldn't find any eslintrc.js files
