### ISSUE TITLE
use fully-suffixed imports (don't omit the `.js`)

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#566]
Import statements in modules (`import X from 'Y'`) include a module specifier (Y) that points at a file or a package. We've been using `-r esm` to run our programs, which is a bit more tolerant these specifiers: it will accept `'./foo'` to mean `./foo.js` or `./foo/index.js`.

To switch to Node's native module support (#527), we have to be more specific. All the "relative" (`./foo.js` or `../foo/bar.js`) imports, and all "deep" (`packagename/inner.js`) imports, [must include the full suffix](https://github.com/nodejs/node/blob/master/doc/api/esm.md#mandatory-file-extensions). We can (and must) keep using non-suffixed specifiers for "bare" (`packagename` and `@orgname/packagename`) imports, which includes built-in modules like `fs` and `path`. We have to fix all of these within a given package before we can mark that package as `type: "module"`.

ESLint (at least the way we've configured it) defaults to [complaining about these](https://github.com/benmosher/eslint-plugin-import/blob/v2.20.1/docs/rules/extensions.md) "extension" suffixes, so we must also update each package's `.eslintrc` file (which might be `.js` or `.json`) to allow it (and in fact to require it for non-bare/package imports). That `rules` stanza (in json format) looks like:

```json
"import/extensions": [ "error", { "js": "ignorePackages" } ]
```

- [ ] acorn-eventual-send
- [ ] agoric-cli
- [ ] assert
- [ ] autoswap-frontend
- [x] bundle-source
- [x] captp
- [ ] cosmic-swingset
- [ ] default-evaluate-options
- [ ] deployment
- [ ] ERTP
- [ ] evaluate
- [x] eventual-send
- [ ] import-manager
- [ ] make-promise
- [x] marshal
- [ ] pixel-demo
- [ ] registrar
- [ ] same-structure
- [ ] sharing-service
- [ ] sparse-ints
- [ ] spawner
- [x] store
- [x] SwingSet
- [ ] swingset-runner
- [ ] tame-metering
- [ ] transform-eventual-send
- [x] transform-metering
- [ ] wallet-frontend
- [ ] weak-store
- [ ] zoe

**Comment by dckc** [comment]
including `.js` is not the norm in the Moddable SDK. I'm not sure the `mcconfig` tool supports it at all, though my mental model of [the modules section of the manifest](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md#modules) is still incomplete.

I don't exactly understand
> Targets and sources can use the * wildcard to represent all files that match.

nor

> There are no extensions:
>  - In the modules object, mcconfig matches .c, .cc, .cpp, .h, .js and .m files."

cc @phoddie

**Comment by phoddie** [comment]
The comments by @warner refer to the JavaScript code executed by the virtual machine. The comments by @dckc refer to the source code files referenced by the manifest file used by the `mcconfig` tool in the Moddable SDK. They are only loosely related.

The host maps the module specifier to module byte code, not XS. On desktop deployments, for example, a host may [dynamically loads module](https://github.com/Moddable-OpenSource/moddable/blob/79b50f509666d3694a908ea59c1866d68733943a/xs/sources/xsPlatforms.c#L358-L360) from JavaScript source files.

**Comment by erights** [comment]
@kriskowal @dckc can we close this?

**Comment by dckc** [comment]
I think it's still necessary for moving off esm (#527), and I think that's still a goal, though not any time soon.

The XS constraints aren't relevant to our current design, but I think we want to move away from rollup to endo eventually.

Meanwhile, xs supports .js now.

**Comment by dckc** [comment]
was this fixed recently? oh... cf45d93c2cd6 in #3311 was only SwingSet and below. Still TODO: ERTP, ...

Note: the package list in the description is incomplete; it's missing `import-bundle`, among others.

**Comment by kriskowal** [comment]
This is provably complete since everything in Agoric SDK runs on Node.js ESM.
