### ISSUE TITLE
agoric deploy output is confusing

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#573]
```sh
$ agoric deploy ./contract/deploy.js ./api/deploy.js
Chain loaded: chain bundle loaded
running /home/david/projects/agoric-sdk/demo/contract/deploy.js
'fs' is imported by contract/deploy.js, but could not be resolved – treating it as an external dependency
- installation made autoswap => [Object: null prototype] { toString: [Function] }
- instance made autoswap => autoswap_5496
Added liquidity.
writing /home/david/projects/agoric-sdk/demo/ui/src/utils/contractID.js
running /home/david/projects/agoric-sdk/demo/api/deploy.js
Done!
```

> Chain loaded: chain bundle loaded

it's not clear to me neither what this means nor how it's related to deploying the contract

> 'fs' is imported by contract/deploy.js, but could not be resolved – treating it as an external dependency

I'm not sure, but i think this is an error message from rollup. It's not really actionable in the context of `agoric deploy`. If this blocks the deployment, the process should probably error instead of continuing. If this is irrelevant to the deployment, i think it should be fixed or hidden

> - installation made autoswap => [Object: null prototype] { toString: [Function] }

This output does not feel [intentional](https://github.com/Agoric/agoric-sdk/blob/074478898e6955aa0725fa962dc23d9e4339b01a/packages/agoric-cli/template/contract/deploy.js#L130)

> Added liquidity.

I think this output is part of the contract
And this is a different "domain" than the messages saying `running xyz.js`

Would it make sense to distinguish them visually? Maybe with an identation level? Or with a different [color](https://www.npmjs.com/package/chalk)?

**Comment by katelynsills** [comment]
@DavidBruant can you check if this is still an issue?

**Comment by DavidBruant** [comment]
I'll check when i can get `agoric deploy` to run ^^ 

#874

**Comment by DavidBruant** [comment]
Current console output:
```
$ agoric deploy ./contract/deploy.js ./api/deploy.js
agoric: deploy: Chain loaded: chain bundle loaded
- instance made simple-exchange => simple-exchange_9794
- admin seat upload ID simple-exchange_9794-admin
writing dappConstants.js
writing /tmp/demo/ui/src/utils/defaults.js
agoric: deploy: Done!
```

It's better (the colors do help to better understand that there are 2 message contexts), but still not super clear

> agoric: deploy: Chain loaded: chain bundle loaded

This message is still a mystery to me

> - instance made simple-exchange => simple-exchange_9794
> - admin seat upload ID simple-exchange_9794-admin

It's not clear to me what these are supposed to mean and how this information is actionable for me

> writing dappConstants.js
> writing /tmp/demo/ui/src/utils/defaults.js

likewise, it's not clear to me why i should care about either of these files and how they play a role between me, the Agoric VM and the contract

I'll read the code to better understand what's going on and propose a better alternative

**Comment by katelynsills** [comment]
I'm going to close this because we have improved the comments and the console log messages in dapp-encouragement. Let's open a new issue if any concerns still remain.
