### ISSUE TITLE
Can SwingSet run on browser?

### ISSUE THREAD

**Issue by danfinlay** [Agoric/agoric-sdk#58]
The docs make this look like a command line tool, but is there a way to also run these vats and support cross-process communication within a browser?

**Comment by dckc** [comment]
@ski I think you asked me this question a few weeks ago.

**Comment by erights** [comment]
Hi @michaelfig I think this is closest to things you are working on, so may I assign you?

**Comment by michaelfig** [comment]
The short answer of "can SwingSet run in a browser" is "not without a lot of work."  The long answer is https://github.com/Agoric/agoric-sdk/issues/58#issuecomment-538566953  And also, that work is not really on Agoric's roadmap at this time.

A better question is "can a vat run in a browser" (i.e. without the deterministic persistent multi-vat world that SwingSet provides for)?  The answer to that is "yes"!  Use SES and CapTP, and be prepared to reestablish your remote objects from scratch on reload.  You can take advantage of any platform features in this model (like async databases, remote hosts, etc): no need to be deterministic.  What we're missing is LavaMoat integration to partition risk nearly as seamlessly as SwingSet provides.

Our most obvious example of this is the [wallet UI](https://github.com/Agoric/agoric-sdk/tree/master/packages/dapp-svelte-wallet/ui) which uses SES and CapTP messaging to talk to the local ag-solo.  It's in Svelte.  We're making more examples of this kind of UI Really Soon Now.

As far as making this pattern generalisable to other runtime environments: -cough-Endo-cough-.  But as @danfinlay 
 knows, MetaMask and Agoric are both going together in this direction.  And we have a plan for how to get there in phases.  As for @ski, the Svelte captp stuff may be what you're looking for.  Feel free to open another issue if you have questions about how to reproduce that model in (IIRC) Vue.

Closing this issue until somebody signs up to do the "lot of work" it would take.

**Comment by dckc** [comment]
It seems like a bunch of the hard work has actually been done. I wonder how much is left:

> The work that may need to be done includes:
> 
> * getting SES to work in the environment (e.g. Workers) without a DOM, from which the Realms shim gets an `<iframe>` to get a new set of primordials. The Compartments API is the way forward here.

The Compartment API is pretty mature by now.

> * providing a meaningful durable state-storage object. Maybe IndexedDB or something.

https://github.com/Agoric/agoric-sdk/pull/3171 seems to make that feasible.

> * providing messaging channels: WebSocket comes to mind but there are a lot of questions about how new connections are established and named that we need to figure out first. The IBC protocol that we're helping to develop is relevant too

I guess that part has a ways to go... but we're making progress: #1670 , 

see also #3180
