### ISSUE TITLE
[ERTP, Zoe] How does ERTP/Zoe/UIs address social attacks related to displaying amounts?

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#589]
I'm creating a separate issue to discuss what started in another issue : https://github.com/Agoric/agoric-sdk/issues/521#issuecomment-588383434

> I'm concerned that there is a social attack here where a user will simply look at the data and see that it matches, but it is actually a different object identity.

I don't understand a specific attack scenario, so it's not clear to me what ERTP/Zoe/UIs is defending against nor whether it's doing a good job at protecting against it

**Comment by katelynsills** [comment]
Thanks for making this issue!

**Comment by katelynsills** [comment]
Closing this because we have a wallet that can display non-fungible amounts, so the display issues are no longer theoretical.
