### ISSUE TITLE
Add reflection information for presences

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#59]
In command-line, development, or debugging environments, it would be valuable to be able to get _alleged_ type and method information for presences and remote promises. Currently, a failed dispatch can return the set of available operations on a presence as part of the error information, but it would be much better to be able to systematically get that information without inducing an error.

**Comment by erights** [comment]
Done, with @warner's atttractive nuisance caveat since it won't have any integrity until we have auxiliary presence data. Closing.
