### ISSUE TITLE
Consider moving UI code in its own monorepo

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#596]
Currently, kernel code and UI/applications are in the same monorepo.

Although this is simpler for development, this imposes boundaries such as monoversion, and creates an unoptimized environements: all builds and tests are running even if the code is only impacting a small portion of the complete architecture.

Consider instead dividing the kernel/chain and the frontend applications. Although currently all code executes in JS, some runs on node/XS and other runs on browsers, and the code should probably be organized along this distinction. 

It's easy to imagine down the road one frontend repo for React(JS) applications, another for iOS(Swing) applications, etc. Each one would have tooling, automation, etc. tailored for the framework used.

**Comment by katelynsills** [comment]
@michaelfig have we completed this with the wallet UI moving out?

**Comment by michaelfig** [comment]
> @michaelfig have we completed this with the wallet UI moving out?

We've done this to the extent that @dtribble wants it, so I'm content to close this.
