### ISSUE TITLE
Rethink the architecture and the deployment of contracts (agoric-cli)

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#605]
I've noticed duplicate code path in the current system:

In `cosmic-wingset`:

```sh
ag-solo upload-contract NAME=ENTRYPOINT.js [NAME=ENTRYPOINT.js...]
```

In `agoric-cli`:

```sh
# Deploy the test contracts
../bin/agoric --sdk deploy contract/deploy.js api/deploy.js
```

In addition, the autoswap contact and the initialization for the `autoswap-frontend` are in package `template`, which should not be involved in the build or runtime of autoswap.

Suggestions:
- create a package, maybe `autoswap-backend` that can be referenced in the setup of `autoswap-frontend` and clearly isolates the code from the `template`. This package can import tools. This will isolate the solution and prevent breaking the application when other changes necessary for `template` are introduced.
- remove all contract code and contract initialization from `agoric-cli`
- remove all template/ui code from `agoric-cli`
- remove all non-template code from `template`
- rethink the structure and naming:
  - There are 3 `deploy.js` 
  - Deploy is probably not the right name (deploy = move into position): for autoswap, the code used to be called "init" (initialize = set to the value or put in the condition) which more accurately describes the creation of the liquidity pool. In any case, this creation step is very specific to the autoswap contract.

`agoric-cli` itself should be about the process, should have dependencies on `template` only for a default setting, and should allow other templates to be provided.

**Comment by jfparadis** [comment]
An illustration of the points mentioned above:

![Screen Shot 2020-02-26 at 8 20 29 AM](https://user-images.githubusercontent.com/2583204/75366737-10d3fb80-5874-11ea-9dd8-f33fe4e3688c.png)

**Comment by katelynsills** [comment]
@michaelfig do you think we can close this?

**Comment by michaelfig** [comment]
> @michaelfig do you think we can close this?

Yippers!
