### ISSUE TITLE
TypeError: o["install"] is not a function

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#606]
When attempting to upload a contract, we get this error:
```
TypeError: o["install"] is not a function
```
The error occurs in `forwardHandlers/applyMethod`:

![Screen Shot 2020-02-26 at 10 43 57 AM](https://user-images.githubusercontent.com/2583204/75376544-1554e000-5885-11ea-9792-600a541509ad.png)

Because argument `o` is a presence:

![Screen Shot 2020-02-26 at 10 45 44 AM](https://user-images.githubusercontent.com/2583204/75376599-2a317380-5885-11ea-8085-26378bc53a74.png)

## Reproduction
1. Run the larger demo as explained in the readme, or scenario 3:

```
cd packages/cosmic-swingset
make scenario3-setup
make scenario3-run
```

2. Try to load a contract
```
cd t3
node --inspect-brk ../bin/ag-solo upload-contract 'zoe:autoswap'='../../agoric-cli/template/contract/deploy-autoswap.js'
```

**Comment by jfparadis** [comment]
Any ETA to resolve this problem? The CLI is also broken (see https://github.com/Agoric/agoric-sdk/issues/634), and it doesn't look that we have any alternative.

**Comment by michaelfig** [comment]
Sorry for the delay, I'm on it now.

**Comment by michaelfig** [comment]
The PR will fix the issue, but you also need to run `upload-contract` with an actual contract, not a deploy script.  So, this is complementary to #634 

Try with: `zoe:autoswap=../../agoric-cli/template/contract/autoswap.js`
