### ISSUE TITLE
Comment to use of tildot

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#608]
We should add a comment to the top of all js files that use tildot `fooP~.bar(glub)` to explain that tildot is a standards track proposal as a syntax for eventual send. The comment should point to a page (that we should host on agoric.com, right?) explaining the benefits of the syntax, and the proposal before TC39.

https://github.com/tc39/proposal-wavy-dot/issues/4
https://github.com/tc39/proposal-wavy-dot

**Comment by michaelfig** [comment]
This needs to be added to the `api/deploy.js`, `contract/deploy.js` and `contract/install-*.js` of

* https://github.com/Agoric/dapp-autoswap
* https://github.com/Agoric/dapp-simple-exchange

**Comment by Chris-Hibbert** [comment]
done for agoric-sdk, dapp-simple-exchange and dapp-autoswap.
