### ISSUE TITLE
in agoric-cli, add copy of deploy.js that supports simpleExchange

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#609]
The existing deploy.js is specific to autoSwap. We should keep that version around (possibly renaming it), and make a copy that doesn't create the liquidity pool, and has other changes for simpleExchange/myFirstDapp.

After Zoe roles are integrated, it's likely that this will simplify down to a single script again.

**Comment by jfparadis** [comment]
Related to https://github.com/Agoric/agoric-sdk/issues/605

**Comment by katelynsills** [comment]
@Chris-Hibbert Is this ready to close?

**Comment by Chris-Hibbert** [comment]
Yep.
