### ISSUE TITLE
Orders: sorting & UUIDs

### ISSUE THREAD

**Issue by jfparadis** [Agoric/agoric-sdk#612]
Do orders have a date, or a token to sort them by?
Do orders have a UUID, something to reference them by (it's important for efficient rendering in the UI).

**Comment by katelynsills** [comment]
I think if I understand what @Chris-Hibbert  is planning correctly, the wallet can add a UUID to replace an inviteHandle when it sends the order.

**Comment by Chris-Hibbert** [comment]
In the wallet, they do have a date that's used as the key. I'm not convinced that we want to share that with the UI.

Would you display that or use it as a sort key? Does it need to be unique across calls? (i.e. will you be merging lists of orders from different sources?)

**Comment by jfparadis** [comment]
@Chris-Hibbert, those are 2 different needs
1. UUIDs are for the UI or any connection to the backend. I don't think we should use timestamp for that. It can be a row# in the storage. It can be a creation count. For security, I would create and use a UUID that has no order and no time associated to it.
2. Sort order is whaterver you see fit. It has no other semantic. You can create a "sequence" field derived from the timestamp, so we can show the items in creation order without revealing the exact timestamp to the UI.

**Comment by katelynsills** [comment]
I think we can close this given the work that @michaelfig has done on the simpleExchange frontend
