### ISSUE TITLE
Convert chainmail files to something more compatible with JavaScript

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#617]
There's been discussion about converting chainmail files to TypeScript
I recall discussions about JSDoc as well, but it's not clear to me whether it was an either/or discussion or a "one for short term another for long term" discussion

If that's helpful to the decision, the TypeScript compiler has lots of options that can be opted into gradually to validate more and more JavaScript code
JSDocs are an option. You can read more about it here: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html

**Comment by katelynsills** [comment]
Thanks for making this an issue! That was on my TODO list, so I'm glad to strike it off. I think we said that within the Zoe Alpha time period, @michaelfig would automate changing our chainmail files to TypeScript interfaces, and that we would not try to do any JSDocs.

**Comment by katelynsills** [comment]
In the interest of time, I wonder if @Chris-Hibbert could try to take on writing the TypeScript interface docs manually so that @michaelfig can focus on other tasks. I'll jointly assign Chris to this.

**Comment by michaelfig** [comment]
> I'll jointly assign Chris to this.

I have a future plan to make this more automatic (probably with typescript-checked JSDocs, as @DavidBruant mentions above, being extracted to `.d.ts` files), but I'm fine with having @Chris-Hibbert take a crack at writing a `.d.ts` interface to describe the things that are currently in the `.chainmail`.

It's just documentation at this point, the tooling needs to get a little more advanced before it can be used for, say, Intellisense.  Enhancing it is something that can happen when I get free again.

**Comment by katelynsills** [comment]
That sounds great to me, thanks @michaelfig!
