### ISSUE TITLE
swingset: use 'tap' for unit tests, not 'tape'

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#644]
As part of #477 we'll be switching to a new SES which is built by calling a `lockdown()` function at the beginning of the process. This irrevocably modifies the global environment (of course, since if it weren't irrevocable, the confined code could just undo the conflinement and then escape). Since we're only using a single shared Realm, all tests that share a process will be subject to the same set of `lockdown()` options. If we need to e.g. use `lockdown({noTameError: true})` in one test, and a fully-tamed lockdown in a different one, we'll need to run those tests in separate processes.

`tape`, which we currently use for both running tests and for the assertions therein, runs everything in a single `node` process. If we were to switch the runner to `tap`, then each test file would be run in a separate process.

I've got a branch for doing this (on just the SwingSet package), and the tests work. The downside is that they take longer. `tap` runs multiple processes in parallel, but even so the `tap` branch takes 107 seconds to run the test suite, whereas the previous `tape` branch only takes 30 seconds (and only uses a single CPU core).

There are a lot of ways we could improve the swingset tests, for sure, so maybe it doesn't need to be that slow forever.

**Comment by warner** [comment]
@jfparadis @michaelfig any opinions?

**Comment by michaelfig** [comment]
> @jfparadis @michaelfig any opinions?

I dislike the slower tests, but the separation seems worthwhile.
