### ISSUE TITLE
Support MyFirstDapp/SimpleExchange demo frontend

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#646]
Integrate myFirstDapp's UI with the changes to ERTP. Some steps include:

 * [ ] The deploy script currently starts with Purses, extracts assays, and uses those to create the contract.
       *  The Issuers aren't accessible from the purses or any other public entrypoint.  Rather than passing the registry names to the app owner, we'll change the way wallets are created to pass in issuers and payments.

 * [ ] Clean up the frontend's deploy script and integrate with the new ERTP.

 * [ ] Make a UI for Simple Exchange based on existing code and any in-progress work we can find.

**Comment by katelynsills** [comment]
@Chris-Hibbert is this ready to close?

**Comment by Chris-Hibbert** [comment]
Sure.
