### ISSUE TITLE
yarn link-cli doesn't work with old Node.js versions

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#661]
Reported by @dtribble:

```
$ sudo yarn link-cli /usr/local/bin/agoric
yarn run v1.22.0
$ node ./scripts/link-cli.js /usr/local/bin/agoric
creating /usr/local/bin/agoric
TypeError: Cannot read property 'writeFile' of undefined
    at <redacted>/agoric-sdk/scripts/link-cli.js:13:12
    at Object.<anonymous> (<redacted>/agoric-sdk/scripts/link-cli.js:15:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is caused by root's Node.js version not implementing the `fs.promises` API.  It should be straightforward to rewrite scripts/link-cli.js to be more portable.

**Comment by katelynsills** [comment]
Are we supporting old node versions?

**Comment by erights** [comment]
Same question. What versions are we talking about? We don't yet have post-alpha customers. Why compromise the quality of our code to run on anything but the latest?

**Comment by michaelfig** [comment]
> Are we supporting old node versions?

Just for the specific `link-cli` script.  The reason is that many people have old (i.e. pre-Node.js 10) versions lying around in system directories, so when they do a `sudo yarn link-cli`, it fails.  `fs.promises` is a relatively new invention, and I don't see any real reason to use it when the compatible `fs` API works just as well.

This code will never be in XS, either.

**Comment by michaelfig** [comment]
This falls into the same category that certain tooling (such as eslint, prettier) needs to use CommonJS, and it will take a long time for them to support native ESM.  Let's not force the world to migrate entirely to ESM and Node 13+ when just a few grungy tooling scripts (like link-cli) can live in the old world until the new world is fully here.

If you disagree, I would be happy to write link-cli as a portable Bourne shell script and dodge that bullet in a different way. 😉

**Comment by warner** [comment]
I actually like the non-promise script better, it reads more easily. I've always found async filesystem operations to be a bit silly (it's not like it's spawning a thread or using `aio` under the hood).

**Comment by michaelfig** [comment]
> I actually like the non-promise script better, it reads more easily. I've always found async filesystem operations to be a bit silly (it's not like it's spawning a thread or using `aio` under the hood).

Actually, that's [exactly what Node.js does](https://nodejs.org/api/fs.html#fs_threadpool_usage)
