### ISSUE TITLE
Wallet design notes

### ISSUE THREAD

**Issue by dtribble** [Agoric/agoric-sdk#671]
The wallet architecture for Agoric testnet is designed to enable the UI for Web application with a blockchain backend to connect to the user's wallet, and allow the users wallet to connect to the on-chain contract for the application. The basic idea is that the Web application proposes offers to the wallet, the wallet presents it to the user via a trusted-path UI, the user approves, and the wallets presents the offer to the on-chain application smart contract (in Zoe).

An example flow diagram for this sequence is:

![wallet](https://user-images.githubusercontent.com/739213/76377171-6c3bca00-6307-11ea-8080-f132993ef327.png)

The app designates the on-chain contract via its name in the [Registry](https://github.com/Agoric/agoric-sdk/tree/master/packages/registrar).

This approach addresses the concerns in [this issue](https://github.com/Agoric/agoric-sdk/issues/448). Amounts are passed by marshaling Brands as their Registry name.

**Comment by katelynsills** [comment]
We need to check whether this design matches the current implementation, and update and provide an equivalent version for our skeleton. 

If this doc is helpful, we should do a similar thing for our deployment steps.

**Comment by katelynsills** [comment]
We need to follow up with a wallet design meeting

**Comment by katelynsills** [comment]
A number of things are outdated here: the registry, not sending invites, offerHandles rather than seats. I think we might want to close and regroup in a different issue. What do you think, @dtribble?

**Comment by katelynsills** [comment]
Closing this issue as outdated.
