### ISSUE TITLE
Deal with problematic harden in `assert.js`

### ISSUE THREAD

**Issue by FUDCo** [Agoric/agoric-sdk#679]
A performance problem discovered in the course of #673: there's a call to `harden` in the implementation of the `details` template tag that was costing something ~25% of the execution time of the ping-pong benchmark.  This makes no sense, since the whole idea behind `details` is that it shouldn't impose much significant cost if it isn't used, which in the case of this particular test it isn't.  So there's something off in the logic of how `details` works.  I ran this past MarkM who judged that he potential hazard from removing this call to `harden` was minimal, so we decided to comment it out for the time being.  My recollection is that MarkM thinks we may be able to achieve the result another way, but doing this isn't on the critical path so we didn't invest time in figuring out how.  However, we really do need to do that, hence this issue so we don't lose track

I originally included this removal of `harden` in #673, but Brian requested it to be extracted into its own PR that we'll land before merging #673, so I will do that (and update this issue to point at it once we have the PR number).

**Comment by erights** [comment]
Add me as a reviewer on that separate PR.

The critical issue is that a `details` template literal expression may only appear either
   * as an argument to `assert` where we know the hardening won't matter, or
   * inside a `harden` anywhere else.

We eventually need a lint rule that enforces this. Something cheezy like regexp hacks plus a bit of manual inspection will do for now while the total number of occurrences are low. Even without that, there's no violation of ocap here, just a violation of the normal patterns of Jessie safety. But that still makes it much harder to reason about ocap safety question of the code containing these violations.

**Comment by FUDCo** [comment]
For the record, the PR for the removal was #684

**Comment by FUDCo** [comment]
@erights I was reviewing my issue backlog and came across this.  It looks, from my inspection of the code, that this is no longer relevant and can be closed, but I hesitate to do so without verifying such with He Who Knows.  So: can this just be closed?

**Comment by erights** [comment]
Thanks. Closing.
