### ISSUE TITLE
Make a `dapp-skeleton` template for `agoric init`

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#681]
Is this contract the simple exchange or the myFirstDapp? I think it's still myFirstDapp but renamed for some reason to simpleExchange? Is that right?

_Originally posted by @katelynsills in https://github.com/Agoric/agoric-sdk/pull/676_

---

I propose splitting off `packages/dapp-simple-exchange` to a new repository, and create a `packages/dapp-skeleton` as the default for `agoric init`.  The Getting Started documentation would be to help people clone `dapp-simple-exchange` and modify it.

If people want to run `agoric init`, that will give them much less (no UI, a totally faked-out Zoe contract and deploy scripts), but enough structure to create a new dApp from scratch.

**Comment by michaelfig** [comment]
@Chris-Hibbert, @dtribble PTAL.

**Comment by Chris-Hibbert** [comment]
I'm not sure how a new repo helps, but I like your proposal to have `agoric init` (documented in "Getting Started") clone a simple example for devs to start from. Would there be separate commands to make dev environments for playing with the frontends, or the entire framework?

**Comment by michaelfig** [comment]
As discussed privately, we want:

```sh
# This command:
agoric init demo
# Is equivalent to:
agoric init --dapp=simple-exchange demo
# Which expands to:
agoric init --dapp=https://github.com/Agoric/dapp-simple-exchange demo
# which runs:
git clone --origin=upstream https://github.com/Agoric/dapp-simple-exchange demo
# then
(cd demo && git config --unset branch.master.remote)
```

We should still work on a `dapp-hello-world` dApp to exercise UI, wallet, Zoe contract, API, and deployment.  This makes it possible to reuse the plumbing in new dApps.

**Comment by katelynsills** [comment]
I think we can close this now that we have dapp-encouragement
