### ISSUE TITLE
[Zoe] Empty object in 'onDemand' exit rule is a presence

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#686]
@michaelfig noticed that when we have the exit rule 'onDemand' and it has an empty object as a value as per the new Zoe Roles PR, it will be treated as a presence rather than as data. We need it to be treated as data. 

We have two options - to make it `undefined` or to insert data that is not very meaningful into the object. Having any key will make it a record rather than a presence. 

Solving this problem should be part of Zoe 0.3.0.

**Comment by michaelfig** [comment]
If it's not too late, can you make it `null` rather than`undefined`?  It may be easier to test for its presence.

**Comment by katelynsills** [comment]
> If it's not too late, can you make it `null` rather than`undefined`? It may be easier to test for its presence.

Not too late at all - I will do that!
