### ISSUE TITLE
[ERTP] Share vat-host.js and vat-mint.js for tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#70]
I wonder whether there's a simple way to have a master copy of vat-host and vat-mint, and have all the tests that need them share it rather than having separate copies in every directory.

_Originally posted by @Chris-Hibbert in https://github.com/Agoric/ERTP/pull/43_

**Comment by warner** [comment]
this was issue 51 in the old ERTP repo

**Comment by katelynsills** [comment]
Closing this issue as there are no longer vat-mint.js and vat-host in ERTP tests.
