### ISSUE TITLE
Tests for whether an implementation follows ERTP?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#71]
I was thinking that it would be useful to have tests that can be run against any implementation to see if the implementation supports the standard ERTP interfaces, especially when we start having user-defined assets. I'm thinking of something like the A+ promises tests, but instead testing whether it has such things as purses and payments, whether those things have the required methods, etc.

**Comment by warner** [comment]
this was issue 52 in the old ERTP repo
