### ISSUE TITLE
[Zoe] Up-call from Zoe

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#717]
Mark is trying a particular redesign experiment. He noticed that all the simple contracts only had one method per seat, and that users must redeem and then call a method on the resulting seat (2 steps). 

Dean observed that architecture-wise, we either have to make the user make a second call, or we must make an up-call from Zoe as a result of redeem. 

The idea is that when the user calls `zoe.redeem`,  this triggers a call from Zoe to the contract, and there is only ever one function associated with a particular invite that can be called. Zoe immediately returns a promise for the return value of the contract function. (Zoe must return a promise - Zoe cannot wait for the contract, or we lose payout liveness.) 

Michael pointed out that there was no loss of generality because the contract can provide any object as the result and the user can use that object for further communication.

In the PR addressing this issue, we should also rename `zoe.redeem` to something more pertinent.

@erights feel free to edit this description.

**Comment by erights** [comment]
Previous exploration at https://github.com/Agoric/agoric-sdk/pull/700 .

Using it as a guide and reminder, I'm starting over with a new branch off current master.

> In the PR addressing this issue, we should also rename zoe.redeem to something more pertinent.

Will do. This actually gives me a good transitional strategy. The new one is `offer`. The old one remains `redeem` until I remove it.
