### ISSUE TITLE
Roadmap for agoric-cli

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#723]
The CLI is documented in https://agoric.com/documentation/getting-started/#prerequisites

We are aiming first for stability (no breaking changes), and then for any feature requests.

Plans for the future:

- [ ] publish everything on NPM so that `npx agoric` works, and update documentation
- [ ] ... any other feature requests

**Comment by michaelfig** [comment]
@dtribble @katelynsills here's the roadmap.  I'm not sure where else to publish it.

**Comment by katelynsills** [comment]
I think when I was thinking "agoric-cli" I was thinking of all our example dapps too, so dapp-simple-exchange, and so forth. I think I'm still not clear on how everything is intended to be connected together. Also, how does the user upload their UI to the cloud?

**Comment by michaelfig** [comment]
That is still TBD, and will be documented in each individual dapp when I actually install them on Heroku.

You can raise issues in https://github.com/Agoric/dapp-simple-exchange as things that the template (and README.md) should mention.

**Comment by katelynsills** [comment]
Could we have an overview planning document for all of what used to be in agoric-cli including dapp-simple-exchange? 

For instance, the fact that we're planning to use Heroku is new to me. I think plans like that, even tentative ones would be great to have shared knowledge on.

**Comment by katelynsills** [comment]
I think we can close this and add to the Zoe Alpha plan instead. Does that sound ok?
