### ISSUE TITLE
Steps in Getting Started documentation may break without getting noticed

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#734]
## Problem

I've performed the current [getting started steps](https://agoric.com/documentation/getting-started/)
I've come across an error at `agoric deploy`

[I'm not the only one](https://github.com/Agoric/agoric-sdk/issues/715) and it's not the first time. Given agoric-cli depends on pretty much every (?!) package of agoric-sdk, i'm inclined to think that it will happen again. But since the steps described in the doc are in the doc, there is no way to know they have broken

This will result in a frustrating developer experience i imagine

## Potential solutions

Write automated tests for what's in the doc
This way, if the tests pass, it should give strong assurance that the doc document something that works as expected
And fix things so the tests pass otherwise

**Comment by katelynsills** [comment]
This is a great idea. I'm adding this to the project board. Let's discuss and see if we can assign someone to this.

**Comment by DavidBruant** [comment]
The error i've seen in #735 is fixed, but i see a different one (something about `exit` not being defined on `undefined`)

This is blocking for me. If i cannot get getting started steps working for me, i cannot understand how zoe contracts work today, i cannot play with them, i cannot write one for non-fungible tokens

Also, if the getting started steps do not work for me, i imagine they won't for other people

I'm self-assigning

**Comment by katelynsills** [comment]
> This is blocking for me. If i cannot get getting started steps working for me, i cannot understand how zoe contracts work today, i cannot play with them, i cannot write one for non-fungible tokens

A potential way to get around the blocking issues - could you first write your Zoe contract in the Zoe packages, in the tests directory locally? That should allow you to understand how Zoe contracts work, play around with them, and write the non-fungible token contract

**Comment by DavidBruant** [comment]
Sounds good, i'll try that!
