### ISSUE TITLE
[ERTP] Accept promises as arguments as long as we can use `E.unwrap` to synchronously get a presence

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#74]
Mark says that we should change all of our APIs so that they taken in presences and not promises. For instance, in `getExclusive`:

```
getExclusive(amount, srcPaymentP, name) {
      return Promise.resolve(srcPaymentP).then(srcPayment => {
        name = name !== undefined ? name : srcPayment.getName(); // use old name
        return takePayment(srcPayment, paymentController, amount, name);
      });
    },
```

`srcPaymentP` should be just `srcPayment` and the function should look like:

```
getExclusive(amount, srcPayment, name) {
   name = name !== undefined ? name : srcPayment.getName(); // use old name
   return takePayment(srcPayment, paymentController, amount, name);
}
```

We must do this because the scooter mechanism requires that the issuer does the money transfers in order when it does the final reorganization of the rights that it holds

**Comment by katelynsills** [comment]
Related: https://github.com/Agoric/agoric-sdk/issues/85

**Comment by katelynsills** [comment]
If we only allow promises as arguments in ERTP if they can be "unwrapped" to synchronously get a presence, that means we cannot have any promise pipelining in ERTP, right? Because promise-pipelining is when promises are not yet resolved, and the "unwrapping" only occurs when they are?

**Comment by erights** [comment]
> If we only allow promises as arguments in ERTP if they can be "unwrapped" to synchronously get a presence, that means we cannot have any promise pipelining in ERTP, right? 

No.

> Because promise-pipelining is when promises are not yet resolved, and the "unwrapping" only occurs when they are?

Resolved to who, where, and when?

Alice and Bob are on separate machines. On machine B:
```js
let total = 0;
const bob = harden({
  getThing() { return harden({foo: 3}); },
  addThing(thingP) {
    total += E.unwrap(thingP).foo;
  },
});
```
On machine A, say that Alice already has `bobP`, a remote promise to the above object. Alice says
```js
const thingP = bobP~.getThing();
bobP~.addThing(thingP);
```
On machine A, when Alice sends `thingP` as an argument, it is unresolved on machine A at that time.
When it arrived on machine B as an argument, it arrives already fulfilled with the local `({foo: 3})` from machine B. Bob is able to immediately `unwrap` it and use it synchronously.

No extra round trips. Promise pipelining worked great.

**Comment by michaelfig** [comment]
[@erights already replied, but I started writing my own, and I'll post anyway in case it makes things clearer.  In the case of conflicts, I defer to him.]

> If we only allow promises as arguments in ERTP if they can be "unwrapped" to synchronously get a presence, that means we cannot have any promise pipelining in ERTP, right? Because promise-pipelining is when promises are not yet resolved, and the "unwrapping" only occurs when they are?

Actually, unwrap is a way to preserve pipelining.  It allows a vat to make an async call to another vat, and then use the resulting promise as an argument to other async calls to the same vat in the same turn.  The synchronous nature happens in the called-to-vat, and the resolved promises are generated by the comms system.

This technique can avoid many uses of `async-await` and `.then`.

Here is the use-case AFAICT:

```js
function makeRefGetter() {
  return harden({
    createRef(name) {
       // without a comms system, we just return the object directly
       // When used with a comms system, our caller gets a promise for a presence of this object.
       return harden({
         getName() { return name; },
       });
    },
    // NOT an async function!
    operateOnRef(refP) {
      // refP can be a local object or a promise for a local ref generated by the comms system
      const ref = E.unwrap(refP);
      // Synchronously operate on the ref.
      const name = ref.getName();
      log('I got the name:', name);
      return name;
    },
  });
}

// Make the refGetter accessible
E(somewhere).setRefGetter(makeRefGetter());

////////////////////////////////
// In another vat.
const rg = E(somewhere).getRefGetter();

// Get a promise for a ref
const fooRefP = E(rg).createRef('foo');
 // operate on the reference without a round-trip
E(rg).operateOnRef(fooRefP);
// same, but has a round-trip
fooRefP.then(fooRef => E(rg).operateOnRef(fooRef));
```

**Comment by katelynsills** [comment]
Thanks so much, these explanations are very clear. Do we have explanations like this currently? If not, can we put them in our documentation somewhere?

**Comment by erights** [comment]
> Do we have explanations like this currently?

AFAIK just in this thread ;)

> If not, can we put them in our documentation somewhere?

We should. Also into the tc39 proposal. As with proxy-presences https://github.com/tc39/proposal-eventual-send/issues/8#issuecomment-582125976 , there remains the timing issue. In this case, `E.unwrap` is already in the shim. The only question is whether we should add it to the proposal immediately. Since the motivation for the proposal is explicitly to support promise pipelining, I think it should go in now.

**Comment by katelynsills** [comment]
Great, I just created an issue to move these thoughts into some sort of documentation.
