### ISSUE TITLE
remove unnecessary 'ses' dependencies

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#740]
I see `package.json` -declared dependencies on SES in the following packages:

* ERTP
* SwingSet
* transform-eventual-send (dev)
* transform-metering (dev)
* zoe

Zoe and ERTP don't import `ses` anywhere. transform-metering imports it from a unit test, as does transform-eventual-send.

I'm going to remove the SES import from Zoe and ERTP: unless they have test cases that deliberately set up a SES environment, they should rely upon a host like SwingSet to set up the SES world for them.

@katelynsills @Chris-Hibbert does that seem reasonable? There might be a Chesterton's Fence here that I don't know about.

**Comment by Chris-Hibbert** [comment]
Sounds right to me.

**Comment by katelynsills** [comment]
Sounds right to me too.
