### ISSUE TITLE
[Zoe] SimpleExchange returns `{ invite, inviteHandle }` from `makeInvite`. Should it?

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#747]
On line 127 below, you return `{ invite, inviteHandle }` from `makeInvite`. But in most contracts, the invite making function just returns the `invite`. Why not follow the same pattern? (Also myFirstDapp)

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/685_

**Comment by DavidBruant** [comment]
The only usage i've seen in tests is this one:

https://github.com/Agoric/agoric-sdk/blob/cdb200b96474cbdf1f2cd6a5b6e3b0718e62eea9/packages/zoe/test/unitTests/contracts/test-simpleExchange.js#L308

It doesn't seem like this alone justifies exposing the inviteHandle
I think that a method on Alice seat (`aliceSeat1.getOffer`) could serve the same purpose (call `zoe.getOffer` on the correct inviteHandle)

**Comment by katelynsills** [comment]
I don't like how wonky this is, but the `offerHandle` can be gotten from the extent of the invite: 

```
const { extent: { handle }} = await inviteIssuer.getAmountOf(invite);
```

We need to do some thinking about how to make this as easy as possible for the user. I think returning it with the invite is the wrong choice, though, because it prohibits promise pipelining. 

I'll make an issue for this.

**Comment by Chris-Hibbert** [comment]
It's wonkier than you suggest. There's an array in there to be destructured as well:

```
    const {
      extent: [{ handle }],
    } = await inviteIssuer.getAmountOf(invite);
```

I prefer @DavidBruant's suggestion. Would a `getOffer()` on the seat serve as well as the publicAPI?  The other choice is to add a helper method somewhere to get the `inviteHandle` given the invite.

**Comment by Chris-Hibbert** [comment]
Also note that [the docs for `zcf.makeInvite()`](https://agoric.com/documentation/zoe/api/zoe-contract-facet.html#zcf-makeinvite-seat-customproperties) say (in the example) that it returns `{invite, inviteHandle}`.  The formal return value is listed as `{Payment}`, presumably because that's the type of the Invite.

**Comment by katelynsills** [comment]
Yeah, I think the thing to be decided is not what `zcf.makeInvite` returns, which should be { invite, inviteHandle } in my opinion, but whether the contracts only return an invite to the user
