### ISSUE TITLE
Enforce that check...() functions in contracts are pure

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#75]
Supporting the general case of [Jessie purity checking](https://docs.google.com/document/d/1pPiu3cjBT5OqEgqtsdDJcW5g1QsgmxvIHQjdkrPej3U/edit#heading=h.knluie3entao) is beyond the scope of what we want to do immediately, but we can start by only allowing closed function expressions. As we have time or need, we can add more checking to allow more possibilities.

This discussion arose out of a discussion of moving collect() from ContractHost to Escrow. It could be provided by the Escrow service the same way that checkAmount() and checkPartialAmount() are.

The start() method also provided by contracts doesn't need to be pure.

The contracts' check* methods wouldn't currently pass a real purity test because they rely on sameStructure.

**Comment by katelynsills** [comment]
This issue is related to the contractHost. #394 
Let's reopen this when we redesign contractHost for its new use case.
