### ISSUE TITLE
unwrap() doesn't work on intra-vat HandledPromises 

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#759]
While putting together a test for `depositInOrder()` in #711, I  found that the promise for a payment returned by `claim()` wasn't being unwrapped.  `depositInOrder()` calls `E.unwrap(paymentP)` before looking the payment up in `paymentLedger`.

```
  const purse = issuer.makeEmptyPurse('my new purse');
  const payment = mint.mintPayment(fungible25);
  const exclusivePaymentP = E(issuer).claim(payment);
  E(purse).depositInOrder(exclusivePaymentP, fungible25);
```

MarkM and I looked at this for a while, and concluded that in unit tests, local within-vat promises aren't being handled by marshall, and so they end up as a HandledPromise wrapping a platform promise, wrapping another HandledPromise. E.unwrap() is unable to follow the chain to find the resolved HandledPromise on the inside, so unwrap doesn't do what we want.

The depositInOrder() design doesn't work for some local promises given this issue, so we can't promise the behavior we intended.

We'll have to remove depositInOrder() from the current state of the PR and then verify that all calls to deposit() (100+ of them) are sending resolved promises. This will be pretty straightforward, but MarkM and I identified at least one case in the first few examples we looked at in which the argument to deposit() was a promise without a 'P' suffix, so I'll have to be careful.

@erights, please correct my misstatements above.

**Comment by erights** [comment]
Hi @Chris-Hibbert everything accurate except
> are sending resolved promises

They need to send presences, not promises.

**Comment by katelynsills** [comment]
Since we believe `unwrap` should be removed from current usage, should this issue be closed?

**Comment by erights** [comment]
Yes. Closing.
