### ISSUE TITLE
dispatch.notifyResolve* removes clist+liveslots entries (receiving side)

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#766]
The first step of #675 is remove table entries on the *receiving* side of a Promise resolution. This occurs as the `dispatch.notify*` call arrives (any of the flavors: `notifyFulfillToData`, `notifyFulfillToPresence`, `notifyReject`, and the as-yet-unimplemented `notifyForward`).

The kernel will first use the clist to map all the capdata slots to Vat identifiers. For promises, this maps "kernel promise identifiers" (`kpid`) to "vat promise identifiers" (`vpid`). Once everything is mapped, the kernel then deletes the clist entry for the *target* of the message (which might also be an argument, that's ok). Finally the kernel invokes `syscall.notify*` with the vat-specific slot values. This enables the kernel to fulfill its pledge that it shall never again speak of the `vpid` that has just been resolved.

Upon receipt, liveslots must deserialize the body of the resolution `dispatch`. This references `slotToVal` to translate the `vpid` values into actual `Promise` objects. Immediately after deserialization, before any syscalls can be provoked, liveslots must delete the `vpid` from `slotToVal`, and must delete the `Promise` from the `valToSlot` WeakMap. It must also delete the `vpid` from `importedPromisesByPromiseID` (we should look at this a bit more closely, I don't remember exactly how it works). This enables the vat to fulfill its own pledge to never mention the resolved `vpid` again.

Note that the abstract *Promise* thus referenced might be referenced again, but if so, it will be assigned a new `vpid`. The reference might come from the kernel, since the `kpid` may stick around for a while (in the arguments of a pending message, in the resolution or rejection of some other Promise, or referenced by some other Vat which hasn't yet forgotten about it too). If the kernel delivers a new message that references the same `kpid`, the kernel will assign it a new `vpid`. Or the reference might come from the vat, since the `Promise` object might be retained by some user-level code which liveslots is unaware of. If this user-level code sends the `Promise` out into the kernel, liveslots will assign it a new `vpid`, and the kernel will be unaware that the new `vpid` it sees (and thus the new `kpid` which it assigns) is at all related to the old one.

The vat which performs the resolution may still have a clist entry for a while: we're addressing that in a second phase. And the kernel may retain the `kpid` for a while, we're addressing that in a third phase.

**Comment by warner** [comment]
For test cases, we should have one vat do something like the following:

```js
const pr = makePromise();
await bob~.foo(pr.p);
pr.res(4);
await bob~.sync();
await bob~.bar(pr.p);
await bob~.sync();
```

and then on bob's side, assert that the promise arriving in `foo()` is different than the promise arriving in `bar()`. The `foo()` promise should be resolved by the time `sync()` is called the first time, and the `bar()` promise by the time `sync()` is called the second time.

We should then repeat this for the other forms of resolution: `pr.rej(Error())`, and `pr.res({})` (for a presence).

**Comment by FUDCo** [comment]
Closing as part of refactoring the tickets for #675.  The underlying work has largely been done, except for promises that resolve to data that reference other promises, which is a project unto itself (see #1049)
