### ISSUE TITLE
Consider adding Zoe helpers to the Zoe contract facet

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#779]
I see the zoe helpers being frequently imported in contracts. Some helpers (like `swap`) feel so central to Zoe's purpose that it might make sense to make it part of the API directly

**Comment by Chris-Hibbert** [comment]
It doesn't necessarily have to be part of Zoe's interface, but it should be more prominent than an importable file in the helpers directory under .../contracts/. Working on zoe-sketchbook, this seemed like the wrong place for it to come from.

**Comment by Chris-Hibbert** [comment]
After some discussion, we settled on moving these to be exported from '@agoric/zoe/contractSupport', with the goal of eventually making a separate package like '@agoric/zoe-contractSupport'

https://github.com/Agoric/agoric-sdk/pull/868

**Comment by Chris-Hibbert** [comment]
https://github.com/Agoric/agoric-sdk/pull/867
