### ISSUE TITLE
Zoe chainmail lacks information about InstanceRecord

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#781]
I don't see it documented

Also, ZoeService has a `getInstance` method while the contract facet has a `getInstanceRecord` method

**Comment by katelynsills** [comment]
We do have the documentation here: https://agoric.com/documentation/zoe/api/records.html#instance-record. 

But, we should add it to the chainmail. Also, I think the ZoeService `getInstance` method should be renamed to `getInstanceRecord`
