### ISSUE TITLE
"publicAPI" feels like a weird name

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#782]
Specifically, the "API" part
Maybe `public` is enough?

The design of `{invite, publicAPI}` surprises me, but maybe that's for another time

**Comment by erights** [comment]
I believe "public" is still a reserved keyword in JS. Could still use it as a property name, but it's awkward because it cannot be a variable name.

**Comment by DavidBruant** [comment]
good catch! Maybe `publicFacet`?
Thinking more about it, maybe `public` is inaccurate. It's public only in the sense that everyone who is aware of the existence of the contract (by getting an invite) can access this API. Only the zoe service is public. The `publicAPI` may or may not be public

**Comment by katelynsills** [comment]
The publicAPI is public to any one who has the `instanceHandle` - which could be put in the registrar, for instance. I think you're right that the distinction is "these methods do not require an invite to use". I don't have a better term for that though.

**Comment by DavidBruant** [comment]
Maybe something with "table" (in echo with `seat`)

**Comment by erights** [comment]
I like that direction!

**Comment by katelynsills** [comment]
Ahh, I finally understood the table reference (a seat at the table, the API being the table...). I think we are using the word table in a database sense already, so that may be difficult. Also, the publicAPI has no associated seats or privileged positions (or really any positions that are different).

**Comment by erights** [comment]
> table in a database sense

That's part of why I didn't have any concrete suggestions. But I like the direction. What are synonyms for table. What other furniture do people sit on chairs around?

**Comment by DavidBruant** [comment]
> I think we are using the word table in a database sense already, so that may be difficult

I just checked and from what i see in the Zoe API documentation, the word table from the internal storage is not reflected in the API (aside from [typos](https://github.com/Agoric/documentation/pull/107))

It is used in comments of [records doc](https://agoric.com/documentation/zoe/api/records.html), but i think that the word "map" could be used ([tables are weakmaps under the hood after all](https://github.com/Agoric/agoric-sdk/blob/cf9346dde2a3fcea435af5149cb958aad5a8016d/packages/zoe/src/state.js#L8-L10))

**Comment by katelynsills** [comment]
I'm not liking `table` or `seat` or `map`. I think they're too figurative and we have problems with comprehension already. publicAPI is intended to be exactly what it is: the public API of the contract. If we have a better name for expressing exactly that, I'm in favor of it, but I think more figurative names are not the right way to go.

**Comment by katelynsills** [comment]
Closed in #1414
