### ISSUE TITLE
[Zoe] IssuerKeywordRecord should be an optional argument in `makeInstance`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#785]
The multipool autoswap shouldn't have to start with any issuers. The agent who makes the instance should use the external method to add a new liquidity pool. Currently, Zoe requires an IssuerKeywordRecord to make an instance, but it should not.

**Comment by DavidBruant** [comment]
I think that solving this would solve #778 along the way

---
edit: ... maybe not
