### ISSUE TITLE
[Zoe] Rewrite `checkIfProposal` and `rejectIfNotProposal` such that `expected` is the same object structure as the proposal

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#794]
These lines triggered an alert in my mind because they don't fit the new Keywords pattern

https://github.com/Agoric/agoric-sdk/blob/e7c5b57fd8d92b092eee6bda654ac40446962a6e/packages/zoe/src/contracts/simpleExchange.js#L95-L103

but i'm not familiar enough with the new code to deduce whether this is actually a bug

**Comment by katelynsills** [comment]
Not a bug, but certainly awkward. We want to only check the keys in this case, to see if the proposal structure matches what we expect, for instance: 

```
{
  give: { Price: amount1 },
  want: { Asset: amount2 },
}
```

The thing is, we don't care about amount1 and amount2. We only want to check the keywords and whether they are under `give` or `want`. The solution to this was to have the keywords as arrays. We could have alternatively had the amounts as null, but that seemed more verbose.

**Comment by katelynsills** [comment]
Another alternative - full proposal but ignore values. Use 'null'

**Comment by katelynsills** [comment]
Current task:

We need to rewrite the `checkIfProposal` and `rejectIfNotProposal` methods so that instead of `expected` including arrays of keys, `expected` should be the same object structure as the `proposal` with `null` for the values.
