### ISSUE TITLE
[ERTP] Improve the packaging of the `makeMint` config

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#80]
We pass a configuration into `makeMint`. Is there a better way to organize the configuration?

**Comment by DavidBruant** [comment]
I don't feel ready to answer the question, but i'm going to try to explore the problem:

## ExtentOps configuration

For the [invite mint](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/contractHost.js#L33), `makeInviteConfig` is used. It [uses](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/config/inviteConfig.js#L21) the `'inviteExtentOps'` string as `extentOpsName`. This string is [passed to `makeUnitOps`](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/mint.js#L245), which itself [uses the string as a key](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/unitOps.js#L27) in the [extentOpsLib object](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/config/extentOpsLib.js)

Same goes for the [pixel extentOps](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/more/pixels/pixelConfig.js#L155)

This feels too complicated, especially the indirection via a string (+args) while it could be an object imported from a module directly (the fact that the [pixelExtentOps is imported from `../../more/pixels`](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/config/extentOpsLib.js#L5) feels like further indication of the problem ) 

The [documentation mentions "strategy"](https://agoric.com/documentation/ertp/guide/default-configuration.html#basic-make-configuration-function), but i haven't found these yet. Is the documentation ahead of the code?


## Generators

The [default config is based on generators](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/config/noCustomization.js#L10-L24). It's not clear to me what this adds by opposition to simple functions ([same thing in pixels](https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/more/pixels/pixelConfig.js#L60))

I feel like it would simplify code from core/mint.js from:
https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/mint.js#L71-L72
to 
```js
const paymentTrait = makePaymentTrait(corePayment, assay);
```

**Comment by erights** [comment]
See https://github.com/agoric-labs/layer-cake for a better explanation of the problem we turned to generators to solve, and for better support for using generators to solve this problem.

That said, if this problem can be solved even better without generators or anything similarly weird, that would be better.

If we stick with generators for traits, we should consider improving, incorporating, and using the layer-cake library.

**Comment by katelynsills** [comment]
> The [documentation mentions "strategy"](https://agoric.com/documentation/ertp/guide/default-configuration.html#basic-make-configuration-function), but i haven't found these yet. Is the documentation ahead of the code?

Ah! This is old documentation that missed our renaming spree somehow. We should make an issue in Documentation to update it

**Comment by DavidBruant** [comment]
> See https://github.com/agoric-labs/layer-cake for a better explanation of the problem we turned to generators to solve, and for better support for using generators to solve this problem.

Hmm... this is new to me and i'll need some time to wrap my head around it
Do you have a problem that layer-cake would solve in the context of ERTP, but in a way that object-as-closures + Object.assign wouldn't solve?

**Comment by DavidBruant** [comment]
I'm piling on the things that could be improved for mint config ergonomics

## Complete incomplete configs with defaults

The invite config is created via some `noCustomization` object with sensible default settings

https://github.com/Agoric/agoric-sdk/blob/f6a5679a024fa408b5803373407fc74aafba5ef5/packages/ERTP/core/config/inviteConfig.js#L17-L24

`makeMint` has a default if no config is passed, but assumes a passed config is complete

https://github.com/Agoric/agoric-sdk/blob/f6a5679a024fa408b5803373407fc74aafba5ef5/packages/ERTP/core/mint.js#L21-L35

A middle ground could be that when a config is passed, it is first completed within 
`makeMint`. This way:
- when nothing is passed, the completion provides the default config for fungible assets
- when a full config is passed, there is nothing to complete and it is used as is
- when a partial config is passed, `makeMint` makes a sensible choice and the burden of completion is lifter off of the user's shoulders

**Comment by katelynsills** [comment]
> A middle ground could be that when a config is passed, it is first completed within
> `makeMint`

I like this idea!
