### ISSUE TITLE
canTradeWith may contain a mismatch between keywords and amountMaths

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#802]
In the following code, `keywords` is the latest version and `amountMaths` is the lexically captured version

https://github.com/Agoric/agoric-sdk/blob/5505d6c639e6135db7f4e700bd0fd1fc392858be/packages/zoe/src/contracts/helpers/zoeHelpers.js#L74-L81

This lexically captured version is created when `makeZoeHelpers(zoe)` is called:

https://github.com/Agoric/agoric-sdk/blob/5505d6c639e6135db7f4e700bd0fd1fc392858be/packages/zoe/src/contracts/helpers/zoeHelpers.js#L10-L12

However, between the call the `makeZoeHelpers(zoe)` and `canTradeWith`, it's possible that a contract may have called `zoe.addNewIssuer(newIssuer, newKeyword);` was called and this creates a mismatch (which results in `TypeError: Cannot read property 'isGTE' of undefined`)

**Comment by katelynsills** [comment]
Yup, good catch.

**Comment by Chris-Hibbert** [comment]
Fixed in #812
