### ISSUE TITLE
[Zoe] Eliminate use of old `setupBasicMints` in tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#808]
Zoe tests are currently in transition between the old format of setting up mints where mints, issuers, etc were all arrays, and the new format, in which we retain the records returned by `produceIssuer`. The new format is currently in a helper file called `setupBasicMints2`. We should eliminate the usage of the old format and rename the new format file to simply `setupBasicMints`.

**Comment by Chris-Hibbert** [comment]
closed by #922
