### ISSUE TITLE
[ERTP] Consider adding an event library as part of ERTP

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#82]
Events have always been a core part of JavaScript (but not ECMAScript)
They have been [part of the DOM](https://dom.spec.whatwg.org/#interface-eventtarget) via `addEventListener` since the beginning
They have been [part of Node.js via the EventEmitter API](https://nodejs.org/dist/latest-v12.x/docs/api/events.html) since pretty much the beginning (API was stable in 0.10 and i didn't look for earlier API, but i think it was already there and stable when i started playing with node 0.6)

I see [events being re-invented in cosmic-swingset](https://github.com/Agoric/cosmic-swingset/blob/7a60b03ea9baac44fb1ba9eb9f832d369fefe719/lib/ag-solo/vats/vat-demo.js#L24-L37) (with an API that's neither the DOM or Node.js API)

I also think that the handoff service is incomplete without events. Once different parties have access to a shared corkboard, the only way to know when the other party has access to the corkboard is via [polling](https://en.wikipedia.org/wiki/Polling_(computer_science)) and this may come at a cost either when addressing a blockchain vat or worst, if performed by a blockchain vat.
Same thing for the corkboard itself. The only way to know if the other person has posted a `foo` message is via polling `lookup('foo')` regularly
It is possible to re-implement an EventEmitter-like API through the corkboard, but i imagine this would come as yet another convention on messages and timing, etc.

If events were parts of ERTP, i anticipat that less work would be needed from people setting up contracts

**Comment by katelynsills** [comment]
As of 2/8/2021, `@agoric/notifier` is a library for notifiers and subscriptions, although subscriptions are currently blocked needing to send `Symbol.asyncIterator` through the kernel. `@agoric/ertp` has a method `purse.getCurrentAmountNotifier()` for getting a notifier that gives recent balances of the purse. In our planning documents, we also outlined a few other event requirements:

* Event for purse (makeEmptyPurse, withdraw, deposit)
* Events for payments (at object level, not blockchain explorer - only minting, burning, ERTP reallocate)

**Comment by erights** [comment]
I think notifier and subscription provided the needed event abstractions. Subscription awaits our ability to send `Symbol.asyncIterator` through the SwingSet kernel, but we're tracking that in another issue. So I'm closing this one.
