### ISSUE TITLE
[Zoe] Check that invite field of `makeInstance` return value is an actual invite

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#820]
No check is performed on the `invite` field ; it is returned as it is

https://github.com/Agoric/agoric-sdk/blob/7ceebe5f45333525eb59a9d6ec7a062f93ea2da7/packages/zoe/src/zoe.js#L336-L342

Edit below by Kate 4/7:
We should add a check:

```inviteIssuer.isLive(invite)```
This will take another turn since isLive returns a promise.

**Comment by katelynsills** [comment]
Not doing a check isn't intentional, so this is a great issue. I think we could do:

```
inviteIssuer.isLive(invite)
``` 

This will take another turn since `isLive` returns a promise, but I think we should do it.
