### ISSUE TITLE
Make it possible for digital assets to be minted on-chain, but outside Zoe/spawner

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#821]
This issue in reference to https://github.com/Agoric/agoric-sdk/issues/543#issuecomment-604112546

This limitation leads to various weird workarounds

**Comment by katelynsills** [comment]
I think the spawner is the right place for this since we need some kind of deployer, but the spawner may change drastically from what it looks like now.

**Comment by katelynsills** [comment]
We went the opposite direction and are now minting synchronously within Zoe.
