### ISSUE TITLE
Calling zoe.redeem inside a contract may be a footgun

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#822]
Issue created after the analysis here: https://github.com/Agoric/agoric-sdk/pull/780#discussion_r401096174

**Comment by katelynsills** [comment]
Autoswap uses `zoe.redeem` to escrow liquidity tokens. I think we cannot eliminate this. If we did make a change, we would want to streamline this process rather than remove it.

**Comment by DavidBruant** [comment]
I'm having an intuition that there is an underlying design problem somewhere
Maybe it's not related to forbidding redeem, maybe it's something else

I'm reopening and i'm going to try to find what the underlying design problem may be

**Comment by DavidBruant** [comment]
Zoe provides "offer safety". My understanding of offer safety is that it protects against bugs in a smart contract code and this protection makes that it's not possible to loose an asset even if there is a bug in the contract.
The way Zoe achieves that is by separating asset handling (assets are posted to, `claim`ed by and `reallocate`d by Zoe) and smart contract code (which only manipulates offerHandles refering to assets, but never assets directly. And offerHandles are accessed by a user and the contract)

I think that letting smart contracts manipulate directly assets/invites/payouts is a breach of the separation of concerns that enable offer safety and this could lead to Zoe not really providing offer safety

I looked at where/how redeem is used in all existing contract code. I see 3 instances of redeem that are internal to contracts:

1) in autoswap:

https://github.com/Agoric/agoric-sdk/blob/0ab9ebf37162a71639acb23000b4183d759b6dcd/packages/zoe/src/contracts/autoswap.js#L148-L155

2) in `makeEmptyOffer`

https://github.com/Agoric/agoric-sdk/blob/0ab9ebf37162a71639acb23000b4183d759b6dcd/packages/zoe/src/contracts/helpers/zoeHelpers.js#L108-L111

3) in the current (but soon another version will replace it) version of the Opera ticket contract:

https://github.com/Agoric/agoric-sdk/blob/adc846a5371edf0bb06f9cacd125fa5c588e5fcf/packages/zoe/src/contracts/operaConcertTicket.js#L88-L103

As i highlighted, the 3 usages have one thing in common which is creating an invite first and then redeeming it right away

At least, i think this would be better served by a dedicated method on the zoe contract facet 
Its signature could be: 
`{offerHandle, payout} = zoeContractFacet.makeOffer(proposal, payments)` (i do not feel strongly on the method name)

Interestingly, the usages i showed above are the only usages of `zoe.getZoeService()` in all current contracts, so maybe or maybe not `getZoeService` could be removed from the zoe contract facet

**Comment by katelynsills** [comment]
> At least, i think this would be better served by a dedicated method on the zoe contract facet
Its signature could be:
{offerHandle, payout} = zoeContractFacet.makeOffer(proposal, payments) (i do not feel strongly on the method name) Interestingly, the usages i showed above are the only usages of zoe.getZoeService() in all current contracts, so maybe or maybe not getZoeService could be removed from the zoe contract facet

Interestingly, this was actually the design we started with! It got changed to `zoe.getZoeService()` on Mark's request, but maybe we should revisit after Zoe Alpha

**Comment by erights** [comment]
Happy to revisit. Until then, I do like the way it is now better. Will explain when we revisit.

**Comment by erights** [comment]
I misunderstood the intent. Yes, I support doing some like this. Perhaps this itself but my understanding isn't that solid yet. And we all now support keeping `getZoeService`.

Good idea and good analysis. My apologies for not reading deeper earlier. Thanks!

**Comment by katelynsills** [comment]
Is #993 enough of a solution to close this issue?

**Comment by erights** [comment]
> Is #993 enough of a solution to close this issue?

Yes.

**Comment by DavidBruant** [comment]
Yes, i think it's good enough for now
Thank you very much for this work!

**Comment by katelynsills** [comment]
Closed by #993
