### ISSUE TITLE
liveslots/HandledPromise: post-resolution calls go to promise, not resolved object

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#823]
As @FUDCo discovered in #766 and #814, our current combination of liveSlots and HandledPromise doesn't process message sends to resolved Promises quite the way we wanted. In a sequence like this:

```js
 const p1 = E(target1).foo();
 E(p1).one();
 await p1; // resolves to target2
 E(p1).two();
```

we expect the `one()` message to be pipelined: the vat does a `syscall.send(target=p1, method='one')` into the kernel, and the kernel either forwards this messge to the deciding vat (if that vat has enabled pipelining, e.g. the comms vat), or queues it in the kernel promise table entry for `p1`. However we expect the `two()` call, which happens *after* `p1` has been resolved, to be sent to the resolution of `p1` (namely `target2`). That is, in the crank that is driven by the delivery of a `notifyFulfillToPresence(target=p1, result=target2)`, we expect to see a `syscall.send(target=target2, method='two')` message.

Instead, I'm seeing `syscall.send(target=p1, method='two')`.

I'll push a branch that has a unit test for this (disabled until we fix it). In yesterday's session, @michaelfig and @erights identified one path through HandledPromise that would behave like this, although I'm not yet sure it's exactly the one that's happening.

**Comment by warner** [comment]
look at the end of `packages/SwingSet/test/test-liveslots.js`, in `doResultPromise` (called with `mode = 'to presence'`) for the failing test

https://github.com/Agoric/agoric-sdk/blob/91f6f159903a2cab567abbe2f632a3d549a878d4/packages/SwingSet/test/test-liveslots.js#L496-L499

**Comment by warner** [comment]
In this sequence, liveslots does the following:

When we send `foo()`:
* `queueMessage()` allocates a vat-side promise ID ("vpid") for the result, e.g. `p+1`
* it then uses `makeQueued(vpid)` to create a HandledPromise whose `unfulfilledHandler` knows how to use `queueMessage` to send messages to `p+1`
```js
  function makeQueued(slot) {
    const handler = {
      applyMethod(_o, prop, args) {
        // Support: o~.[prop](...args) remote method invocation
        return queueMessage(slot, prop, args);
      },
    };
    const pr = {};
    pr.p = new HandledPromise((res, rej, resolveWithPresence) => {
      pr.rej = rej;
      pr.resPres = () => resolveWithPresence(handler); // fulfilledHandler
      pr.res = res;
    }, handler); // unfulfilledHandler
    return harden(pr);
  }
```
* the Promise is registered in `importedPromisesByPromiseID` under `p+1`, for use by the eventual resolution notification
* the Promise is also registered in `valToSlot` and `slotToVal`, in case we send the Promise in a subsequent argument

Next, when we pipeline the call to `one()`, that `unfulfilledHandler` does a `syscall.send` to `p+1`

Later, when the target responds to the initial `foo()` with `target2` (i.e. resolving the result promise to some object reference like `o-2`), the kernel will deliver a `dispatch.notifyFulfillToPresence('p+1', 'o-2')`:

```js
  function notifyFulfillToPresence(promiseID, slot) {
    const val = convertSlotToVal(slot);
    importedPromisesByPromiseID.get(promiseID).res(val);
  }
```

This first uses `convertSlotToVal` to build a Presence out of the `target2` resolution. It does this by creating a new HandledPromise, using its `resolveWithPresence()` method immediately, throwing out the Promise object, and retaining the generated Presence object. The call to `resolveWithPresence()` gets a handler that remembers the new object reference (`o-2`).

```js
        // prepare a Promise for this Presence, so E(val) can work
        const pr = makeQueued(slot);
        const presence = pr.resPres();
        presence.toString = () => `[Presence ${slot}]`;
        harden(presence);
        val = presence;
```

(and registers it in `slotToVal`/`valToSlot` for use in subsequent messages). Finally it looks up the resolver in `importedPromisesByPromiseID`, and invokes it with the new Presence object.



According to our conversation yesterday, the intention here was that the old promise (`p1`), along with its `unfulfilledHandler` (which would send things to `p+1`), should be completely subsumed by the new Presence (and most especially by it's new `fulfilledHandler`, which will send things to `o-2`).

One pathway we discussed was whether the old Promise was being *forwarded* to the new *Promise*, rather than being *fulfilled* to the new *Presence*. I think @michaelfig spotted a bug in HandledPromise which would fail to update the handler in this case.

However I don't think we're triggering that directly, because we throw that new HandledPromise away, and only use the Presence.

So one question I have: if we fulfill `p1` to a *Presence* that is built by calling `resolveWithPresence()` on some `p2`, then is `p1` supposed to be subsumed by `p2`? That is, should `p1` start behaving identically to `p2`, including the handler that now points its messages at `o-2` instead of the original `p+1`?

**Comment by warner** [comment]
I think @michaelfig said he could take a look at this.

**Comment by warner** [comment]
I did a trial run of rebasing #871 on top of my additional tests, and strangely they continue to pass. I have a specific test (https://github.com/Agoric/agoric-sdk/blob/d28c8981225bf24f4d2765dd5471f1d9a97f3463/packages/SwingSet/test/test-vpid-liveslots.js#L322) that should be sensitive to this being fixed, and it's still behaving the old way (we see a pipelined `syscall.send` to the kernel promise, rather than a send to the resolved object). I'm wondering if #886 has a larger effect than I previously thought.

**Comment by FUDCo** [comment]
I remain concerned that the changes in #871, while improving things, don't actually address the failure mode I've been seeing.  That's why I'm looking forward to getting it landed so I can step through my failure case in the debugger (even if everything now works perfectly, it would at least help me try to understand how the promise shortening thing works).
