### ISSUE TITLE
add isPromise() to the make-promise package

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#828]
We don't currently have a way for SES code to detect whether something is a promise. This would be useful, and we know how to build it.

```
export function isPromise(maybePromise)
  return Promise.resolve(maybePromise) === maybePromise;
}
```

An [IBIS](https://docs.google.com/document/d/1prTppy1FOmmi-oEXIZ7zA4Ft08xXX7h1fuBb5aDlrBU/edit#heading=h.lejkhjy7gfp9) summary extracted from a discussion I had with @warner:

``` text
? separate files or multiple exports
   :- isPromise as a property of makePromise  ==> one export
     + most backward compatible
   :- makePromise is default export, isPromise as a named export from the same file.
      ? Can '-r esm' support that?
	      esm would export that as { default, name1, name2 }
   :+ export makePromise and isPromise separately from makePromise.
      ==> import { makePromise, isPromise } from '@agoric/make-promise'
      + cleanest
      + This is probably the safest and easiest to evolve to
      ! change all `import makePromise from '@agoric/makePromise'  to  `import { makePromise } from '@agoric/makePromise'
      ! bump all package.json files to depend on 0.0.2
      ! change make-promise, bump make-promise/package.json to 0.0.2, add NEWS.md

?~ split packages or combined
  :~+ combined
    + our isPromise() has to understand HandledPromises, so it should be part of makePromise
  : split because there there are lots of isPromise packages
```

 [ ] change all `import makePromise from '@agoric/makePromise'  to  `import { makePromise } from '@agoric/makePromise'
 [ ] bump the package.jsons to depend on 0.0.2
 [ ] change make-promise, bump make-promise/package.json to 0.0.2, add NEWS.md

**Comment by Chris-Hibbert** [comment]
Okay, so much for that. The current version of makePromise doesn't support 
```
import { makePromise } from '@agoric/make-promise';
```
which was the basis for our slow-but-steady migration plan. Is there a change I can make to makePromise so it can support both the current usage, and a desired future where we can also import `isPromise`?

**Comment by michaelfig** [comment]
> Is there a change I can make to makePromise so it can support both the current usage, and a desired future where we can also import isPromise?

I'd say, mark it as a breaking change (with `feat!: named exports only`), and just change all the callers at once.  While we're making breaking changes, I'd go further and have `makePromise()` return an object with `.resolve` and `.reject` and `.promise` properties (spelled out).  Maybe it should be called `makeDeferred()` or something new.  Here's a chance to have the API be more explicit and less mgclly abbrvtd.

**Comment by Chris-Hibbert** [comment]
The only reason we hesitated to just change all the callers at once and call it good was that there are other packages depending on it. Do we have to worry  about version skew with any of the external callers?  (fewer now than at any later time!) How will this impact the testnet release?

**Comment by michaelfig** [comment]
If you make a major semantic version bump (the `!` in `feat!: ...`), then those callers will just continue to use the old version.  No impact unless they voluntarily upgrade and need to adapt to the new API.

**Comment by michaelfig** [comment]
I was hesitant in the past to make a breaking change (and bump the major version number) to a package that exported a `default`.  `@agoric/evaluate`.  We shouldn't be afraid of that, and our code is better off if we embrace that the major version can be bumped for any good reason.

**Comment by michaelfig** [comment]
React is React 16, and Babel is Babel 7, and Chrome is Chrome 89868 because this has gradually made its way into user-accepted practice.

**Comment by michaelfig** [comment]
With the Lerna infrastructure (which is going to be documented soon), if these changes follow conventional commits, all the consumers of the modified package will also get their versions bumped as necessary.

[Sorry for the multiple messages.  I keep thinking I've replied adequately, then remember something else.]
