### ISSUE TITLE
rewrite transform-metering to new SES API

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#831]
Once https://github.com/Agoric/SES-shim/issues/256 is fixed, SES will provide Compartment-level control over both `endowments` (globals) and a new thing tentatively named "global lexicals". Both will be per-Compartment, not per-evaluation. Likewise `transforms` will only be per-compartment, and furthermore the transforms will be reworked to be simpler, and no longer get to interact with endowments.

This will require/enable a cleanup to the `transform-metering` package. The new API will be something like:

```js
import { makeMeteringTransformer } from `@agoric/transform-metering`;

const { meteringTransformer, meterName } = makeMeteringTransformer();
```

`meteringTransformer` will be a function that accepts a string (`originalSrc`) and returns a new string (`transformedSrc`). It should be added to the `transforms` array of a new Compartment.

The name of the meter (which has a default, but can be overridden with an option to `makeMeteringTransformer()`) will be baked into the code that `meteringTransformer` injects, therefore it must be added as a global lexical for the evaluation to succeed. The transformer function also parses `originalSrc` and throws an error if it sees any unbound references to this name, to prevent the original code from manipulating its own meter (and thus evading metering limits).

The meter itself must be provided by the calling code, but it should obey an API defined by `transform-metering`. There might be a helper function to build a suitable meter object.

```js
const meter = makeMeter();
const globalLexicals = { [meterName]: meter };
const c = new Compartment(endowments, { transforms: [meteringTransformer],
                                        globalLexicals,
));
```

@michaelfig did I get this right?

I think this blocks #477.

**Comment by michaelfig** [comment]
You have that right.  Just don't forget to harden the meter.

**Comment by warner** [comment]
I'm pretty sure this will depend upon an improvement to SES described in https://github.com/Agoric/SES-shim/issues/256

**Comment by michaelfig** [comment]
Looks like this is done.
