### ISSUE TITLE
[Zoe] Add a contract shutdown method to the Zoe Contract Facet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#836]
A zcf method, maybe zcf.shutdown() that will instruct Zoe to not accept any further offers are accepted, no invites are redeemed, no publicAPI methods are callable, etc.

This could be like the EVM SUICIDE call - should we remove this instance entirely from the instanceRecord?

**Comment by katelynsills** [comment]
Idea by @DavidBruant

**Comment by erights** [comment]
Interestingly, in the upper zoe vs lower zoe split, this is exactly what would happen if the upper flushed current allocations to the lower zoe and then crashed. Given that, it would be trivial to enable it to purposely `shutdown` in the same manner.

**Comment by katelynsills** [comment]
This is done in #1414
