### ISSUE TITLE
Something about "redeem"+"reallocate" is confusing

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#839]
When i first read the Zoe API, it felt weird to me that there was a method to "reallocate", but none to "allocate" (whatever this might mean)

It took me some time to understand that calls to `redeem` create an initial "allocation", that is, an *association* or mapping between an `offerHandle` (created by the call to `redeem`) and ERTP assets. And `.reallocate` re-organizes the association of ERTP assets with `offerHandle`s (with various nice security properties)

I feel like the word "redeem" focuses too much on the invitation part of the process and invisibilizes all the "send an proposal + payments + create an offerHandle with the payments associated with it".
I think the word "redeem" is vestigial to the time of contractHost where the process was [only](https://github.com/Agoric/documentation/blob/0795ef4793126f492c18c94477ba3197f7e715b9/main/ertp/api/contract-hosts.md#contracthostredeeminvite) "send the invite, get the seat back". But that's less relevant here because so much more is happening

I do not have a good proposal yet, but to get the ball rolling, i share this renaming proposal:
- `redeem` => `makeOffer` (with `invite` as first argument because making an offer only makes sense in the context of an existing contract)
- `reallocate` => `reassociateOfferAssets`

**Comment by katelynsills** [comment]
Closing this in favor of https://github.com/Agoric/agoric-sdk/issues/848, which was the output of the design meeting.

I don't think we should rename `reallocate`
