### ISSUE TITLE
[ERTP] Mint Payments instead of Purses

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#84]
It seems to be a common pattern that the holder of a mint will mint new ERTP assets on the fly, and immediately send them to the recipient. A payment would be ideal for this, rather than having to create a purse and then `withdrawAll`. Is there a reason we don't have this, or could we add it?

**Comment by DavidBruant** [comment]
> Mint.mint(quatloos(4)) should returns a Payment rather than a Purse

I'm also coming to the same conclusion; a payment feels more appropriate

**Comment by dtribble** [comment]
I think this should be revised to"mint payments *instead* of purses"
