### ISSUE TITLE
Migrate uses of makePromise outside agoric-sdk to new version

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#842]
I put this in agoric-sdk for ease of tracking. Normally it would go in each package needing an update.

**Comment by Chris-Hibbert** [comment]
This seems to have already been done in dapp-simpleExchange and dapp-autoswap.

I think the tassat branch should update to new copies of all the contracts, rather than having the contracts edited.

Did I miss anything, @michaelfig, @dtribble ?

**Comment by katelynsills** [comment]
Anything left to do on this issue?

**Comment by Chris-Hibbert** [comment]
makePromise has migrated to ProducePromise, which should migrate to makePromiseKit.  

https://github.com/Agoric/agoric-sdk/issues/1349
