### ISSUE TITLE
Which uses of 'if (Promise.resolve(p) === p)` should be replaced with isPromise(p)?

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#844]
Is there any reason why some of these need to remain independent of the version in make-promise? Otherwise, I'd prefer to migrate them.

[captp.js](https://github.com/Agoric/agoric-sdk/blob/29b53998664f2a11840e5350cc4c72533de635f0/packages/captp/lib/captp.js#L33)

[repl.js:16](https://github.com/Agoric/agoric-sdk/blob/29b53998664f2a11840e5350cc4c72533de635f0/packages/cosmic-swingset/lib/ag-solo/vats/repl.js#L16)

[repl.js:125](https://github.com/Agoric/agoric-sdk/blob/29b53998664f2a11840e5350cc4c72533de635f0/packages/cosmic-swingset/lib/ag-solo/vats/repl.js#L125)

[marshal.js](https://github.com/Agoric/agoric-sdk/blob/29b53998664f2a11840e5350cc4c72533de635f0/packages/marshal/marshal.js#L199)

[liveSlots.js](https://github.com/Agoric/agoric-sdk/blob/29b53998664f2a11840e5350cc4c72533de635f0/packages/SwingSet/src/kernel/liveSlots.js#L168)

**Comment by erights** [comment]
AFAICT all should be migrated. I see no problems.

**Comment by warner** [comment]
want to make a PR? I'm happy to do it too.

**Comment by Chris-Hibbert** [comment]
No need. I'll take care of it. I seem to be on-call for small tasks this week.
