### ISSUE TITLE
[Zoe] Rename `zoe.redeem` to `zoe.offer`

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#848]
The Zoe Service method `redeem` should be renamed to `offer`. Whoever takes this on should ensure that it changes on our documentation as well and create a task for that.

**Comment by Chris-Hibbert** [comment]
@katelynsills, @erights, Is this obsoleted by #853?

**Comment by katelynsills** [comment]
I think it's closed by #853, but not made obsolete. It should be open while the PR is open and closed when the PR is merged.

**Comment by katelynsills** [comment]
Ah, I see what you mean now. I reassigned Mark to this and pulled you off, @Chris-Hibbert
