### ISSUE TITLE
[ERTP] Unergonomic pricePixelAmount() race in Pixel demo

### ISSUE THREAD

**Issue by michaelfig** [Agoric/agoric-sdk#85]
In the Pixel demo, when converting the example not to use the `history[N]` array, the only unavoidable unergonomic interaction is:

```js
amt2 = px2!getBalance();
amt2.then(a => home.gallery!pricePixelAmount(a)); // why .then?
```

It would be nice if `pricePixelAmount` could accept a promise for an amount instead of just an amount, as I'd like to be able to do something like:
```js
amt2 = px2!getBalance();
home.gallery!pricePixelAmount(amt2);
```

This wasn't obvious before when relying on the `history[N]` array, as Promises in the history are rewritten to their resolution.  However, this rewrite was a data race in which the `getBalance()` must resolve before the `pricePixelAmount()`.

**Comment by katelynsills** [comment]
I think we may be able to close this issue, since the pixel demo and unwrap are no longer things that exist. @erights, what do you think?

**Comment by erights** [comment]
y
