### ISSUE TITLE
Zoe proposal expressiveness is limited

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#855]
> we do have a plan for Zoe enforcement of offer safety for this case. The so-called "multiples" offer I explain above. That's not going to happen soon. Until then, the auditorium's meaningful offer safety depends on the contract, not on Zoe.
>
> Even after we add multiples, exclusive choice, offsets, and perhaps other things we find we need, there will always be an expressiveness limit to the offer safety Zoe itself can guarantee. The case that will probably be most painful soonest is offers in terms of "current" market prices, such as a "market order" entered into an exchange. We have no plans to have Zoe enforce safety relative to dynamic market prices at the time. This would always have to be delegated up to the contract.
>
> Cases like market prices, which will come up a lot across many contracts, might cause another partitioning of risk within what Zoe regards as the contract level. @katelynsills did some good investigation of this early on, of generically parameterizable contract templates, that specialized code could be plugged into to create custom contracts. The templates could be highly vetted highly reusable frameworks. Such a template might be the code enforcing such higher-level safety properties, independent of what the specialized code is doing. This applies the Zoe risk partitioning principle at a higher layer of abstraction. The key thing is that multiple such templates can co-exist, each of which understand a different "language" for expressing such higher level offer safety constraints. No one such language need be universal.
> 
> I look forward to the day we get back to exploring that.

_Originally posted by @erights in https://github.com/Agoric/agoric-sdk/pull/780_

**Comment by DavidBruant** [comment]
If feel like the maximum expressiveness would be that the person attaches an `isAllocationSatisfying(amountKeywordRecords)` function to the proposal for `zoefc.reallocate` to use to take into account the participant's view of what is satisfying for them

I imagine there is a reason why this option isn't viable. Maybe Denial-Of-Service attacks? (function contains a `while(1){}` which freezes the contract, maybe the Zoe service?)

**Comment by erights** [comment]
Yes. We do expect to use mobile code for such purposes, but are not yet prepared to do so. That's why, for example, we currently only allow a fixed menu of math helpers, are require them to be selected by registered name rather than sending mobile code.

However, hypothetically, even if we did this, I don't see how it's that different than the plan explained above. The contract already is mobile code. The contract template --- highly reused highly vetted mobile code parameterized by specialized code --- needs to be understood to understand what it is guaranteeing. Seems like similar trust relationships.

**Comment by katelynsills** [comment]
I'm closing this issue since there are no planned changes associated with it.
