### ISSUE TITLE
Create regular agd exports of mainnet

### ISSUE THREAD

**Issue by toliaqat** [Agoric/agoric-sdk#8567]
## What is the Problem Being Solved?
We need agd exports of mainnet for creating the main fork snapshots. 

## Description of the Design
Run a script in a crop / CI job that creates a agd export and stores it on gcloud storage for other processes to consume.

## Security Considerations
NA

## Scaling Considerations
Need beefy machine to run this script because agd export loads the database in memory and can crash if not enough memory.

## Test Plan
Use the export generated by this process by seperate cron job that creates a main fork snapshot.

**Comment by mhofman** [comment]
I recommend this script starts by state-syncing the node and immediately halt it (`halt_height=1`), that should produce the leanest DB to export (same content but easier to iterate over).

I wish there was a way to produce a genesis export directly from state-sync. In the future, maybe we can hack that together: the `data/snapshots` basically contains chunks of a gzip stream or protobuf messages that have the raw IAVL DB entries, and swing-store export artifacts.

**Comment by mhofman** [comment]
Do we have this automated somehow? Where is the process documented?
