### ISSUE TITLE
I ignored conventional commits while working on a PR

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#857]
While working on https://github.com/Agoric/agoric-sdk/pull/780 , i ignored conventional commits because i assumed my PR would be squash-merged (and so, the PR commits won't be a part of the final commit history)

This makes Continuous Integration a bit noisy (i received lots of emails about the tests failing; i hope i was the only one receiving these emails :-/) and the notion of "failing" less relevant

It's not clear to me which problem checking conventional commits on each PR push solves

**Comment by katelynsills** [comment]
Conventional commits are being used to generate release notes. Closing for now.
