### ISSUE TITLE
Consider setting up a lintbot

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#858]
I wrote https://github.com/Agoric/agoric-sdk/pull/797 via the github editing interface
The Continuous Integration makes sure the code is syntactically correct and does not break any test and that's great
... and ESLint tells me something about spaces that could be fixed automatically with `eslint --fix`

I think it'd be cool if it was possible to push code to a PR and a bot runs `eslint --fix` and adds the corresponding commit directly (and maybe posts a message to the PR if some errors cannot be `--fix`ed)
Letting robot work to robots so human can focus on the higher-level things

**Comment by turadg** [comment]
This would require letting CI write commits and push them to the repo. E.g. with https://github.com/marketplace/actions/add-commit

I think we won't risk allowing that so I'm closing this issue.
