### ISSUE TITLE
Current CoveredCall hardcodes the "NatStrategy"

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#86]
It seems like this line:

https://github.com/Agoric/ERTP/blob/eb8d8812f787b67a5dfbb213f25923fc05e0a2e2/core/coveredCall.js#L73

should rely on the relevant strategy instead of hardcoding what equality means for quantities.

**Comment by DavidBruant** [comment]
After a refactoring with name changing from `quantity` to `extent` and the move to the monorepo, the relevant line is now 
https://github.com/Agoric/agoric-sdk/blob/8428d8d3bb5fae1d84516c12fc7fa78922a423f5/packages/ERTP/core/coveredCall.js#L77

**Comment by katelynsills** [comment]
@DavidBruant Thanks for making this current

**Comment by katelynsills** [comment]
Closing this because this coveredCall will be deprecated by https://github.com/Agoric/agoric-sdk/issues/394
