### ISSUE TITLE
Opinion: the user interface should be part of the contract

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#87]
This issue is an outcome of a discussion i've had with @Chris-Hibbert and, in a way, a follow-up to my understanding of the design decisions around invites (#109 )
At this stage, it's only intended to be a discussion. If there is agreement of the opinion, another discussion is necessary to decide how it affects ERTP and other parts of the stack

I believe that the user interface should be part of the contract

The user interface mediates how physical persons interact with the contract. If the user interface is not provided by the contract, then, it does not have the same integrity properties as the rest of the contract and i believe it weakens the security properties of the overall system

To take a caricatural example, if i play chess, i play black and my UI contains only black pieces and my opponent's white pieces are invisible, i'm disadvantaged if my opponent has a UI which provides complete information. We are playing the same game, the same contract, but the user interfaces favors their side of the game
There are many subtle variations of this example, but i think this example makes the problem clearly apparent
The same way one may want to audit the code to be sure that the game mechanics are not biaised, one may want to be sure that the user interface honestly reflects the game mechanics

Aside from having security benefits, having the UI as part of the contract moves the responsibility of defining the interfaces to the contract author. And it's hard for me to think of how it could be differently. Contracts will propose an arbitrarily complex and rich set of models of interactions with the contract. I don't think there is a way to generically expose such complexity as user interfaces (if there was, we'd be done with software?). Agoric may provide components/patterns/"good pratices" at most, but to preserve arbitrary expressivity, the interface itself will certainly be constructed with the contract

If there is agreement on this idea, i can share ideas on how this could affect ERTP and other projects

**Comment by katelynsills** [comment]
Just to add a consideration, we cannot have the user-interface code on-chain as part of Zoe, since that would add a huge amount of data to the state of the chain. But, we would be able to add the code elsewhere and add a reference to that code, in the same way that Cosmos references IPFS pages in their proposals. https://cosmos.bigdipper.live/proposals/5

**Comment by katelynsills** [comment]
Our current thinking is that the contract developer and the UI developer may actually be different entities. We may want to allow for an explosion of different frontends using the same contracts. Furthermore, although the user receives information about what is happening from the dapp UI, any payments or offer go through their trusted wallet, so the threat of dapp UI being able to mislead the user is diminished.

With the above considerations, I think we cannot and should not make the UI part of the contract at this point. I'm going to close this as non-actionable, but there may be further work on having a standard of referencing IPFS data along with the contract. In the meantime, the contract can always provide a custom method on the `publicFacet` to specify its preferred front-end, if that is desired.
