### ISSUE TITLE
Consider renaming "AmountKeywordRecord" to "allocation" where that's relevant

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#875]
`zoe.getCurrentAllocation(offerHandle)` returns an "AmountKeywordRecord"
`zoe.reallocate(offerHandles, newAmountKeywordRecords, sparseKeywords)` takes a list of "AmountKeywordRecord" as second argument and that's the description of the allocations that are expected if `reallocate` succeeds

"AmountKeywordRecord" is a mouthful. "Allocation" is possibly more descriptive and it's also coherent with `getCurrentAllocation` and `reallocate` wording

**Comment by katelynsills** [comment]
Let's keep the AmountKeywordRecord name and revisit later

**Comment by katelynsills** [comment]
I think now that we can have a type 'AmountKeywordRecord' we can rename the parameter to 'allocations'

**Comment by katelynsills** [comment]
Closed by #1002
