### ISSUE TITLE
Consider renaming assertCapASCII to assertKeyword

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#876]
I'm referring to:

https://github.com/Agoric/agoric-sdk/blob/80f866ceea41f376efdaad914320f6e537dfeb19/packages/zoe/src/cleanProposal.js#L7-L14

https://github.com/Agoric/agoric-sdk/blob/80f866ceea41f376efdaad914320f6e537dfeb19/packages/zoe/src/cleanProposal.js#L66-L68

**Comment by katelynsills** [comment]
This was renamed from `assertKeyword`, because Zoe helpers already had a function named `assertKeywords`, and that was too similar. Closing.
