### ISSUE TITLE
Note: Promise.resolve(p).then(t => {...}) is not safe from reentrancy attack

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#88]
More here: https://github.com/Agoric/eventual-send/issues/37

**Comment by katelynsills** [comment]
@erights, is there further work for this issue? If not, can we close it?

**Comment by erights** [comment]
Thanks for reopening. On this one we have an enabler. @michaelfig 's `E.when` is a safe alternative to `... .then`. But we need to use it consistently and catch ourselves when we don't. We have not taken those steps yet.

**Comment by katelynsills** [comment]
Is there anything to fix in ERTP? We already use `E.when` there. There is one remaining `.then:

https://github.com/Agoric/agoric-sdk/blob/94e0078673ff15e47c2fcf32f472d27c416a1cd8/packages/ERTP/src/issuer.js#L237

**Comment by erights** [comment]
That use of `.then` is perfectly fine. Great that ERTP already conforms! Thanks!

Yes, this issue is in no way specific to ERTP.

**Comment by erights** [comment]
`E.when` is the best we can do, so closing this.
