### ISSUE TITLE
[Zoe] zoe.makeInstance returns an invite, not a record containing an 'invite' property

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#887]
https://github.com/Agoric/agoric-sdk/blob/dda5944776d8561a0ec50e495b9402cfd845f986/packages/zoe/test/swingsetTests/zoe/vat-alice.js#L300

This line uses destructuring to extract an 'invite' out of the return value of `zoe.makeInstance`. But it returns the invite itself, not a record.

Happens several places.

**Comment by DavidBruant** [comment]
Related: https://github.com/Agoric/agoric-sdk/issues/820

**Comment by Chris-Hibbert** [comment]
fixed in #820
