### ISSUE TITLE
understand send/resolve/send ordering issue in liveslots/HandledPromise

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#894]
While writing tests for #859, I had two places where I observed a strange difference between the ordering of vat-level messages and the resulting kernel syscalls it made. We think this involves HandledPromise, the protective turn boundaries it imposes (to prevent its handler from reentrancy violations), and the way SwingSet (specifically liveslots) uses it.

In one case, I have code which creates a promise, sends a message that references it, resolves the promise, and then sends a second message referencing it:

```
// target1 is a Presence to some remote object
const pr = producePromise();
E(target1).one(pr.promise);
pr.resolve(x)
E(target1).two(pr.promise);
```

However, I observed liveslots emitting the syscalls in a different order:

```
syscall.send(target1, "one", p1);
syscall.send(target1, "two", p1);
syscall.fulfillToData(p1, x)
```

To avoid this (and provoke the behavior that I wanted to test), I had to insert a stall into the original code:

```
const pr = producePromise();
E(target1).one(pr.promise);
await Promise.resolve();
pr.resolve(x)
E(target1).two(pr.promise);
```

In the other instance, I had to add *two* stalls. This case sent messages *to* the Promise, in addition to merely referencing it as an argument. The first promise here was passed in by an outside caller, so messages to it ought to be pipelined into the kernel. The second was created locally and shared with the outside world.

```js
const pr = producePromise();
function fromOutside(target1, p1) {
  E(target1).one(p1);
  E(p1).two();
  pr.resolve(x);
  // stalls needed here
  E(target1).three(p1);
  E(p1).four();
```

Here, I add to add two `await Promise.resolve()` at the indicated place to achieve the intended order of syscalls. The final "four" message is sent to the resolution of `p1`, or discarded/rejected if that resolution is not capable of accepting messages:

```
syscall.send(target1, "one", [p1])
syscall.send(p1, "two". [])
syscall.resolve(pr, x)
syscall.send(target1, "three", [p1])
syscall.send(various, "four") // sometimes
```

We think this may have something to do with #823 and #871

**Comment by warner** [comment]
https://github.com/Agoric/agoric-sdk/tree/894-fix-ordering (specifically [this commit](https://github.com/Agoric/agoric-sdk/commit/73dc85c48fb165ba605115bc1836556af43d6667)) is my attempt to change liveslots to use HandledPromise properly (and to test this behavior more thoroughly). I split `makeQueued` into two separate calls: `makeImportedPromise` (which uses the `unfulfilledHandler`) and `makeImportedPresence` (which only uses the `fulfilledHandler`). I created multiple separate methods for resolving the Promise in various ways.

What I've learned is that there's a race between the resolution of a HandledPromise (specifically the sequence of multiple turns necessary to complete the resolution) and messages being sent to it (`p~.foo()`).

In one attempt to deal with this race, we made the promise's `unfulfilledHandler` use a mutable slot to keep track of where messages ought to be sent. When the kernel notifies the vat about a kernel-side promise being resolved, in addition to calling `resolve()`, we also modify this slot to point at the new target. We found that a test which resolved a result promise, waited exactly one turn (`await Promise.resolve()`), then sent a message to this HP (`E(p1).foo()`), would see the message sent to the unfulfilledHandler rather than the resolution of the message. The mutable slot was an attempt to make it go to the new target earlier. And the whole goal was to make sure that once the `.then()` fires on the result promise (and we make a `syscall.fulfillToPresence()`, and retire the VPID), that we never again try to send messages to the old VPID (which is still held by the old `unfulfilledHandler`, which isn't supposed to be used ever again, but because of this race, it was used for one more turn).

https://github.com/Agoric/agoric-sdk/pull/1055 combines @michaelfig 's fix to HP to make the `unfulfilledHandler` stop being used the moment `resolve()` is called, with my replacements for `makeQueued` and new tests.

**Comment by warner** [comment]
I'm trying to fully understand how ordering works here, to see if what I'm asking for makes sense. I wrote the following test program to examine the behavior:

```js
import { E, HandledPromise } from '@agoric/eventual-send';

async function run() {
  const unfulfilledHandler = {
    applyMethod(_o, prop, args, returnedP) {
      console.log(`applyMethod[${prop}]`);
    },
  };

  let resolve;
  let reject;
  const p = new HandledPromise((res, rej, _resPres) => {
    resolve = res;
    reject = rej;
  }, unfulfilledHandler);

  const target1 = {
    one() { console.log('t1.one'); },
    two() { console.log('t1.two'); },
    three() { console.log('t1.three'); },
    four() { console.log('t1.four'); },
    five() { console.log('t1.five'); },
  };

  console.log(`E(p).one()`);
  E(p).one();

  console.log('end turn group 1');
  await Promise.resolve();
  console.log('\nbegin turn group 2');

  console.log(`E(p).two()`);
  E(p).two();
  console.log(`resolve(target)`);
  resolve(target1);
  console.log(`E(p).three()`);
  E(p).three();

  console.log('end turn group 2');
  await Promise.resolve();
  console.log('\nbegin turn group 3');

  console.log(`E(p).four()`);
  E(p).four();

  console.log('end turn group 3');
  await Promise.resolve();
  console.log('\nbegin turn group 4');

  console.log(`E(p).five()`);
  E(p).five();

  console.log('end turn group 4');
  await Promise.resolve();
  console.log('\nbegin turn group 5');
}

console.log('begin turn 1');
run();
console.log('end turn 1');
```

When I run this against current trunk (cab6be8a813c3337eb88f52c853e428860eb4d0b), I get the following sequence:

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
applyMethod[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2
applyMethod[two]
t1.three

begin turn group 3
E(p).four()
end turn group 3
t1.four

begin turn group 4
E(p).five()
end turn group 4
t1.five

begin turn group 5
```

Note that the unfulfilled handler was used for `two` (which was sent before the resolve), while the final resolved target was used for `three`. Also note that each delivery occurred after exactly one turn of delay: all messages sent during a turn are delivered during the `await Promise.resolve()` that follows. E.g. `two` and `three` are both delivered just before the log of "begin turn group 3".

(if I change the `resolve()` to a `reject()`, I see `one` and `two` delivered, and nothing else)


When I run it against @michaelfig's 894-change-handled-promise branch (https://github.com/Agoric/agoric-sdk/pull/1053), specifically commit 51765e3ed09331f185763c035c3479455d814fa9 (which should be equivalent to his 4b26ef9adb67b0e1111f7cf2bde058c98a8e69d0), I get this new sequence:

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
applyMethod[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2

begin turn group 3
E(p).four()
end turn group 3
t1.two
t1.three

begin turn group 4
E(p).five()
end turn group 4
t1.four

begin turn group 5
t1.five
```

Here, the delivery of `one` (to the unfulfilled handler) takes just one turn, but all subsequent messages take *two* turns: `two` and `three` aren't delivered until after we've had two `await Promise.resolve()` cycles (after the "end turn group 3" log). I think this implies that `E(p).two()` pushes some callback X onto a queue, and when X makes it to the front, X doesn't actually deliver the message, but rather it pushes a second callback Y onto the queue. The message is finally delivered when Y makes it to the front.

In addition, both `two` and `three` are delivered to the resolved target, even though `two` was sent before the resolution.

(if I change the `resolve()` to a `reject()`, I only see `one` delivered, not `two`, nor anything else)

**Comment by warner** [comment]
## Background

At the syscall/kernel level, we talk about "kernel promise records", which are bookkeeping entries (rows of the kernel promise table), not actual Javascript `Promise` objects. Each one has a kernel identifier (the `kpid`). Any number of vats might know about a given promise (they have a `vpid` in their c-list which maps to/from the `kpid`), but at most one of them is the Decider (the kernel keeps track of which vat has this resolution authority, if any).

Promises are always created by vats, and the kernel hears about them for the first time in the result field of an outbound message (the optional `result=` argument of a `syscall.send()`), the arguments of an outbound message (the `args.slots` field of `syscall.send()`), or the data to which a promise is resolved or rejected (`data.slots` of `syscall.fulfillToData()` or `syscall.reject()`). The decider flag is always initially held by the vat which created the promise. The decider authority is transferred to the kernel when the promise is put in the `result=` field (it is now held by the message, whose execution will resolve the promise), and remains there while the message waits in a queue. When the kernel finally delivers this message (usually to a different vat, but it could return home again), the authority will shift to the receiving vat. Vats can consume (and destroy) this authority by resolving the promise, via a `syscall.fulfill*` variant.

As a result, at the lowest level, each vat has one of three relationships to a promise record:

* unknown
* known but not the decider
* known and is the decider

and the state shifts over time: receiving messages can grant decider authority, and sending it as a result can shed it.

However, our liveslots layer does not fully expose the flexibility that the syscall interface grants. Javscript Promises, as currently specified, do not give us a way to discover when they've been resolved to some other Promise, limiting some potential speedups (e.g. `syscall.forward()`).

Since liveslots can never learn when it would be useful to shed decision-making authority for some existing promise, it never does so, and always creates a new kernel promise for the `result=` of every outbound message. With more engine support, we could implement a shortcut where e.g. Alice does `p1.resolve(bob~.foo())`, and liveslots could transfer her `p1` decision authority to Bob, removing herself (and a bit of latency) from the resolution pathway between bob's `foo()` and someone waiting on `p1`. Note that other (non-liveslots-based) vats are not limited in this fashion, so liveslots must be prepared to *receive* decision-making authority for pre-existing promises, but we know it will never *send* messages which shed such authority. We might have it from the beginning, or we might acquire it later, but once we have the decider flag, we might consume it but we'll never give it away.

Also, inbound messages with a `result=` field will name a promise ID, but liveslots does not create a corresponding `Promise` object, because any such Promise would remain just out of reach of the invoked method ("on the other side of the `return`"). However the caller gets a promise, and they might pass it back to us, so we must be prepared to handle it.

Therefore the "user-level code", above liveslots, has the following potential relationships to a promise record (all described from Alice's point of view):

* exported: Alice does `p1 = new Promise(); bob~.foo(p1)`. Bob might send the Promise back (or send it to Carol, who sends it to Alice, etc), so liveslots must remember the mapping and round-trip it back to the original `Promise` object. Alice will always be the decider (liveslots cannot shed this authority). Liveslots must do `p1.then()` to detect when alice resolves the promise, and the callback must inform the kernel with some `syscall.fulfill*` call.

* inbound result=: This is not reified into a `Promise` object, but instead liveslots calls the target method asynchronously, and attaches a `.then` callback to the resulting Promise that will signal the kernel (`syscall.fulfill*`) when the result is available. We will always be the decider.

* inbound result= plus imported: The caller might send our result promise back to us (bob does `p1 = alice~.foo(); alice~.bar(p1)`). Alice will always be the decider of p1, but now she is also a subscriber. We must create a HandledPromise to represent p1, and if Alice exports this, it must round-trip back to Bob as the same Promise he got from `foo()`. I'm not sure what the handler should do, but sending the messages into the kernel (which will hopefully send them back to us) seems good enough. When we resolve the original promise, we must also resolve our local HandledPromise because the kernel *won't* echo the resolution back to us.

* imported plus inbound result: Bob's vat sends a promise to us (e.g. `alice~.foo(new Promise())`), and we stash it (`function foo(p1) { storedP = p1; }`). Then Bob (who is not limited to liveslots) transfers the decider flag to us by using the same ID in a `result=` field (perhaps with some magic like `p1.resolve(alice~.bar())` or `baz() { return alice~.bar() }`). Alice has all the responsibilities of the previous case, but she learns about them in a different order.

* only imported: like above but nobody ever transfers decider authority to Alice. Bob's vat sends the promise to alice (e.g. `alice~.foo(new Promise())`), who receives it with `function foo(p1) { ... }`, and might send messages to it (`p1~.bar()`) or react to it's resolution (`p1.then(...)`). To support outbound messages, Alice's liveslots must deliver a `HandledPromise` into `foo()` as the `p1` argument, with a handler that will make `syscall.send()` calls into the kernel. To support reacting to resolution, Alice's liveslots must watch for the kernel to deliver `dispatch.notifyFulfill*` calls, and `resolve()` the `HandledPromise` with the deserialized result. In this case, Alice never becomes the decider: the HandledPromise's resolver is not visible to user-level code, and is only invoked by liveslots in response to instructions from the kernel.

* outbound result=: `p1 = bob~.foo()`. Liveslots must create a HandledPromise to serve as `p1` for the caller, and add a handler to support `p1~.bar()`, and add the HP to a table so `bob~.baz(p1)` can export the correct VPID. Someone else is the decider, at least initially, so liveslots must prepare to receive `dispatch.notifyFulfill*` and resolve the HandledPromise when that occurs.

* outbound result= plus inbound result. We start with `p1 = bob~.foo()`, but bob does some magic non-liveslots `foo() { return alice~.bar() }` and thus sends us our own VPID back in a `result=` field. We are now the decider (and will never transfer the flag elsewhere, since we *are* limited to liveslots). When we resolve the return value of `bar()`, we must notify the kernel (`syscall.fulfill*`). The kernel won't echo back our own resolution, so we must *also* resolve the HandledPromise as if we'd received `dispatch.notifyFulfill*`.

**Comment by warner** [comment]
The current-trunk behavior (uniform one-turn delay, `two(); resolve(); three()` delivering `two` to the handler and `three` to the resolved target) *feels* correct to me. The changed behavior feels less uniform. But the real question is how this is used by liveslots, and to what extent liveslots is doing something weird (or, perhaps more likely, if the tests I wrote to try and exercise lots of possible combinations is doing something weird).

My current cleaned-up liveslots code (https://github.com/Agoric/agoric-sdk/blob/a8491ad76b67e833fbf5f6805174fa008f3f8921/packages/SwingSet/src/kernel/liveSlots.js#L56) calls the HandledPromise's `resolve()` function in the same turn as the kernel delivers a `dispatch.notifyFulfill*` event. It also deactivates the handler, just in case.

I have [a test](https://github.com/Agoric/agoric-sdk/blob/a8491ad76b67e833fbf5f6805174fa008f3f8921/packages/SwingSet/test/test-vpid-liveslots.js#L235) which exercises the "imported plus inbound result" case, whose core looks like:

```js
let p1;
const pr = producePromise();
return harden({
  promise(p) {
    p1 = p;
  },
  result() {
    return pr.promise;
  },
  async run(target1, target2) {
    const p2 = E(target1).one(p1);
    const p3 = E(p1).two();
 
    resolvePR(pr, mode, target2);
    for (let i = 0; i < stalls; i += 1) {
      await Promise.resolve();
    }
 
    const p4 = E(target1).three(p1);
    const p5 = E(p1).four();
  },
});
```

The `resolvePR()` function resolves a Promise that was returned by an earlier inbound call. This causes the imported `p1` to become resolved to the same thing (`mode` specifies whether it gets resolved to a local object, a remote object, non-callable data, or rejected). The `for` loop inserts a variable number of stalls, to explore what happens when `three()` and `four()` are sent at various points in the resolution process.

I have to keep reminding myself that the `resolvePR()` here is *not* resolving `p1`. It is effectively resolving the hidden result promise that lies waiting beyond the `return` in `result()`. This hidden result promise gets forwarded to `pr.promise`, and it is that `pr.promise` which we resolve in `resolvePR()`. So I don't think I should expect the same ordering behavior in this code as I see [earlier](https://github.com/Agoric/agoric-sdk/issues/894#issuecomment-624162429).

The problem that prompted this investigation was that we want to retire the VPIDs when liveslots calls `syscall.fulfillToPresence/etc`, but we observed the unfulfilledHandler using the retired VPID in a `syscall.send` *after* it had been retired.

Oh, I need to do another test like [earlier](https://github.com/Agoric/agoric-sdk/issues/894#issuecomment-624162429), except resolving the HandledPromise to a *Presence*, rather than a local object. I'll do that next.

**Comment by warner** [comment]
Ok, new test:

## Test Code

```js
import { E, HandledPromise } from '@agoric/eventual-send';

async function run() {
  const unfulfilledHandler = {
    applyMethod(_o, prop, args, returnedP) {
      console.log(`unfulfilledHandler[${prop}]`);
    },
  };

  const target1 = {
    one() { console.log('t1.one'); },
    two() { console.log('t1.two'); },
    three() { console.log('t1.three'); },
    four() { console.log('t1.four'); },
    five() { console.log('t1.five'); },
  };

  const fulfilledHandler = {
    applyMethod(_o, prop, args, returnedP) {
      console.log(`fulfilledHandler[${prop}]`);
    },
  };

  let resolve;
  let reject;
  const p = new HandledPromise((res, rej, _resPres) => {
    resolve = res;
    reject = rej;
  }, unfulfilledHandler);

  let presence1;
  new HandledPromise((_res, _rej, resPres) => {
    presence1 = resPres(fulfilledHandler);
  });

  console.log(`E(p).one()`);
  E(p).one();

  console.log('end turn group 1');
  await Promise.resolve();
  console.log('\nbegin turn group 2');

  console.log(`E(p).two()`);
  E(p).two();
  console.log(`resolve(target)`);
  //resolve(target1);
  resolve(presence1);
  //reject(Error('nope'));
  console.log(`E(p).three()`);
  E(p).three();

  console.log('end turn group 2');
  await Promise.resolve();
  console.log('\nbegin turn group 3');

  console.log(`E(p).four()`);
  E(p).four();

  console.log('end turn group 3');
  await Promise.resolve();
  console.log('\nbegin turn group 4');

  console.log(`E(p).five()`);
  E(p).five();

  console.log('end turn group 4');
  await Promise.resolve();
  console.log('\nbegin turn group 5');
}

console.log('begin turn 1');
run();
console.log('end turn 1');
```

## Old Behavior (trunk)

### resolve-to-local-object

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
unfulfilledHandler[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2
unfulfilledHandler[two]
t1.three

begin turn group 3
E(p).four()
end turn group 3
t1.four

begin turn group 4
E(p).five()
end turn group 4
t1.five

begin turn group 5
```

### resolve-to-presence

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
unfulfilledHandler[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2
unfulfilledHandler[two]
fulfilledHandler[three]

begin turn group 3
E(p).four()
end turn group 3
fulfilledHandler[four]

begin turn group 4
E(p).five()
end turn group 4
fulfilledHandler[five]

begin turn group 5
```

## New Behavior (branch)

### resolve-to-local-object

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
unfulfilledHandler[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2

begin turn group 3
E(p).four()
end turn group 3
t1.two
t1.three

begin turn group 4
E(p).five()
end turn group 4
t1.four

begin turn group 5
t1.five
```

### resolve-to-presence

```
begin turn 1
E(p).one()
end turn group 1
end turn 1
unfulfilledHandler[one]

begin turn group 2
E(p).two()
resolve(target)
E(p).three()
end turn group 2
fulfilledHandler[two]
fulfilledHandler[three]

begin turn group 3
E(p).four()
end turn group 3
fulfilledHandler[four]

begin turn group 4
E(p).five()
end turn group 4
fulfilledHandler[five]

begin turn group 5
```

## differences

When resolving to a Presence, the ordering is the same between `master` and the branch; the only difference is that `two()` is sent to the `fulfilledHandler` in the branch, whereas it was being sent to the `unfulfilledHandler` in `master` The new behavior is important for the "imported plus inbound result" case, where we must both resolve a local HandledPromise (which might have messages queued up on it) and also notify the kernel (which we're using to retire the VPID). We need to know that the unfulfilledHandler will never again be used after the `resolve()` is done, which is what the branch now does (and what trunk was not doing).

When resolving to a Presence, the messages are delivered to the handler at the times I expect: one turn after they are sent.

When resolving to a local object (thus using the default handler), there are two differences between `master` and the branch. The first is that `two()` is delivered to the target, rather than the unfulfilled handler (matching what happens with a Presence). The second is that all target-delivered messages are delayed by *two* turns, not one. This is surprising, but probably not a big deal. Each Promise can only be resolved once, and there's no synchronous channel between local and remote objects, so I don't *think* this would violate any ordering constraints (at least not in a way user code could observe).

I think my ideal case would be for the new code to provide the same uniform one-turn delay as it does for Presences, and as the old code did.

## vs tests

I still have to think carefully about my liveslots test and what it should expect.

**Comment by michaelfig** [comment]
At @erights prompting, I removed some unrelated changes from the "new code", rebased, and force-pushed.  Would you, @warner, be able to test against this "new new code"?

**Comment by warner** [comment]
@michaelfig I took your commit f54030f98bd71b4db80cc3191c6d56901d8e6dff and rebased my swingset changes on top. The updated swingset tests pass. My non-swingset test program (above) produced the same results as the previous branch.

Do you think it would be possible to get HandledPromise to treat resolve-to-Presence and resolve-to-local-object the same way? Specifically, the non-swingset test program shows messages sent to a resolved-to-local-object HP to be delivered *two* turns after they're sent, and ideally they'd be delivered just *one* turn after being sent (the same delay as for `fulfilledHandler` invocations in the resolve-to-Presence case). I have no idea if that's a deep consequence of some safety property, or if it's something easier to change.

**Comment by warner** [comment]
I opened #1069 for the lower-priority local-object two-cycle stall issue.

PR #1068 removes an unnecessary stall in liveslots' `deliver()` pathway which was causing the most surprising ordering issues I uncovered.

I think I now understand all the issues I care to, so it's time to close this ticket.
