### ISSUE TITLE
improve logging of expected-failed assertions

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#903]
While examining a failed CI run, I noticed the Zoe tests emitting lines like these:

```
    ✔ Alice should have received the ticket for the correct number
    FAILED ASSERTION false
right element {
  show: 'Steven Universe, the Opera',
  start: 'Web, March 25th 2020 at 8pm',
  number: 1
} was not in left
    ✔ performExchange from Joker should throw when trying to buy ticket 1
```

and:

```
  ZoeHelpers assertKeywords

    ✔ Asset and Price are the correct keywords
    ✔ Order doesn't matter
    FAILED ASSERTION false
keywords: [ 'Asset', 'Price' ] were not as expected: [ 'TokenA', 'TokenB' ]
    ✔ The wrong keywords will throw
    FAILED ASSERTION false
keywords: [ 'Asset', 'Price' ] were not as expected: [ 'Asset', 'Price', 'Price2' ]
    ✔ An extra keyword will throw
    FAILED ASSERTION false
keywords: [ 'Asset', 'Price' ] were not as expected: [ 'Asset' ]
    ✔ a missing keyword will throw
```

I learned that these are expected, and don't represent a problem (at least not one we're trying to solve right now). The actual failure I was searching for (which flunked the CI run) looked like this:

```
  zoe - swapForOption - valid inputs - with SES
...
    adding dref vatAdmin [d8]
    FAILED ASSERTION false
source code didn't match
    doProcess: vat[v6][o+0].bootstrap dispatch failed: Error <Object <[Object: null prototype] {}>>: source code didn't match
        at fullRevive (/SwingSet/kernel/packages/marshal/marshal.js:615:50)
        at Object.unserialize (/SwingSet/kernel/packages/marshal/marshal.js:663:21)
        at Object.notifyReject (/SwingSet/kernel/packages/SwingSet/src/kernel/liveSlots.js:441:21)
        at eval (/SwingSet/kernel/packages/SwingSet/src/kernel/vatManager.js:298:48)

    ✖ should be equivalent
    -----------------------
      operator: deepEqual
      expected: |-
        [ '=> alice, bob, carol and dave are set up', '=> alice.doSwapForOption called', '@@ schedule task for:100, currently: 0 @@', 'call option made', 'swap invite made', 'The offer has been accepted. Once the contract has been completed, please check your payout', 'The offer has been accepted. Once the contract has been completed, please check your payout', 'daveMoolaPurse: balance {"brand":{},"extent":3}', 'daveSimoleanPurse: balance {"brand":{},"extent":0}', 'daveBucksPurse: balance {"brand":{},"extent":0}', 'bobMoolaPurse: balance {"brand":{},"extent":0}', 'bobSimoleanPurse: balance {"brand":{},"extent":0}', 'bobBucksPurse;: balance {"brand":{},"extent":1}', 'aliceMoolaPurse: balance {"brand":{},"extent":0}', 'aliceSimoleanPurse: balance {"brand":{},"extent":7}' ]
      actual: |-
        [ '=> alice, bob, carol and dave are set up', '=> alice.doSwapForOption called', '@@ schedule task for:100, currently: 0 @@', 'call option made', 'swap invite made' ]
      at: Test.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/zoe/test/swingsetTests/zoe/test-zoe.js:126:7)
      stack: |-
  Error: should be equivalent
  at Test.assert [as _assert] (/home/warner/stuff/agoric/agoric-sdk/node_modules/tape/lib/test.js:225:54)
  at Test.bound [as _assert] (/home/warner/stuff/agoric/agoric-sdk/node_modules/tape/lib/test.js:77:32)
  at Test.tapeDeepEqual (/home/warner/stuff/agoric/agoric-sdk/node_modules/tape/lib/test.js:422:10)
  at Test.bound [as deepEquals] (/home/warner/stuff/agoric/agoric-sdk/node_modules/tape/lib/test.js:77:32)
  at Test.<anonymous> (/home/warner/stuff/agoric/agoric-sdk/packages/zoe/test/swingsetTests/zoe/test-zoe.js:126:7)
```

It'd be great if we had some way to mark these "expected failure" assertions with something more reassuring, so we don't get distracted by them when trying to find the actual failure. I've seen test frameworks where these are marked as `TODO` or `Expected Failure`, and in many cases they get counted in the summary (to remind us that, in an ideal tree, there would be zero of them). These TODOs are a form of in-tree bug triage, where we've written the tests for a known problem (yay!) and we certainly don't want to abandon that hard work, but for whatever reason we haven't yet fixed the core problem (boo!) and need to keep going anyways. Having the test emit TODO is somewhat better than either breaking the build (preventing any higher-priority work from proceeding) or deleting/commenting-out the test (losing the reminder that there is a lower-priority fix to be made), and slightly increases the chances that the test can be refactored/updated as other code is changed, even if it's not entirely passing.

cc @katelynsills and @Chris-Hibbert who know the most about the state of Zoe tests

**Comment by katelynsills** [comment]
> I've seen test frameworks where these are marked as TODO or Expected Failure, and in many cases they get counted in the summary (to remind us that, in an ideal tree, there would be zero of them)

I want to push back against this view. Checking that our code throws intentionally when a user or consumer code misbehaves is a good test to have, and we should not be trying to eliminate these tests. I think we do want to have better logs, and perhaps intentionally suppress the logging from `assert` on demand.

**Comment by warner** [comment]
> Checking that our code throws intentionally when a user or consumer code misbehaves is a good test to have, and we should not be trying to eliminate these tests.

Oh, sorry, yes I agree completely. We have preconditions and error-checking code for very good reasons, and we throw an error as soon as we possibly can, to narrow the range of possible bugs that need to be investigated. And those precondition checks represent behavior that we should absolutely be checking.

Maybe I'm misunderstanding the reason those particular tests print the results that they're printing. If they're testing what happens when e.g. user code calls it badly, and we're asserting that an exception is thrown, then yeah we should keep that test forever. In that case my ask would be that the stdout of that test doesn't look so much like a failure. That might mean using a different kind of `t.assert`. E.g. I know I've used `t.throws` in a couple of places to make sure things are throwing when they're supposed to, and `t.throws` is silent unless the function throws the wrong kind of exception, or completes without an exception. If the Zoe test is behaving correctly, it should not print anything in all caps or using words like "FAILED ASSERTION" or displaying the two things that don't match (as if that was something the human running the test might need to know in order to diagnose a test failure), as those are all just the sort of things that an actual failing test would do to draw attention to itself.

The scenario I was describing/imagining would be one where I add a test that `increment(4)` returns `5`, but it doesn't yet because we haven't written `increment` yet, so rather than comment out or delete the hard-won knowledge that 4+1 is supposed to be 5, I mark the test as allowed to fail. In that case, there's a clear end-state where the test should be run normally and not allowed to fail.

If the tests I called out are really "it ought to raise an exception" sorts of tests, rather than TODO sorts of tests, I'll adjust this ticket to be about changing the way the successes are logged so they don't look like failures.

**Comment by katelynsills** [comment]
> That might mean using a different kind of t.assert. E.g. I know I've used t.throws in a couple of places to make sure things are throwing when they're supposed to, and t.throws is silent unless the function throws the wrong kind of exception, or completes without an exception. If the Zoe test is behaving correctly, it should not print anything in all caps or using words like "FAILED ASSERTION" or displaying the two things that don't match (as if that was something the human running the test might need to know in order to diagnose a test failure), as those are all just the sort of things that an actual failing test would do to draw attention to itself.

It's `@agoric/assert` in the Zoe code (used correctly) that is logging 'FAILED ASSERTION', not our tests. We are already using `t.throws` in these cases. 

The solution is to change `@agoric/assert` to selectively turn off logging, so we can turn it off for tests. Maybe this is a feature already.

**Comment by erights** [comment]
> The solution is to change @agoric/assert to selectively turn off logging, so we can turn it off for tests. Maybe this is a feature already.

You may find the following useful:

https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/assert/test/throwsAndLogs.js#L54

It should be general enough to be reused for other tests.

**Comment by erights** [comment]
See how I use it at https://github.com/Agoric/agoric-sdk/blob/master/packages/assert/test/test-assert.js

**Comment by warner** [comment]
ah ah, yes.. so it's a question of who that message is aimed at: normally the operator of the real system (who might luck out and see it on the console), but it's also being seen by the operator of the tests (who mistakes it for something unintentional).

I've used logging systems (probably Twisted's [assertWarns](https://github.com/twisted/twisted/blob/59a04d29ca5351d314eebe8cb4d693083cc0b88d/src/twisted/trial/_synctest.py#L585)) where the warning-emitting/logging code was in cahoots with the testing framework, so your test could run a function with a wrapper that captured all warnings emitted until it finished. This would both consume the warning (and preserve the silence of a passing test) and require that the right kind of warning was provoked. Another flavor of this looked for `log.error()` calls, which would normally flunk the test. I don't know that our logger and our test library are sufficiently cozy to use a strategy like that, though.

**Comment by katelynsills** [comment]
> ah ah, yes.. so it's a question of who that message is aimed at: normally the operator of the real system (who might luck out and see it on the console), but it's also being seen by the operator of the tests (who mistakes it for something unintentional).

Yup, I think that's exactly right and a great characterization.

**Comment by DavidBruant** [comment]
related: #618

**Comment by DavidBruant** [comment]
```sh
    ✔ Alice should have received the ticket for the correct number
    FAILED ASSERTION false
right element {
  show: 'Steven Universe, the Opera',
  start: 'Web, March 25th 2020 at 8pm',
  number: 1
} was not in left
    ✔ performExchange from Joker should throw when trying to buy ticket 1
```

I can talk about this one
In the `performExchange from Joker should throw when trying to buy ticket 1` test, [there is an expectation that calling `performExchange` will throw](https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/zoe/test/unitTests/contracts/test-operaConcertTicket.js#L269-L272) one way or another to indicate a failure

But the way that happens right now is that [a function deeply called by](https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/ERTP/src/mathHelpers/setMathHelpers.js#L87-L90) `performExchange` is the one throwing via an assertion and the assertion library seems to [systematically log](https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/assert/src/assert.js#L189) `FAILED ASSERTION false`

This is not a behavior i wanted, but it was not a behavior i could not change in the scope of the PR, because i didn't want to change either `assert` or any of the intermediaries between `performExchange` and `assert`

I think that systematic logging is not a good default for `assert`. Especially for a function which also throws an error (which will generate a log with stacktrace either after being caught or by Node.js if not caught)

On the solution side, I would argue towards removing the default systematic logging currently at line 189 and 159:

https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/assert/src/assert.js#L187-L192

https://github.com/Agoric/agoric-sdk/blob/b48efb1e4586df78b561914834b554e66163bb57/packages/assert/src/assert.js#L156-L163

**Comment by katelynsills** [comment]
> On the solution side, I would argue towards removing the default systematic logging currently at line 189 and 159:

+1

**Comment by katelynsills** [comment]
![Screen Shot 2020-04-15 at 1 53 37 PM](https://user-images.githubusercontent.com/2441069/79388114-a2c9bd80-7f21-11ea-8a10-9bf804de8add.png)

Currently, logging looks like this - worse than the descriptions above. Dean mentioned needing to split into guard vs assert.

**Comment by erights** [comment]
> Currently, logging looks like this - worse than the descriptions above. Dean mentioned needing to split into guard vs assert.

Certainly we need more distinctions. What distinction would guard vs assert be?

**Comment by katelynsills** [comment]
> Certainly we need more distinctions. What distinction would guard vs assert be?

Ask @dtribble :) He also said we should do this after hackathon release

**Comment by erights** [comment]
@katelynsills @dtribble we're doing this now with ava, so closing. Right?
