### ISSUE TITLE
[Getting started] Error running agoric start

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#908]
```sh
$ agoric start --reset
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: /home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
/home/david/projects/agoric-sdk/packages/cosmic-swingset/lib/ag-solo/main.js:1
Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/david/projects/agoric-sdk/node_modules/node-lmdb/build/Release/node-lmdb.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1197:18)
agoric: start: /home/david/projects/agoric-sdk/packages/cosmic-swingset/bin/ag-solo set-fake-chain --role=two_chain --delay=0 fake-chain
agoric: [Error: ENOENT: no such file or directory, symlink '../../../../_agstate/agoric-wallet' -> '_agstate/agoric-servers/dev/html/wallet'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'symlink',
  path: '../../../../_agstate/agoric-wallet',
  dest: '_agstate/agoric-servers/dev/html/wallet'
}
```

I think the relevant part is `Error: /snap/core/current/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found`

It's the first time i'm seeing this error. It's not clear to me which change caused it, nor how to fix it

I'm using Ubuntu 19.10 (and apparently `libc` as a snap package, which must be the default now?)

**Comment by DavidBruant** [comment]
```sh
$ ldd --version
ldd (Ubuntu GLIBC 2.30-0ubuntu2.1) 2.30
```

so... that's fun...

**Comment by michaelfig** [comment]
This is similar to the other problems you had with snaps.  When lmdb is built as part of `yarn install` of the agoric-sdk, it is using one version of node (with its libc), but when you're running it, you're using a different version of node (with its own libc).

**Comment by DavidBruant** [comment]
yes, it felt familiar
I wonder why it's coming back now

**Comment by DavidBruant** [comment]
ok, i know
i recently (~2 months) re-installed my computer
and i installed Node.js via snap (because i had forgotten of the previous experience)

I uninstalled the snap version and re-installed the non-snap version and it works fine now
Thanks @michaelfig for the support
