### ISSUE TITLE
how to model a market place of digital art works?

### ISSUE THREAD

**Issue by dckc** [Agoric/agoric-sdk#91]
This morning I learned (via @entropee @jimscarver) about an [art on the blockchain](https://github.com/rchain-community/art-aotb) community that wants to make non-fungible tokens for art objects. I started trying to adapt the pixel demo code, but I got stuck thinking about where the mint fits into that situation: one mint for all the world's art? one mint per artist? one mint per work-of art? 

I'm thinking about using https://iscc.codes/concept/ to define the mint(s).  i.e. an art object is a "pixel" in ISCC code space.

maybe ... you upload a digital artifact to some service (maybe running locally) and the service derives an identifier (usinng perceptual hashing of images, for example) and then the mint would issue an ownwership purse for that, just like the coordinates of a pixel.

If anybody else with a copy of the image tries to mint a purse for it, the mint could refuse. i.e. we presume the first party to present the object is the creator...

**Comment by katelynsills** [comment]
I think Chris gave a good answer so I'm closing this issue.
