### ISSUE TITLE
What makes higher-order composition powerful

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#9103]
(This came up in internal chat. @katelynsills suggested it should be captured somewhere before it gets lost. Hence this issue.)

There are two features that together make higher-order composition powerful: 
   1. that the invites are themselves payments that fit within our generic notion of erights. This is normally what we think to highlight.
   1. That most of our contracts are generically parameterizable --- that they can exchange any kind of eright without needing knowledge of the specific eright.

AtomicSwap, covered call, and most auctions, are generally parameterizable. Autoswap is not.
Pegasus is currently not, but apparently can be.

**Comment by erights** [comment]
Hi @Chris-Hibbert , it seems this is about the same topic you are thinking of writing about, so I assigned to you and @Tyrosine22

**Comment by gacogo** [comment]
> > We should figure out whether there's a way to formalize these and write them down somewhere. They are touched on at most glancingly in the API docs we've produced.
> 
> Yes, please! Desperately needed! https://agoric.com/papers/reasoning-about-risk-and-trust-in-an-open-world/abstract/ formalizes
> 
> * the mint maker in a way that should generalize to formalizing ERTP.
> * the escrow exchange agent in a way that should generalize to some aspects of Zoe.
> 
> However, this paper may be much more formal than what you have in mind.

The anchored link here is dead - It should resolve to this one: https://papers.agoric.com/papers/reasoning-about-risk-and-trust-in-an-open-world/abstract/
