### ISSUE TITLE
orchestration - ICA Controller - deposit payment to ICA

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/agoric-sdk#9193]
1. As new user of an orchestration contract, I need to “deposit” (move) my fungible funds into a place controlled by orchestration so it can do things with it. 

    - for assets starting on Agoric in a smart-wallet
       - Only chains available through vbank (by BLD stakers)

    -  for assets starting on a remote Cosmos chain [into an agoric-controlled-ICA on the same remote chain]
       - ~~Contract notified of funds received in order to act~~ see https://github.com/Agoric/agoric-sdk/issues/9968
       - for assets starting on an external chain (no ICA)

2. As a user of an orchestration contract, I need to withdraw assets from a LocalChain Account and ICA into my smart wallet
```[tasklist]
### Tasks
- [ ] https://github.com/Agoric/agoric-sdk/issues/9925
```

**Comment by 0xpatrickdev** [comment]
The way I currently imagine this might work - is with an LCA and IBC Transfer:
  - `E(chainAccount).deposit(payment)`
  - `ChainAccount` sees if a `LocalChainAccount` is available in state. If not, one is requested.
  -  `E(LocalChainAccount).deposit(pmt)`
  - `E(LocalChainAccount).transfer(chainAccountAddr, amount)`

**Comment by dckc** [comment]
this only works for brands that are registered in the vbank by BLD staker governance.
Does that suffice?

```js
   const allegedPurse = E(bankAcct).getPurse(allegedBrand); 
```

_p.s. see #9211_

**Comment by dckc** [comment]
(tangential...)

```js
   const allegedPurse = E(bankAcct).getPurse(allegedBrand); 
```

"alleged" seems misused there. The caller relies on the `bankManager`, right? it's not in a position to be suspicious of it. Seems like the result of `getPurse` has to be presumed correct.
