### ISSUE TITLE
clean up unscoped tags

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#935]
just a reminder to myself to delete all the unscoped tags on the repo.. I think @michaelfig said these got accidentally resurrected as part of some `lerna` release script.

There are two tags that surprise me, named `packages/cosmic-swingset/v0.14.1` and `packages/cosmic-swingset/v1.0.0`. @michaelfig , I plan to delete those too, unless you tell me they're important.

**Comment by michaelfig** [comment]
Please delete them.  That was a failed Golang experiment.

**Comment by warner** [comment]
Done. @michaelfig please see if you can delete those tags from your local release-building repo too, maybe we can finally exterminate them once and for all.
