### ISSUE TITLE
Where should zoe make amounts visible?

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/agoric-sdk#951]
from a comment in #944:

 Zoe provides access to offer amounts from both [the external facet](https://github.com/Agoric/agoric-sdk/blob/881e4fead2bf61ebbd13f716f2221c9ed3015881/packages/zoe/src/zoe.js#L739) and the [contract facet](https://github.com/Agoric/agoric-sdk/blob/881e4fead2bf61ebbd13f716f2221c9ed3015881/packages/zoe/src/zoe.js#L461), but filters the records differently. (The contract facet filters out amounts.)

@erights asked
> Why is it ok to expose the amount on the zoe service and not zcf?
> 
> With the allocations filtered out, the contract (via zcf) cannot see the allocations on the offers and uses a separate getAllocations API. I like that because it separates the things that can and cannot change about an offer.
> 
> Here, using the zoe service (which the contract can do as well) we see the full offers. Since the only thing that changes is the allocation, the notifier only provides notifications carrying only the allocations. This suggests that we should provide the same separation here.

@katelynsills replied

> I think we just didn't have a reason to get the allocation separately before in the zoe service. I'm fine with splitting the zoe service getOffer into two methods: getOffer(s) and getCurrentAllocation(s)

**Comment by katelynsills** [comment]
Closed by #1009
