### ISSUE TITLE
[bundle-source] syntax censorship workaround might silently change program meaning.

### ISSUE THREAD

**Issue by erights** [Agoric/agoric-sdk#958]
At https://github.com/Agoric/agoric-sdk/blob/8ff994bfe0acd6c0bdafe292f6d1c4fbfcf98301/packages/bundle-source/src/index.js#L60-L62

we evade the SES-shim's censorship of import expressions and html comment by textually replacing them with other strings. However, this replacement is done textually, not by parsing, and so will replace these even when they occur within literal strings.

As Patrick Henry would have said if he were a programmer, "Death before confusion!". This replaces one bad behavior --- the SES-shim's overly conservative rejection, which failed safe --- with an overly aggressive rewrite which fails unsafe.

See https://github.com/Agoric/SES-shim/issues/261

**Comment by michaelfig** [comment]
@erights, yes, we definitely need a way to turn off SES's conservative rejection by supplying our own rewrite as a transform.

I'm happy if you'd like to work on enabling this option (first in old-SES, but also in new-SES), as I don't have the bandwidth for it right now.  I can write the parsing transform I'd apply once that is done.

**Comment by erights** [comment]
I don't understand. I do not want to solve this only at the price of losing safety; of relying on javascript code to accurately tokenize javascript code. We should leave SES-shim's safety checks ***on***. The danger this issue raises is that the bundler damages the meaning of the program it's bundling, which endangers that program but at least does not endanger anything else. If we turn off SES's safety checks and tokenize incorrectly, then everyone is at risk from everyone.

There is a principled way to introduce a parser-based solution while minimizing the risk to fallible parsers. Use a parser-based rewrite here to do essentially what you're doing here, but without damaging the meaning of the program if the parser and rewriter are correct. If they are not correct, then they are at worst as bad as the current state, where the parser-based rewrite endangers the program being rewritten, but not anyone else.

**Comment by michaelfig** [comment]
I plan on postponing this until we can have a more comprehensive solution using @warner's `import-bundle`, as well as changing Zoe and spawner to accept bundles directly as an argument and use `import-bundle` to evaluate the.

OTOH, if we don't rewrite strings, then they will still trigger failures with the SES-shim's checks.  It's entirely possible that sources of those usages are deeply nested with imported packages, and not easily modifiable by the user.  What should we do in that situation?

**Comment by erights** [comment]
What's an illustrative tiny example?

**Comment by michaelfig** [comment]
> What's an illustrative tiny example?

I don't have a good one anymore (they all involve comments).

So perhaps the final solution is a HTML- and JS-comment-rewriting parser so that most comments are left intact (helps with debugging), but the HTML ones are converted to JS, and both comments' contents are rewritten to defang any apparent `import()` expression.

**Comment by michaelfig** [comment]
> So perhaps the final solution is a HTML- and JS-comment-rewriting parser so that most comments are left intact (helps with debugging), but the HTML ones are converted to JS, and both comments' contents are rewritten to defang any apparent `import()` expression.

This is implemented in bundle-source.
