### ISSUE TITLE
[Zoe] Proposal for alternative payout rules expression

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#96]
Current payout rules look like this: 

```js
[
    {
      kind: 'wantExactly',
      units: ticketAssay.makeUnits(1),
    },
    {
      kind: 'offerAtMost',
      units: dollarAssay.makeUnits(10),
    },
]
```

A simpler way of expressing the same thing could be:
```js
{
  wantExactly: ticketAssay.makeUnits(1),
  offerAtMost: dollarAssay.makeUnits(10),
}
```

This could work for the simple cases (and it "almost" reads like in English). The more complex cases (several `offer`/`want`) would still require an array. But even this array could be of objects with properties `wantExactly`, `wantAtLeast`, `offerExactly`, `offerAtMost`

Another possible improvement would be for `offerAtMost` and `offerExactly` to be directly **a payment** (this removes the step to create a separate array passed to the `escrow` method)

**Comment by katelynsills** [comment]
We're adopting the idea of `want` and `offer` as keys of the offer rules. Thank you for the idea! See https://github.com/Agoric/agoric-sdk/issues/469

Closing this in favor of #469
