### ISSUE TITLE
capTP cannot currently be run on many web sites

### ISSUE THREAD

**Issue by danfinlay** [Agoric/agoric-sdk#965]
I was experimenting with using CapTP inside MetaMask as a way of adding our API to pages the user visits, but:
- capTP includes `harden()` which includes an `eval()` operation in its internals.
- some sites have content-security policies that disallow evaluating on their domain.

I may be able to get around this by either:
1. requesting _even more extreme_ permissions that enable ignoring this content-security policy (that seems pretty awful even if that is possible)
2. Asking consumers to bring their own `capTP` library that they would have to run with the proper content-security permissions.
3. Simply only work with sites that allow unsafe-eval.

Just documenting this here, I'm not sure this is a solvable problem, so feel free to close this. I just wanted to point this out and share the observation somewhere. Curious for any thoughts on how I should best proceed. I'll probably go with `3` right now for experimentation's sake.

**Comment by erights** [comment]
> capTP includes harden() which includes an eval() operation in its internals

Hi @danfinlay where does `harden` use `eval`? I couldn't  find it.

**Comment by erights** [comment]
Hi @danfinlay doing some housecleaning. Does this bug still represent a question or problem to be addressed?

**Comment by danfinlay** [comment]
No, I think this is ok to close.
