### ISSUE TITLE
agoric start --reset gives "SecurityWarning: '@agoric/harden' is ineffective without SES"

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#971]
I'm doing the ["starting a project" steps](https://agoric.com/documentation/getting-started/start-a-project.html)

On `agoric start --reset`, i get:
```sh
$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
SecurityWarning: '@agoric/harden' is ineffective without SES
agoric: start: setting sim chain with 0 second delay
SecurityWarning: '@agoric/harden' is ineffective without SES
agoric: start: linking html directories
SecurityWarning: '@agoric/harden' is ineffective without SES
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
```

It works, but i get this warning being repeated in a way that isn't actionable

If that helps, i think that i have never cloned or installed ses(-shim) on my machine

**Comment by warner** [comment]
closed by #973, plus a note on #477 to remind myself to remove the warning-disabler when we move to new SES
