### ISSUE TITLE
[Zoe] Feedback on the Zoe chaimail

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#98]
https://github.com/Agoric/ERTP/blob/0a1a6ac1a7eabe1c3fcd28380550afa35412dd84/core/zoe/zoe.chainmail

- The `InstanceInformation` interface is not defined
- `installationHandle` is an object and there is no corresponding interface (i don't know whether it should)
- `getInstance` is said to "Credibly get the instance from the instanceHandle", but returns an `InstanceInformation` (is "instance" the same thing than "InstanceInformation"?)
- A bit like for contractHost ( Agoric/agoric-sdk#95 ), it's not clear to me how much the installation step is worth the cost of adding another concept. `zoe.install(source, terms)` (or any better name) could work

**Comment by katelynsills** [comment]
Closing this in favor of an updated #496
