### ISSUE TITLE
Find a good name for "home"/"referencesPromise"

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#987]
This topic came up in discussions in the support channel during the hackathon

The RELP exposes `home`. Currently, deploy scripts use the name `referencesPromise`

What is being names is the object available in deploy scripts that is the "entrypoint" for a "main" vat running in the blockchain

I feel there is no strong consensus yet on the topic

**Comment by katelynsills** [comment]
I'm ok sticking with `home` if we have to for consistency (sorry for introducing `referencesPromise`, I got ahead of myself because `homeP` just seemed so confusing to a beginner), but I think we could do better. Maybe:

`startingCapabilities`

**Comment by erights** [comment]
What's the problem with `home`? (FWIW I always liked it)

**Comment by katelynsills** [comment]
At the time, we had a variable named `homeP` in the deploy script with very little explanation, so I was trying to add some meaning to it. 

Here's the context:

![Screen Shot 2020-04-24 at 10 14 28 AM](https://user-images.githubusercontent.com/2441069/80239111-7d6d3b80-8614-11ea-874b-d63097fff636.png)

**Comment by katelynsills** [comment]
HomeP is fine with me.
