### ISSUE TITLE
Does it make sense to run a deploy script before the "referencesPromise" is resolved?

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/agoric-sdk#988]
This seems to be a recurring pattern:

```js
export default async function deployContract(
  referencesPromise,
  { bundleSource, pathResolve },
) {
  // Let's wait for the promise to resolve.
  const references = await referencesPromise;

  // Unpack the references.
  const {
    // *** ON-CHAIN REFERENCES ***
    zoe,
    registry,
  } = references;

// ...
```

adapted from https://github.com/Agoric/dapp-encouragement/blob/bfc928e2c867bc1ba090993cb1cec7bfcf1bfe4f/contract/deploy.js#L20-L29

The deploy script exports a function called with a promise as argument and the first thing it does is `await` its resolution

If, for some reason, the chain isn't reachable (and the promise hangs indefinitely or throws), there is probably no reason to run the deploy function
If the objects from the promise aren't reachable, does the deploy do anything useful?

If there is consensus, i would argue in favor of waiting for the resolution before calling the deploy function and calling the deploy function with the `references`/`home` directly as argument instead of the promise

**Comment by katelynsills** [comment]
That makes sense to me
