### ISSUE TITLE
Unable to use setPrice on Xnet (no oracle invitation found for Gov 1 account)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/agoric-sdk#9957]
## Describe the bug
During testing of Vaults and Auction core eval fix - I ran into some issues attempting to change the price to test liquidations

See https://agoricopco.slack.com/archives/C07EETFFVEH/p1724562419010319?thread_ts=1724552945.969779&cid=C07EETFFVEH for more information (will add more detail later)

## Platform Environment
 - what OS are you using? what version of Node.js?
 - is there anything special/unusual about your platform?
 - what version of the Agoric-SDK are you using? (run `git describe --tags --always`)

## Screenshots
If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by dckc** [comment]
diagnosis: we neglected to accept the oracle invitation.

I looked for it and thought it wasn't there, but I was reading the output of `agoric wallet show` wrong - I looked at purses instead of balances.

@turadg and I are making progress now. Will let you know when we have set prices.

**Comment by dckc** [comment]
Setting prices is working now:

```
{"timestamp":"2024-08-26T18:24:30.000Z","price":12.34}
```
