### ISSUE TITLE
[Zoe] Improve InviteAnOffer Helper

### ISSUE THREAD

**Issue by katelynsills** [Agoric/agoric-sdk#997]
From the Zoe meeting:

- Needs to close over zcf, within the contract, usability is poor
- Boilerplate to get to library is too hard
- We should require the parameters for inviteAnOffer
- Move inviteDesc into makeInvitation

(Kate): I think we should rename it too. A user had confusion about whether it was just making an invite or also making an offer.

**Comment by erights** [comment]
The name `inviteAnOffer` is my fault. I have come to hate it. Better name appreciated.

The only parameter to `inviteAnOffer` that should be mandatory is `inviteDesc`, once it's pulled out of `customProperties`. `customProperties` should be ***very*** optional as very few invites need one. `expected` should be optional as well, even though we do want to encourage it.

Once we have lint rules at the zoe level, to detect hazards and suggest best practices, a lint rule should check that
   * The value of the `inviteDesc` parameter is always a literal string
   * That literal string is unique per textual call site within the contract code.

**Comment by katelynsills** [comment]
I think what you're saying is different than what was being said in the meeting, so I think there was a misunderstanding. My understanding was:

- `inviteDesc` as an invite extent property gets pulled into Zoe as a requirement, so `inviteAnOffer` shouldn't have anything to do with enforcing that requirement anymore. `zcf.makeInvitation` would have a required parameter `inviteDesc`.
- The point of having a helper is that it would do something different than real API endpoint, so in that case, the only reason to use inviteAnOffer is to enforce `expected` properties. If expected is undefined, they should use `zcf.makeInvitation` instead. So I think `expected` should be required for the `inviteAnOffer` helper, although that's a good point that customProperties should not be required for either `inviteAnOffer` or `zcf.makeInvitation`
- I think we can go further than lint rules, if we are enforcing `inviteDesc` within Zoe, which I think we should. We can easily throw in the `zcf.makeInvitation` call if either of your two above requirements are not met.

**Comment by erights** [comment]
Fixed by #960
